# CSC 4792 MINI PROJECT

In [1]:
!pip install pandas requests beautifulsoup4 lxml pdfplumber pypdf kaggle

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (6.1.2)
Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 2.1 MB/s eta 0:00:00
Collecting pypdf
  Downloading pypdf-6.18.1-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: kaggle in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.13/dist-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.13/dist-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.13/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.13/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.11.7)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 2.9 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 37.7 MB/s eta 0:00:00
Downloading pypdf-6.18.1-py3-none-any.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 9.9 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 23.5 MB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 24.7 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pypdf, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdf-6.18.1 pypdfium2-5.13.0

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import BytesIO
from io import StringIO
from urllib.parse import urljoin
from urllib.parse import urlparse
import pdfplumber
import os
import re

In [3]:
pd.__version__

'2.2.3'

In [4]:
council = "Mumbwa Town council"
base_url = "https://www.mumbwacouncil.gov.zm/"

print(council)
print(base_url)

Mumbwa Town council
https://www.mumbwacouncil.gov.zm/

In [5]:
response = requests.get(base_url, timeout=30, verify=False)
print("Status code:", response.status_code)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status code: 200

In [6]:
soup = BeautifulSoup(response.text, "html.parser")
print(soup.title.get_text(strip=True))

Mumbwa Town Council – Mumbwa

In [7]:
links = []

for a in soup.find_all("a", href=True):
  links.append({
      "text": a.get_text(" ", strip=True),
      "url": a["href"]
  })

links_df = pd.DataFrame(links)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

links_df.head(100)

,text,url
0,,https://www.mumbwacouncil.gov.zm/
1,Home,https://www.mumbwacouncil.gov.zm/
2,About,#
3,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
6,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
7,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
8,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
9,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
10,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
11,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
13,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
14,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
15,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
16,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
17,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
18,Media Center,#
19,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
20,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
21,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
22,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
23,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
24,Home,https://www.mumbwacouncil.gov.zm/
25,About,#
26,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
29,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
30,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
31,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
32,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
33,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
34,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
36,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
37,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
38,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
39,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
40,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
41,Media Center,#
42,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
43,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
44,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
45,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
46,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
47,,https://www.facebook.com/mumbwacouncil?mibextid=LQQJ4d
48,Learn More,https://greensafaris.com/ila/
49,Learn More,https://www.bing.com/travel/hotels/detail?q=Ila+Safari+Lodge+by+Green+Safaris&id=YN8203x13069317605180350720&hname=Ila+Safari+Lodge+by+Green+Safaris&loc=Mumbwa%2C+ZM&displaytext=Mumbwa%2C+ZM&lat=-14.973811&lon=25.925482&cin=2025-03-02&cout=2025-03-03&guests=2A0C&age=&hotellistid=YN8203x13069317605180350720&type=hotel&form=HTSEST&entrypoint=HTSEST
50,Learn More,https://www.bing.com/travel/hotels/detail?q=Ila+Safari+Lodge+by+Green+Safaris&id=YN8203x13069317605180350720&hname=Ila+Safari+Lodge+by+Green+Safaris&loc=Mumbwa%2C+ZM&displaytext=Mumbwa%2C+ZM&lat=-14.973811&lon=25.925482&cin=2025-03-02&cout=2025-03-03&guests=2A0C&age=&hotellistid=YN8203x13069317605180350720&type=hotel&form=HTSEST&entrypoint=HTSEST
51,Learn More,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/Shiwezwa-1-by-3-class-room-Block-1.jpg
52,Readmore,https://www.mumbwacouncil.gov.zm/?page_id=1479
53,View Tracker,https://www.mumbwacouncil.gov.zm/?page_id=932
54,CDF Skills Bursaries Applicants,http://www.lusangazicouncil.gov.zm/wp-content/uploads/2023/05/1647006602-1.pdf
55,Download Latest Statement,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/08/Press-Statement-CDF-1.pdf
56,View Previous Statements,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/08/CDF-STATEMENT-previous.pdf
57,Download Guidelines,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/08/FINAL-CDF-GUIDELINES-FEBRUARY-2022-1.pdf
58,,https://www.mumbwacouncil.gov.zm/?p=3959
59,MUMBWA TOWN COUNCIL REAFFIRMS COMMITMENT TO EXPANDING WATER ACCESS AND PROMOTING GENDER EQUALITY,https://www.mumbwacouncil.gov.zm/?p=3959
60,Read More »,https://www.mumbwacouncil.gov.zm/?p=3959
61,,https://www.mumbwacouncil.gov.zm/?p=3722
62,APPROVAL OF 2026 COUNCIL BUDGET,https://www.mumbwacouncil.gov.zm/?p=3722
63,Read More »,https://www.mumbwacouncil.gov.zm/?p=3722
64,,https://www.mumbwacouncil.gov.zm/?p=3715
65,COUNCIL CHAIRPERSON CELEBRATES NEW YEAR BABIES IN MUMBWA DISTRICT,https://www.mumbwacouncil.gov.zm/?p=3715
66,Read More »,https://www.mumbwacouncil.gov.zm/?p=3715
67,,https://www.mumbwacouncil.gov.zm/?p=3690
68,MUMBWA CENTRAL MP COMMISSIONS CHIKANDA RURAL HEALTH POST IN NALUSANGA WARD,https://www.mumbwacouncil.gov.zm/?p=3690
69,Read More »,https://www.mumbwacouncil.gov.zm/?p=3690
70,COMPLAINTS,https://www.mumbwacouncil.gov.zm/?page_id=1935
71,,https://www.facebook.com/mumbwacouncil?mibextid=LQQJ4d
72,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/
73,Local Government Service Comission,https://www.lgsc.gov.zm/
74,Ministry of Finance and National Planning,https://www.mofnp.gov.zm/
75,Ministry of Agriculture,https://www.agriculture.gov.zm/
76,National Assembly of Zambia,https://www.parliament.gov.zm/
77,Local Government Training Institute,http://www.clgti.co.zm/
78,Local Government Association of Zambia Knowledge and Learning Hub,https://www.lgazambia.org.zm/hub/about
79,SMART Zambia,https://www.szi.gov.zm/

In [8]:
keywords = ["administrative", "ward", "council","report", "resolution", "committee", "development", "publication", "about us", "services", "management", "departments"]

relevant_links = links_df[links_df["text"].str.lower().str.contains("|".join(keywords), na=False)]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

relevant_links

,text,url
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
7,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
10,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
19,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
30,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
33,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
42,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
59,MUMBWA TOWN COUNCIL REAFFIRMS COMMITMENT TO EXPANDING WATER ACCESS AND PROMOTING GENDER EQUALITY,https://www.mumbwacouncil.gov.zm/?p=3959
62,APPROVAL OF 2026 COUNCIL BUDGET,https://www.mumbwacouncil.gov.zm/?p=3722
65,COUNCIL CHAIRPERSON CELEBRATES NEW YEAR BABIES IN MUMBWA DISTRICT,https://www.mumbwacouncil.gov.zm/?p=3715
68,MUMBWA CENTRAL MP COMMISSIONS CHIKANDA RURAL HEALTH POST IN NALUSANGA WARD,https://www.mumbwacouncil.gov.zm/?p=3690
72,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/

In [9]:
publications_url = "https://www.mumbwacouncil.gov.zm/?page_id=195"

response = requests.get(publications_url, timeout=30, verify=False)
print(response.status_code)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200

In [10]:
soup = BeautifulSoup(response.text, "html.parser")

publication_links = []
for a in soup.find_all("a", href=True):
  text = a.get_text(" ", strip=True)
  url = a["href"]

  publication_links.append({
      "document_title": text,
      "document_url": url
  })

publication_df = pd.DataFrame(publication_links)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
publication_df.head(100)

,document_title,document_url
0,,https://www.mumbwacouncil.gov.zm/
1,Home,https://www.mumbwacouncil.gov.zm/
2,About,#
3,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
6,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
7,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
8,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
9,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
10,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
11,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
13,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
14,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
15,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
16,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
17,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
18,Media Center,#
19,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
20,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
21,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
22,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
23,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
24,Home,https://www.mumbwacouncil.gov.zm/
25,About,#
26,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
29,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
30,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
31,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
32,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
33,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
34,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
36,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
37,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
38,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
39,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
40,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
41,Media Center,#
42,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
43,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
44,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
45,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
46,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
47,"Landlord-and-Tenant-Business-Premises-Act – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Landlord-and-Tenant-Business-Premises-Act.pdf
48,Lands-Acquisition-Act –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Lands-Acquisition-Act.pdf
49,"Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Lands-Acquisition-Act.pdf
50,"Lands-and-Deeds-Registry-Act – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Lands-and-Deeds-Registry-Act.pdf
51,"Liqour-Licensing-Act-2011 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Liqour-Licensing-Act-2011.pdf
52,"Registration-of-Business-Names-Act – 2011 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Registration-of-Business-Names-Act-2011.pdf
53,"SI-2011-96 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/SI-2011-96.pdf
54,"The-Constituency-Development-Fund-Act-No.-11-of-2018 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Constituency-Development-Fund-Act-No.-11-of-2018.pdf
55,"The-Local-Government-Act-No.-2-of-2019 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Local-Government-Act-No.-2-of-2019.pdf
56,"The-Occupational-Health-and-Safety-Act-2010 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Occupational-Health-and-Safety-Act-2010-1.pdf
57,"The-Public-Finance-Management-ACT-2018 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
58,The-Public-Procurement-Act-No.-8-2020 –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Procurement-Act-No.-8-2020.pdf
59,"Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
60,The-Solid-Waste-Regulation-and-Management-Act-2018 –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Solid-Waste-Regulation-and-Management-Act-2018.pdf
61,"Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
62,The-Urban-and-Regional-Planning-Act-2015 –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Urban-and-Regional-Planning-Act-2015.pdf
63,"Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
64,The-Zambia-National-Public-Health-Institute-Act-No.-19-of-2020pdf –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Zambia-National-Public-Health-Institute-Act-No.-19-of-2020pdf.pdf
65,"Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
66,"Mumbwa Town Council – Final Newsletter – Uploaded on: February 13, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/02/Mumbwa-Town-Council-Final-Newsletter.pdf
67,"Press Statement Mumbwa CDF – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Press-Statement-Mumbwa-CDF-Nov.pdf
68,"Press Statement On Monitoring Kaindu Road – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/PRESS-STATEMENT-ON-MONITORING-KAINDU-ROAD.pdf
69,Mumbwa IDP,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/05.07.2024-Final-Alignment-Submission-of-the-Mumbwa-IDP.pdf
70,"– Uploaded on: January 17, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/05.07.2024-Final-Alignment-Submission-of-the-Mumbwa-IDP.pdf
71,2026 CDF APPLACATIONS-GRANTS,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLACATIONS-GRANTS.pdf
72,–,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLACATIONS-GRANTS.pdf
73,"Uploaded on: July 16, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLACATIONS-GRANTS.pdf
74,"2026 CDF APPLICATIONS-SKILLS BURSARIES – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-SKILLS-BURSARIES.pdf
75,"2026 CDF APPLICATIONS-COMMUNITY PROJECTS – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-COMMUNITY-PROJECTS.pdf
76,"2026 CDF APPLICATIONS-SECONDARY BOARDING BURSARIES – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-SECONDARY-BOARDING-BURSARIES.pdf
77,,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-SECONDARY-BOARDING-BURSARIES.pdf
78,"2026 Budget – Uploaded on: August 20, 2026",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2026/08/MUMBWA-HeadMandateObjectiveSubProg-15.04.2026.pdf
79,"2025 Budget – Uploaded on: December 5, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2025-BUDGET.pdf
80,"2024 Financial Statements – Uploaded on: December 2, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/FINANCIAL-STATEMENTS-FOR-THE-YEAR-ENDED-31ST-DECEMBER-2024.pdf
81,2025 Semi-Annual Budget Performance Report,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Semi-Annual-Budget-Performance-Report-for-2025.pdf
82,"2024 Mumbwa Town Council Budget – Uploaded on: September 15, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/MUMBWA-2024-0BB-Draft-1.0-2.pdf
83,2024 Detailed Receipts And Payments By Program,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/DETAILED-RECEIPTS-AND-PAYMENTS-BY-PROGRAM.pdf
84,"– Uploaded on: September 15, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/DETAILED-RECEIPTS-AND-PAYMENTS-BY-PROGRAM.pdf
85,"2023 Financial Statement – Uploaded on: January 24, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/2023-AUDITED-FINANCIAL-STATEMENT.pdf
86,2022 Financial Statement –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2022.pdf
87,"Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2022.pdf
88,"2021 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2021.pdf
89,"2020 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2020.pdf
90,"2019 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2019.pdf
91,"2018 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2018-2.pdf
92,"2024 Approved CDF Community Projects – Uploaded on: September 13, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/2024-CDF-COMMUNITY-PROJECTS-AS-AT-31ST-AUGUST-2024.pdf
93,"2024 Proposed CDF Projects All Components – Mumbwa and Nangoma Constituencies – Uploaded on: October 10, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/10/2024-CDF-Proposed-Projects-All-Components-Mumbwa-and-Nangoma-Constituencies.pdf
94,View more,https://www.mumbwacouncil.gov.zm/?page_id=932
95,"2025 Minutes of Stakeholders First Monitoring Meeting for the Zambia Devolution Support Program (ZDSP) – Uploaded on: November 17, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/Stakeholders-Minutes-of-The-First-Monitoring-Meeting-for-the-Zambia-Devolution-Support-Program-ZDSP.pdf
96,"2025 Stakeholders-engangement-plan – Uploaded on: December 5, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/ACE-Scanner_2025_12_051.pdf
97,"2025 Minutes of Stakeholders Meeting on The Council Budget – Uploaded on: September 15, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Minutes-of-Stake-holders-Meeting-on-The-2025-Council-Budget.pdf
98,2025 Stakeholders engagement meeting on the review of,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2026-Stakeholders-Engangement-Meeting-on-the-2026-Budget-1.pdf
99,Mumbwa Town Council Budget and Plan for the 2026 Budget,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2026-Stakeholders-Engangement-Meeting-on-the-2026-Budget-1.pdf

### council administrative data

In [11]:
administrative_keywords = [
    "administration",
    "management",
    "services",
    "department",
    "about us"
]
admin_df = publication_df[publication_df["document_title"].str.lower().str.contains("|".join(administrative_keywords), na=False)]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
admin_df

,document_title,document_url
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
57,"The-Public-Finance-Management-ACT-2018 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
60,The-Solid-Waste-Regulation-and-Management-Act-2018 –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Solid-Waste-Regulation-and-Management-Act-2018.pdf

In [12]:
response = requests.get("https://www.mumbwacouncil.gov.zm/?page_id=2877", timeout=30, verify=False)
soup = BeautifulSoup(response.text, "html.parser")
text = soup.get_text("\n", strip=True)
print(text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Page not found – Mumbwa Town Council
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Menu
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Search
Nothing here
It looks like nothing was found at this location. Maybe try a search?
Search…
Contact Information
Mumbwa Town Council
Mumbwa District
Central Province
Tel: 260211800074
P.O. Box: 830001
Email; councilmumbwa@yahoo.com
COMPLAINTS
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
Local Government Association of Zambia Knowledge and Learning Hub
SMART Zambia
©2025. SMART Zambia Institute. All Rights Reserved.

In [13]:
response = requests.get("https://www.mumbwacouncil.gov.zm/?page_id=792", timeout=30, verify=False)
soup = BeautifulSoup(response.text, "html.parser")
text = soup.get_text("\n", strip=True)
print(text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Services – Mumbwa Town Council
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Menu
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Search
The Council shall undertake the following responsibilities to ensure effective governance and public welfare within its jurisdiction:
Infrastructure and Administration
Establish and maintain offices and buildings necessary for the administration of Council affairs, as well as facilities for public meetings and assemblies.
Law, Order, and National Security
Maintain law and order, safeguard national security, and promote efficient governance within the Council’s jurisdiction.
Advertising and Public Spaces
Regulate and control the erection and display of advertisements and advertising devices in, or visible from, streets and other public areas.
Animal Welfare and Livestock Management
Oversee the keeping and movement of livestock to ensure orderly management.
Regulate and control animal slaughter for human consumption, including certification of meat, disposal of diseased carcasses, and the prevention of the sale of unfit meat.
Maintain hygiene standards in abattoirs and cold storage facilities, and monitor the processing of animal by-products.
Supervise the transportation of animal carcasses within the district.
Transportation and Road Safety
Develop and maintain road infrastructure to facilitate safe and efficient transportation.
Regulate traffic and vehicle parking, including the establishment and management of parking meters and designated parking facilities.
Implement measures to enhance road safety for all users.
Public Lighting and Utilities
Establish and maintain street lighting systems to enhance safety and accessibility in public spaces.
Business Regulation and Licensing
Inspect and enforce compliance in business establishments, ensuring adherence to regulations concerning the sale and consumption of intoxicating liquor on and off the premises.
Housing and Urban Development
Construct, purchase, and maintain buildings and facilities to support residential accommodation within the Council’s jurisdiction.
Encourage the development of adequate housing for local residents.
Land Use and Environmental Management
Regulate and oversee land use and building construction in the interest of public health, safety, and orderly urban development. Supervise the demolition and removal of buildings, ensuring compliance with Council approvals.
Contact Information
Mumbwa Town Council
Mumbwa District
Central Province
Tel: 260211800074
P.O. Box: 830001
Email; councilmumbwa@yahoo.com
COMPLAINTS
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
Local Government Association of Zambia Knowledge and Learning Hub
SMART Zambia
©2025. SMART Zambia Institute. All Rights Reserved.

In [14]:
response = requests.get("https://www.mumbwacouncil.gov.zm/?page_id=770", timeout=30, verify=False)
soup = BeautifulSoup(response.text, "html.parser")
text = soup.get_text("\n", strip=True)
print(text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Departments – Mumbwa Town Council
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Menu
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Search
Institutional Management
Planning
Engineering Services
Finance
Human Resource and Administration
Fisheries, Livestock and Veterinary Services
Agriculture
Consists of the principle officer who in this regard is the Council Secretary, as well as procurement and audit sections.
The role of planning department is to plan the overall layout of the district, upgrading of shanty areas to modern standards, setting up of township boundaries, coming up with standard building plans which have to be adopted by everyone building, land distribution, processing of title deeds, HIV/AIDS, gender and human rights sensitisation, and community development activities. Through the section of public health, ensure a clean, healthy and green environment.
The role of this department is to facilitate engineering services such as; feeder roads, borehole drilling, inspection of buildings, scrutinizing building plans to make sure it’s the required standard, providing burial site, fire brigade services, maintenance of plant and machinery,
Collection of revenue, preparation of statutory obligation, preparation of books of accounts.
Staff establishment, management of assets, records keeping, training and development, recruitment, staff appraisals, minutes and report writing, discipline, explanation of conditions of service to staff, Public relations services.
Content Loading...
Content Loading...
Contact Information
Mumbwa Town Council
Mumbwa District
Central Province
Tel: 260211800074
P.O. Box: 830001
Email; councilmumbwa@yahoo.com
COMPLAINTS
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
Local Government Association of Zambia Knowledge and Learning Hub
SMART Zambia
©2025. SMART Zambia Institute. All Rights Reserved.

### Ward development committee information

In [15]:
ward_keywords = [
    "ward",
    "WDC",
    "stakeholder",
    "community",
    "development",
    "proposals",
    "projects",
    "policy"
]

wdc_df = publication_df[
    publication_df["document_title"].str.lower().str.contains("|".join(ward_keywords), na=False)
]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
wdc_df

,document_title,document_url
15,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
38,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
54,"The-Constituency-Development-Fund-Act-No.-11-of-2018 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Constituency-Development-Fund-Act-No.-11-of-2018.pdf
75,"2026 CDF APPLICATIONS-COMMUNITY PROJECTS – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-COMMUNITY-PROJECTS.pdf
92,"2024 Approved CDF Community Projects – Uploaded on: September 13, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/2024-CDF-COMMUNITY-PROJECTS-AS-AT-31ST-AUGUST-2024.pdf
93,"2024 Proposed CDF Projects All Components – Mumbwa and Nangoma Constituencies – Uploaded on: October 10, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/10/2024-CDF-Proposed-Projects-All-Components-Mumbwa-and-Nangoma-Constituencies.pdf
95,"2025 Minutes of Stakeholders First Monitoring Meeting for the Zambia Devolution Support Program (ZDSP) – Uploaded on: November 17, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/Stakeholders-Minutes-of-The-First-Monitoring-Meeting-for-the-Zambia-Devolution-Support-Program-ZDSP.pdf
96,"2025 Stakeholders-engangement-plan – Uploaded on: December 5, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/ACE-Scanner_2025_12_051.pdf
97,"2025 Minutes of Stakeholders Meeting on The Council Budget – Uploaded on: September 15, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Minutes-of-Stake-holders-Meeting-on-The-2025-Council-Budget.pdf
98,2025 Stakeholders engagement meeting on the review of,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2026-Stakeholders-Engangement-Meeting-on-the-2026-Budget-1.pdf
101,"2024 Minutes for the Stakeholders Engagement Meeting With Business Community – Uploaded on: November 26, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/Minutes-for-the-Skaeholders-Engagement-Meeting-With-Business-Community-Held-on-5-July-2024.pdf
102,"2024 Minutes of Stakeholders meeting on Output Budget – Uploaded on: June 24, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/Minutes-of-Stakeholders-meeting-on-Output-Budget-for-the-year-2024_rotated.pdf
103,"2023 Minutes of the Stakeholders Meeting – Uploaded on: January 17, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/Minutes-of-Stakeholders-Meeting-Held-on-8-December-2023-at-Mumbwa-Civic-Centre.pdf
109,"Minutes of the Stakeholders Meeting 8 December 2023 – Uploaded on: December 11, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/12/Minutes-of-Stakeholders-Meeting-Held-on-8-December-2023-at-Mumbwa-Civic-Centre-1.pdf
123,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/

In [16]:
response = requests.get("https://www.mumbwacouncil.gov.zm/?page_id=2868", timeout=30, verify=False)
soup = BeautifulSoup(response.text, "html.parser")
text = soup.get_text("\n", strip=True)
print(text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Civic Leaders – Mumbwa Town Council
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Menu
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Search
Civic Leaders
Contact Information
Mumbwa Town Council
Mumbwa District
Central Province
Tel: 260211800074
P.O. Box: 830001
Email; councilmumbwa@yahoo.com
COMPLAINTS
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
Local Government Association of Zambia Knowledge and Learning Hub
SMART Zambia
©2025. SMART Zambia Institute. All Rights Reserved.

### public council resolutions

In [17]:
resolution_keywords = [
    "resolution",
    "audit",
    "report"
]

resolution_df = publication_df[
    publication_df["document_title"].str.lower().str.contains("|".join(resolution_keywords), na=False)
]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

resolution_df

,document_title,document_url
81,2025 Semi-Annual Budget Performance Report,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Semi-Annual-Budget-Performance-Report-for-2025.pdf
115,"CDF-Report-2022 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/CDF-Report-2022.pdf
116,"Local-Government-operations-Report-2022 _- Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Local-Government-operations-Report-2022_2.pdf
117,"MTC Audited Financial Statement for 2021 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MTC-Audited-Financial-Statement-for-2021.pdf

In [18]:
response = requests.get("https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Semi-Annual-Budget-Performance-Report-for-2025.pdf", timeout=30, verify=False)
response.raise_for_status()
with pdfplumber.open(BytesIO(response.content)) as pdf:

  for page_number, page in enumerate(pdf.pages, start=1):
    print(f"\n======== Page {page_number} ========\n")

    text = page.extract_text()
    if text: print(text)

    tables = page.extract_tables()
    for table_number, table in enumerate(tables, start=1):
      print(f"\n--- Table {table_number} ---")

      table_df = pd.DataFrame(table)
      print(table_df.to_string(index=False, header=False))

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

======== Page 1 ========

E C.;] co \ - ] o + (! N G) N Y xN SE z
F n > t U F ! ' \ f o . J l r t d , . ! H o , A ) ' o o o o p 3 o r @ o a o I I o 3 D ) a o @ t I p 3 D p o o N o a l @a z : 3 0 ) r a o o A o o ) mo a a t a a o D I ) ) l 0 I o a o o o a a o o o o a I D q o o t o o n o I a o 5g t I s r E I o F t l ( o o o ]) m a o o a p : l N Eo t I o{ t O . n 5 p o l N To Io{ ) D o a l D 5 ot o o o o c0 . o G o o p o o d 6 o e a N b o oI 3 o Io , ( a P 'E n o @ t l \ , ) i o o N - , ro @ N i , o o t o i A c r . r ) r 1 ) l o o p I 0x . ) ) o o d o o n o 6 t o o @ (r b o o o I a I D \ d o o o L o o o !o U n ! e o p p . a . o p N U A o _ I @ L a o o I D o p o a 6 o n i o A x o ) o r : p o o a E - o ! E o 4 t i o A o ) ) r F o o o o t g C 8 S 5 H U !.H , J ' $ t z E a E ! E t , ,> ' ' - F d > O 4 l € 6 F
' H , ! o ! o , ' o p . o p o p o il @ I a p D E E n ' E F
N i;...: o
R o3 3\ E:d'
F
B
o. Fl
z
o
E
. . o - oI o o 6 < o o t t ) ) t ( @ @ o Jl " . @ ! O { - {( + . , I o \ C ( t -. o . n n 1 ) l . b \ ( b ( + O N o ! , , ' 0 ( c N { ( I r 0 o l . ' l o N + o N \ o ) H,E P H @o g ( . o+ o o . l ) I ) - ' \ l + I c s o o o . " \ o l - \ o . o I @ 0( @ I 1, " o o c A o ol o .1 ! U o o t P . o( 0i o t - \ o , ) t \- 'o ( N ( o + o n o o , s o , - Oo C( ( \(: @ + o n N, , . - O o b \ ( ! D . ] r ) & A \ O ( 9 o o { ! o (n " _ O t O - ( o . + n r 1 j H,E
t
p o D6 o
p
F
" J N - + o I i ( o o o J , t ] \ + o c t ! o . o ) @ o I $ - l \ c N+ 5 + o ) ) " ( i ( N N N N c } ! o 1 " " o N( t ! N c o D ) , . . ( o 0 L @ C N f 0 D - , \ . H { . '1 N \ ( ao E o , ) t ) l D E s c U( l o o - il " \ O i o N ( o N , l , C P O \] ! F c ( \ I o - o n - o l \ c o + o : o - u o: o { { N oo r \ \ - o \ @: m O ( o n - N : o ? J a ( o i ( + A r r e o t ! t ! - _( o : (( N ( ! , , ! , " - U \ : N \ f o o1 ' " . o t \ i m : O o 5 \ o ) . o ( o: N - A o n n N H { u9 t 9 E No C o J l ) l 4 E P . c p N o N o ^ r
o
o
b c o H\ c ^ 0(,0 ) I i l N \ 0 i \ o o 1 ] \( o { { o, - . @( o ! ( \ + N ( J . o , ) , \ | - P ( ( 5 t c \ , ! o ) l L " q @o i o - N N o l - " \ o o P @ N \ ( oo ,l H {& ! ! I BI o o , € o a ON a + u J : ! ; ! \ o @o I n c - ( b - N c l o , - \ o b No o \ - o $ u ( 9 -. n 1 b ( ( ( P O D ! ,. @ o 9 N $ A ) \ f - 0 0 (( P @\o n { 1 1 , N \ 9 O - c { o l o 1 r ( : \ t C ! A o \ N , ) " " ( @I @ 0 N o o 0 , 0 o O b A o - j cO (j O c . ! J o o " ( o O I O o ! " *( i \ + A ( o ! n H {& ! ; B . N l ( \ n )
t E o t' E o
X -D \ J 5 o' U e U U U s -e < -o ' I I
D o p
I
o < s ) i o O s \ 6 N \ o 01 o ( o n \ o s ! \ o o O @ l \o @ I \ 6 + o \ \ A o !o .\ o N \o N N < o\ t o\ C @ o\ ! o o

======== Page 2 ========

z olz
o
4f,
!\ o l I 1) 3 D a o ! a N ? t I 1l I l O l
o f 0)
C, l o F o o lu
a o q c p o
o
o , At I oaD ) p o
o
E ( E D rE lldr
o o - D tl , o A o ) . a o I ID
o o 2 Sp t )i p a o o { p o- E ! e I I T t H I
a o ? o o o ! Dt j 3 u - o @p o [0 o p o o o I I o o a N o p) a o z D p , E o ( c d D ) l l I l t o l ..
o o - DI o a 7oq
qo a a $ o o t o T l r l l I
p 3 o s
D
o $'ll
a
a
tss
o
o,
0oa l=Dc: 1@Z 9 z z I z I
p) od lrll9. o o o ;1
o p o o o i-o o I r 9 {: . E @ l> 9 rf X E !s!3 r ' a -D 3 . a lD t] X a o - o a J -o a =o l l l l l
o a AI)
:;
o 5
6.',,s
E el I
\)
(n N ( o n
@
c c Ol o -u o l o
;l
c o ( \ n t N ol\) { p t t
c @ o F ot I
GI
I

======== Page 3 ========

>Nla
rob
FtJb
ooE
a + o 0 D ^ O '0Er ? tsH > - ( ! :r 8 @ I 3 Qvm i3 c : 2 o a o 9.O C c I o J o o m C ! t o o o !^ '0 ZQ, O o F . r - & i0 r I I o 9 (l v dg O" i r '_ 'g ' P I ! ip a tr > T i3 tE ; E E "
4 - o a < n - T 5 b o U 0 6 3 : i o 5 9 f . , . a o T ,1 ! J r - o { : g C \ c : E q :( c - P oP ' b 4 d x r o 3 H a E o o o . o E ; i 9 - j r : - I i a- i Y i ! l . . H t L + L E J d Q O o D x ( @ o o ! d t o D ! k r 0 j p o i g ;. p o I o 7 3 og 0 -,O6d ,- Ji; o . ( o o : D r ^ l 1 . o , < S E 0 > : ? c O s '| G ar @ ! 5 7 - 3 o X ! P i : @ l f x - o . 7 o ^ i C D 0 - 6 n ) t r o K lD r ) 1 o o E o o J t - 3 l oli o o o N I - - o O a ha 5 i i - r o ! - - , > - o z 0 o c 0 o A o I ) ) ' t o d o C X N! o d !
w r.
n : u a t 0 " = - 9 ' o o d o o p o
o
) F dn r - r ^ ai
:
l 5
H
r P , g o r P r y 3 - I
^O
o
.
o
0:a
o - d < . r, 3 E O I H ; i i i
-
5 o d ] m l ,
'
y <
J
a s o S h * U b o ) ^ d H o o 5 o , ? 3 . i
P
i 13 o p o o o t o
p
s I D , f H o o o z !I o d l ) ' F ' E O E o E i = F - ! E > E i t \
n o
t i r ! , z d b d g i S 3 c
c q o - o o a . +o o t,
N o o
o a p
Ad)
r5
o
O N+ ( N n (, N ._l o p
CT c p - C. (o<
t-)
o|.) N O O t\) oN t\) o
N
(n (
N
n
N
01 (
N
n
(N,
N(, N(,
(n
N{
o o o o r a o o 0q ( o o t, o o
N No No N o D+ s o
(
N
n
to\) N
(n
No r!
D
X X X X
" \ t t - ( \ , o 1 ) , \ ( o + + i + ! ] " j o ( b + - + D ( ! n n " -@ 9 o \ + + N + o \ - - @ ( \ - + ( o n , , ( N A ,| " I < o b o t \ \ o ) i " o (n A ' A c a b o b O (! " " 6 o b O o o O o o o b o l " (( o I o o D, o t N d
o
t
>i
ol,
bi'
Nor?
N N
(, ={sodp
900 Ol o N \ J-.1 Cr<
o (, o o " o (n UoI BE
b, b o b o b O h
r Fd
6
cor { : - c n o (, I (o! N E{i P el E' o ;
\c Ct CoN O O
o
C' b b o b b o FIJ
N
o N
o (,l
o U r9 o U o U i! o in o U V) o U a) o t ,u o U \1 o U iq Url o o N o TJ o U T' o U\ o o o o oo cr )
o d
5 N
o
FT ^z ^z { o N (tr
i 'f a ;. 8 < q 6 a 5 +i i ^ l o ! L 6 p ^ ' 0 5 o * o ^ a tldH O a 3 d ra d J H o r 9 . h 6 Ol- ^ o o { o 3 O q i o 9 ^ o4 6 . o d y a q d o B tr o U s c s i o o E oC F po T o, Tm m I!D H o = ,E 'U 'd "U r l t+ r . r g , E i b * g T

======== Page 4 ========

o - p 0q ^g 5 o 1 C iC 3 lrA X ^ - r rN o y^ q o o a t !L X a ' d i t 5 i o O a'13 a : = I < r - n a a 6 a E o ; N !/ a a F 7a o p : P i,a ; t E r ; i 3 'e
lm c0q !^0tc o o o, 9 o ! f c o L o o rc. a d o r5 ; a oX l2 lD .
x o ! J $ t I. , , - 6 p > : 5 u O ) . o =o p - i 5 ; a ' o * o . 3 + s a L o t $ ! ' S D t a i o o o o p a F; (2 . t o 8 ^) l D X l = o D i - D O !- ! - X o : 6 i & P + P O - J ( o* N , ) a @ 6 ! t x D s ) q p D < + Q - ip o a o o @ < i e o O a, o
^ p @ o o o . o PS 5 t X N (^ s ,T Q U o a o L- -o S p- r l O@ o o 1 L e !0 3 i + r ) D
oo-o a 9 ( s D o- o o d ()rX 0p ! Q * 6H o t W s
ho P fr o o aa o o oo- o Pi
Q/. o A)
+a o o o
'0 frt
o
o 30- ;
o < di:
o o 's.!
tos ots @a
6l
@pa@)
0 o q o 0q

======== Page 5 ========

(n OAJ ( o ,) ( t' , ) (,
o o t t / < 7 O o () - o 0 7o U o o lt -itfd r
o'3 j!
o P {i o o I I oL
ots o o o0(
6; o
o oO o
{ o 7 E/
(n Fe o o oo a o F C
a o . t o o !
!DP s o E o '0
a p o o o X.
p t o I *i
o (D A) 9<
p o
@
@o 5 !
o o g C
x
N)
\o
!I[ @
.N
I
c 3 -sn
o o o o o
\ \) Uit U iq FJ
4. 4i
o ciOo'
3 o = n o < . ili , I H oo o, i L q .6 h o w C o O o I
a o ( : @ o: (

======== Page 6 ========

NAME:XYZTOWN COUNCIL
DEBT and ARREARS
OUTSTANDING AMOUNTS OUTSTANDING AMOUNTI
Narration
1-Jan-2025 30-Jun-2025
ZMW ZMW
PE'S 2,327,343.91 2,068,802.32
ZAMTEL
zEsco
WATER
LEGAL COSTS
NAPSA ARREARS 6,463,898.17 6,588,745.29
NAPSA ARREARS . PENALTIES
LAST ARIIEARS 7,227,970.14 1,227,910.14
LASI ARREARS - PENALTIES
OTHER PENSION ARREARS
OTHER PENSIONS ARREARS. PENALTIES 881,877.13 999,855.36
ZRA PAYE 8,479,661.07 9,628,664.1,0
ZRA. PENALTIES
GOODS & SERVICES
CAPITAL
Total 1,9,374,690.36 20,s13,977.21

======== Page 7 ========

MUMBWA TOWN COUNCIL
Seml I n A t n e n rn u a a l l A In u te d r i n t a R l e A co u m d m lt e R d e a p ti o o r n ts and Im entation Period: Jan 2O25 to Jun 2O2S
No SubJect Matter Audit Finding Recom A m u e d nd it af lan Management Action Taken
Governance (Established
1 Committees & Meetings)
2 Budget Execution
Income - Own Source
3
Revenue
rrru vuurrLrrs duuuurrLtrtB vuurtulr ls uurrsroerlllg ar elllclent
4 Accounting procedures and procedures and processes are recommends going measures through recommendations
:ontrols
efficient and discrete lorward a.11 council from I.T to ensure the right back up
rrru lilLCltta{1 nuutl ulllt rlrc uuulrull rs IIrpreltlellLlIlg tne
5 Stores management The stores section is working recommends that the public finance act no 1 of 2018 to the
effiently soo far. stores section later therefore, all procedures are
6 Procurement procedures and contr P o r ls are workin P g r efficiently r I e II c C o m IIIL m C e T n IIA d s A t U h O a l t I th U e NIT t r h rr e c p u u u b u l r i l c u ll f in r a s n c c u e lI e m ltl a ly n ag a e o m n e e n rr t n g a c t t o
controls
so far. procurement section no 1 of 2018 and the procurement act
rrrc Payrurr rlmagement ano I cl I lrrs vuqllult rs uutrtrIllty aorlertng to
Payroll management controls are working efficiently recommends that the the public finance management act
so far. payroll section no 1 of 2018 in the mangement of its
II 1 L rrrE vuurrurl rs uurrtllLly uutlrB LIlc
8 Risk management The Risk management is working recommends that the approved Risk management system to
at optimum efficiencv council adheres to the manage and control risks
REPUBLIC OF ZAMBIA
MINISTRY OF LOCAL GOVERNMENT
i;;";il@
DIRECTOR OF FINANCE
MUMI}WA'I'OWN COUNCIL
P.O. BOX 83OOO1, MUMBWA

In [19]:
response = requests.get("https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/CDF-Report-2022.pdf", timeout=30, verify=False)
response.raise_for_status()
with pdfplumber.open(BytesIO(response.content)) as pdf:
  page = pdf.pages[266]
  text = page.extract_text()
  if text: print(text)

  tables = page.extract_tables()
  for table_number, table in enumerate(tables, start=1):
    print(f"\n--- Table {table_number} ---")

    table_df = pd.DataFrame(table)
    print(table_df.to_string)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

80. Mumbwa Town Council
a. Mumbwa Central Constituency
i. Soft Loans - Failure to Collect Loan Repayments
According to the CDF Guidelines on Loan Repayment b (i) states that the first
payment shall be 60 days from the date of getting the loan; (ii) the subsequent
instalments shall be paid at the end of each month.
During the period under review, sixty (60) applicants were selected and awarded
soft loans in amounts totalling K2,557,090 to undertake various projects.
However, it was observed that the sixty (60) beneficiaries were required to pay
monthly amounts totalling K112,336 with repayment periods ranging from
twelve (12) to thirty six (36) months.
Contrary to the guidelines, 31st October 2023, the Council only collected
K78,525 as loan repayment for the months of August and September 2023
leaving a balance of K149,147. See table 1 below.
Table 1: Uncollected Loan Repayment
248
ME
AST
n
ueo
o n t h
d in g
g u s t
p te m
t a l
b e r
L o a n A
E x p e
K
1
1
2
mc
112
o u
t e d
2 ,3
2 ,3
4 ,6
n
337
t
662
L o a n
A m o u n t
P a id K
5 0 ,0 3 4
2 8 ,4 9 0
7 8 ,5 2 5
B a
6
8
1 4
la n
K2
,3
3 ,8
6 ,1
c
044
e
267
ii. Nangoma Constituency
• Secondary Schools (Boarding) and Skills Development
During the period under review, amounts totalling K4,890,583 was received
as funding for secondary school boarding and skills development bursaries.
As at 31st December 2022, amounts totalling K1,261,140 had been spent
leaving a balance of K3,629,443.

In [ ]:
response = requests.get("https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Local-Government-operations-Report-2022_2.pdf", timeout=30, verify=False)
response.raise_for_status()
with pdfplumber.open(BytesIO(response.content)) as pdf:
  page = pdf.pages[186]
  text = page.extract_text()
  if text: print(text)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

81. Mumbwa Town Council
a. Unapproved Payments
Section 54 (1) (a) (b) of the Public Finance Management (General) Regulations, 2020
states that, “where a hard copy payment voucher is used, the original of a payment
voucher shall be signed by a warrant holder, sub warrant holder or by any other authorised
office holder and indicate the name and, designation of the office holder signing, and the
date below the office holder’s signature.”
Contrary to the Regulation, three (3) payment in amounts totalling K8,185 made during
the year under review, were processed without approval by a responsible officer.
82. Mushindamo Town Council
a. Failure to Collect Plot Premium
Regulation No. 9 (h) of the Public Finance Management (General) Regulations, 2020
requires the head of accounting unit of a local authority to “collect in a timely manner all
revenue and other public monies due and payable to the local authority.”
During the period under review, the Council was expected to collect amounts totalling
K250,000 from plot premiums. However, as at 31st October 2023, amounts totalling
K125,000 were collected leaving a balance of K125,000.
b. Failure to Maintain a General Revenue Cashbook
Regulation No. 133(1) of the Public Finance Management (General) Regulation 2020
provides that an office holder who collects revenue should keep a General Revenue Cash
Book which should be updated daily or immediately revenue is received or collected.
Contrary to the Regulation, the Council did not maintain a daily revenue cash book for
the period under review. Consequently, the completeness of revenue collected in amounts
totalling K3,201,377 could not be validated.
c. Expenditure - Irregular Payment of Accommodation Allowances
During the period under review, the Council paid nineteen (19) officers amounts totalling
K53,600 as accommodation allowance.
However, the payments were irregular in that they were not provided for in the Terms and
167

In [20]:
response = requests.get("https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MTC-Audited-Financial-Statement-for-2021.pdf", timeout=30, verify=False)
response.raise_for_status()
with pdfplumber.open(BytesIO(response.content)) as pdf:

  for page_number, page in enumerate(pdf.pages, start=1):
    print(f"\n======== Page {page_number} ========\n")

    text = page.extract_text()
    if text: print(text)

    tables = page.extract_tables()
    for table_number, table in enumerate(tables, start=1):
      print(f"\n--- Table {table_number} ---")

      table_df = pd.DataFrame(table)
      print(table_df.to_string(index=False, header=False))

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

======== Page 1 ========

,
y11
cou.rrunulceltous fo qe eppjessep lo
fqe 3onucrl gecr.eleA
r=f:+Zg0 Z.Dl 8000L, 1u tedll dleese bnole
lVX:+290 Z.tl gOOOLt
3ruBli: No':'""
unuq\!,econuctl@r.u16q.6on zu
conuc!IJunJuq\v/p@{eqoo 'cour
urnurgnAV IOI,AN
OOnNSl]
cl^tC
lgrrrwel'zoZE lNOfdl:NOSNCl= 33N1U3'
VASNnf
d O' 8ox 8t000t
Jqo vnpllor thnJ^tSMv
5euere1. zv\!stv
oJgco oJ}{ro Ynprlor cauorI€
:i?ffsooLt
Tnsvxr
$,H,)?:;i$X,"TSg$:# if
lf?,,T11'^f,,i,'"^oro\^NronNrrrdourHrt
uoJereuco rs ui,pe 10 crrcnrJ€ rel]aJ pnr ztr, 1A1e;cq' z\zt Mllq r'eEulps ]o ]qe q€ o^e snqloc1
ruu*or \^qorees }{ro conucrI ert rls slrpuE epodlep lqe ctueuclp siela',oul vnpllep gedop
y l c i c i o f , f p # ruE :r l(, ? , g li r 1 n' # rri T rri , "p :; { J .ro # relo : : t : o l u i )to( codres oJirro 3011orlru3 pocn,.oul es ;ebnr:ep ,, rruo
dorrcros ?vvas(oJz0r 6
eup }{ro Jreesnrr eup cruuucrp
)l(
J:Tl:irfff,:r';::J#fHH;r,,^eelruE qsJp ou rnespe{,, re,rwet,,zozt { qrcq
Dr( 3odres oSsrEuep vnplep clueuclP
e ls] slelouiauls Jor lqa clueucleI leur oupop
QecaurqeJ( Z0ZI'
]ljT::##liff?]iff,[r,li:liI'$it::ili::I[T:HX,',,,sac,.e1ur.(,)vpurrursl;e1,ou(
lonrs gpl{tJnllf
'iffn].^-
rnnurg[rV IOTAN JOI|NJI]
.;'rf.'.r*,oirf:k
ronNrrrslfrunrvuA \,- r) , ,i i, i; fiff{
\i'6yr:rr*s""i?I{-.91 {
J,' rcedwu$v"
rr:
#,#'Lrf1i+"":#?^oJu*aul
eup
d'o gox 90021
TnsJ€ >e=
l

======== Page 2 ========

IHt=
Sxruvcl NlNnI3s ol rH3 sonNctl t^tf=ltNe H3]O tN
sdsclvr-
3Hvt lE3u' wnngMV ClnC Ct=NrU3' tNOfd3No3NC3 VnSNnf' ON
conNclI'
rnSSoV ' LgrH t lVA' zoze YL loitv Honus'
l l3u,lgl=uS dUfSSNl:
S/N NVNIS oJ conNcli-t-ou MVUO
cqeule \uBsnuro -\71nurqmE IoMu Conuctl - Conucrl Cqettdersou
L'
Z' geu6medo 1-Bupsou -yelnaeu[auuqe Merp - 6edn1A Conuctl Cqetrdersou
t' Cqllmeuqe vnpteA )1ys'( -\ye)aqo
V' Cl.ttlouLqa Oeqq{, -Sl.Lorue
g' 3qluAeuue posedq -pe;nseuOe
lnlEue vutos -)eulleuqo
9'
Hlcltluln gnurol -Nelnqeupe
L'
8'HlluBlnMeur cllJJorp -\yelele
lnqtupB -lyndoue
6' geogte(,'1-
,;g'ltyoou6e SeAronJ n -NeIeseIB
,g ,1'1yoo(re nlole )fys'( -3qtqo;{o
Lz'\uo^ou clLesoutauB -\ynULqe
,lf'nnlole vnquuo N -slLrcqeuzn
.17'lynnudnle l:uorsl -lydnsn
L 9'sqBuLelupr ZBuqMo -NelnAMr
,l g'slLeuqeue'Vn6nslrue 3' -Neurqele
! z'sqluqMeurqMe lluos - yAOZMB
Ig'sltlutdoupo \yalnru - 1y{oo[e
16'slBJnupe lro^oJ -SeuOoue
20'SnleUBu lBuLllE Uy )UUs'( -slt!uLq!zq!
zr'snsl)n osceJ -lnlela
V8S]NI MIIH VdOI'OEA:
l' clLxnuqa clLlqBuqe - 11;s yoAel gt6quess' seutor CqleJ slLelnuqrle
6nse 1ynu[eue - g1s goleg gt6quass '{Unleupaute Cqlalpou
Z'
t' geple[ CqlqnlnuB - 1;ts yoAel 1;t6quess' ClLtqnlnurB ClLreJpou
1;etuooife Clyre -cq!seln
V'
:
IN VIISNICVNCS:
t' Heupsou yecqeufele )1yr( - Conucll gecteleuf
Z' Oqll{,eeupe )1yr'( - Sonucll fJaEsnJsJ
t' uoplE lueslLn - olslrlcl lpncelrou ourcoJ
?' lreucts 1ynnufn )1yr( - clrlaJ vpu,llulslJElr^o OJJI9OJ

======== Page 3 ========

CeclllB !unqeuqe )1ys( - cqleJ HnuLBu uesonrso oJucoJ
9' I/t'
luoss ln{elo )1ys'( - lclslucl soclel Mallera o$rcer
9'
furueunol N6ole - lc'o'l'c' zewqle dollco
L'
'leuo] yesefe - lunurqMe coJJecllouel coulre
8'
rnslluo sllezMo - 6lslJlcl MoJIs gndeurtsor
6'
lJeucls ltyooube - 6lslpcl YDtlcnlynr.e gJllco
,10'
I.l'loJJeluo laluqo - 1e6e1 oltrcor
,17'3qlleAe gql1efe - \unurqMe olslucl HeBlllt olJlcer
! g')EqnlE Mlusloua )1yr'( - souloJ cou,lu,llllea cleJI
,r'1I71BUIU l'yenuqe )nt'( - ooututlpoo CleU> )yecolper(
EAINAIIVIION
l' oJ' slluesxn NeAIE - olslucl vpu'llulslrBll^e oJucer
clorlB NeMe - glJloa o] ll..ro drosgeul )SO(
z'
YtnDn sleulnln - olslrlcl lulorutellou oJucaJ - zVNls
g'
NVZ
vruoouo yellurB -
NVZ
Nlqoue roqu -
9'
gifPue[ SpeuqBsSB - glgso ol 1qa drostpoul -)SO(
9'
fn
L .\/tBllBs cqoMo - cJoMu
NVIIONVI'VNIHI=!I'I VNO Od3NINC dUVA=U:
dpol lo llto coutu'toucoluoul ol lqo ueellu6' lqe Neltouel vull.ror.u
rvres snu6 eup llLareBuaJ ]qe qonsa ABs lop lu e \v/oJp oJ drefer ql
conucllloJ oeqq{r cltlloULqo'
CONNCII'S]CUIIIVUA.S UfdOUI
ulcllLlogtzt VOOdIION OJ IH3 VNOIISO JINVNCIVI' SIVI=!I'ISNI
U=dOUr JOU rH3 ^llvu tiNO=O tlsr O3C fUIt83U' ZOZL
lqa )onulll serle]B;[ ledouop lltE] DLa vnpl]or gauerpl e;ler llLe
Pnpll lLPp raleesap P rlrlnler pelep ZLsl yyeuq' ZgZt ontlluluB tqe
slplns oJ wnurqMP foMu Jonufll slPleuauls o, P,f,fonuls es El lqe
eup o] 1qe [eel ZOZI lu srrorpPure Mllq lqe lolPl vnlqoupas
V::onultut dollllos oJ Z016 Pup lqa lleesnut pup llupurlel
weuBBauaul 3lrlnlel No' 9 oJ ZOZL'
wauqa$ ]nulteJ qeerp lqel lqe slelns oJ odlulou oJ rtqe onJroue
o] ]qe enpll MPs 1e111[ Ps axdr.assep qA lqa enptlors ou dp8a 6 oJ
.7

======== Page 4 ========

lqe ;lueurt!el slErteueuls ledoll ;ol wnuqme loMu 3onurt1' lu ell
lueleuel larald$ eup deifluouls eup qPleule slLee] ]or ]qe [aer.
tLs] 6ofaltqal' 797,1 lu efrolpPu)a 6llq lqe )psq gpsrs
eupap
lularuellouel dnqllr sallor yrronulluB sleuperps )taSVS( eup lqe
l-o)el vn}{Lopltas yrronulluE dollrtas )iffds(,'
l] MEs JnulLeJ ledouep lqP} ]lLe pnp] r.adou lu)lnpop slelauaul
o] lesq le:eld]s eup de[luauls' 1qe sleleueul oJ louderpsou o;
gnP8el eup P)lnel euonuls' s]E]auau] oJ Joraldls eup dB[ueuls
JoJ l'olel goloJuuteul 3bnelrzpllou jnup pup sleleueul oJ la:a1d1s
eup de[ueuls ]or fousll]neur[ 6ar,elodueul lnup Pup e snuLueuf
o1 s16u111reu1 erlonulluE eup olqar exdleuelouf 1u;or.utellou ou
deBe 17 lo t9'
weuqeJs MaJe elso !uloluap lltel PJlsluE 1r.ou llLa Morlsqod qelp
1u 3qou6me JJou'I l,llq ]o l61q vdr.u'z0zt'lqa yy1u1s1uf,o1 lolpl
Do^aJuuaul pup unrel 6errelodu'raul lupllP]ap 1qe1 1qa[ mela 1u
lqa dloress oJ ruoqlllguE axlaluel lnupluE lllet monlp qe
eddot'11ouep 1o l-orPl vmqoul!es Mlllt flaeu enpll relolps'
bne11;1ap slelr' dr.odar.Mesla ueueBeutaul dlerlrses euouE olqaJs
pe^elodruaulel
oJ P snu oj )MPlqP IMo wllllou )y ZOOO OOO( ;or
3nl1qar' ]qp] Wa yy1u1s1r'[ qep extaupop p lell to
dn;doses'
WnluqMP IoMu Jonulll ]o n:8au11[ snqull lqe r.ebnlloutsuls slplap
eqo^e jor lqa fonulll lo qe roustperap Jor lqe dosslqle gnupluB'
rlLe )onurll 5arla1euf jnuqer 1edoyap lqpt lqa vnpllor Douerpl
ltPp }onup wnuqMP IoMu fonulll JluPullel slPlaueuls MlllLonl
eu]nuqJeufas eup P flaeJeu,fs qep qaau 6r.eu1ep' 1u.rdl[tuB lltBt
uo Bddaeleure Mps lo qo urepe qeJoJa lqa dnqltl V,ffonuls
Joutu'lluaa )dV)( Pl depleueul'
I{La )onu)tl SartJatBuf dleseulop lqe vnpllor geueJel.s enpllep
Jlueullel sleleuteu] ledo;1 ;ot. )oJplel epodllou q[ llto )onurtl eup
rousebnaultell("
eup uela snqulsslou lo lqe yy1u1s1r.I o1 l'olpl
DolaJuueul eup unJel 6arreloduaul Jor fouslpeJellou'
YUaJ Pollqarsllou eup ou P dt.odosel qA 3onullllol posedq
3q1u[eue' pn1[ saroupep qA )onullllor welntu sqlurdoupo' tl mesl
alsol-[lo llrDl:

======== Page 5 ========

tl'"
tedoy lcr lqa ifecr euPoP qecewqet' ZOZ; qo
ePodTeP'
lunlf rtXIUY,fI Jod.iO{. I IINnI,f No' Nlc lILHLtto=gtztt NlNnIfS OJ IH3
l lssIlNC H3l'-o lN oHvna=t
sd3clvl' conNcll- COnNctI- ,19r,
NnwgMv clnlS C3NIu=' lNol=dfNo=Ncf vnlNnl' ON InSSOVA'
l lVA' z\zt YL toiv? Honus
\=
SIEUoP Jqls " cer oJ
\a
Huupsou xBcqaulalu
JONN,fII'SgSUgI iff
b
,i

======== Page 6 ========

t'
A
lAln{,Ilf.{tzY ..JO{tl{i J OIIi\tf IT
I(UY,fI I{IY{T,fIYI SIYIrtIAISNIS dOU IHlf AIVU
lfNo lfI( g I sr t( lf ,f fwlfg lfu,70,71

======== Page 7 ========

WNIhSIAV IOTAN
JONNJII.
Srr.rV:.rCtVrSJVJs{rrtNIS JOU IHS A3VU gNI(gO gIs ItgJXl{IABlfU Z0ZI
.JYglg Od JONJSNIS dY9s
gadop o31qe comrcrJ '
slelaueul og yesdousrqrlrlres Jor vuunel CrUBucreI slelauauls 8
1 upedeupeul VnprloJ,s yadotl 6-t I
sl?}euteul oJ):esq yecerdls eup 4e{,ureuls IZ
sleleutaul oJ3oudurrsou oggnpSp eup vcln?l vuonuls IE
slulouroul oJCBsq yaceldls uup 6e(ueuls gor.I-ocuJ Do^orurueul gbnplsullou Cnup LN
slelouraul oJCBsg gacaldls uup 4e(ueuls go;Jouslltneuc(, qeneloduaul gnup ts
g nuruu&,og gr8urgcuul ycconulluS dolrcres t9-z0
Noles lo lqe crusucrsl slEleuauls
7 t-co

======== Page 8 ========

WN{,ISTAY IOrt,N JONN
,fII,
uwNctvl.srvratlCurrs uou rHlf lsyu gNoso rlsr (sclf{rssau z0zI
ugdour od JHg SOnNCII'
Il.ro 3onucrI qes lqa dleesn;e or3d;aseulruS ]qe ;alcog 1o3e1qar \v,l]q ]qa UUEucIE[ slElelreuls Jor lqe xacr
EUPOP EISI CACAUIqOJ' ZOZI *,ILIJIL PISCIOSO 1JLO SON;CES'NIIIrZEIIOU BUP q,IBUCAS OJCSSq JOJ AIN*q^,E
JoMu JonuorJ pn;ruB lqe dauop nupa;Jolrer,'
gec48;onup Eup [roJBlrou oJlqa 3onurrI
IAInurqME l6rslrrc] rs srlnelop ru JoulJe[ dJolruco oJze]uqte'.i.: ltas oua qnupJop eup UU{ lrlourolJos
\i/asl oJJpSBIE crl{,,, lqe czdrluJ oJzltuqte' {rnuq\r,p prslJrcl sqeJos qoJpeJs \v/llq 151>e(eue tu lqe u,esl'
11azqr-1ezqr, gqrqn{nurr eup N,rr.r^elu ru rqe gontH' curqouqo ru ]qe uoyq ausl' 153eqrt,e eup ;eseurde
ZL"
lo ]qe NoUq. l1 ts locetep qel^\,oeu lou8rlnpes ZS.lg. eup V0, eesl oJ CJaoUMrcq uer.rpreu uup
qol(/aeu 4og. eup lgos6, sonlq oJlILe Ebnrlo;'
rqo prslrlcr rs cm.;aulI{. pwpep ru]O 1rt,o )7( couslrlnorrcros ueueJ(, Nlnuq\y/E Eup NBuSorue' aqe
couslrlneucras pre Jnuqer plnpep rUI:o l6 ?pururslrulr^o r,,/,erps'wnutg\r,.e qus eler,eu )11( n',ur.ps \\/qIJq
ruclnpe
141dnsn, yulrr,,euxaurqe, yelurleurqo. 14rtnurge, Sqlurqlzql, lnynlcoue, 15etuqe1u' 1n1e1e' 3qrqo1(.o'
puJnrzrt,r, l5zynsuu8e' 15eu3oue qes alsql )s( i5uynqeupu' 3qoute' 5eezr*v' 3qlse;n' yr{,ooKe'
gqrcqeuzn, l5eu8ouu eup Ne{eselp.
lhnuq\r,,B llle lqa rosl oJcoulreJ dronruce Jres ou u qIBq dlelaen mtlq eu une;u8e ele^ellou oJ IZ00
ruolaJs gqolo seB lo^el' Jqo lodoSr.edq(, rs u-ros]1X r.rsruS eup gp11u3 mltoso utouolou( ts tuler.rndlap q(
rsolulep qrlls urepe nd drapounueullX oJ^uJrons rulr.nsIAe HooI DJeullolp 3ourd1ex, es ^eII Bs oxleuSIAe
zoues oJ tJou oxtpe redlecatueul'
Jqe 3eue;p leupscede rs lqui oJe 8aut1(.s1odru3 d1u1een' 11otler,e;'tqa €lttlnpo pt.ods coustpereqlX e1
Jrs sonrqeru qorpeJ \!,lrq rqe )Byro uuls. )BJne ur^aJ Jo;urs }qe prslrrct,s qonupu:{, mrlq 1;eseurde
crslJrcl qeJor.e il qrsecls lqa prslJrcl' V unuqoJ oJ slJoBu.rs ru lqo re8tou ot-t8ruule tu lqe 3;uss dletus
:JiIl;##'"'';'T;i f 'o ,,u ,o ,,,
zewgte qgs lqreo prslrucl e8ro acoyoSrcul ;p8rous' ge8rou 1 JecoIAe less lqeu gggruru dal Euunrn oJ
JT€ UJEJJ uup qus 1oeut{ 1o c1e{ sorls' AlqrJo ra81ou 11 Jecerles qelr'iaeu 800 ]o I'000uur oJruruSell da;
uurtnur rvifl{r lpraJeul JeurJe dyuleun sorls' 1usl1X';e8rou 111 Jocor,los uoJa lqeu l'000ulu ;uru3p1 de;
uuunIl1 rv,1lq ner.{ psed sorJs eup suup( c1u(,Joeu'Jqo qnl) oJc3ulrul dror,tuce tuclnptuS lnuq^{,e lles
lu re8rou 11'
dOdNI'VIION CISIUISN.JION
1qe ule;e8e dodnlellou peusrl(, og {^]nuqme prslrrc} Es oJ }{to 2000 dodnleltou cousns sleups ?1 9'9
deodle de;sbne;a yrloua}or'Jqrs g8nre rs paJr^ap gour l{ra loleI ptsq.rcl dodnlelrou o3lS8'89I oJ
.V/qrcq 76,999 ma Jeuelos eup L6'L6g ete ueles' ou lqe olqeJ qeup geutlg slelrslr3s eslr]rtele lqe
dodnlelrou uiztv,Lgz )tl,bgL uu1es' 1g1' ,(69 laurpes(' lqase ^urrl€rous ru dodnluqou g8nr'es cuu
;l::JI#;". rugnouco ou pe^alodu.roui dJoarpuuros ru rqe prslrrcl sruoo sarltcos \trLII uol qe dro^lpep

======== Page 9 ========

,f
IHNWSAV IOTAN .
JOONJII.
{INVNCM'SJVJSLSNIS dOU IHA AgyU gNOgO eIsJ OS3SWSA,fU Z0ZI
ugdOUI Od .JHg )OON,fII'
lArtnuq\te.s selllauaul dugeru ys urosp{ prsdersep \r/rlq € lol oJrsolelep qouestesps' JqeJe "Jo qot,elo:'
soulo lrueeJ seuJeueuls esdecrull( pouS tqe 1nSE)-€J6ouBn goep' rt^lnuq\^e -lguploss 3oruoJ uosp
uup o}{raJ JeopeJ r.oups' gr8q couceulJulrous oJtqo dodnlellou EJe Jonup sronup lqe lomusqtdo llzu8outt
eup qlpnsuu8e eJeus' .
JqeJe rs loceJrzep d;essnre gor leup JoJ seuleuteul eup cnllJlellou ru Wnutq\AE' JqIs Is uol qo\l,eleJ pno
lo ]qe Jec] lqp] onl oJB rtotel oJZe'go0)uz oJIBup slr8qp(, less lqeu q?IJrs droleclap Jol.ost )I l'200)uz('
NepoUBI 4up>s' gurue 141uue8euau1 VJeEs u€ p CoJeNs'
Jqe eppross oJlqe l.e8lslar.ep oJgca oJl4lnurq ^E Jo\y/u ConucII )1rp13( ts es Jollo^^s:
J{.ro 3r^r3 cau4e .
lupedeupauce V^oune go?p
d o gox 8t000I
ihnrtngh/V
3orudosrlrou oJ lq e Conucrl
yrnuq\!,B Jo(/u JonucrI rs u qop( co;dorele esrteqlrsqop nupaJ ylircla I St oJlqe Couslllnllou oJZBUqIE
)yuaupuerp( ycl No'Z oJZcrg eup soolrou 9 oJlqo I.ocEI go^erurllou} vcl' l66I )ed Z8I oJl{re I'?tt,s
o].zBuqr'€ Vs e I'ocel yn1qojl(,' lqe Jor,u JonucrI upurrursloJs lqe lAlnutqr.l,B CrslJrcl'
Jl.ro ConucrI rS coudosep ogeu eleclep 3onucrI Jlrpr;de;sou uup eloclep 3onuct1ot.s' qo\&,e^oJ
ru 1qe {,eur" nupeJ Je^ro\r, sruce }qeJe r/es e DeuaJBI glec}rou' Jqe I'ocel vn1qort1{ rrres
uuueSep gK z lqo UJsl \v/es u.oUL feuncrK 7971 1o 16u(,zozl 'V/qau rJ \\iEs prssol^oP
)onucrJs(
u€ p e ued/ 3onucrJ mes eJeclep ]o oJgce ru yn8nsl ZOZI lo seJAo u gne-(,ee: 1a;ur nd lo ,TOZ9'
Jqo 1rce 3qerrdarsou \^s€ eleclep {ou.r Bu.rorLS }qo 3onucrloJs lu,TOZI JoJ t{le derrop oJu^o
?up l.rsIJ{e8rs

======== Page 10 ========

t
urNurSIAV IO\AN JONNJII'
dINVNCIyI STYIX{,SNIS {.OU rHA ^SYU ,fNI(lfO eIsI CgSgWgSSU Z0ZI
UlfdOUr Od IHlf SOnNCII'
ConucrloJs r&.qo seJlap J{out l-llurmK 7971 1o 16e(,ZOZI MeJo:
SUN NVINS csNo g ' u dOSIJION {\/YUq
I cJEcrons s'HBurslule WBla 14rte(,o: 15o1 eddlrceqla
Z Jla^aJ lleuoou8u rth8le 6ednQ, 141e,for l5uu8oue
e JJrBJlro lBsnruo IhEIO conucIIJoJ CqoULB
V loues sqnuqolu i4ynlnu8e rthBIE JonucIloJ )Bu"r[U€ 'Iqo
g 4oqq sqnudoupo . iAII€A Jonucllor 141Xoo(,a
9 JleB^oI 141nyeu8u rtAIBIE JonucrlloJ )eez$iS
L IArtBuPs gt,eupu rtAIBIO Sonucr[OJ Sq{UqHF
g zeULqMa s{rBur?upr rthI€E conucrlloJ Nsln^\\,r
6 s]elE g')qlfoupE ceUtEle Jonucrllor NU€ tqBlE
l0 do ME s'gomue WI€E conucuroJ sqrcqEuzn
.
I I osceJ snsr.)n WBIE 3onucrJloJ I'nt€lo
lZ I.uupsou gzu8trredo IhEIO ]onucIloJ 1;e1rt,eu(.euqe
le 3qae lpzutoo,fe WI€E Jonuc[[or J{rlsBln
Iy losedq 3quXeure WEIE SonucmoJ i5elnsuu8e
lg Huurq"ze O'l6nuXnruqrt,e rtAIBIg 3onusrlloJ NBJ)BSEIB
l9 JnIDII JA .eU,Iqo ' IAIBIE JonucrlloJ 14lndoue
lL gnrno{ Hlcqqtn rthI€E SomlclloJ NelnqBupB
{^Inutq"
lg wo^au JqBseuaue rtAIBle JonucrlloJ
l6 3qr.slodqer SIuqnu-!I rt\rtule JonucrlloJ ):qtqo4o
]nrr"
ZO yru8sle(,yrnqqmaule ' JonucrlloJ y4ldnsn
ZL Sl.rIInULqeJqlqEruqE WBIE souror cqreJ sqEIDuqIq 15o1 eddlrcuqle
ZZ gnupu(,14yoouo . WEIE cqqJl^loouo 15o1 eddqcuqla
ZE J.oouBrp )eloute rtArtulo cqleJxElupn 15o1 uddyrceqle
Jqe CIslJIcl ulso qes t^o )Z( oleclep lauqeJs oJ derlreutoul ouo JoJ l4lnruqme JouIeI 3ouslyneucK
eup tqe olqar. Jor Npu8o;ue 7ous1l1neuc(,' 1qe {reuqeJs oJ dEJlreueul lqpl qelp oJuco {our 1uuncr(,
7971 1o rtyeK ZOZI .,.,ote:
SU\t NYIAIlf cgNqgu JONSIIIOgNSA
I gou:31epo l5eufnne rtAIBIE I InUtq\^E JoUJBI
Z 11ou'golp Huu.lisoupe rth?le l5eu8ouu
Jl.re EJJr€rs oJ Jeulrel r5olerurlleu} lu lqe pls}rlp ur'e coorplu"}ep q{ tqe qls]rlc] Cowu,rlsFouer I rr'
galrx ppodn rv/us lqe ICJslJJcl CourulssroueJ JoJ ImuqrAE qls}Jlcl gt.ow pnJruE lqo reBJ nupaJ JeAIiM'
n

======== Page 11 ========

W0thSl ,I.O\!/N JOlfNSII'
r"[.rVt.rClVrSIYISIhSN.JS dOU JHS ASVU gNI(gq tIs (3OSW3SSU Z0ZI
ugdouJod JHs conNcrT
Jqo ]onucrJlors {,qo qolp oJucs {ou yn3ns1 zozl to qecelitqer z0z I h/ere:
S/N NYI Ilf csN(su dOSIIION
{AvuI(
I JqBrlle l ]Esnuro rt4l3le oonucrI 3quu.dersou {Io1 uddquqle
Z I.eupsou geu8rr,,edo IhEIE qednif Jonuc I Cqeldersor ye1rt,eu{euqe
t lnqqpp geor;r"e(,1 ' rthBIE SonuclloJ 141ndoue
n vulos JnleUtB rthEIE SonucrlloJ )BurrIBIugo
g slr4.uq\I/uruq\\,e dues I IEIE JonucIIloJ )eAz-\AE
g SIBJnUpB Jre^or IAI?IE conucrlloJ qleu8oue
L 3qn"r(,ulre losedq rth?13 SonucFIoJ l5ulnseu8e
cqoltt"
g Jlrlloutqe qeqq{ rt IBIA Somrcllor
t
6 snsrlD oscet - rthBIE Sonuclllor I'MBIE
l0 sqeruquuB yn8nstqe 3 rt IBIE conucllor NBruqEq
I I lArto^ou cqBseurouE rtAIBIO eonrrcFJoJ Inu.rqB
lZ Hlclputn gn;ao(, WBIE SonucFloJ NBlnqBupE
It
):{rrlN/eupe ynple{, daU(Ble conuclloJ NeIPsel)e
ly q,rtoou8u SE^ronJ W rtAIBIE conucrllor NEl)BsI€e
IS 141oo(,u nlolB deu.rJ€ e SonucIJoJ 3qtq04o
lg 16nnurdn1>e guerst WsIE SonrrcrlloJ lrrtdnsn
IL gqrudoupo rthol^lu rtn"le conuclloJ yr(,oo(,a
lg wnqq vnpr.rrro N WBIA SonrrcrlloJ sqrcqEeuzn
l6 11euoo(,e 34n,e rtAIBIE Somrclllor SqISEln
zo sl[Bursupr ZEULqMe rtAI?la JomrcrlloJ NelnA\Ar
fBu.rrl"
cr snleulBu JAI rthl€e Jonurllor sqqqtzqI
,TZ Hrrupln\r/BuI JIIJJoTp rtAI?le JonucIIJor lhElBIB
zt Sqrl)nutge Sl.rqeluqe rtAI?le seuror cqleJ Sq"IDUqIIE sqBlnutqrlB ,fqleJpo
l^rtnleupeul"
Zy 14rtnse 4nu(,uuru rtAIBIE Sl.rlaJ IAInleupeu.rE cqleJp)
ZS gep1e(,3qlqnlnutE rt^I?le c{rJeJ cqJqnlnu.rE SqllcnlnurB JqleJpor
Jiro qrslrrct EJso qes lnro )Z( eleclep yrouqeJe oJdJ€ lreueul oue JoJ ^lnuqn/B JoulJeI cousltlneuc( uup
lqo ol{roJ Jor. l5eu8ourz 3ous1r1neuc(,' Jqe rthauqars oJdEJlreueul lqel qelp oJuca pnrtuS lqa (,eu; r*rore:
S/IN NYIAIlf caNolfu JONSIIINSNJA
I ]lopo 15eufnrvre WEIE I InuqaE ceulrBl
Z Sollrus Nzo^n . rtAIBIE lleuEoue
J1re pJJerrs oJ JaulJBI coloJurueul lu lqa plslrlcl J€ e coorpruelep q(, 1qe Clslrtcl 3outu(lsslouer' qn;tu3
lqa {.eer nupsl.JoArorA WJ' delrx 15podn ^\,ps lqe CrslJrcl CoututlssloueJ JoJ lhnulqM€ clslJlcl'
Jqe secJolpJrul oJwnuqr,e Jo\^u Jonucrl rs q6p€ op q(, lqo 3onucrl sec;elur(' 1qe conucrI Sacre1er(,
eup lqa Jesl oJlqe SeJJeJeJrl€ BJe eddotulep q(, lqe I'ocBI Co^swlueul sor^lca Coututlsslou'
Jqo JonucrI gacralet{, rs ussr6ep q(,gont )y( Heups oJpedeyueuls uuruel{, gtuuuca' 61euutu3' Alorls
eup vpururslJerrou JoJ lqo suroollL oda;e]1ou oJ lqo oonu)rI erLp e unuqoJ oJ nulls ueruel( 1a8e1'
4;ocn;euraul,dnqllc Haullq pup
Couunurl(,go^eloduoul.
s

======== Page 12 ========

wnurlftt/Y IO\AN ,fOnNlII'
fir.rFrL5ivr srv,Jgursurrs r.ou rHs Agvu gNogI( eIs I(xOsI^luslfu z0zI
UlfdOUJO{.IHrt
JONNSII.
dnurllous oJlqa conuJJl .
Jqo urgru Jnuclrou oJlqo conuclJ Js lqo peJrr,e&, oJ locBI dnqlrc 8oops "up seJAlces lo lqa deodle tu 1qa
crslJJcl uup prscqer8e uJJ or eu(, ogtqe Jnucllous sat onl lu vulcle lta oJlqa Cousllrtyrou oJ zmuqte
)yruoupuauls( yc1 No'z oJzcrg eup seroup scqapnla oJ JEd zgr oJ lrre I'eh/s oJ zewqtz \v/qrcq
rucJnpe, uruouB olqars. dor,er lo utulo g(,-1zms' doma; 10 utule rs8nleltous' turdostltou o31eates' Jeas
uup cqe;6es uup lo JoJurpele' locul doJrcras 1o droruole' 8nlpe eup ;e8nlpo pe^olodueul tu 1qa plslJlcl
tqron8q lurrons relenuul pedeurueuls oJlqe 3onucrl'
CJuPuclsI uosnlls
zozt 20,70
xr^EJrrB xrABJqB
3usq yacadls tl,gzo,o t zz'Llg'bgL
4u(.ueu1s -aTg6TitT
ztditts-
lurro'saT)pacr"euse( ru J'srr Bup c,sq gbn;auleuls --ifETlT -iff.'EET?6'?6
yaf 4o1;c;as ypodlap qnr.;uB lqa AaBr
Iqo ConucrI prp uo1 epodl uu(, 4a(, dollcres pnrruS 1qe (om.:
galulep 4ur.1{ IJEusErlJous
J{reJe \v/eJe uo r.alulep deg(, lJ,useclrous pnrrira 1qo gueucrzl (eur'
4;oda;gr6 dJEul uup gbn;dueul
J{re ConucrI dnr.cqusep d;ode'u(,, d1uu1 zup abmdueul euonulluS 1o yg'tl9f60
15o dl.oda;e,, d1eu1 uup ebnrduaul me:a prsdosep ogpnuuS lqe {eer-'
1u1uuB;q1a yssels
JI.reJo ,4AaJa uo dmcqs€ es oJ ruleu3lqle essels pnrruB lqe
Ieur..
gurdlo(raas
][#'iff?:ifflir':;j;iffrll:r119;l:t^rrr'vs rtz. Jqo rol,r e,*onur sdeul ou aurdlo(eas,
HaEllJr Bup geye1(, o;grud;o(zaas
Jqa ConucrJ rs ur^uJe or;.r1s resdousrqrJrlles Je8mpluS lqa seigal(, uup qeellq oJourdlo(,aes zs d;ascuqep
Ju lqe gccndproup. gaellq uup geJe1(,yc1 No.E9 oJz0t0 uup loo{ uddrodrlela ues€ nres lo sege8nerp
lqe1; se:ga1{ eup
qeulW,
[ocJoBlros I
Tl:'j:d, ,nuuB lqe gueucrp (,eur *lnrrr, ,tgo,zgt lo ^BJps sdousol.ruE Ar€rons sdouluS
3o;dor.ule SoclBl gasdous;q;1;1(,
;#:jt""*r, ,r, uol ,..el>o pouelrous pnrruB ]qe (,eur,lor/J€ ps lqo snddou oJAJ€ rons socre11(, resdousrqle
9

======== Page 13 ========

WOWS$/Y JO\AN JO0NCII'
UfNVt.rCtVr SIVJSTIISNJS dOU IHS ASVU gNqSO tls Olf)XlngSSX Z0ZI
ugdouJ od JHg ,fOnNJT
vnpllors
lu lruo ^Jlq vulcla zg0 oJ lqo Jous4lntlou p Teuqre )yureupruaut( vc] No'z oJ z0 I g' lqe ]onrlcll ls
enpllep q(,lqe ynpyoJ-gauareJ
'
gF orpar oJl{re conuclI .
u3dngnS od zwliiffv
rtx 0J D0Asw
l'y(3d'1'
ifnlF8lltv tott,dl SOnNJtl
t $ l'i'Y,l ZCII
Ci{ tt (i r": i 1'JI ill'l :ri ,d i;91;$)-($$
li$' G]1,X s[0ff0I'
i\r}'{H,c.,1?1'
L

======== Page 14 ========

IhNI\,IB{,V JO\T1N
uw[rlvr s.rvJs C w O n N N N J J s I I. Jou r , Hs t,,svx gNogtr rlsr tra3g{ragJ'u z0zI
SJYISIAISNJ Od UlfSdONSIBII'IJI lfS {.OU YN NOYT dT NYN3IVT SJYISIAIlfNJS
Jqe {/nurg\y/E Jo\r/u JonucrJ rs Jesdousrqle go; lcl.ader.ruS lqs JluEucIEI sleleutouls loJ lqe (ezl" oupep
e l * cacawqe\ 7971 {^qr3q eJo {ea {our uEleJrEI u[ss1u1erueu1' h/qe}qeJ pno }o {pnp oJ a;JoJ' Eup EJe
dl.eder.ap, ru p1 ur?loJr?l l.asdecls' 1u uccoJpEuce r^llg lqo cEs{t gBSIs luloJusllouJ€ dnqllc secloJ
vcconunuB sluuperp )IdSvS(. Iu d;edupuB lqe gueucrzl slelaueuls, 1qe ConucrJ salec}op eddllcuqle

## CLEANING OF RAW DATA & DATASET CREATION
The raw data collected in previous actions is now cleaned and exported to three of the following created datasets:
- council administrative data.csv
- ward development committee information.csv
- public council resolutions.csv

In [26]:
COUNCIL_NAME = "Mumbwa Town Council"

#Functions
def clean_text(value):
    #whitespace/newlines removed and return a clean string.
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()

def extract_year(value):
    #Extracting a 4-digit year from a title where possible
    match = re.search(r"\b(20\d{2})\b", str(value))
    return int(match.group(1)) if match else pd.NA

def remove_upload_text(title):
    #Removing 'Uploaded on...' text from publication titles.
    title = clean_text(title)
    title = re.sub(r"\s*[–-]\s*Uploaded on:.*$", "", title, flags=re.I)
    return title.strip(" -–")


#COUNCIL ADMINISTRATIVE DATA
admin_records = [
    {
        "council_name": COUNCIL_NAME,
        "record_type": "department",
        "category": "Institutional Management",
        "description": "Consists of the principal officer, the Council Secretary, as well as procurement and audit sections.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=770"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "department",
        "category": "Planning",
        "description": "Plans the overall layout of the district, upgrading of shanty areas, township boundaries, standard building plans, land distribution, title deeds, HIV/AIDS, gender and human rights sensitisation, community development activities, and public health.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=770"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "department",
        "category": "Engineering Services",
        "description": "Facilitates feeder roads, borehole drilling, inspection of buildings, scrutiny of building plans, burial sites, fire brigade services, and maintenance of plant and machinery.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=770"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "department",
        "category": "Finance",
        "description": "Collection of revenue, preparation of statutory obligations, and preparation of books of accounts.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=770"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "department",
        "category": "Human Resource and Administration",
        "description": "Staff establishment, asset management, records keeping, training and development, recruitment, staff appraisals, minutes and report writing, discipline, conditions of service, and public relations services.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=770"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "department",
        "category": "Fisheries, Livestock and Veterinary Services",
        "description": "",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=770"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "department",
        "category": "Agriculture",
        "description": "",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=770"
    },

    # Services extracted from the Services page
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Infrastructure and Administration",
        "description": "Establish and maintain offices, buildings, public meeting facilities and assemblies needed for Council administration.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Law, Order, and National Security",
        "description": "Maintain law and order, safeguard national security, and promote efficient governance within the Council jurisdiction.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Advertising and Public Spaces",
        "description": "Regulate and control advertisements and advertising devices visible from streets and other public areas.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Animal Welfare and Livestock Management",
        "description": "Regulate livestock movement, animal slaughter, meat certification, disposal of diseased carcasses, hygiene in abattoirs and cold storage, animal by-products, and transport of carcasses.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Transportation and Road Safety",
        "description": "Develop and maintain road infrastructure, regulate traffic and parking, and implement road-safety measures.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Public Lighting and Utilities",
        "description": "Establish and maintain street lighting systems for safety and accessibility.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Business Regulation and Licensing",
        "description": "Inspect business establishments and enforce compliance, including regulations concerning the sale and consumption of intoxicating liquor.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Housing and Urban Development",
        "description": "Construct, purchase and maintain buildings and facilities for residential accommodation and encourage adequate housing development.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    },
    {
        "council_name": COUNCIL_NAME,
        "record_type": "service",
        "category": "Land Use and Environmental Management",
        "description": "Regulate land use and building construction for public health, safety and orderly development, including demolition and removal of buildings.",
        "source_url": "https://www.mumbwacouncil.gov.zm/?page_id=792"
    }
]

council_admin_df = pd.DataFrame(admin_records)
for col in council_admin_df.select_dtypes(include="object").columns:
    council_admin_df[col] = council_admin_df[col].map(clean_text)

council_admin_df = (
    council_admin_df
    .drop_duplicates()
    .reset_index(drop=True)
)


#Ward Committe Information
wdc_pattern = (
    r"\bward\b|"
    r"\bWDC\b|"
    r"\bcommunity\b|"
    r"\bCDF\b|"
    r"\bstakeholder\b|"
    r"\bdevelopment\b|"
    r"\bproject\b"
)

wdc_info_df = publication_df.copy()
wdc_info_df["document_title"] = wdc_info_df["document_title"].map(clean_text)
wdc_info_df["document_url"] = wdc_info_df["document_url"].map(clean_text)

wdc_info_df = wdc_info_df[
    wdc_info_df["document_title"].str.contains(wdc_pattern, case=False, na=False, regex=True)
].copy()

# Keep actual downloadable/informational records, not menu links.
wdc_info_df = wdc_info_df[
    wdc_info_df["document_url"].str.contains(r"\.pdf($|\?)", case=False, na=False, regex=True)
].copy()

wdc_info_df["title"] = wdc_info_df["document_title"].map(remove_upload_text)
wdc_info_df["year"] = wdc_info_df["document_title"].map(extract_year)

def classify_wdc(title):
    t = title.lower()
    if "community project" in t or "proposed" in t or "project" in t:
        return "community project"
    if "stakeholder" in t or "minutes" in t:
        return "stakeholder/community meeting"
    if "cdf" in t:
        return "CDF"
    return "development information"

def identify_constituency(title):
    t = title.lower()
    if "mumbwa" in t and "nangoma" in t:
        return "Mumbwa Central and Nangoma"
    if "nangoma" in t:
        return "Nangoma"
    if "mumbwa" in t:
        return "Mumbwa Central"
    return ""

wdc_info_df["information_type"] = wdc_info_df["title"].map(classify_wdc)
wdc_info_df["constituency"] = wdc_info_df["title"].map(identify_constituency)
wdc_info_df["council_name"] = COUNCIL_NAME

wdc_info_df = wdc_info_df[
    ["council_name", "year", "information_type", "constituency", "title", "document_url"]
].rename(columns={"document_url": "source_url"})

wdc_info_df = (
    wdc_info_df
    .drop_duplicates(subset=["title", "source_url"])
    .sort_values(["year", "title"], na_position="last")
    .reset_index(drop=True)
)

#Public Council Resolutions/reports
resolution_sources = publication_df.copy()
resolution_sources["document_title"] = resolution_sources["document_title"].map(clean_text)
resolution_sources["document_url"] = resolution_sources["document_url"].map(clean_text)

resolution_sources = resolution_sources[
    resolution_sources["document_title"].str.contains(
        r"\bminutes\b|\bresolution\b",
        case=False,
        na=False,
        regex=True
    )
    & resolution_sources["document_url"].str.contains(
        r"\.pdf($|\?)",
        case=False,
        na=False,
        regex=True
    )
].drop_duplicates(subset=["document_url"])

resolution_keywords = re.compile(
    r"\b(resolved|resolution|agreed|approved|adopted|recommended|decision)\b",
    flags=re.I
)

resolution_records = []

for _, row in resolution_sources.iterrows():
    title = remove_upload_text(row["document_title"])
    url = row["document_url"]

    try:
        r = requests.get(url, timeout=45, verify=False)
        r.raise_for_status()

        with pdfplumber.open(BytesIO(r.content)) as pdf:
            for page_number, page in enumerate(pdf.pages, start=1):
                page_text = page.extract_text() or ""
                page_text = page_text.replace("\r", "\n")

                candidates = [
                    clean_text(line)
                    for line in page_text.split("\n")
                    if resolution_keywords.search(line or "")
                ]

                for statement in candidates:
                    if len(statement) >= 20:
                        resolution_records.append({
                            "council_name": COUNCIL_NAME,
                            "year": extract_year(title),
                            "source_document": title,
                            "page_number": page_number,
                            "resolution_text": statement,
                            "source_url": url
                        })

    except Exception as e:
        print(f"Could not process resolution source: {title}")
        print("Reason:", e)

public_resolutions_df = pd.DataFrame(
    resolution_records,
    columns=[
        "council_name",
        "year",
        "source_document",
        "page_number",
        "resolution_text",
        "source_url"
    ]
)

if not public_resolutions_df.empty:
    public_resolutions_df["resolution_text"] = public_resolutions_df["resolution_text"].map(clean_text)
    public_resolutions_df = (
        public_resolutions_df
        .drop_duplicates(subset=["source_document", "page_number", "resolution_text"])
        .reset_index(drop=True)
    )

# Export to cvs and preview
council_admin_df.to_csv("council administrative data.csv", sep="|", index=False, encoding="utf-8-sig")
wdc_info_df.to_csv("ward development committee information.csv", sep="|", index=False, encoding="utf-8-sig")
public_resolutions_df.to_csv("public council resolutions.csv", sep="|", index=False, encoding="utf-8-sig")

print("Created:")
print(f"1. council administrative data.csv -> {len(council_admin_df)} rows")
print(f"2. ward development committee information.csv -> {len(wdc_info_df)} rows")
print(f"3. public council resolutions.csv -> {len(public_resolutions_df)} rows")

print("\nAdministrative data preview:")
display(council_admin_df.head())

print("\nWDC information preview:")
display(wdc_info_df.head())

print("\nPublic resolutions preview:")
display(public_resolutions_df.head())

/tmp/ipykernel_2175/3188244587.py:174: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  wdc_info_df["document_url"].str.contains(r"\.pdf($|\?)", case=False, na=False, regex=True)
/tmp/ipykernel_2175/3188244587.py:227: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  & resolution_sources["document_url"].str.contains(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Created:
1. council administrative data.csv -> 16 rows
2. ward development committee information.csv -> 10 rows
3. public council resolutions.csv -> 119 rows

Administrative data preview:

,council_name,record_type,category,description,source_url
0,Mumbwa Town Council,department,Institutional Management,"Consists of the principal officer, the Council Secretary, as well as procurement and audit sections.",https://www.mumbwacouncil.gov.zm/?page_id=770
1,Mumbwa Town Council,department,Planning,"Plans the overall layout of the district, upgrading of shanty areas, township boundaries, standard building plans, land distribution, title deeds, HIV/AIDS, gender and human rights sensitisation, community development activities, and public health.",https://www.mumbwacouncil.gov.zm/?page_id=770
2,Mumbwa Town Council,department,Engineering Services,"Facilitates feeder roads, borehole drilling, inspection of buildings, scrutiny of building plans, burial sites, fire brigade services, and maintenance of plant and machinery.",https://www.mumbwacouncil.gov.zm/?page_id=770
3,Mumbwa Town Council,department,Finance,"Collection of revenue, preparation of statutory obligations, and preparation of books of accounts.",https://www.mumbwacouncil.gov.zm/?page_id=770
4,Mumbwa Town Council,department,Human Resource and Administration,"Staff establishment, asset management, records keeping, training and development, recruitment, staff appraisals, minutes and report writing, discipline, conditions of service, and public relations services.",https://www.mumbwacouncil.gov.zm/?page_id=770

WDC information preview:

,council_name,year,information_type,constituency,title,source_url
0,Mumbwa Town Council,2018,development information,,The-Constituency-Development-Fund-Act-No.-11-of-2018,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Constituency-Development-Fund-Act-No.-11-of-2018.pdf
1,Mumbwa Town Council,2022,CDF,,CDF-Report-2022,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/CDF-Report-2022.pdf
2,Mumbwa Town Council,2023,CDF,Mumbwa Central,Press Statement Mumbwa CDF,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Press-Statement-Mumbwa-CDF-Nov.pdf
3,Mumbwa Town Council,2024,community project,,2024 Approved CDF Community Projects,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/2024-CDF-COMMUNITY-PROJECTS-AS-AT-31ST-AUGUST-2024.pdf
4,Mumbwa Town Council,2024,stakeholder/community meeting,,2024 Minutes for the Stakeholders Engagement Meeting With Business Community,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/Minutes-for-the-Skaeholders-Engagement-Meeting-With-Business-Community-Held-on-5-July-2024.pdf

Public resolutions preview:

,council_name,year,source_document,page_number,resolution_text,source_url
0,Mumbwa Town Council,2023,"MINUTES OF THIRD ORDINARY COUNCIL MEETING OF 9TH OCTOBER, 2023",8,would be resolved quickly by relevant authorities.,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MINUTES-OF-THIRD-ORDINARY-COUNCIL-MEETING-OF-9TH-OCTOBER-2023.pdf
1,Mumbwa Town Council,2023,"MINUTES OF THIRD ORDINARY COUNCIL MEETING OF 9TH OCTOBER, 2023",9,2023 be Received and Adopted as part of,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MINUTES-OF-THIRD-ORDINARY-COUNCIL-MEETING-OF-9TH-OCTOBER-2023.pdf
2,Mumbwa Town Council,2023,"MINUTES OF THIRD ORDINARY COUNCIL MEETING OF 9TH OCTOBER, 2023",10,Received and Adopted as part of the proceedings of,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MINUTES-OF-THIRD-ORDINARY-COUNCIL-MEETING-OF-9TH-OCTOBER-2023.pdf
3,Mumbwa Town Council,2023,"MINUTES OF THIRD ORDINARY COUNCIL MEETING OF 9TH OCTOBER, 2023",10,Adopted as part of the proceedings of the,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MINUTES-OF-THIRD-ORDINARY-COUNCIL-MEETING-OF-9TH-OCTOBER-2023.pdf
4,Mumbwa Town Council,2023,"MINUTES OF THIRD ORDINARY COUNCIL MEETING OF 9TH OCTOBER, 2023",11,Received and Adopted as part of the proceedings of,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MINUTES-OF-THIRD-ORDINARY-COUNCIL-MEETING-OF-9TH-OCTOBER-2023.pdf