In [ ]:
%pip install --upgrade certifi requests urllib

Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (2026.7.22)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
ERROR: Could not find a version that satisfies the requirement urllib (from versions: none)
ERROR: No matching distribution found for urllib

In [ ]:
!pip install pdfplumber pypdf

Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.4 MB/s eta 0:00:00
Collecting pypdf
  Downloading pypdf-6.18.0-py3-none-any.whl.metadata (7.5 kB)
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 5.1 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 50.5 MB/s eta 0:00:00
Downloading pypdf-6.18.0-py3-none-any.whl (393 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.8/393.8 kB 25.9 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 78.2 MB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 95.0 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pypdf, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdf-6.18.0 pypdfium2-5.13.0

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO
from urllib.parse import urljoin
from urllib.parse import urlparse
import os
import pdfplumber

In [ ]:
url="https://www.mumbwacouncil.gov.zm/"

In [ ]:
tracker_url = "https://www.mumbwacouncil.gov.zm/?page_id=932"

tracker_response = requests.get(
    tracker_url,
    verify=False,
    timeout=30
)

tracker_soup = BeautifulSoup(tracker_response.text, "html.parser")

print("Status:", tracker_response.status_code)
print("Tables:", len(tracker_soup.find_all("table")))
print("Links:", len(tracker_soup.find_all("a")))

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
Tables: 0
Links: 114

In [ ]:
tracker_links = []

for link in tracker_soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(tracker_url, link["href"])

    tracker_links.append({
        "text": text,
        "url": href
    })

tracker_links_df = pd.DataFrame(tracker_links)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

display(tracker_links_df)

,text,url
0,,https://www.mumbwacouncil.gov.zm/
1,Home,https://www.mumbwacouncil.gov.zm/
2,About,https://www.mumbwacouncil.gov.zm/?page_id=932
3,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
6,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
7,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
8,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
9,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
10,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
11,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
13,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
14,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
15,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
16,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
17,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
18,Media Center,https://www.mumbwacouncil.gov.zm/?page_id=932
19,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
20,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
21,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
22,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
23,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
24,Home,https://www.mumbwacouncil.gov.zm/
25,About,https://www.mumbwacouncil.gov.zm/?page_id=932
26,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
29,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
30,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
31,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
32,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
33,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
34,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
36,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
37,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
38,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
39,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
40,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
41,Media Center,https://www.mumbwacouncil.gov.zm/?page_id=932
42,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
43,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
44,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
45,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
46,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
47,Mumbwa District CDF Tracker,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-a9139946aa299b19e5ad
48,Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-f138f186aa299b19ff9f
49,2022,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-e3349586aa299b1a18c9
50,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
51,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
52,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
53,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
54,2023,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-23160756aa299b1a18c9
55,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
56,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
57,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
58,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
59,2024,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-0cd37796aa299b1a18c9
60,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
61,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
62,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
63,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
64,2025,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-ba4cca96aa299b1a18c9
65,Community Projects,https://www.mumbwacouncil.gov.zm/?page_id=932
66,2025 Approved Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Mumbwa-Central.pdf
67,2025 Proposed Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-MUMBWA.pdf
68,Skills Development,https://www.mumbwacouncil.gov.zm/?page_id=932
69,2025 Approved CDF Skills Development Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Mumbwa-Constituency.pdf
70,Secondary Boarding Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
71,2025 Approved CDF Secondary Boarding School Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Mumbwa-Constituency.pdf
72,Empowerment Grants,https://www.mumbwacouncil.gov.zm/?page_id=932
73,2025 Approved CDF Empowerment Grants for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Grants-for-Mumbwa-Constituency.pdf
74,Empowerment Loans,https://www.mumbwacouncil.gov.zm/?page_id=932
75,Disaster,https://www.mumbwacouncil.gov.zm/?page_id=932
76,Nangoma Constituency,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-9d5391e6aa299b19ff9f
77,2022,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-fefae236aa299b1ab4a9
78,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
79,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
80,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
81,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
82,2023,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-29af4b16aa299b1ab4a9
83,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
84,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
85,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
86,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
87,2024,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-1aca2996aa299b1ab4a9
88,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
89,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
90,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
91,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
92,2025,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-23ac2676aa299b1ab4a9
93,Community Projects,https://www.mumbwacouncil.gov.zm/?page_id=932
94,2025 Approved Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Nangoma-Constituency.pdf
95,2025 Proposed Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-NANGOMA.pdf
96,Empowerment Grants,https://www.mumbwacouncil.gov.zm/?page_id=932
97,2025 Approved CDF Empowerment Grants for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approve-CDF-Grants-for-Nangoma-Constituency.pdf
98,Empowerment Loans,https://www.mumbwacouncil.gov.zm/?page_id=932
99,Skills Development Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
100,2025 Approved CDF Skills Development Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Nangoma-Constituency.pdf
101,Secondary Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
102,2025 Approved CDF Secondary Boarding School Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Nangoma-Constituency.pdf
103,Disaster,https://www.mumbwacouncil.gov.zm/?page_id=932
104,COMPLAINTS,https://www.mumbwacouncil.gov.zm/?page_id=1935
105,,https://www.facebook.com/mumbwacouncil?mibextid=LQQJ4d
106,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/
107,Local Government Service Comission,https://www.lgsc.gov.zm/
108,Ministry of Finance and National Planning,https://www.mofnp.gov.zm/
109,Ministry of Agriculture,https://www.agriculture.gov.zm/
110,National Assembly of Zambia,https://www.parliament.gov.zm/
111,Local Government Training Institute,http://www.clgti.co.zm/
112,Local Government Association of Zambia Knowledge and Learning Hub,https://www.lgazambia.org.zm/hub/about
113,SMART Zambia,https://www.szi.gov.zm/

In [ ]:
links = []

for link in tracker_soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(url, link["href"])

    links.append({
        "text": text,
        "url": href
    })

links_df = pd.DataFrame(links)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

display(links_df)

,text,url
0,,https://www.mumbwacouncil.gov.zm/
1,Home,https://www.mumbwacouncil.gov.zm/
2,About,https://www.mumbwacouncil.gov.zm/
3,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
6,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
7,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
8,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
9,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
10,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
11,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
13,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
14,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
15,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
16,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
17,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
18,Media Center,https://www.mumbwacouncil.gov.zm/
19,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
20,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
21,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
22,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
23,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
24,Home,https://www.mumbwacouncil.gov.zm/
25,About,https://www.mumbwacouncil.gov.zm/
26,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
29,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
30,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
31,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
32,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
33,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
34,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
36,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
37,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
38,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
39,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
40,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
41,Media Center,https://www.mumbwacouncil.gov.zm/
42,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
43,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
44,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
45,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
46,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
47,Mumbwa District CDF Tracker,https://www.mumbwacouncil.gov.zm/#collapse-a9139946aa299b19e5ad
48,Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/#collapse-f138f186aa299b19ff9f
49,2022,https://www.mumbwacouncil.gov.zm/#collapse-e3349586aa299b1a18c9
50,1st Quarter,https://www.mumbwacouncil.gov.zm/
51,2nd Quarter,https://www.mumbwacouncil.gov.zm/
52,3rd Quarter,https://www.mumbwacouncil.gov.zm/
53,4th Quarter,https://www.mumbwacouncil.gov.zm/
54,2023,https://www.mumbwacouncil.gov.zm/#collapse-23160756aa299b1a18c9
55,1st Quarter,https://www.mumbwacouncil.gov.zm/
56,2nd Quarter,https://www.mumbwacouncil.gov.zm/
57,3rd Quarter,https://www.mumbwacouncil.gov.zm/
58,4th Quarter,https://www.mumbwacouncil.gov.zm/
59,2024,https://www.mumbwacouncil.gov.zm/#collapse-0cd37796aa299b1a18c9
60,1st Quarter,https://www.mumbwacouncil.gov.zm/
61,2nd Quarter,https://www.mumbwacouncil.gov.zm/
62,3rd Quarter,https://www.mumbwacouncil.gov.zm/
63,4th Quarter,https://www.mumbwacouncil.gov.zm/
64,2025,https://www.mumbwacouncil.gov.zm/#collapse-ba4cca96aa299b1a18c9
65,Community Projects,https://www.mumbwacouncil.gov.zm/
66,2025 Approved Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Mumbwa-Central.pdf
67,2025 Proposed Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-MUMBWA.pdf
68,Skills Development,https://www.mumbwacouncil.gov.zm/
69,2025 Approved CDF Skills Development Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Mumbwa-Constituency.pdf
70,Secondary Boarding Bursaries,https://www.mumbwacouncil.gov.zm/
71,2025 Approved CDF Secondary Boarding School Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Mumbwa-Constituency.pdf
72,Empowerment Grants,https://www.mumbwacouncil.gov.zm/
73,2025 Approved CDF Empowerment Grants for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Grants-for-Mumbwa-Constituency.pdf
74,Empowerment Loans,https://www.mumbwacouncil.gov.zm/
75,Disaster,https://www.mumbwacouncil.gov.zm/
76,Nangoma Constituency,https://www.mumbwacouncil.gov.zm/#collapse-9d5391e6aa299b19ff9f
77,2022,https://www.mumbwacouncil.gov.zm/#collapse-fefae236aa299b1ab4a9
78,1st Quarter,https://www.mumbwacouncil.gov.zm/
79,2nd Quarter,https://www.mumbwacouncil.gov.zm/
80,3rd Quarter,https://www.mumbwacouncil.gov.zm/
81,4th Quarter,https://www.mumbwacouncil.gov.zm/
82,2023,https://www.mumbwacouncil.gov.zm/#collapse-29af4b16aa299b1ab4a9
83,1st Quarter,https://www.mumbwacouncil.gov.zm/
84,2nd Quarter,https://www.mumbwacouncil.gov.zm/
85,3rd Quarter,https://www.mumbwacouncil.gov.zm/
86,4th Quarter,https://www.mumbwacouncil.gov.zm/
87,2024,https://www.mumbwacouncil.gov.zm/#collapse-1aca2996aa299b1ab4a9
88,1st Quarter,https://www.mumbwacouncil.gov.zm/
89,2nd Quarter,https://www.mumbwacouncil.gov.zm/
90,3rd Quarter,https://www.mumbwacouncil.gov.zm/
91,4th Quarter,https://www.mumbwacouncil.gov.zm/
92,2025,https://www.mumbwacouncil.gov.zm/#collapse-23ac2676aa299b1ab4a9
93,Community Projects,https://www.mumbwacouncil.gov.zm/
94,2025 Approved Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Nangoma-Constituency.pdf
95,2025 Proposed Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-NANGOMA.pdf
96,Empowerment Grants,https://www.mumbwacouncil.gov.zm/
97,2025 Approved CDF Empowerment Grants for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approve-CDF-Grants-for-Nangoma-Constituency.pdf
98,Empowerment Loans,https://www.mumbwacouncil.gov.zm/
99,Skills Development Bursaries,https://www.mumbwacouncil.gov.zm/
100,2025 Approved CDF Skills Development Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Nangoma-Constituency.pdf
101,Secondary Bursaries,https://www.mumbwacouncil.gov.zm/
102,2025 Approved CDF Secondary Boarding School Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Nangoma-Constituency.pdf
103,Disaster,https://www.mumbwacouncil.gov.zm/
104,COMPLAINTS,https://www.mumbwacouncil.gov.zm/?page_id=1935
105,,https://www.facebook.com/mumbwacouncil?mibextid=LQQJ4d
106,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/
107,Local Government Service Comission,https://www.lgsc.gov.zm/
108,Ministry of Finance and National Planning,https://www.mofnp.gov.zm/
109,Ministry of Agriculture,https://www.agriculture.gov.zm/
110,National Assembly of Zambia,https://www.parliament.gov.zm/
111,Local Government Training Institute,http://www.clgti.co.zm/
112,Local Government Association of Zambia Knowledge and Learning Hub,https://www.lgazambia.org.zm/hub/about
113,SMART Zambia,https://www.szi.gov.zm/

In [ ]:
financial_keywords = [
    "budget",
    "cdf",
    "grant",
    "loan",
    "bursar",
    "bursaries",
    "disbursement",
    "expenditure",
    "financial",
    "revenue",
    "funding",
    "approved"
]

financial_links_df = tracker_links_df[
    tracker_links_df["text"].str.lower().str.contains(
        "|".join(financial_keywords),
        na=False
    )
].drop_duplicates()

display(financial_links_df)

,text,url
13,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
47,Mumbwa District CDF Tracker,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-a9139946aa299b19e5ad
66,2025 Approved Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Mumbwa-Central.pdf
69,2025 Approved CDF Skills Development Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Mumbwa-Constituency.pdf
70,Secondary Boarding Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
71,2025 Approved CDF Secondary Boarding School Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Mumbwa-Constituency.pdf
72,Empowerment Grants,https://www.mumbwacouncil.gov.zm/?page_id=932
73,2025 Approved CDF Empowerment Grants for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Grants-for-Mumbwa-Constituency.pdf
74,Empowerment Loans,https://www.mumbwacouncil.gov.zm/?page_id=932
94,2025 Approved Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Nangoma-Constituency.pdf
97,2025 Approved CDF Empowerment Grants for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approve-CDF-Grants-for-Nangoma-Constituency.pdf
99,Skills Development Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
100,2025 Approved CDF Skills Development Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Nangoma-Constituency.pdf
101,Secondary Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
102,2025 Approved CDF Secondary Boarding School Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Nangoma-Constituency.pdf

In [ ]:
pdf_url = "https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Mumbwa-Central.pdf"

pdf_response = requests.get(
    pdf_url,
    verify=False,
    timeout=60
)

print("Status:", pdf_response.status_code)
print("File size:", len(pdf_response.content), "bytes")
print("Content type:", pdf_response.headers.get("Content-Type"))

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
File size: 1158683 bytes
Content type: application/pdf

In [ ]:
import io

pdf_file = io.BytesIO(pdf_response.content)

with pdfplumber.open(pdf_file) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_num, page in enumerate(pdf.pages, start=1):
        text = page.extract_text()

        print(f"\n{'='*60}")
        print(f"PAGE {page_num}")
        print(f"{'='*60}")

        if text:
            print(text[:5000])
        else:
            print("No text extracted from this page.")

Number of pages: 2

============================================================
PAGE 1
============================================================
! o @ N
5
o g o a = ) c o o = oci^ a o o ) = o = . o i ^ -o 6 - i= . ! o 1 a o Z ; O i p a o .i - - ) 3 o o o C 3 t ) o x D ? - o Co) Co = )
o o= Oqf, T] o= d->^ !
@ o = o ? o o c = z. . o g o r o o + o = ( =c h c = ^ : o @ ^ E @ A O q @- o o @ a o o x - @ 6 o c x B . o - ^ . " Hj ^ ' ; ( 6 i q l , < ' E ?. - o 'c o o o E v x . a 6 6 -o d O - N - r 6 ^ e o - = < - n N - o ' = o q 9 Y4 . ) - , o 3 o o o z
o o o o o 6o.o'. o io = - o fr a ao ,o : o r ooJ@ o !am d
a =
T
oYl
5
o c o c 3 8 6 sg . o a c o m o c o o o- m o o J f o o = - o o mo c o o c o o m o o Uo' No N ) )
o a6 = f, f (Jr
E
T
n
( o- c ) c Co f, ) Co c = ) c o c o = ) E i n lq C oC) E co 6 3 ) - c o c = ) c o Co = ) o o - - o .{ o m c,
o
f
o
f
o
f
o
= Ao
o
f
o
5
o- o
o o
co)
r TI
83
o
o C3 q = o c 3 q € o c 3 E o o c = o c 3 o = o C3 6 € 6 o c = € o c =q € o r-=
cz.
-{=
c)
o
c q € o = c q € o = 3 o C 3 o € o C3 o € o o c = € c o I o = o o c 3 = c q € o 3 o o 5 - A t ) o n
rn
=c)
C{
x
z. o o x =ulag
@o o- o 5 a c o = o o o 3 q = = o o o o 3 e = oo o s c o 9 o ? ) - . o o o 3 o 3 _ U o N = J > ' o o = -g < { = F u,
z,
o c z. o Q< (,s c 3 x i D @ \ Io o x o o ; o \ x o a c O ) z m , c)
@o o o = c d € o a < = = < . o 9 =- o o o = c 3 5 E o o - = o o o a B a o =a = f a o- -O = o l - ! o i il T o: _ o o o = = o o o 3 q 3 R a o = q o = - i=o e o e o o =o = !o o o . . r ! c 2 - . l 7 c o )
= z.
(n
T -{
N No N a N N N O N N N oN oN N o N o N E a < 3 =C
m
z.
7 o C)
o o o = =- aJ=6' z. c)m =o
o 9 o =q a= 9 =o o F
3 fo = aa9 =o cot) -=s-c P. o a a 6 = - z. N N D o
*q o = H r= - a g Q d r ? = N o .r, + ^ Q @ = , g d - a !- < z l i o = = t 6 9 zN = - l o q c =o == = ^ gH : 3o a l ; c Oo 3 c + o i o s 3 a . o 4 Cd o = o v o o Co =o c =o o o o =o D . o 9 9 = 9 €G L o O d = o d , 5 - y E a € - o c d o 5 a =o o 5 . ' @ o o == o 5 o = o o 6 5 a 3 . o o o 9 f 5 -o C 6 6 o 3 @ o o ) o o c d d 3 @ ) @ - d P = i 'e o i i l if i o 3 i r E c o o 6 J , ! " l . ) , o C r r Z e - ) l --"
,,
t-E) mv1
EsrP- r)
gS 1 t\,
E E a E a o E o d E E d ! ! o E E o E E a E o 6 9 4e q - m . x J ( t\ J 5 t
o o o o oo oo o q oo oo o o d\ t z l B
=o+q \
a

============================================================
PAGE 2
============================================================
@ ! o
z
?
a
a,
o
Eo - - ! ! C , a ! X j
=
t
c
a o.J
o
F
a
J
=
= o
=p
ID
:l = :)
F.F =) =)
1ADtr SA aa 9d -$q$A6-
=a = o o o E o o=
v
o o o o o o
p f p
o- o- o- o- o-
t, D D !, D
o o
=
O 7 5 " o Vt o N \ ) T E & t9
E = I
= =
7 ? 7 7
a
o 3 ' = o' 3 =
l0 lJ
z - 7 o z
= c C o f 1_ E E
ID IoD o- rz P
tD rr ID c
2:. - 7 o 2
F!
.
.
o' C a = = 6 g c
ID o p TJ
ID o 0q
No N O N N Op N O l! ) O p N O l p .J
/0"8[
':, 9) C)
3 o C = l r\ @ a .i* ua a ^o tta .d 9: aga o ^5 = ( a Iq
o 5A t+ o d^ l+ = )+. o do^ l Y + = la" k o
p p p
2a 2d g
%}\ lisi @ o0 5 a o o0 = 0 Uq o0a g = = a ' 0-aa
:J O
o
D
=a fo
! E c : E ! !
o o o o o
o o o o @a o a

In [ ]:
with pdfplumber.open(pdf_file) as pdf:
    for page_num, page in enumerate(pdf.pages, start=1):
        tables = page.extract_tables()

        print(f"\nPAGE {page_num}")
        print("Tables found:", len(tables))

        for table_num, table in enumerate(tables, start=1):
            print(f"\n--- TABLE {table_num} ---")
            for row in table:
                print(row)

PAGE 1
Tables found: 0

PAGE 2
Tables found: 0

In [ ]:
print(tracker_soup.get_text("\n", strip=True)[:15000])

CDF Tracker – Mumbwa Town Council
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Menu
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Search
Mumbwa District  CDF Tracker
Edit
Mumbwa Constituency
Edit
2022
Edit
1st Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
2nd Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
3rd Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
4th Quarter
Toggle Content
2023
Edit
1st Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
2nd Quarter
Toggle Content
3rd Quarter
Toggle Content
4th Quarter
Toggle Content
2024
Edit
1st Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
2nd Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
3rd Quarter
Toggle Content
4th Quarter
Toggle Content
2025
Edit
Community Projects
2025 Approved Community Projects-Mumbwa Central
2025 Proposed Community Projects-Mumbwa Central
Skills Development
2025 Approved CDF Skills Development Bursaries for Mumbwa Constituency
Secondary Boarding Bursaries
2025 Approved CDF Secondary Boarding School Bursaries for Mumbwa Constituency
Empowerment Grants
2025 Approved CDF Empowerment Grants for Mumbwa Constituency
Empowerment Loans
Coming Soon…
Disaster
Toggle Content
Nangoma Constituency
Edit
2022
Edit
1st Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
2nd Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
3rd Quarter
Toggle Content
4th Quarter
Toggle Content
2023
Edit
1st Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
2nd Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
3rd Quarter
Toggle Content
4th Quarter
Toggle Content
2024
Edit
1st Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
2nd Quarter
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.
3rd Quarter
Toggle Content
4th Quarter
Toggle Content
2025
Edit
Community Projects
2025 Approved Community Projects-Nangoma Constituency
2025 Proposed Community Projects-Nangoma Constituency
Empowerment Grants
2025 Approved CDF Empowerment Grants for Nangoma Constituency
Empowerment Loans
Coming Soon…
Skills Development Bursaries
2025 Approved CDF Skills Development Bursaries for Nangoma Constituency
Secondary Bursaries
2025 Approved CDF Secondary Boarding School Bursaries for Nangoma Constituency
Disaster
Toggle Content
Contact Information
Mumbwa Town Council
Mumbwa District
Central Province
Tel: 260211800074
P.O. Box: 830001
Email; councilmumbwa@yahoo.com
COMPLAINTS
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
Local Government Association of Zambia Knowledge and Learning Hub
SMART Zambia
©2025. SMART Zambia Institute. All Rights Reserved.

In [ ]:
# Find all elements containing "1st Quarter"
quarter_elements = tracker_soup.find_all(
    string=lambda text: text and "1st Quarter" in text
)

print("Found:", len(quarter_elements), "1st Quarter sections")

for i, element in enumerate(quarter_elements, start=1):
    print(f"\n{'='*70}")
    print(f"1ST QUARTER SECTION {i}")
    print(f"{'='*70}")
    print(element.parent.parent.prettify()[:10000])

Found: 6 1st Quarter sections

======================================================================
1ST QUARTER SECTION 1
======================================================================
<div aria-controls="elementor-tab-content-1051" aria-expanded="false" class="elementor-tab-title" data-tab="1" id="elementor-tab-title-1051" role="tab">
 <span aria-hidden="true" class="elementor-toggle-icon elementor-toggle-icon-left">
  <span class="elementor-toggle-icon-closed">
   <i class="fas fa-caret-right">
   </i>
  </span>
  <span class="elementor-toggle-icon-opened">
   <i class="elementor-toggle-icon-opened fas fa-caret-up">
   </i>
  </span>
 </span>
 <a class="elementor-toggle-title" href="">
  1st Quarter
 </a>
</div>


======================================================================
1ST QUARTER SECTION 2
======================================================================
<div aria-controls="elementor-tab-content-2311" aria-expanded="false" class="elementor-tab-title" data-tab="1" id="elementor-tab-title-2311" role="tab">
 <span aria-hidden="true" class="elementor-toggle-icon elementor-toggle-icon-left">
  <span class="elementor-toggle-icon-closed">
   <i class="fas fa-caret-right">
   </i>
  </span>
  <span class="elementor-toggle-icon-opened">
   <i class="elementor-toggle-icon-opened fas fa-caret-up">
   </i>
  </span>
 </span>
 <a class="elementor-toggle-title" href="">
  1st Quarter
 </a>
</div>


======================================================================
1ST QUARTER SECTION 3
======================================================================
<div aria-controls="elementor-tab-content-8901" aria-expanded="false" class="elementor-tab-title" data-tab="1" id="elementor-tab-title-8901" role="tab">
 <span aria-hidden="true" class="elementor-toggle-icon elementor-toggle-icon-left">
  <span class="elementor-toggle-icon-closed">
   <i class="fas fa-caret-right">
   </i>
  </span>
  <span class="elementor-toggle-icon-opened">
   <i class="elementor-toggle-icon-opened fas fa-caret-up">
   </i>
  </span>
 </span>
 <a class="elementor-toggle-title" href="">
  1st Quarter
 </a>
</div>


======================================================================
1ST QUARTER SECTION 4
======================================================================
<div aria-controls="elementor-tab-content-1101" aria-expanded="false" class="elementor-tab-title" data-tab="1" id="elementor-tab-title-1101" role="tab">
 <span aria-hidden="true" class="elementor-toggle-icon elementor-toggle-icon-left">
  <span class="elementor-toggle-icon-closed">
   <i class="fas fa-caret-right">
   </i>
  </span>
  <span class="elementor-toggle-icon-opened">
   <i class="elementor-toggle-icon-opened fas fa-caret-up">
   </i>
  </span>
 </span>
 <a class="elementor-toggle-title" href="">
  1st Quarter
 </a>
</div>


======================================================================
1ST QUARTER SECTION 5
======================================================================
<div aria-controls="elementor-tab-content-1441" aria-expanded="false" class="elementor-tab-title" data-tab="1" id="elementor-tab-title-1441" role="tab">
 <span aria-hidden="true" class="elementor-toggle-icon elementor-toggle-icon-left">
  <span class="elementor-toggle-icon-closed">
   <i class="fas fa-caret-right">
   </i>
  </span>
  <span class="elementor-toggle-icon-opened">
   <i class="elementor-toggle-icon-opened fas fa-caret-up">
   </i>
  </span>
 </span>
 <a class="elementor-toggle-title" href="">
  1st Quarter
 </a>
</div>


======================================================================
1ST QUARTER SECTION 6
======================================================================
<div aria-controls="elementor-tab-content-2231" aria-expanded="false" class="elementor-tab-title" data-tab="1" id="elementor-tab-title-2231" role="tab">
 <span aria-hidden="true" class="elementor-toggle-icon elementor-toggle-icon-left">
  <span class="elementor-toggle-icon-closed">
   <i class="fas fa-caret-right">
   </i>
  </span>
  <span class="elementor-toggle-icon-opened">
   <i class="elementor-toggle-icon-opened fas fa-caret-up">
   </i>
  </span>
 </span>
 <a class="elementor-toggle-title" href="">
  1st Quarter
 </a>
</div>

In [ ]:
quarter_titles = tracker_soup.find_all(
    "div",
    class_="elementor-tab-title"
)

for i, title in enumerate(quarter_titles, start=1):
    quarter_name = title.get_text(" ", strip=True)
    content_id = title.get("aria-controls")

    content = tracker_soup.find(
        id=content_id
    )

    print(f"\n{'='*70}")
    print(f"SECTION {i}: {quarter_name}")
    print(f"Content ID: {content_id}")
    print(f"{'='*70}")

    if content:
        print(content.get_text("\n", strip=True))
    else:
        print("NO CONTENT FOUND")

======================================================================
SECTION 1: 1st Quarter
Content ID: elementor-tab-content-1051
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 2: 2nd Quarter
Content ID: elementor-tab-content-1052
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 3: 3rd Quarter
Content ID: elementor-tab-content-1053
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 4: 4th Quarter
Content ID: elementor-tab-content-1054
======================================================================
Toggle Content

======================================================================
SECTION 5: 1st Quarter
Content ID: elementor-tab-content-2311
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 6: 2nd Quarter
Content ID: elementor-tab-content-2312
======================================================================
Toggle Content

======================================================================
SECTION 7: 3rd Quarter
Content ID: elementor-tab-content-2313
======================================================================
Toggle Content

======================================================================
SECTION 8: 4th Quarter
Content ID: elementor-tab-content-2314
======================================================================
Toggle Content

======================================================================
SECTION 9: 1st Quarter
Content ID: elementor-tab-content-8901
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 10: 2nd Quarter
Content ID: elementor-tab-content-8902
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 11: 3rd Quarter
Content ID: elementor-tab-content-8903
======================================================================
Toggle Content

======================================================================
SECTION 12: 4th Quarter
Content ID: elementor-tab-content-8904
======================================================================
Toggle Content

======================================================================
SECTION 13: Community Projects
Content ID: elementor-tab-content-8421
======================================================================
2025 Approved Community Projects-Mumbwa Central
2025 Proposed Community Projects-Mumbwa Central

======================================================================
SECTION 14: Skills Development
Content ID: elementor-tab-content-8422
======================================================================
2025 Approved CDF Skills Development Bursaries for Mumbwa Constituency

======================================================================
SECTION 15: Secondary Boarding Bursaries
Content ID: elementor-tab-content-8423
======================================================================
2025 Approved CDF Secondary Boarding School Bursaries for Mumbwa Constituency

======================================================================
SECTION 16: Empowerment Grants
Content ID: elementor-tab-content-8424
======================================================================
2025 Approved CDF Empowerment Grants for Mumbwa Constituency

======================================================================
SECTION 17: Empowerment Loans
Content ID: elementor-tab-content-8425
======================================================================
Coming Soon…

======================================================================
SECTION 18: Disaster
Content ID: elementor-tab-content-8426
======================================================================
Toggle Content

======================================================================
SECTION 19: 1st Quarter
Content ID: elementor-tab-content-1101
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 20: 2nd Quarter
Content ID: elementor-tab-content-1102
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 21: 3rd Quarter
Content ID: elementor-tab-content-1103
======================================================================
Toggle Content

======================================================================
SECTION 22: 4th Quarter
Content ID: elementor-tab-content-1104
======================================================================
Toggle Content

======================================================================
SECTION 23: 1st Quarter
Content ID: elementor-tab-content-1441
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 24: 2nd Quarter
Content ID: elementor-tab-content-1442
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 25: 3rd Quarter
Content ID: elementor-tab-content-1443
======================================================================
Toggle Content

======================================================================
SECTION 26: 4th Quarter
Content ID: elementor-tab-content-1444
======================================================================
Toggle Content

======================================================================
SECTION 27: 1st Quarter
Content ID: elementor-tab-content-2231
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 28: 2nd Quarter
Content ID: elementor-tab-content-2232
======================================================================
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

======================================================================
SECTION 29: 3rd Quarter
Content ID: elementor-tab-content-2233
======================================================================
Toggle Content

======================================================================
SECTION 30: 4th Quarter
Content ID: elementor-tab-content-2234
======================================================================
Toggle Content

======================================================================
SECTION 31: Community Projects
Content ID: elementor-tab-content-1671
======================================================================
2025 Approved Community Projects-Nangoma Constituency
2025 Proposed Community Projects-Nangoma Constituency

======================================================================
SECTION 32: Empowerment Grants
Content ID: elementor-tab-content-1672
======================================================================
2025 Approved CDF Empowerment Grants for Nangoma Constituency

======================================================================
SECTION 33: Empowerment Loans
Content ID: elementor-tab-content-1673
======================================================================
Coming Soon…

======================================================================
SECTION 34: Skills Development Bursaries
Content ID: elementor-tab-content-1674
======================================================================
2025 Approved CDF Skills Development Bursaries for Nangoma Constituency

======================================================================
SECTION 35: Secondary Bursaries
Content ID: elementor-tab-content-1675
======================================================================
2025 Approved CDF Secondary Boarding School Bursaries for Nangoma Constituency

======================================================================
SECTION 36: Disaster
Content ID: elementor-tab-content-1676
======================================================================
Toggle Content

In [ ]:
publications_url = "https://www.mumbwacouncil.gov.zm/?page_id=195"

publications_response = requests.get(
    publications_url,
    verify=False,
    timeout=60
)

print("Status:", publications_response.status_code)

publications_soup = BeautifulSoup(
    publications_response.text,
    "html.parser"
)

publication_links = []

for link in publications_soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(publications_url, link["href"])

    if text:
        publication_links.append({
            "text": text,
            "url": href
        })

publications_df = pd.DataFrame(publication_links).drop_duplicates()

pd.set_option("display.max_colwidth", None)
display(publications_df)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200

,text,url
0,Home,https://www.mumbwacouncil.gov.zm/
1,About,https://www.mumbwacouncil.gov.zm/?page_id=195
2,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
3,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
4,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
5,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
6,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
7,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
8,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
9,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
10,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
11,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
12,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
13,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
14,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
15,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
16,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
17,Media Center,https://www.mumbwacouncil.gov.zm/?page_id=195
18,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
19,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
20,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
21,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
22,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
46,"Landlord-and-Tenant-Business-Premises-Act – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Landlord-and-Tenant-Business-Premises-Act.pdf
47,Lands-Acquisition-Act –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Lands-Acquisition-Act.pdf
48,"Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Lands-Acquisition-Act.pdf
49,"Lands-and-Deeds-Registry-Act – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Lands-and-Deeds-Registry-Act.pdf
50,"Liqour-Licensing-Act-2011 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Liqour-Licensing-Act-2011.pdf
51,"Registration-of-Business-Names-Act – 2011 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Registration-of-Business-Names-Act-2011.pdf
52,"SI-2011-96 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/SI-2011-96.pdf
53,"The-Constituency-Development-Fund-Act-No.-11-of-2018 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Constituency-Development-Fund-Act-No.-11-of-2018.pdf
54,"The-Local-Government-Act-No.-2-of-2019 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Local-Government-Act-No.-2-of-2019.pdf
55,"The-Occupational-Health-and-Safety-Act-2010 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Occupational-Health-and-Safety-Act-2010-1.pdf
56,"The-Public-Finance-Management-ACT-2018 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
57,The-Public-Procurement-Act-No.-8-2020 –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Procurement-Act-No.-8-2020.pdf
58,"Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Public-Finance-Management-ACT-2018.pdf
59,The-Solid-Waste-Regulation-and-Management-Act-2018 –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Solid-Waste-Regulation-and-Management-Act-2018.pdf
61,The-Urban-and-Regional-Planning-Act-2015 –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Urban-and-Regional-Planning-Act-2015.pdf
63,The-Zambia-National-Public-Health-Institute-Act-No.-19-of-2020pdf –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Zambia-National-Public-Health-Institute-Act-No.-19-of-2020pdf.pdf
65,"Mumbwa Town Council – Final Newsletter – Uploaded on: February 13, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/02/Mumbwa-Town-Council-Final-Newsletter.pdf
66,"Press Statement Mumbwa CDF – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Press-Statement-Mumbwa-CDF-Nov.pdf
67,"Press Statement On Monitoring Kaindu Road – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/PRESS-STATEMENT-ON-MONITORING-KAINDU-ROAD.pdf
68,Mumbwa IDP,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/05.07.2024-Final-Alignment-Submission-of-the-Mumbwa-IDP.pdf
69,"– Uploaded on: January 17, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/05.07.2024-Final-Alignment-Submission-of-the-Mumbwa-IDP.pdf
70,2026 CDF APPLACATIONS-GRANTS,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLACATIONS-GRANTS.pdf
71,–,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLACATIONS-GRANTS.pdf
72,"Uploaded on: July 16, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLACATIONS-GRANTS.pdf
73,"2026 CDF APPLICATIONS-SKILLS BURSARIES – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-SKILLS-BURSARIES.pdf
74,"2026 CDF APPLICATIONS-COMMUNITY PROJECTS – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-COMMUNITY-PROJECTS.pdf
75,"2026 CDF APPLICATIONS-SECONDARY BOARDING BURSARIES – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-SECONDARY-BOARDING-BURSARIES.pdf
76,"2026 Budget – Uploaded on: August 20, 2026",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2026/08/MUMBWA-HeadMandateObjectiveSubProg-15.04.2026.pdf
77,"2025 Budget – Uploaded on: December 5, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2025-BUDGET.pdf
78,"2024 Financial Statements – Uploaded on: December 2, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/FINANCIAL-STATEMENTS-FOR-THE-YEAR-ENDED-31ST-DECEMBER-2024.pdf
79,2025 Semi-Annual Budget Performance Report,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Semi-Annual-Budget-Performance-Report-for-2025.pdf
80,"2024 Mumbwa Town Council Budget – Uploaded on: September 15, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/MUMBWA-2024-0BB-Draft-1.0-2.pdf
81,2024 Detailed Receipts And Payments By Program,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/DETAILED-RECEIPTS-AND-PAYMENTS-BY-PROGRAM.pdf
82,"– Uploaded on: September 15, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/DETAILED-RECEIPTS-AND-PAYMENTS-BY-PROGRAM.pdf
83,"2023 Financial Statement – Uploaded on: January 24, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/2023-AUDITED-FINANCIAL-STATEMENT.pdf
84,2022 Financial Statement –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2022.pdf
85,"Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2022.pdf
86,"2021 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2021.pdf
87,"2020 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2020.pdf
88,"2019 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2019.pdf
89,"2018 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2018-2.pdf
90,"2024 Approved CDF Community Projects – Uploaded on: September 13, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/2024-CDF-COMMUNITY-PROJECTS-AS-AT-31ST-AUGUST-2024.pdf
91,"2024 Proposed CDF Projects All Components – Mumbwa and Nangoma Constituencies – Uploaded on: October 10, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/10/2024-CDF-Proposed-Projects-All-Components-Mumbwa-and-Nangoma-Constituencies.pdf
92,View more,https://www.mumbwacouncil.gov.zm/?page_id=932
93,"2025 Minutes of Stakeholders First Monitoring Meeting for the Zambia Devolution Support Program (ZDSP) – Uploaded on: November 17, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/Stakeholders-Minutes-of-The-First-Monitoring-Meeting-for-the-Zambia-Devolution-Support-Program-ZDSP.pdf
94,"2025 Stakeholders-engangement-plan – Uploaded on: December 5, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/ACE-Scanner_2025_12_051.pdf
95,"2025 Minutes of Stakeholders Meeting on The Council Budget – Uploaded on: September 15, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Minutes-of-Stake-holders-Meeting-on-The-2025-Council-Budget.pdf
96,2025 Stakeholders engagement meeting on the review of,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2026-Stakeholders-Engangement-Meeting-on-the-2026-Budget-1.pdf
97,Mumbwa Town Council Budget and Plan for the 2026 Budget,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2026-Stakeholders-Engangement-Meeting-on-the-2026-Budget-1.pdf
98,"– Uploaded on: December 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2026-Stakeholders-Engangement-Meeting-on-the-2026-Budget-1.pdf
99,"2024 Minutes for the Stakeholders Engagement Meeting With Business Community – Uploaded on: November 26, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/Minutes-for-the-Skaeholders-Engagement-Meeting-With-Business-Community-Held-on-5-July-2024.pdf
100,"2024 Minutes of Stakeholders meeting on Output Budget – Uploaded on: June 24, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/Minutes-of-Stakeholders-meeting-on-Output-Budget-for-the-year-2024_rotated.pdf
101,"2023 Minutes of the Stakeholders Meeting – Uploaded on: January 17, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/Minutes-of-Stakeholders-Meeting-Held-on-8-December-2023-at-Mumbwa-Civic-Centre.pdf
102,"MINUTES OF THIRD ORDINARY COUNCIL MEETING OF 9TH OCTOBER, 2023 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MINUTES-OF-THIRD-ORDINARY-COUNCIL-MEETING-OF-9TH-OCTOBER-2023.pdf
103,"Minutes of the Ordinary Council Meeting held on Friday, 28th July, 2023 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Minutes-of-the-Ordinary-Council-Meeting-held-on-Friday-28th-July-2023.pdf
104,"Minutes of Special Council Meeting held on 30th August, 2023 –",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/minutes-of-Special-Council-Meeting-held-on-30th-August-2023.pdf
105,"Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MINUTES-OF-THIRD-ORDINARY-COUNCIL-MEETING-OF-9TH-OCTOBER-2023.pdf
106,"Minutes of Special Council meeting held on 16th May, 2023 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Minutes-of-Special-Council-meeting-held-on-16th-May-2023.pdf
107,"Minutes of the Stakeholders Meeting 8 December 2023 – Uploaded on: December 11, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/12/Minutes-of-Stakeholders-Meeting-Held-on-8-December-2023-at-Mumbwa-Civic-Centre-1.pdf
108,"MINUTES OF THE FIRST ORDINARY COUNCIL MEETING, 2024/2025, MUMBWA CIVIC CENTRE – Uploaded on: November 23, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/THE-THIRD-ORDINARY-COUNCIL-MEEETING-FOR-THE-20242025-CIVIC.pdf
109,"FOURTH ORDINARY COUNCIL MEETING MINUTES – 2023/2024, MUMBWA CIVIC CENTRE – Uploaded on: November 23, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/THE-FOURTH-ORDINARY-COUNCIL-MEETING-FOR-20232024-CIVIC-YEAR.pdf
110,"FOURTH ORDINARY COUNCIL MEETING MINUTES – 2024/2025, MUMBWA CIVIC CENTRE – Uploaded on: November 23, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/THE-ORDINARY-COUNCIL-MEETING-FOR-THE-20252026.pdf
111,"SECOND ORDINARY COUNCIL MEETING MINUTES – 2024/2025, MUMBWA CIVIC CENTRE – Uploaded on: November 23, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/THE-SECOND-ORDINARY-COUNCIL-MEETING-FOR-THE-YEAR-20242025-CIVIC.pdf
112,"SECOND ORDINARY COUNCIL MEETING MINUTES – 2023/2024, MUMBWA CIVIC CENTRE – Uploaded on: November 23, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/11/THE-SECOND-ORDINARY-MEETING-FOR-THER-2023-2024-CIVIC.pdf
113,"CDF-Report-2022 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/CDF-Report-2022.pdf
114,"Local-Government-operations-Report-2022 _- Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Local-Government-operations-Report-2022_2.pdf
115,"MTC Audited Financial Statement for 2021 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MTC-Audited-Financial-Statement-for-2021.pdf
116,"Dump site Profile 2023 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Dump-site-Profile-2023..pdf
117,"GRIEVANCE_HANDLING_PROCEDURES_2 – Uploaded on: February 13, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/02/GRIEVANCE_HANDLING_PROCEDURES_21.docx
118,"Annual Procurement Plan 2023 – Uploaded on: April 24, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/04/Annual-Procurement-Plan-2023-.docx
119,COMPLAINTS,https://www.mumbwacouncil.gov.zm/?page_id=1935
120,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/
121,Local Government Service Comission,https://www.lgsc.gov.zm/
122,Ministry of Finance and National Planning,https://www.mofnp.gov.zm/
123,Ministry of Agriculture,https://www.agriculture.gov.zm/
124,National Assembly of Zambia,https://www.parliament.gov.zm/
125,Local Government Training Institute,http://www.clgti.co.zm/
126,Local Government Association of Zambia Knowledge and Learning Hub,https://www.lgazambia.org.zm/hub/about
127,SMART Zambia,https://www.szi.gov.zm/

In [ ]:
financial_keywords = [
    "budget",
    "financial",
    "receipts",
    "payments",
    "cdf",
    "revenue",
    "expenditure",
    "fund",
    "grant",
    "disbursement"
]

financial_publications_df = publications_df[
    publications_df["text"].str.lower().str.contains(
        "|".join(financial_keywords),
        na=False
    )
].drop_duplicates(subset=["url"])

display(financial_publications_df)

,text,url
12,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
53,"The-Constituency-Development-Fund-Act-No.-11-of-2018 – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/The-Constituency-Development-Fund-Act-No.-11-of-2018.pdf
66,"Press Statement Mumbwa CDF – Uploaded on: December 8, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/Press-Statement-Mumbwa-CDF-Nov.pdf
70,2026 CDF APPLACATIONS-GRANTS,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLACATIONS-GRANTS.pdf
73,"2026 CDF APPLICATIONS-SKILLS BURSARIES – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-SKILLS-BURSARIES.pdf
74,"2026 CDF APPLICATIONS-COMMUNITY PROJECTS – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-COMMUNITY-PROJECTS.pdf
75,"2026 CDF APPLICATIONS-SECONDARY BOARDING BURSARIES – Uploaded on: July 11, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/07/2026-CDF-APPLICATIONS-SECONDARY-BOARDING-BURSARIES.pdf
76,"2026 Budget – Uploaded on: August 20, 2026",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2026/08/MUMBWA-HeadMandateObjectiveSubProg-15.04.2026.pdf
77,"2025 Budget – Uploaded on: December 5, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2025-BUDGET.pdf
78,"2024 Financial Statements – Uploaded on: December 2, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/FINANCIAL-STATEMENTS-FOR-THE-YEAR-ENDED-31ST-DECEMBER-2024.pdf
79,2025 Semi-Annual Budget Performance Report,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Semi-Annual-Budget-Performance-Report-for-2025.pdf
80,"2024 Mumbwa Town Council Budget – Uploaded on: September 15, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/MUMBWA-2024-0BB-Draft-1.0-2.pdf
81,2024 Detailed Receipts And Payments By Program,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/DETAILED-RECEIPTS-AND-PAYMENTS-BY-PROGRAM.pdf
83,"2023 Financial Statement – Uploaded on: January 24, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/2023-AUDITED-FINANCIAL-STATEMENT.pdf
84,2022 Financial Statement –,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2022.pdf
86,"2021 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2021.pdf
87,"2020 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2020.pdf
88,"2019 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2019.pdf
89,"2018 Financial Statement – Uploaded on: August 27, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2018-2.pdf
90,"2024 Approved CDF Community Projects – Uploaded on: September 13, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/2024-CDF-COMMUNITY-PROJECTS-AS-AT-31ST-AUGUST-2024.pdf
91,"2024 Proposed CDF Projects All Components – Mumbwa and Nangoma Constituencies – Uploaded on: October 10, 2024",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/10/2024-CDF-Proposed-Projects-All-Components-Mumbwa-and-Nangoma-Constituencies.pdf
95,"2025 Minutes of Stakeholders Meeting on The Council Budget – Uploaded on: September 15, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Minutes-of-Stake-holders-Meeting-on-The-2025-Council-Budget.pdf
97,Mumbwa Town Council Budget and Plan for the 2026 Budget,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2026-Stakeholders-Engangement-Meeting-on-the-2026-Budget-1.pdf
100,"2024 Minutes of Stakeholders meeting on Output Budget – Uploaded on: June 24, 2025",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/Minutes-of-Stakeholders-meeting-on-Output-Budget-for-the-year-2024_rotated.pdf
113,"CDF-Report-2022 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/CDF-Report-2022.pdf
115,"MTC Audited Financial Statement for 2021 – Uploaded on: December 22, 2023",https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/12/MTC-Audited-Financial-Statement-for-2021.pdf

In [ ]:
budget_2026_url = "https://www.mumbwacouncil.gov.zm/wp-content/uploads/2026/08/MUMBWA-HeadMandateObjectiveSubProg-15.04.2026.pdf"

budget_2026_response = requests.get(
    budget_2026_url,
    verify=False,
    timeout=60
)

print("Status:", budget_2026_response.status_code)
print("File size:", len(budget_2026_response.content), "bytes")
print("Content type:", budget_2026_response.headers.get("Content-Type"))

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
File size: 753483 bytes
Content type: application/pdf

In [ ]:
import io

budget_2026_file = io.BytesIO(budget_2026_response.content)

with pdfplumber.open(budget_2026_file) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_num, page in enumerate(pdf.pages[:3], start=1):
        text = page.extract_text()

        print(f"\n{'='*60}")
        print(f"PAGE {page_num}")
        print(f"{'='*60}")

        if text:
            print(text[:3000])
        else:
            print("NO TEXT FOUND")

Number of pages: 52

============================================================
PAGE 1
============================================================
OUTPUT BASED ANNUAL BUDGET Page 1
HEAD9209 MUMBWA TOWN COUNCIL
1.0 MANDATE
To provide operational and service excellence, innovation, community engagement and observance of
good financial management and accountability. This is in agreement with the Republican Constitution
(Amendment) Act No.2 of 2016 Part IX on the System of Devolved Governance [Article 147 (2)] and Part
XI on the System of Local Government.
2.0 STRATEGY
The Local Authority will achieve its mandate by strengthening community participation in service
delivery and local governance by promoting public private partnerships in service provision. Further, the
Local Authority will expedite completion of infrastructure projects especially those nearing completion
in order to improve the socio-economic status of the district.
3.0 NATIONAL DEVELOPMENT PLAN FRAMEWORK
Cluster : 01 Economic Transformation and Job Creation
Cluster Outcome 01 An Industrialised and Diversified Economy
Strategy : 01 Improve agricultural production and productivity
Strategy : 03 Promote value addition and manufacturing
Strategy : 04 Promote tourism growth
Strategy : 05 Improve transport and logistics
Strategy : 06 Enhance Generation, Transmission and Distribution of Electricity
Strategy : 08 Enhance management and productive use of water resources
Cluster Outcome 02 Enhanced Citizenry Participation in the Economy
Strategy : 02 Promote Enterprise development
Cluster Outcome 03 A Competitive Private Sector
Strategy : 01 Promote quality and productivity
Cluster : 02 Human and Social Development
Cluster Outcome 01 Improved Education and Skills Development
Strategy : 01 Enhance access to quality, equitable and inclusive education
Strategy : 02 Improve technical, vocational and entrepreneurship skills
Strategy : 04 Enhance science, technology and innovation
Cluster Outcome 02 Improved Health, Food and Nutrition
Strategy : 01 Strengthen Public health
Strategy : 04 Strengthen Integrated Health Information Systems
Cluster Outcome 04 Reduced Poverty, Vulnerability and Inequalities
Strategy : 04 Increasing access to decent and affordable housing
Strategy : 05 Reduce vulnerability associated with HIV and AIDS
Cluster : 03 Environmental Sustainability
Cluster Outcome 01 Enhanced Mitigation and adaptation to Climate Change
Strategy : 02 Strengthen climate change mitigation
Cluster Outcome 02 Sustainable Environment and Natural Resources Management
Strategy : 01 Promote Integrated Environmental Management
Strategy : 02 Enhance natural resources management
Cluster : 04 Good Governance Environment
Cluster Outcome 01 Improved Policy and Governance Environment
Strategy : 01 Decentralise Public Service Delivery Systems
Strategy : 03 Strengthen transparency and accountability mechanisms
Strategy : 05 Strengthen public service performance management systems
Cluster Outcome 02 Improved Rule of Law, Human Rights and Constitutionalism
Strategy : 01 Strengthen human rights and constitutionalism
Strategy : 02 Strengthen the criminal and jus

============================================================
PAGE 2
============================================================
Page 2 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
01 Local taxes/rates
001 Residential 863,624 915,441 979,522
002 Commercial 694,382 736,045 787,568
003 Industrial 682,464 723,412 774,051
004 Hospitality 956,218 1,013,591 1,084,542
005 Mining/Plant 604,958 641,255 686,143
006 Power transmission 416,572 441,566 472,476
007 Plant and Machinery 559,125 592,673 634,160
SubItem Total 4,777,343 5,063,984 5,418,462
001 Personal levy 90,000 95,400 102,078
SubItem Total 90,000 95,400 102,078

============================================================
PAGE 3
============================================================
OUTPUT BASED ANNUAL BUDGET Page 3
HEAD9209 MUMBWA TOWN COUNCIL
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
02 Fees and Charges
001 Consent fees 506,900 537,314 574,926
002 Survey fees 552,000 585,120 626,078
003 Building inspection-fees 35,000 37,100 39,697
004 Plan scrutiny fee 4,350 4,611 4,934
005 Change of premise use 45,839 48,589 51,991
007 Rentals/lease of Council’s properties 138,000 146,280 156,520
008 Non-Land Application forms fees 236,020 250,181 267,694
009 Rentals from houses 27,000 28,620 30,623
011 Search fees 6,000 6,360 6,805
013 Market fees 350,150 371,159 397,140
014 Parking fees 36,000 38,160 40,831
016 Loading fees (buses, trucks, trains, taxies etc.) 1,424,375 1,509,838 1,615,526
017 Affidavit fees 26,400 27,984 29,943
020 Hire of halls 1,500 1,590 1,701
032 Hire of plant and equipment 175,000 185,500 198,485
033 Refuse disposal 90,000 95,400 102,078
035 Commercial & non-commercial Exhibitions 73,800 78,228 83,704
037 Farm visits 40,080 42,484 45,459
039 Franchise fees 9,400 9,964 10,661
041 Dumb site fees 20,000 21,200 22,684
042 Animal Ante mortem fees 4,800 5,088 5,444
043 Registration (Brand marks) 2,000 2,120 2,268
045 Notice of marriage fees 70,000 74,200 79,394
046 Abattoir/meat inspection fees 517,200 548,232 586,608
050 Vendor Fees 27,375 29,018 31,049
051 Farm produce Fee 78,240 82,934 88,740
053 Certification of documents 6,500 6,890 7,372
055 Illegal Paring of vehicles 31,500 33,390 35,727
056 Repairs of cars/garage/car wash 120,000 127,200 136,104
063 Billboards and banners 221,100 234,366 250,772
066 Penalties 184,671 195,751 209,454
067 Ablution Fee 384,800 407,888 436,440
072 Booth fees 200,000 212,000 226,840
073 Ntemba fees 260,000 275,600 294,892
087 Animal Identification Mark Fees (Brand marks) 47,880 50,753 54,306
099 Other fees and charges 64,500 68,370 73,156
SubItem Total 6,018,380 6,379,482 6,826,047

In [ ]:
import io
import pdfplumber

budget_2026_file = io.BytesIO(budget_2026_response.content)

with pdfplumber.open(budget_2026_file) as pdf:
    print("Total pages:", len(pdf.pages))

    for page_num, page in enumerate(pdf.pages, start=1):
        text = page.extract_text()

        print("\n" + "=" * 70)
        print(f"PAGE {page_num}")
        print("=" * 70)

        if text:
            # Clean up excessive whitespace
            preview = " ".join(text.split())
            print(preview[:500])
        else:
            print("NO TEXT FOUND")

Total pages: 52

======================================================================
PAGE 1
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 1 HEAD9209 MUMBWA TOWN COUNCIL 1.0 MANDATE To provide operational and service excellence, innovation, community engagement and observance of good financial management and accountability. This is in agreement with the Republican Constitution (Amendment) Act No.2 of 2016 Part IX on the System of Devolved Governance [Article 147 (2)] and Part XI on the System of Local Government. 2.0 STRATEGY The Local Authority will achieve its mandate by strengthening community par

======================================================================
PAGE 2
======================================================================
Page 2 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL APPROVED CODE REVENUE DESCRIPTION REVISED BUDGET BUDGET 2026 BUDGET 2027 ESTIMATE 2028 01 Local taxes/rates 001 Residential 863,624 915,441 979,522 002 Commercial 694,382 736,045 787,568 003 Industrial 682,464 723,412 774,051 004 Hospitality 956,218 1,013,591 1,084,542 005 Mining/Plant 604,958 641,255 686,143 006 Power transmission 416,572 441,566 472,476 007 Plant and Machinery 559,125 592,673 634,160 SubItem Total 4,777,343 5,063,9

======================================================================
PAGE 3
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 3 HEAD9209 MUMBWA TOWN COUNCIL APPROVED CODE REVENUE DESCRIPTION REVISED BUDGET BUDGET 2026 BUDGET 2027 ESTIMATE 2028 02 Fees and Charges 001 Consent fees 506,900 537,314 574,926 002 Survey fees 552,000 585,120 626,078 003 Building inspection-fees 35,000 37,100 39,697 004 Plan scrutiny fee 4,350 4,611 4,934 005 Change of premise use 45,839 48,589 51,991 007 Rentals/lease of Council’s properties 138,000 146,280 156,520 008 Non-Land Application forms fees 236,020 25

======================================================================
PAGE 4
======================================================================
Page 4 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL APPROVED CODE REVENUE DESCRIPTION REVISED BUDGET BUDGET 2026 BUDGET 2027 ESTIMATE 2028 03 Licenses 002 Liquor licence 237,000 251,220 268,805 003 Firearm and ammunition licence 22,000 23,320 24,952 004 Petroleum Storage licence 418,500 443,610 474,663 005 Dog licence 30,000 31,800 34,026 007 Fish Licences/origin of fish 44,400 47,064 50,358 099 Other Licences 220,000 233,200 249,524 SubItem Total 971,900 1,030,214 1,102,329 CODE REVE

======================================================================
PAGE 5
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 5 HEAD9209 MUMBWA TOWN COUNCIL APPROVED CODE REVENUE DESCRIPTION REVISED BUDGET BUDGET 2026 BUDGET 2027 ESTIMATE 2028 06 Charges 003 Premium Plot- Residential 669,000 709,140 758,780 007 Land Application Charges 18,750 19,875 21,266 008 Land Conversion 3,197,500 3,389,350 3,626,605 009 Change of ownership 98,000 103,880 111,152 SubItem Total 3,983,250 4,222,245 4,517,802 APPROVED CODE REVENUE DESCRIPTION REVISED BUDGET BUDGET 2026 BUDGET 2027 ESTIMATE 2028 07 Othe

======================================================================
PAGE 6
======================================================================
Page 6 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL 31 Non-Financial Assets 47,453,127 52,163,183 65,316,312 32 Financial Assets 6,984,926 7,473,871 - 41 Current Liabilities (Payable within one year) 2,403,381 1,588,000 1,208,000 Head Total 107,759,311 180,530,727 165,906,043 Figure 1: Budget Allocation by Economic Classification 12.99% 20.13% 15.14% 0.73% 11.65% 39.37% Goods and Services Current Liabilities (Payable within one year) Grants and Other Payments(Transfers) Non-Financial

======================================================================
PAGE 7
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 7 HEAD9209 MUMBWA TOWN COUNCIL Table:2 Budget Allocation by Programme 2024 2025 2026 Programme Code Approved Approved Budget Budget(K) Budget(K) Estimates(K) 1 Constituency Development 61,271,284 72,116,301 80,065,100 2 Local Governance 4,747,244 3,329,422 3,404,859 3 Integrated Development Planning 2,966,989 1,894,846 2,476,953 4 Economic and business development 697,049 793,435 777,282 5 Public health and Environmental protection 2,288,188 1,805,457 2,463,497 6

======================================================================
PAGE 8
======================================================================
Page 8 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL Table 3: Budget Allocation by Programme and Sub-Programme PROGRAMME/SUB-PROGRAMME 2024 BUDGET 2025 BUDGET 2026 BUDGET Approved Expendit Approved Expendit Estimate ure ure* - - 1 Constituency Development 61,271,284 72,116,301 80,065,100 779 Community Projects 34,924,632 - 43,925,383 - 57,119,825 780 Women and Youth Empowerment 11,641,544 - 12,456,452 - 5,518,484 781 CDF Administration 3,063,564 - 3,278,014 - 3,630,581 782 Secondary Sc

======================================================================
PAGE 9
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 9 HEAD9209 MUMBWA TOWN COUNCIL 035 Accounting Management 4,383,197 - 3,964,291 - 3,795,846 036 Legal Services 850,741 - 790,412 - 1,127,267 - - 12 Resource Mobilisation and Management 1,731,459 1,412,318 1,746,942 067 Revenue Mobilisation and Enhancement 1,731,459 - 1,412,318 - 1,746,942 - - 13 District Health servcies - 6,109,336 6,432,992 001 Primary Health Services - - 5,432,712 - 5,756,368 002 District Health Coordination - - 676,624 - 676,624 - - 15 Transport

======================================================================
PAGE 10
======================================================================
Page 10 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL for inspections of public and business premises to ensure compliance to public health standards;Water Supply and Sanitation Services has an allocation of K797,569 for the supply of clean drinking water to the community; Solid Waste Management has been allocated K636,770 for refuse disposal; while Pest Control has an allocation of K34.200. Housing and Community Amenities has been allocated K13.1 million to implement the following six

======================================================================
PAGE 11
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 11 HEAD9209 MUMBWA TOWN COUNCIL capacity programs in agribusiness and marketing. The Agriculture Coordination sub-programme has been allocated K132,680 to facilitate general operations under this programme and also procurement of goods and services. The Fisheries and Livestock Programme which will be implemented through five (5) sub-programmes has been allocated K503,175. Of the total programme allocation, K105,310 has been allocated to Livestock Production, and P

======================================================================
PAGE 12
======================================================================
Page 12 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 1 : Constituency Development Programme Objective To facilitate equitable development, reduce poverty, support job creation and provide for vulnerable learners to access Secondary Boarding Schools and Technical Education, Vocational and Entrepreneurship Training Institutions. Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved

======================================================================
PAGE 13
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 13 HEAD9209 MUMBWA TOWN COUNCIL Programme: 1Constituency Development Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target Community Projects Implemented 01 Number of commiunity projects implemented (0) (0) 28 25 25 02 Number of desks procured (0) (0) 1,145 630 1,000 03 Number of maternity annexes constructed (0) (0) 1 1 2 04 Number of boreholes drilled (0) (0) (0) (0) 15 05 Kilometers of Rural Roads Rehabili

======================================================================
PAGE 14
======================================================================
Page 14 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 2 : Local Governance Programme Objective To facilitate community participation in decision making for sustainable local development. Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 01Personal Emoluments 2,280,270 - 552,542 - 432,018 01Salaries and Wages 552,270 - 552,542 - 432

======================================================================
PAGE 15
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 15 HEAD9209 MUMBWA TOWN COUNCIL Programme: 2Local Governance Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target Council Meetings Held 01 Number of ordinary Council meetings held (0) (0) 4 3 3 02 Number of Committee meetings held 28 28 23 18 18 03 Number of special ordinary Council meetings held (0) (0) 1 3 2 04 Number of special Committee meetings held (0) (0) 1 1 2 Ward Development Committees Operationali

======================================================================
PAGE 16
======================================================================
Page 16 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 3 : Integrated Development Planning Programme Objective To guide spatial, social-economic, and environmental planning in the district. Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 01Personal Emoluments 1,120,907 - 1,425,932 - 1,384,057 01Salaries and Wages 1,120,907 - 1,425

======================================================================
PAGE 17
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 17 HEAD9209 MUMBWA TOWN COUNCIL Programme: 3Integrated Development Planning Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target EIA Reports Reviewed 01 Number of EIA reports reviewed (0) (0) 4 4 4 World Enviroment Day Commemorated 01 Number of Trees Planted (0) (0) - - 250 GIS Unit Created 01 Number of Neigbourhood Plans Digitized (0) (0) 1 1 4 02 Number of Local Area Plans developed (0) (0) 1 1 1 03 Number

======================================================================
PAGE 18
======================================================================
Page 18 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 4 : Economic and business development Programme Objective To provide an enabling business environment that will attract investors from both within and outside the district. Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 01Personal Emoluments 505,554 - 569,570 - 616,809 01Sala

======================================================================
PAGE 19
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 19 HEAD9209 MUMBWA TOWN COUNCIL Programme: 4Economic and business development Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target Trade in the District Facilitated 01 Number of business regulation compliance inspections conducted 12 12 12 36 12 02 Number of new businesses registered (0) (0) 20 40 30 03 Number of modern Bus Station constructed (0) (0) (0) (0) 1 04 Number of Modern Council Rest House conferen

======================================================================
PAGE 20
======================================================================
Page 20 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 5 : Public health and Environmental protection Programme Objective To promote public health and sustainable management of the environment in the district. Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 01Personal Emoluments 769,111 - 853,356 - 912,047 01Salaries and Wages 769

======================================================================
PAGE 21
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 21 HEAD9209 MUMBWA TOWN COUNCIL Programme: 5Public health and Environmental protection Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target Unclaimed Bodies Buried 01 Percentage of unclaimed bodies buried (0) (0) 100 100 100 Public Health Services Undertaken 01 Number of health permits issued 500 500 635 602 600 02 Number of premises inspected 700 650 700 652 600 03 Number of abattoirs inspected (0) (0) 3 3

======================================================================
PAGE 22
======================================================================
Page 22 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 6 : Housing and Community Amenities Programme Objective To promote sustainable infrastructure development and community amenities. Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 01Personal Emoluments 2,611,769 - 3,574,379 - 3,526,875 01Salaries and Wages 2,611,769 - 3,574,379

======================================================================
PAGE 23
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 23 HEAD9209 MUMBWA TOWN COUNCIL Programme 0006: Housing and Community Amenities Table 5: Programme Budget Allocation by Subprogramme 2024 BUDGET 2025 BUDGET 2026 BUDGET PROGRAMME/SUBPROGRAMME Approved Expendit Approved Expendit Estimates ure ure* 6 Housing and Community Amenities 10,472,316 15,039,781 13,115,225 008Roads and Drainages 1,185,396 - 1,530,885 - 264,855 011Parks and Gardens 95,570 - 231,020 - 100,715 012Markets and Bus Stations 1,672,702 - 2,188,471 -

======================================================================
PAGE 24
======================================================================
Page 24 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL Programme: 6Housing and Community Amenities Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target Public Infrastructure Rehabilitated and Constructed 01 Number of public infrastructure rehabilitated (0) (0) 4 4 3 02 Number of Council Buildings Constructed (0) (0) (0) (0) 2 03 Number of Ablution blocks Constructed (0) (0) (0) (0) 1 04 Number of Markets maintained (0) (0) (0) (0)

======================================================================
PAGE 25
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 25 HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 7 : Recreation Culture and Religion Programme Objective To promote recreation, culture, religious affairs, and talent identification in the district Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 02Use of Goods and Services 12,818 - 1,116,856 - 688,909 02General Operations 12

======================================================================
PAGE 26
======================================================================
Page 26 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL Programme: 7Recreation Culture and Religion Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target Inventory of Cultural Practices Conducted 01 Number of inventories of cultrual practices conducted (0) (0) 1 1 1 Cultrual and Creative Industries in the District Developed 01 Number of of cultrual and creative industries in the district developed (0) (0) 1 1 1 Grants to Chiefs Disb

======================================================================
PAGE 27
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 27 HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 8 : Education and skills development Programme Objective To facilitate literacy and skills development in the communities Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 01Personal Emoluments - - - - 547,467 01Salaries and Wages - - - - 547,467 02Use of Goods and Services 2,00

======================================================================
PAGE 28
======================================================================
Page 28 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL Programme: 8Education and skills development Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target District Departments Surveyed 01 Number of Survey reports produced (0) (0) (0) (0) 2 Shelves Procured 01 Number of Shelves Procured (0) (0) (0) (0) 2 NA17 Boxes Procured 01 Number of NA17 Boxes Procured (0) (0) (0) (0) 100 Early Childhood Training Provided 01 Number of children ta

======================================================================
PAGE 29
======================================================================
OUTPUT BASED ANNUAL BUDGET Page 29 HEAD9209 MUMBWA TOWN COUNCIL BUDGET PROGRAMMES Programme 10 : Public order and safety Programme Objective To enforce adherence to by-laws and other applicable laws and promote safety of private and public property Table 4: Programme Budget Allocation by Economic Classification 2024 BUDGET 2025 BUDGET 2026 BUDGET ECONOMIC CLASSIFICATION Approved Expendit Approved Expendit Estimates ure ure* 01Personal Emoluments 3,385,046 - 5,038,140 - 5,510,844 01Salaries and W

======================================================================
PAGE 30
======================================================================
Page 30 OUTPUT BASED ANNUAL BUDGET HEAD9209 MUMBWA TOWN COUNCIL Programme: 10Public order and safety Table 6: Programme Outputs Key Output and Output Indicator 2024 2025 2026 Target Actual Target Actual* Target Routine Patrols Conducted 01 Number of routine police patrols conducted (0) (0) 12 10 24 Building Regulations Compliance Checks Conducted 01 Number of stage inspections conducted (0) (0) 24 18 30 02 Number of plans scrutinized for planning permission (0) (0) 30 22 20 03 Number of building

======================================================================
PAGE 31
======================================================================

In [ ]:
import io
import pdfplumber

budget_2026_file = io.BytesIO(budget_2026_response.content)

with pdfplumber.open(budget_2026_file) as pdf:

    for page_num in range(2, 7):
        page = pdf.pages[page_num - 1]
        text = page.extract_text()

        print("\n" + "=" * 80)
        print(f"PAGE {page_num}")
        print("=" * 80)

        if text:
            print(text)
        else:
            print("NO TEXT FOUND")

================================================================================
PAGE 2
================================================================================
Page 2 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
01 Local taxes/rates
001 Residential 863,624 915,441 979,522
002 Commercial 694,382 736,045 787,568
003 Industrial 682,464 723,412 774,051
004 Hospitality 956,218 1,013,591 1,084,542
005 Mining/Plant 604,958 641,255 686,143
006 Power transmission 416,572 441,566 472,476
007 Plant and Machinery 559,125 592,673 634,160
SubItem Total 4,777,343 5,063,984 5,418,462
001 Personal levy 90,000 95,400 102,078
SubItem Total 90,000 95,400 102,078

================================================================================
PAGE 3
================================================================================
OUTPUT BASED ANNUAL BUDGET Page 3
HEAD9209 MUMBWA TOWN COUNCIL
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
02 Fees and Charges
001 Consent fees 506,900 537,314 574,926
002 Survey fees 552,000 585,120 626,078
003 Building inspection-fees 35,000 37,100 39,697
004 Plan scrutiny fee 4,350 4,611 4,934
005 Change of premise use 45,839 48,589 51,991
007 Rentals/lease of Council’s properties 138,000 146,280 156,520
008 Non-Land Application forms fees 236,020 250,181 267,694
009 Rentals from houses 27,000 28,620 30,623
011 Search fees 6,000 6,360 6,805
013 Market fees 350,150 371,159 397,140
014 Parking fees 36,000 38,160 40,831
016 Loading fees (buses, trucks, trains, taxies etc.) 1,424,375 1,509,838 1,615,526
017 Affidavit fees 26,400 27,984 29,943
020 Hire of halls 1,500 1,590 1,701
032 Hire of plant and equipment 175,000 185,500 198,485
033 Refuse disposal 90,000 95,400 102,078
035 Commercial & non-commercial Exhibitions 73,800 78,228 83,704
037 Farm visits 40,080 42,484 45,459
039 Franchise fees 9,400 9,964 10,661
041 Dumb site fees 20,000 21,200 22,684
042 Animal Ante mortem fees 4,800 5,088 5,444
043 Registration (Brand marks) 2,000 2,120 2,268
045 Notice of marriage fees 70,000 74,200 79,394
046 Abattoir/meat inspection fees 517,200 548,232 586,608
050 Vendor Fees 27,375 29,018 31,049
051 Farm produce Fee 78,240 82,934 88,740
053 Certification of documents 6,500 6,890 7,372
055 Illegal Paring of vehicles 31,500 33,390 35,727
056 Repairs of cars/garage/car wash 120,000 127,200 136,104
063 Billboards and banners 221,100 234,366 250,772
066 Penalties 184,671 195,751 209,454
067 Ablution Fee 384,800 407,888 436,440
072 Booth fees 200,000 212,000 226,840
073 Ntemba fees 260,000 275,600 294,892
087 Animal Identification Mark Fees (Brand marks) 47,880 50,753 54,306
099 Other fees and charges 64,500 68,370 73,156
SubItem Total 6,018,380 6,379,482 6,826,047

================================================================================
PAGE 4
================================================================================
Page 4 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
03 Licenses
002 Liquor licence 237,000 251,220 268,805
003 Firearm and ammunition licence 22,000 23,320 24,952
004 Petroleum Storage licence 418,500 443,610 474,663
005 Dog licence 30,000 31,800 34,026
007 Fish Licences/origin of fish 44,400 47,064 50,358
099 Other Licences 220,000 233,200 249,524
SubItem Total 971,900 1,030,214 1,102,329
CODE REVENUE DESCRIPTION APPROVED REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
04 Levies
001 Livestock Movement levy 80,400 85,224 91,190
002 Birds levy 48,000 50,880 54,442
003 Fish levy 18,000 19,080 20,416
004 Pole levy 5,264 5,580 5,971
005 Charcoal levy 72,000 76,320 81,662
006 Sand levy 49,200 52,152 55,803
008 Quarry levy 28,800 30,528 32,665
011 Telecommunication Mast 190,000 201,400 215,498
016 Grain Levy 1,080,000 1,144,800 1,224,936
017 Trading (Wholesale) Business Levy 375,000 397,500 425,325
018 Trading (Retail) Consumable groceries business 316,000 334,960 358,407
019 Retail Merchants non-consumable business 265,500 281,430 301,130
020 Trading (Retail) chain stores and supermarkets 5,000 5,300 5,671
026 Hawker 3,000 3,180 3,403
027 Peddler 3,600 3,816 4,083
028 Filling Station 50,000 53,000 56,710
031 Car Wash 22,500 23,850 25,520
032 Hospitality 325,000 344,500 368,615
033 Commercial Banks 30,000 31,800 34,026
034 Micro- Finance and Money-Lenders 50,000 53,000 56,710
099 Other levies 3,682,000 3,902,920 4,176,124
SubItem Total 6,699,264 7,101,220 7,598,305
CODE REVENUE DESCRIPTION APPROVED REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
05 Permits
001 Health permits 607,500 643,950 689,027
002 Permit for opaque beer 7,000 7,420 7,939
003 Herbalist permit 5,500 5,830 6,238
005 Transportation of meat products 540,000 572,400 612,468
008 Burial permits and grave sites 47,500 50,350 53,875
009 Fire certificate 1,161,800 1,231,508 1,317,714
010 Extension of Business hours permits 21,600 22,896 24,499
011 Social gathering permit 27,000 28,620 30,623
099 Primary, Secondary and Tertiary permits 56,000 59,360 63,515
SubItem Total 2,473,900 2,622,334 2,805,897

================================================================================
PAGE 5
================================================================================
OUTPUT BASED ANNUAL BUDGET Page 5
HEAD9209 MUMBWA TOWN COUNCIL
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026
BUDGET 2027 ESTIMATE 2028
06 Charges
003 Premium Plot- Residential 669,000 709,140 758,780
007 Land Application Charges 18,750 19,875 21,266
008 Land Conversion 3,197,500 3,389,350 3,626,605
009 Change of ownership 98,000 103,880 111,152
SubItem Total 3,983,250 4,222,245 4,517,802
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026 BUDGET 2027 ESTIMATE 2028
07 Other Incomes
002 Surplus/ Deficit from Commercial Ventures 120,278 127,495 136,419
099 Other Income 68,000 72,080 77,126
SubItem Total 188,278 199,575 213,545
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026 BUDGET 2027 ESTIMATE 2028
08 National Support (Grants)
001 Constituency Development Fund 80,065,100 84,869,004 90,809,835
002 Roads Grant 6,832,481 7,242,430 7,749,400
003 Health Grant 6,432,992 6,818,972 7,296,300
004 Local Government Equalisation Fund 17,054,618 18,077,895 19,343,348
005 Grants in lieu of Rates 350,000 371,000 396,970
099 Other Grants 24,148,681 25,597,601 27,389,433
SubItem Total 134,883,872 142,976,902 152,985,286
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2026 BUDGET 2027 ESTIMATE 2028
09 Donor Support (Grants)
001 Devolution Capital Grant 5,819,856 6,169,048 6,600,881
SubItem Total 5,819,856 6,169,048 6,600,881
Grand Total 165,906,043 175,860,403 188,170,633
4.0 BUDGET SUMMARY
The total budget for the Council for the year 2026 stands at K165.9 million representing a 9.8
percentange decrease from the previous years’ budget which stood at K183.8 million( K180.5 Million
being the approved budget for 2025 and the K3.3 Million was later approved as suplementary budget).
The decrease is mainly attributed to the Cash For Work funds which have reduced from K51 million to
K22.7 million, the Zambia Devolution Support Programme Capital grant which has reduced from K8.3
million to K5.8 million.This budget will support the implementation of 16 programmes in line with the
Council’s Integrated Development Plan and the 8th National Development Plan.
Table:1 Budget Allocation by Economic Classification
No ECONOMIC CLASSIFICATION 2024 2025 2026 BUDGET
APPROVED APPROVED ESTIMATE (K)
BUDGET (K) BUDGET (K)
21 Personal Emoluments 18,524,209 20,756,763 25,110,993
22 Goods and Services 16,082,536 31,880,886 33,391,520
25 Social Assistance Benefits (0) 49,217,990 21,553,524
26 Grants and Other Payments(Transfers) 16,311,132 17,450,033 19,325,693

================================================================================
PAGE 6
================================================================================
Page 6 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
31 Non-Financial Assets 47,453,127 52,163,183 65,316,312
32 Financial Assets 6,984,926 7,473,871 -
41 Current Liabilities (Payable within one year) 2,403,381 1,588,000 1,208,000
Head Total 107,759,311 180,530,727 165,906,043
Figure 1: Budget Allocation by Economic Classification
12.99%
20.13%
15.14% 0.73%
11.65%
39.37%
Goods and Services Current Liabilities (Payable within one year)
Grants and Other Payments(Transfers) Non-Financial Assets
Personal Emoluments Social Assistance Benefits
The budget allocation by Economic Classification shows that the total Council budget stands at K165.9
million of which K65.3 million representing 39.3 percent has been allocated to Non-Financial Assets to
cater for capital projects,Goods and Services has been allocated K33.3 million representing 20.1 percent
of the total budget to cover for fuel for feeder roads under Constituency Development Fund and other
administrative expenses.
Personnel Emoluments has been allocated K25.1 million representing 15 percent for salaries and wages
while Social Assitance benefits has been allocated K21,553,524 representing 12.9 percent to cater for
Cash for Work.
Out of the total budget,K19.3 million representing 11.6 percent has been allocated to Grants and Other
Payments (Transfers) to cater for bursaries and empowerments.Lastly, Current Liabilities (Payable within
one year) stands at K1.2 million representing 0.7 percent of the total budget for the partial settlement of
the debt and arrears.

In [ ]:
import pandas as pd
import re
import pdfplumber

# Re-read pages 2-6 directly into a dictionary
pages_text = {}
budget_2026_file.seek(0)  # Reset buffer pointer

with pdfplumber.open(budget_2026_file) as pdf:
    for page_num in range(2, 7):
        pages_text[page_num] = pdf.pages[page_num - 1].extract_text() or ""

data_rows = []

# Regex patterns for line items: CODE (e.g. 001) | DESCRIPTION | BUDGET 2026
item_pattern = re.compile(r"^(\d{3})\s+(.*?)\s+([\d,]+)\s+[\d,]+\s+[\d,]+$")
category_pattern = re.compile(r"^(\d{2})\s+([A-Za-z\s/()]+)$")

# --- 1. Parse Pages 2-5: Detailed Revenue Line Items ---
current_category = "General Revenue"

for page_num in range(2, 6):
    text = pages_text.get(page_num, "")
    for line in text.split("\n"):
        line = line.strip()

        # Check for category headers like "01 Local taxes/rates"
        cat_match = category_pattern.match(line)
        if cat_match:
            current_category = cat_match.group(2).strip()
            continue

        # Match standard line items
        match = item_pattern.match(line)
        if match:
            code = match.group(1)
            desc = match.group(2).strip()
            amount_str = match.group(3).replace(",", "")
            amount = float(amount_str)

            data_rows.append({
                "year": 2026,
                "financial_type": "Revenue Budget",
                "category/code": f"{code} ({current_category})",
                "description": desc,
                "amount": amount,
                "source": "2026 Approved Budget PDF (Pages 2-5)"
            })

# --- 2. Parse Pages 5-6: Economic Classification Allocations ---
econ_items = [
    ("21", "Personal Emoluments", 25110993.0),
    ("22", "Goods and Services", 33391520.0),
    ("25", "Social Assistance Benefits", 21553524.0),
    ("26", "Grants and Other Payments(Transfers)", 19325693.0),
    ("31", "Non-Financial Assets", 65316312.0),
    ("41", "Current Liabilities (Payable within one year)", 1208000.0)
]

for code, desc, amount in econ_items:
    data_rows.append({
        "year": 2026,
        "financial_type": "Expenditure Budget (Economic Classification)",
        "category/code": code,
        "description": desc,
        "amount": amount,
        "source": "2026 Approved Budget PDF (Pages 5-6)"
    })

# Convert to pandas DataFrame
budget_2026_df = pd.DataFrame(data_rows)

# Inspect the result
print(f"Successfully extracted {len(budget_2026_df)} structured rows.")
display(budget_2026_df.head(15))
display(budget_2026_df.tail(10))

Successfully extracted 99 structured rows.

,year,financial_type,category/code,description,amount,source
0,2026,Revenue Budget,001 (Local taxes/rates),Residential,863624.0,2026 Approved Budget PDF (Pages 2-5)
1,2026,Revenue Budget,002 (Local taxes/rates),Commercial,694382.0,2026 Approved Budget PDF (Pages 2-5)
2,2026,Revenue Budget,003 (Local taxes/rates),Industrial,682464.0,2026 Approved Budget PDF (Pages 2-5)
3,2026,Revenue Budget,004 (Local taxes/rates),Hospitality,956218.0,2026 Approved Budget PDF (Pages 2-5)
4,2026,Revenue Budget,005 (Local taxes/rates),Mining/Plant,604958.0,2026 Approved Budget PDF (Pages 2-5)
5,2026,Revenue Budget,006 (Local taxes/rates),Power transmission,416572.0,2026 Approved Budget PDF (Pages 2-5)
6,2026,Revenue Budget,007 (Local taxes/rates),Plant and Machinery,559125.0,2026 Approved Budget PDF (Pages 2-5)
7,2026,Revenue Budget,001 (Local taxes/rates),Personal levy,90000.0,2026 Approved Budget PDF (Pages 2-5)
8,2026,Revenue Budget,001 (Fees and Charges),Consent fees,506900.0,2026 Approved Budget PDF (Pages 2-5)
9,2026,Revenue Budget,002 (Fees and Charges),Survey fees,552000.0,2026 Approved Budget PDF (Pages 2-5)
10,2026,Revenue Budget,003 (Fees and Charges),Building inspection-fees,35000.0,2026 Approved Budget PDF (Pages 2-5)
11,2026,Revenue Budget,004 (Fees and Charges),Plan scrutiny fee,4350.0,2026 Approved Budget PDF (Pages 2-5)
12,2026,Revenue Budget,005 (Fees and Charges),Change of premise use,45839.0,2026 Approved Budget PDF (Pages 2-5)
13,2026,Revenue Budget,007 (Fees and Charges),Rentals/lease of Council’s properties,138000.0,2026 Approved Budget PDF (Pages 2-5)
14,2026,Revenue Budget,008 (Fees and Charges),Non-Land Application forms fees,236020.0,2026 Approved Budget PDF (Pages 2-5)

,year,financial_type,category/code,description,amount,source
89,2026,Revenue Budget,004 (National Support (Grants)),Local Government Equalisation Fund,17054618.0,2026 Approved Budget PDF (Pages 2-5)
90,2026,Revenue Budget,005 (National Support (Grants)),Grants in lieu of Rates,350000.0,2026 Approved Budget PDF (Pages 2-5)
91,2026,Revenue Budget,099 (National Support (Grants)),Other Grants,24148681.0,2026 Approved Budget PDF (Pages 2-5)
92,2026,Revenue Budget,001 (Donor Support (Grants)),Devolution Capital Grant,5819856.0,2026 Approved Budget PDF (Pages 2-5)
93,2026,Expenditure Budget (Economic Classification),21,Personal Emoluments,25110993.0,2026 Approved Budget PDF (Pages 5-6)
94,2026,Expenditure Budget (Economic Classification),22,Goods and Services,33391520.0,2026 Approved Budget PDF (Pages 5-6)
95,2026,Expenditure Budget (Economic Classification),25,Social Assistance Benefits,21553524.0,2026 Approved Budget PDF (Pages 5-6)
96,2026,Expenditure Budget (Economic Classification),26,Grants and Other Payments(Transfers),19325693.0,2026 Approved Budget PDF (Pages 5-6)
97,2026,Expenditure Budget (Economic Classification),31,Non-Financial Assets,65316312.0,2026 Approved Budget PDF (Pages 5-6)
98,2026,Expenditure Budget (Economic Classification),41,Current Liabilities (Payable within one year),1208000.0,2026 Approved Budget PDF (Pages 5-6)

In [ ]:
budget_2026_file.seek(0)  # Reset buffer pointer

with pdfplumber.open(budget_2026_file) as pdf:
    for page_num in range(7, 10):
        text = pdf.pages[page_num - 1].extract_text()
        print("\n" + "=" * 80)
        print(f"PAGE {page_num}")
        print("=" * 80)
        print(text if text else "NO TEXT FOUND")

================================================================================
PAGE 7
================================================================================
OUTPUT BASED ANNUAL BUDGET Page 7
HEAD9209 MUMBWA TOWN COUNCIL
Table:2 Budget Allocation by Programme
2024 2025 2026
Programme
Code Approved Approved Budget
Budget(K) Budget(K) Estimates(K)
1 Constituency Development 61,271,284 72,116,301 80,065,100
2 Local Governance 4,747,244 3,329,422 3,404,859
3 Integrated Development Planning 2,966,989 1,894,846 2,476,953
4 Economic and business development 697,049 793,435 777,282
5 Public health and Environmental protection 2,288,188 1,805,457 2,463,497
6 Housing and Community Amenities 10,472,316 15,039,781 13,115,225
7 Recreation Culture and Religion 25,788 1,142,856 699,909
8 Education and skills development 2,000 150,341 723,657
9 Social Protection (0) - -
10 Public order and safety 5,012,160 6,611,175 7,401,149
11 Management and support Services 14,015,358 12,737,868 15,912,325
12 Resource Mobilisation and Management 1,731,459 1,412,318 1,746,942
13 District Health servcies - 6,109,336 6,432,992
15 Transport Services 3,892,823 3,681,698 6,832,481
16 Agricultural Services - 517,781 502,947
17 Fisheries and Livestock 166,613 486,160 503,175
18 Social Protection and Community Development 470,041 52,701,950 22,847,549
107,759,311 180,530,727 165,906,043
Head Total
Figure 2:Budget Allocation by Programme
4.12%
4.4061.%4.025%% 13.77%
1.48%
0.30%
9.59%
2.05%
1.49% 48.26%
7.91%
0.30%
Agricultural Services Constituency Development
District Health servci0e.s44% Economic and business development
Education and skills development Fisheries and Livestock
0.47%
Housing and Community Amenities Integrated Development Planning
3.88%
Local Governance Management and support Services
Public health and Environmental protection Public order and safety
Recreation Culture and Religion Resource Mobilisation and Management
Social Protection and Community Development Transport Services

================================================================================
PAGE 8
================================================================================
Page 8 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
Table 3: Budget Allocation by Programme and Sub-Programme
PROGRAMME/SUB-PROGRAMME 2024 BUDGET 2025 BUDGET 2026 BUDGET
Approved Expendit Approved Expendit Estimate
ure ure*
- -
1 Constituency Development 61,271,284 72,116,301 80,065,100
779 Community Projects 34,924,632 - 43,925,383 - 57,119,825
780 Women and Youth Empowerment 11,641,544 - 12,456,452 - 5,518,484
781 CDF Administration 3,063,564 - 3,278,014 - 3,630,581
782 Secondary School and Skills Development Bursaries 11,641,544 - 12,456,452 - 13,796,210
- -
2 Local Governance 4,747,244 3,329,422 3,404,859
003 (cid:9)Legislative Functions 2,019,244 - 3,276,491 - 3,335,054
010 Local Elections 1,000,000 - 52,931 - 69,805
045 Citizen Engagement 1,728,000 - - - (0)
- -
3 Integrated Development Planning 2,966,989 1,894,846 2,476,953
006 Environmental planning - - 16,384 - (0)
021 Spatial Planning 2,236,412 - 1,097,874 - 1,581,774
033 Socio Economic planning 730,576 - 780,588 - 895,179
- -
4 Economic and business development 697,049 793,435 777,282
038 Trade facilitation and Licensing 697,049 - 793,435 - 777,282
- -
5 Public health and Environmental protection 2,288,188 1,805,457 2,463,497
019 Health Inspections 651,515 - 760,776 - 994,958
023 Pest control 8,080 - 59,856 - 34,200
027 Solid Waste Management 714,647 - 709,479 - 636,770
034 Water supply and Sanitation Services 913,946 - 275,346 - 797,569
- -
6 Housing and Community Amenities 10,472,316 15,039,781 13,115,225
008 Roads and Drainages 1,185,396 - 1,530,885 - 264,855
011 Parks and Gardens 95,570 - 231,020 - 100,715
012 Markets and Bus Stations 1,672,702 - 2,188,471 - 2,341,622
017 Community Centres 3,829,560 - 8,449,680 - 5,981,066
026 Public Housing 2,391,677 - 2,639,726 - 4,426,967
031 Street Lighting 1,297,412 - - - (0)
- -
7 Recreation Culture and Religion 25,788 1,142,856 699,909
001 Cultural Affairs 19,259 - 16,474 - 16,474
032 Registration of Marriages and Deaths 6,529 - 3,800 - 5,300
042 Sports Promotion - - 1,122,582 - 678,135
- -
8 Education and skills development 2,000 150,341 723,657
001 District archives 2,000 - 19,201 - 19,915
039 Library Services - - 131,140 - 703,742
- -
9 Social Protection (0) - -
037 Support to Indigent People (0) - - - -
- -
10 Public order and safety 5,012,160 6,611,175 7,401,149
014 Building Regulations 543,005 - 476,657 - 500,965
018 Community Policing 1,674,639 - 1,464,097 - 1,733,858
041 Fire Protection Services 2,794,516 - 4,670,421 - 5,166,327
- -
11 Management and support Services 14,015,358 12,737,868 15,912,325
001 Human Resource 4,661,150 - 5,006,706 - 6,915,309
003 Public Relations 537,173 - 585,559 - 509,370
009 Executive Management 869,826 - 664,871 - 935,968
016 (cid:9)ProcurementMangement 795,364 - 571,924 - 687,065
024 ICT 1,186,477 - 759,978 - 836,757
028 (cid:9)Auditing 731,431 - 394,128 - 1,104,743

================================================================================
PAGE 9
================================================================================
OUTPUT BASED ANNUAL BUDGET Page 9
HEAD9209 MUMBWA TOWN COUNCIL
035 Accounting Management 4,383,197 - 3,964,291 - 3,795,846
036 Legal Services 850,741 - 790,412 - 1,127,267
- -
12 Resource Mobilisation and Management 1,731,459 1,412,318 1,746,942
067 Revenue Mobilisation and Enhancement 1,731,459 - 1,412,318 - 1,746,942
- -
13 District Health servcies - 6,109,336 6,432,992
001 Primary Health Services - - 5,432,712 - 5,756,368
002 District Health Coordination - - 676,624 - 676,624
- -
15 Transport Services 3,892,823 3,681,698 6,832,481
001 Road Transport 3,742,847 - 3,200,587 - 6,351,370
003 Water Transport 149,976 - 481,111 - 481,111
- -
16 Agricultural Services - 517,781 502,947
071 Agricultural Crop production, Advisory and Technical - - 319,854 - 308,724
Services
072 Agribusiness Development and Marketing - - 52,400 - 61,543
073 Agriculture Co-ordination - - 145,527 - 132,680
- -
17 Fisheries and Livestock 166,613 486,160 503,175
074 Fisheries and Livestock Marketing - - 105,310 - 108,996
075 Animal Health Services 166,613 - 129,000 - 133,506
076 Fisheries Production and Productivity Improvement - - 67,182 - 69,456
077 Livestock Production and Productivity Improvement - - 68,128 - 70,602
078 District Fisheries and Livestock Coordination - - 116,540 - 120,616
- -
18 Social Protection and Community Development 470,041 52,701,950 22,847,549
079 District Social welfare 470,041 - 52,696,778 - 22,840,652
080 Community Development - - 5,172 - 6,897
Head Total 107,759,311 - 180,530,727 - 165,906,043
The Constituency Development Programme has been allocated K80.1 million shared among Four (4) sub-
programmes as follows: Community Projects have been allocated K57.1 million in order to address
challenges of inadequate public infrastructure in communities and Esterblishment of Solar Plants; Youth
and Women Empowerments have been allocated K5.5 million to provide needed capital for
entrepreneurship initiatives; Secondary Boarding School and Skills Development Bursaries have been
allocated K13.7 million for the provision of bursaries to vulnerable learners and disadvantaged youths
respectively. Lastly, K3.6 million has been reserved for Administrative cost to ensure adequate
monitoring and supervision of CDF projects.
Local Governance has been allocated K3.4 million shared among two (2) sub programmes as follows:
Legislative Function has an allocation of K3.3 million meant for facilitating the holding of all Council
Committees meetings as well as Ordinary Council meetings while Local Election has an allocation of
K69,805 meant for engaging key stakeholders including Ward Development Committees.
Integrated Development Planning has been allocated K2.4 million and shared among Two (2) sub-
programmes as follows: Spatial Planning has an allocation of K1.5 million for land management and
administration; Socio-Economic Planning has been allocated K895,179 for the coordination of district
development activities.
Economic and Business Development has been allocated K777,282 for Trade Facilitation and Licensing in
order to promote business growth and promote new investments in the district thereby creating jobs for
the people of Mumbwa.
Public Health and Environmental Protection programme has been allocated K2.4 million towards the
implementation of four (4) sub-programmes as follows: Health Inspections has been allocated K994,958

In [ ]:
import pandas as pd
import re

pg7_text = pages_text.get(7, "")
pg8_text = pages_text.get(8, "")
pg9_text = pages_text.get(9, "")

prog_rows = []

# --- 1. Parse Table 2 (Page 7): Programme Allocations ---
prog_pattern = re.compile(r"^(\d{1,2})\s+(.*?)\s+([\d,-]+)\s+([\d,-]+)\s+([\d,-]+)$")

for line in pg7_text.split("\n"):
    line = line.strip()
    match = prog_pattern.match(line)
    if match and "Head Total" not in line:
        p_code = match.group(1)
        p_name = match.group(2).strip()
        amt_2024 = match.group(3).replace(",", "").replace("-", "0")
        amt_2025 = match.group(4).replace(",", "").replace("-", "0")
        amt_2026 = match.group(5).replace(",", "").replace("-", "0")

        # Add 2026 entry
        prog_rows.append({
            "year": 2026,
            "financial_type": "Programme Budget",
            "category/code": f"Prog {p_code}",
            "description": p_name,
            "amount": float(amt_2026),
            "source": "2026 Approved Budget PDF (Page 7)"
        })

# --- 2. Parse Table 3 (Pages 8-9): Sub-Programme Allocations ---
# Pattern matches lines like "779 Community Projects 34,924,632 - 43,925,383 - 57,119,825"
subprog_pattern = re.compile(r"^(\d{3})\s+(.*?)\s+[\d,-]+\s+-\s+[\d,-]+\s+-\s+([\d,-]+|\(0\))$")

combined_sub_text = pg8_text + "\n" + pg9_text

for line in combined_sub_text.split("\n"):
    line = line.strip()
    # Clean OCR artefacts like (cid:9)
    line = re.sub(r"\(cid:\d+\)", "", line).strip()

    match = subprog_pattern.match(line)
    if match:
        sp_code = match.group(1)
        sp_name = match.group(2).strip()
        amt_2026_raw = match.group(3).replace(",", "").replace("(0)", "0").replace("-", "0")

        prog_rows.append({
            "year": 2026,
            "financial_type": "Sub-Programme Budget",
            "category/code": f"SubProg {sp_code}",
            "description": sp_name,
            "amount": float(amt_2026_raw),
            "source": "2026 Approved Budget PDF (Pages 8-9)"
        })

# Append to master budget_2026_df
df_programmes = pd.DataFrame(prog_rows)
budget_2026_df = pd.concat([budget_2026_df, df_programmes], ignore_index=True)

print(f"Extracted {len(df_programmes)} programme/sub-programme rows. Total records: {len(budget_2026_df)}")
display(budget_2026_df.tail(20))

Extracted 0 programme/sub-programme rows. Total records: 99

,year,financial_type,category/code,description,amount,source
79,2026,Revenue Budget,099 (Permits),"Primary, Secondary and Tertiary permits",56000.0,2026 Approved Budget PDF (Pages 2-5)
80,2026,Revenue Budget,003 (Charges),Premium Plot- Residential,669000.0,2026 Approved Budget PDF (Pages 2-5)
81,2026,Revenue Budget,007 (Charges),Land Application Charges,18750.0,2026 Approved Budget PDF (Pages 2-5)
82,2026,Revenue Budget,008 (Charges),Land Conversion,3197500.0,2026 Approved Budget PDF (Pages 2-5)
83,2026,Revenue Budget,009 (Charges),Change of ownership,98000.0,2026 Approved Budget PDF (Pages 2-5)
84,2026,Revenue Budget,002 (Other Incomes),Surplus/ Deficit from Commercial Ventures,120278.0,2026 Approved Budget PDF (Pages 2-5)
85,2026,Revenue Budget,099 (Other Incomes),Other Income,68000.0,2026 Approved Budget PDF (Pages 2-5)
86,2026,Revenue Budget,001 (National Support (Grants)),Constituency Development Fund,80065100.0,2026 Approved Budget PDF (Pages 2-5)
87,2026,Revenue Budget,002 (National Support (Grants)),Roads Grant,6832481.0,2026 Approved Budget PDF (Pages 2-5)
88,2026,Revenue Budget,003 (National Support (Grants)),Health Grant,6432992.0,2026 Approved Budget PDF (Pages 2-5)
89,2026,Revenue Budget,004 (National Support (Grants)),Local Government Equalisation Fund,17054618.0,2026 Approved Budget PDF (Pages 2-5)
90,2026,Revenue Budget,005 (National Support (Grants)),Grants in lieu of Rates,350000.0,2026 Approved Budget PDF (Pages 2-5)
91,2026,Revenue Budget,099 (National Support (Grants)),Other Grants,24148681.0,2026 Approved Budget PDF (Pages 2-5)
92,2026,Revenue Budget,001 (Donor Support (Grants)),Devolution Capital Grant,5819856.0,2026 Approved Budget PDF (Pages 2-5)
93,2026,Expenditure Budget (Economic Classification),21,Personal Emoluments,25110993.0,2026 Approved Budget PDF (Pages 5-6)
94,2026,Expenditure Budget (Economic Classification),22,Goods and Services,33391520.0,2026 Approved Budget PDF (Pages 5-6)
95,2026,Expenditure Budget (Economic Classification),25,Social Assistance Benefits,21553524.0,2026 Approved Budget PDF (Pages 5-6)
96,2026,Expenditure Budget (Economic Classification),26,Grants and Other Payments(Transfers),19325693.0,2026 Approved Budget PDF (Pages 5-6)
97,2026,Expenditure Budget (Economic Classification),31,Non-Financial Assets,65316312.0,2026 Approved Budget PDF (Pages 5-6)
98,2026,Expenditure Budget (Economic Classification),41,Current Liabilities (Payable within one year),1208000.0,2026 Approved Budget PDF (Pages 5-6)

In [ ]:
import pandas as pd
import re
import pdfplumber

prog_rows = []

budget_2026_file.seek(0)

with pdfplumber.open(budget_2026_file) as pdf:
    # --- 1. Parse Table 2 (Page 7): Programme Allocations ---
    pg7_text = pdf.pages[6].extract_text() or ""
    for line in pg7_text.split("\n"):
        line = line.strip()
        # Look for lines starting with 1-2 digits, text, and 3 financial figures
        match = re.match(r"^(\d{1,2})\s+(.*?)\s+([\d,]+|-)\s+([\d,]+|-)\s+([\d,]+|-)$", line)
        if match and "Head Total" not in line and "Code" not in line:
            p_code = match.group(1)
            p_name = match.group(2).strip()
            amt_2026 = match.group(5).replace(",", "").replace("-", "0")

            prog_rows.append({
                "year": 2026,
                "financial_type": "Programme Budget",
                "category/code": f"Prog {p_code}",
                "description": p_name,
                "amount": float(amt_2026),
                "source": "2026 Approved Budget PDF (Page 7)"
            })

    # --- 2. Parse Table 3 (Pages 8-9): Sub-Programme Allocations ---
    sub_text = (pdf.pages[7].extract_text() or "") + "\n" + (pdf.pages[8].extract_text() or "")
    for line in sub_text.split("\n"):
        # Clean cid artifacts
        line = re.sub(r"\(cid:\d+\)", "", line).strip()

        # Matches lines starting with 3-digit sub-programme code (e.g. 779, 003, 038)
        # and captures the final number (2026 estimate) on the line
        match = re.match(r"^(\d{3})\s+(.*?)\s+([\d,\s\-\(\)]+)$", line)
        if match:
            sp_code = match.group(1)
            rest = match.group(2).strip()

            # Extract all numerical chunks from the end of the line
            numbers = re.findall(r"[\d,]+|\(0\)", line)
            if numbers:
                amt_2026_raw = numbers[-1].replace(",", "").replace("(0)", "0")
                # Remove trailing numbers from description if caught
                sp_name = re.sub(r"\s+[\d,]+.*$", "", rest).strip()

                prog_rows.append({
                    "year": 2026,
                    "financial_type": "Sub-Programme Budget",
                    "category/code": f"SubProg {sp_code}",
                    "description": sp_name,
                    "amount": float(amt_2026_raw),
                    "source": "2026 Approved Budget PDF (Pages 8-9)"
                })

# Append to master budget_2026_df
df_programmes = pd.DataFrame(prog_rows)
budget_2026_df = pd.concat([budget_2026_df, df_programmes], ignore_index=True)

print(f"Successfully extracted {len(df_programmes)} programme/sub-programme rows.")
print(f"Total dataset records: {len(budget_2026_df)}")
display(budget_2026_df.tail(20))

Successfully extracted 69 programme/sub-programme rows.
Total dataset records: 168

,year,financial_type,category/code,description,amount,source
148,2026,Sub-Programme Budget,SubProg 016,ProcurementMangement,687065.0,2026 Approved Budget PDF (Pages 8-9)
149,2026,Sub-Programme Budget,SubProg 024,ICT,836757.0,2026 Approved Budget PDF (Pages 8-9)
150,2026,Sub-Programme Budget,SubProg 028,Auditing,1104743.0,2026 Approved Budget PDF (Pages 8-9)
151,2026,Sub-Programme Budget,SubProg 035,Accounting Management,3795846.0,2026 Approved Budget PDF (Pages 8-9)
152,2026,Sub-Programme Budget,SubProg 036,Legal Services,1127267.0,2026 Approved Budget PDF (Pages 8-9)
153,2026,Sub-Programme Budget,SubProg 067,Revenue Mobilisation and Enhancement,1746942.0,2026 Approved Budget PDF (Pages 8-9)
154,2026,Sub-Programme Budget,SubProg 001,Primary Health Services,5756368.0,2026 Approved Budget PDF (Pages 8-9)
155,2026,Sub-Programme Budget,SubProg 002,District Health Coordination,676624.0,2026 Approved Budget PDF (Pages 8-9)
156,2026,Sub-Programme Budget,SubProg 001,Road Transport,6351370.0,2026 Approved Budget PDF (Pages 8-9)
157,2026,Sub-Programme Budget,SubProg 003,Water Transport,481111.0,2026 Approved Budget PDF (Pages 8-9)
158,2026,Sub-Programme Budget,SubProg 071,"Agricultural Crop production, Advisory and Technical",308724.0,2026 Approved Budget PDF (Pages 8-9)
159,2026,Sub-Programme Budget,SubProg 072,Agribusiness Development and Marketing,61543.0,2026 Approved Budget PDF (Pages 8-9)
160,2026,Sub-Programme Budget,SubProg 073,Agriculture Co-ordination,132680.0,2026 Approved Budget PDF (Pages 8-9)
161,2026,Sub-Programme Budget,SubProg 074,Fisheries and Livestock Marketing,108996.0,2026 Approved Budget PDF (Pages 8-9)
162,2026,Sub-Programme Budget,SubProg 075,Animal Health Services,133506.0,2026 Approved Budget PDF (Pages 8-9)
163,2026,Sub-Programme Budget,SubProg 076,Fisheries Production and Productivity Improvement,69456.0,2026 Approved Budget PDF (Pages 8-9)
164,2026,Sub-Programme Budget,SubProg 077,Livestock Production and Productivity Improvement,70602.0,2026 Approved Budget PDF (Pages 8-9)
165,2026,Sub-Programme Budget,SubProg 078,District Fisheries and Livestock Coordination,120616.0,2026 Approved Budget PDF (Pages 8-9)
166,2026,Sub-Programme Budget,SubProg 079,District Social welfare,22840652.0,2026 Approved Budget PDF (Pages 8-9)
167,2026,Sub-Programme Budget,SubProg 080,Community Development,6897.0,2026 Approved Budget PDF (Pages 8-9)

In [ ]:
budget_2026_file.seek(0)

with pdfplumber.open(budget_2026_file) as pdf:
    for page_num in range(12, 17):
        text = pdf.pages[page_num - 1].extract_text()
        print("\n" + "=" * 80)
        print(f"PAGE {page_num}")
        print("=" * 80)
        print(text if text else "NO TEXT FOUND")

================================================================================
PAGE 12
================================================================================
Page 12 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
BUDGET PROGRAMMES
Programme 1 : Constituency Development
Programme Objective
To facilitate equitable development, reduce poverty, support job creation and provide for vulnerable learners to access
Secondary Boarding Schools and Technical Education, Vocational and Entrepreneurship Training Institutions.
Table 4: Programme Budget Allocation by Economic Classification
2024 BUDGET 2025 BUDGET 2026 BUDGET
ECONOMIC CLASSIFICATION
Approved Expendit Approved Expendit Estimates
ure ure*
02Use of Goods and Services 3,063,564 - 9,834,041 - 11,084,052
02General Operations 3,063,564 - 9,834,041 - 11,084,052
03Transfers 16,298,162 - 17,439,033 - 19,314,693
01Transfers 16,298,162 - 17,439,033 - 19,314,693
04Assets 41,909,558 - 44,843,227 - 49,666,354
01Non-Financial Assets (Capital Expenditure) 34,924,632 - 37,369,356 - 49,666,354
02Financial Assets 6,984,926 - 7,473,871 - -
Programme Total 61,271,284 - 80,065,100
72,116,301 -
The budget allocation by Economic Classification indicates that of the K80 million allocated for
Constituency Development, K49.6 million has been apportioned to Assets for Community Projects such
as the construction of schools and Esterblishment of Solar Plants, K19.3 million has been allocated
towards Transfers to cater for empowerment grants, skills and secondary school bursaries while Use of
Goods and Services has been allocated K11.1 million for monitoring and administration.
Programme 0001: Constituency Development
Table 5: Programme Budget Allocation by Subprogramme
2024 BUDGET 2025 BUDGET 2026 BUDGET
PROGRAMME/SUBPROGRAMME
Approved Expendit Approved Expendit Estimates
ure ure*
1 Constituency Development 61,271,284 72,116,301 80,065,100
779Community Projects 34,924,632 - 43,925,383 - 57,119,825
780Women and Youth Empowerment 11,641,544 - 12,456,452 - 5,518,484
781CDF Administration 3,063,564 - 3,278,014 - 3,630,581
782Secondary School and Skills Development 11,641,544 - 12,456,452 - 13,796,210
Bursaries
Programme Total 61,271,284 - 72,116,301 - 8800,0,06655,1,10000
The Constituency Development Programme has been allocated K80.1 million shared among four (4) sub-
programmes as follows: Community Projects have been allocated K57.1 million in order to address
challenges of inadequate public infrastructure in communities and also Esterblishment of Solar Plants;
Youth and Women Empowerments have been allocated K5.5 million to provide needed Capital for
Entrepreneurship initiatives; Secondary Boarding School and Skills Development Bursaries have been
allocated K13.7 million for the provision of bursaries to vulnerable learners and disadvantaged youths
respectively. Lastly, K3.6 million has been reserved for Administrative cost to ensure adequate
monitoring and supervision of CDF projects.

================================================================================
PAGE 13
================================================================================
OUTPUT BASED ANNUAL BUDGET Page 13
HEAD9209 MUMBWA TOWN COUNCIL
Programme: 1Constituency Development
Table 6: Programme Outputs
Key Output and Output Indicator 2024 2025 2026
Target Actual Target Actual* Target
Community Projects Implemented
01 Number of commiunity projects implemented (0) (0) 28 25 25
02 Number of desks procured (0) (0) 1,145 630 1,000
03 Number of maternity annexes constructed (0) (0) 1 1 2
04 Number of boreholes drilled (0) (0) (0) (0) 15
05 Kilometers of Rural Roads Rehabilitated (0) (0) (0) (0) 50
06 Number of Solar Plants Established (0) (0) (0) (0) 2
Empowerment Funds Disbursed
01 Number of beneficiaries empowered with grants (0) (0) 50 134 50
Monitoring of CDF Projects Conducted
01 Percentage of CDF projects monitored (0) (0) 100 100 100
Bursaries Offered to Beneficiaries
01 Number of successful applicants sponsored with skills bursaries (0) (0) 792 792 800
02 Number of succesful student applicants sponsored with secondary bursaries (0) (0) 481 481 500
Executive Authority:
Controlling Officer: Programmes under which this Council will be accounted for by theCouncil Secretary, Mumbwa Town Council
Under this Programme, the Council targets to implement 25 approved projects in the twenty one wards of
the district, procure three 1000 desks, construct two (2) Maternity annexes for Nangoma and Mumbwa
constituencies and rehabilitate 50 Kilometers of Rural Roads, drill and equip 15 boreholes in the district and
Esterblish Two ( 2 ) Solar Plants in the two Constituencies of the District, empower 50 women and youths
with grants. Additionally, the Council aims at sponsoring 800 applicants for skills development and also
sponsor 500 applicants for secondary school bursaries. To ensure effective and efficient implementation, the
Council targets to monitor 100 percent of the CDF projects under implementation.

================================================================================
PAGE 14
================================================================================
Page 14 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
BUDGET PROGRAMMES
Programme 2 : Local Governance
Programme Objective
To facilitate community participation in decision making for sustainable local development.
Table 4: Programme Budget Allocation by Economic Classification
2024 BUDGET 2025 BUDGET 2026 BUDGET
ECONOMIC CLASSIFICATION
Approved Expendit Approved Expendit Estimates
ure ure*
01Personal Emoluments 2,280,270 - 552,542 - 432,018
01Salaries and Wages 552,270 - 552,542 - 432,018
03Personnel Related Costs 1,728,000 - - - -
02Use of Goods and Services 2,090,374 - 2,671,780 - 2,909,589
02General Operations 2,090,374 - 2,671,780 - 2,909,589
04Assets 376,600 - 105,100 - 63,252
01Non-Financial Assets (Capital Expenditure) 376,600 - 105,100 - 63,252
Programme Total 4,747,244 - 3,404,859
3,329,422 -
The budget allocation by Economic Classification shows that use of Goods and Services has been
allocated K2.9 million for general operations which include councilors allowances during Council and
Committee meetings as well as citizens engagement, K432,018 has been allocated towards Personal
Emoluments to cater for salaries, wages and other personnel related costs while K63,252 has been
allocated towards the Acquisition of Assets such as office equipment.
Programme 0002: Local Governance
Table 5: Programme Budget Allocation by Subprogramme
2024 BUDGET 2025 BUDGET 2026 BUDGET
PROGRAMME/SUBPROGRAMME
Approved Expendit Approved Expendit Estimates
ure ure*
2 Local Governance 4,747,244 3,329,422 3,404,859
003(cid:9)Legislative Functions 2,019,244 - 3,276,491 - 3,335,054
010Local Elections 1,000,000 - 52,931 - 69,805
045Citizen Engagement 1,728,000 - - - (0)
Programme Total 4,747,244 - 3,329,422 - 3,34,0440,48,58959
Local Governance has been allocated K3.3 million shared among two (2) sub programmes as follows:
Legislative Function has an allocation of K3.3 million meant for facilitating the holding of all Council
Committees meetings as well as Ordinary Council meetings while Local Election has an allocation of
K69,805 meant for engaging key stakeholders including Ward Development Committees.

================================================================================
PAGE 15
================================================================================
OUTPUT BASED ANNUAL BUDGET Page 15
HEAD9209 MUMBWA TOWN COUNCIL
Programme: 2Local Governance
Table 6: Programme Outputs
Key Output and Output Indicator 2024 2025 2026
Target Actual Target Actual* Target
Council Meetings Held
01 Number of ordinary Council meetings held (0) (0) 4 3 3
02 Number of Committee meetings held 28 28 23 18 18
03 Number of special ordinary Council meetings held (0) (0) 1 3 2
04 Number of special Committee meetings held (0) (0) 1 1 2
Ward Development Committees Operationalised
01 Number of Ward Development Committees operationalised (0) (0) 21 21 21
Executive Authority:
Controlling Officer: Programmes under which this Council will be accounted for by theCouncil Secretary, Mumbwa Town Council
The Council will hold Three (3) ordinary Council meetings and 18 Committee meetings, two (2) special
ordinary Council meeting, two (2) special Committee meeting and facilitating the functioning of 21 Ward
Development Committees.

================================================================================
PAGE 16
================================================================================
Page 16 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
BUDGET PROGRAMMES
Programme 3 : Integrated Development Planning
Programme Objective
To guide spatial, social-economic, and environmental planning in the district.
Table 4: Programme Budget Allocation by Economic Classification
2024 BUDGET 2025 BUDGET 2026 BUDGET
ECONOMIC CLASSIFICATION
Approved Expendit Approved Expendit Estimates
ure ure*
01Personal Emoluments 1,120,907 - 1,425,932 - 1,384,057
01Salaries and Wages 1,120,907 - 1,425,932 - 1,384,057
02Use of Goods and Services 1,246,082 - 408,914 - 1,057,896
02General Operations 1,246,082 - 408,914 - 1,057,896
04Assets 600,000 - 60,000 - 35,000
01Non-Financial Assets (Capital Expenditure) 600,000 - 60,000 - 35,000
Programme Total 2,966,989 - 2,476,953
1,894,846 -
The budget allocation by Economic Classification for Integrated Development Planning indicates that
K1.3 million has been allocated to Personal Emoluments cover for salaries, wages and other personnel
related costs, K1.1 Million has been allocated to the use of Goods and Services for general operations
while Assets has been allocated K35,000 for the procurement of furniture and office equipment.
Programme 0003: Integrated Development Planning
Table 5: Programme Budget Allocation by Subprogramme
2024 BUDGET 2025 BUDGET 2026 BUDGET
PROGRAMME/SUBPROGRAMME
Approved Expendit Approved Expendit Estimates
ure ure*
3 Integrated Development Planning 2,966,989 1,894,846 2,476,953
006Environmental planning - - 16,384 - (0)
021Spatial Planning 2,236,412 - 1,097,874 - 1,581,774
033Socio Economic planning 730,576 - 780,588 - 895,179
Programme Total 2,966,989 - 1,894,846 - 2,24,7467,69,59353
Integrated Development Planning has been allocated K2.4 million and shared among three (2) sub-
programmes as follows: Spatial Planning has an allocation of K1.5 Million for land management and
administration; Socio-Economic Planning has been allocated K895,179 for the coordination of district
development activities.

In [ ]:
import pandas as pd
import re
import pdfplumber

prog_econ_rows = []

budget_2026_file.seek(0)

# Regex patterns
prog_header_pattern = re.compile(r"^Programme\s+(\d{1,2})\s*:\s*(.*)$")
# Matches economic lines like "01Personal Emoluments ... 1,384,057" or "02General Operations ... 11,084,052"
econ_line_pattern = re.compile(r"^(\d{2})\s*([A-Za-z\s\(\)/-]+?)\s+[\d,\s\-\(\)]+$")

current_prog_num = None
current_prog_title = None

with pdfplumber.open(budget_2026_file) as pdf:
    # Scan through pages 10 to 52 for granular line-item breakdowns
    for page_idx in range(9, len(pdf.pages)):
        text = pdf.pages[page_idx].extract_text() or ""
        lines = text.split("\n")

        for line in lines:
            line = line.strip()

            # 1. Detect Programme Header
            prog_match = prog_header_pattern.match(line)
            if prog_match:
                current_prog_num = prog_match.group(1)
                current_prog_title = prog_match.group(2).strip()
                continue

            # 2. Detect Economic Classification lines under Table 4
            econ_match = econ_line_pattern.match(line)
            if econ_match and current_prog_title:
                code_prefix = econ_match.group(1)
                desc = econ_match.group(2).strip()

                # Exclude summary/total lines or headers
                if desc.lower() in ["programme total", "economic classification", "approved", "estimates"]:
                    continue

                # Extract all numbers from the line; the last number is 2026 Estimate
                numbers = re.findall(r"[\d,]+|\(0\)", line)
                if numbers:
                    amt_str = numbers[-1].replace(",", "").replace("(0)", "0")
                    try:
                        amt = float(amt_str)
                        prog_econ_rows.append({
                            "year": 2026,
                            "financial_type": f"Programme {current_prog_num} Expenditure",
                            "category/code": f"Prog {current_prog_num} ({code_prefix})",
                            "description": f"{current_prog_title} - {desc}",
                            "amount": amt,
                            "source": f"2026 Approved Budget PDF (Page {page_idx + 1})"
                        })
                    except ValueError:
                        continue

# Append to master dataset
df_prog_econ = pd.DataFrame(prog_econ_rows)
budget_2026_df = pd.concat([budget_2026_df, df_prog_econ], ignore_index=True)

print(f"Extracted {len(df_prog_econ)} detailed programme economic classification items.")
print(f"Total dataset records: {len(budget_2026_df)}")
display(budget_2026_df.tail(25))

Extracted 209 detailed programme economic classification items.
Total dataset records: 377

,year,financial_type,category/code,description,amount,source
352,2026,Programme 16 Expenditure,Prog 16 (01),Agricultural Services - Number of motor vehicles insured,2.0,2026 Approved Budget PDF (Page 41)
353,2026,Programme 17 Expenditure,Prog 17 (02),Fisheries and Livestock - Use of Goods and Services,503175.0,2026 Approved Budget PDF (Page 42)
354,2026,Programme 17 Expenditure,Prog 17 (02),Fisheries and Livestock - General Operations,503175.0,2026 Approved Budget PDF (Page 42)
355,2026,Programme 17 Expenditure,Prog 17 (17),Fisheries and Livestock - Fisheries and Livestock,503175.0,2026 Approved Budget PDF (Page 43)
356,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of Agriculture shows conducted,5.0,2026 Approved Budget PDF (Page 44)
357,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of Fisheries and Livestock Entreprenuership Trainings conducted,20.0,2026 Approved Budget PDF (Page 44)
358,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number Animals Vaccinated against Management Diseases,130000.0,2026 Approved Budget PDF (Page 44)
359,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of Animal Disease Surveillance activities conducted,40.0,2026 Approved Budget PDF (Page 44)
360,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of Aquaculture Extension Services conducted,120.0,2026 Approved Budget PDF (Page 44)
361,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of Fisheries Patrols conducted,38.0,2026 Approved Budget PDF (Page 44)
362,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of livestock trainings conducted,70.0,2026 Approved Budget PDF (Page 44)
363,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of climate smart livestock technologies and practices promoted,6.0,2026 Approved Budget PDF (Page 44)
364,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of Fisheries and Livestock activities Monitored and Supervised,24.0,2026 Approved Budget PDF (Page 44)
365,2026,Programme 17 Expenditure,Prog 17 (01),Fisheries and Livestock - Number of Livestock activities Monitored and Evaluated,12.0,2026 Approved Budget PDF (Page 44)
366,2026,Programme 18 Expenditure,Prog 18 (02),Social Protection and Community Development - Use of Goods and Services,22847549.0,2026 Approved Budget PDF (Page 45)
367,2026,Programme 18 Expenditure,Prog 18 (02),Social Protection and Community Development - General Operations,22847549.0,2026 Approved Budget PDF (Page 45)
368,2026,Programme 18 Expenditure,Prog 18 (18),Social Protection and Community Development - Social Protection and Community Development,22847549.0,2026 Approved Budget PDF (Page 45)
369,2026,Programme 18 Expenditure,Prog 18 (01),Social Protection and Community Development - Number of infants supported with baby formula and supplimentary feeds,15.0,2026 Approved Budget PDF (Page 46)
370,2026,Programme 18 Expenditure,Prog 18 (01),Social Protection and Community Development - Number of stranded persons repatriated,15.0,2026 Approved Budget PDF (Page 46)
371,2026,Programme 18 Expenditure,Prog 18 (01),Social Protection and Community Development - Number of vulnerable persons assisted with social support,20.0,2026 Approved Budget PDF (Page 46)
372,2026,Programme 18 Expenditure,Prog 18 (01),Social Protection and Community Development - Number of persons assisted with medical bills and appliances,10.0,2026 Approved Budget PDF (Page 46)
373,2026,Programme 18 Expenditure,Prog 18 (01),Social Protection and Community Development - Number of place of safety for older persons provided,1.0,2026 Approved Budget PDF (Page 46)
374,2026,Programme 18 Expenditure,Prog 18 (01),Social Protection and Community Development - Number of beneficiaries receiving Cash for Work,5987.0,2026 Approved Budget PDF (Page 46)
375,2026,Programme 18 Expenditure,Prog 18 (02),Social Protection and Community Development - Proportion of Cash For Work funds disbursed,100.0,2026 Approved Budget PDF (Page 46)
376,2026,Programme 18 Expenditure,Prog 18 (01),Social Protection and Community Development - Number of community members sensitised in functional adult litracy,160.0,2026 Approved Budget PDF (Page 46)

In [ ]:
# --- Data Cleaning ---
# Filter out target/output indicators (e.g. "Number of...", "Kilometers of...", "Proportion of...", "Percentage of...")
cleaning_keywords = r"number of|kilometers of|proportion of|percentage of|ratio of|count of"

cleaned_budget_2026_df = budget_2026_df[
    ~budget_2026_df['description'].str.contains(cleaning_keywords, case=False, na=False)
].copy()

# Reset index after dropping rows
cleaned_budget_2026_df.reset_index(drop=True, inplace=True)

print(f"Original record count: {len(budget_2026_df)}")
print(f"Cleaned record count (monetary items only): {len(cleaned_budget_2026_df)}")

# Display summary breakdown by financial type
print("\nSummary breakdown of financial entries:")
print(cleaned_budget_2026_df['financial_type'].value_counts())

# Save 2026 Budget subset to CSV (pipe-separated)
output_filename = "db-unza26-csc4792-mumbwa_2026_approved_budget.csv"
cleaned_budget_2026_df.to_csv(output_filename, sep="|", index=False)

print(f"\nSuccessfully saved cleaned dataset to '{output_filename}' using '|' separator.")

Original record count: 377
Cleaned record count (monetary items only): 263

Summary breakdown of financial entries:
financial_type
Revenue Budget                                  93
Sub-Programme Budget                            53
Programme Budget                                16
Programme 11 Expenditure                        11
Programme 10 Expenditure                         7
Programme 1 Expenditure                          7
Programme 6 Expenditure                          7
Programme 2 Expenditure                          7
Programme 5 Expenditure                          7
Programme 12 Expenditure                         7
Expenditure Budget (Economic Classification)     6
Programme 4 Expenditure                          6
Programme 8 Expenditure                          6
Programme 7 Expenditure                          6
Programme 3 Expenditure                          6
Programme 15 Expenditure                         5
Programme 17 Expenditure                         4
Programme 13 Expenditure                         3
Programme 16 Expenditure                         3
Programme 18 Expenditure                         3
Name: count, dtype: int64

Successfully saved cleaned dataset to 'db-unza26-csc4792-mumbwa_2026_approved_budget.csv' using '|' separator.

In [ ]:
import io
import requests
import urllib3

# Suppress SSL verification warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# 1. Get URL from row 77
budget_2025_url = "https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/2025-BUDGET.pdf"

# 2. Download PDF bypassing SSL verification
budget_2025_response = requests.get(budget_2025_url, verify=False)

print(f"Download Status: {budget_2025_response.status_code}")
print(f"File size: {len(budget_2025_response.content)} bytes")

# Store in BytesIO buffer
budget_2025_file = io.BytesIO(budget_2025_response.content)

Download Status: 200
File size: 819434 bytes

In [ ]:
import pdfplumber

budget_2025_file.seek(0)

pages_text_2025 = {}

with pdfplumber.open(budget_2025_file) as pdf:
    print(f"Total pages in 2025 Budget: {len(pdf.pages)}")

    # Extract text from pages 2 to 9 (0-indexed: 1 to 8)
    for p_num in range(1, min(9, len(pdf.pages))):
        text = pdf.pages[p_num].extract_text() or ""
        pages_text_2025[p_num + 1] = text
        print(f"\n--- PAGE {p_num + 1} ---")
        print(text[:400] + "..." if len(text) > 400 else text)

Total pages in 2025 Budget: 60

--- PAGE 2 ---
Page 2 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
Cluster : 04 Good Governance Environment
Cluster Outcome 01 Improved Policy and Governance Environment
Strategy : 01 Decentralise Public Service Delivery Systems
Strategy : 03 Strengthen transparency and accountability mechanisms
Strategy : 05 Strengthen public service performance management systems
Cluster Outcome 02 Improved Rule of ...

--- PAGE 3 ---
OUTPUT BASED ANNUAL BUDGET Page 3
HEAD9209 MUMBWA TOWN COUNCIL
CODE REVENUE DESCRIPTION APPROVED REVISED BUDGET
BUDGET 2025 BUDGET 2026 ESTIMATE 2027
01 Local taxes/rates
001 Residential 863,624 932,714 998,004
002 Commercial 694,382 749,933 802,428
003 Industrial 682,464 737,061 788,655
004 Hospitality 956,218 1,032,715 1,105,006
005 Mining/Plant 604,958 653,355 699,089
006 Power transmission 416...

--- PAGE 4 ---
Page 4 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
CODE REVENUE DESCRIPTION APPROVED REVISED BUDGET
BUDGET 2025 BUDGET 2026 ESTIMATE 2027
02 Fees and Charges
001 Consent fees 454,900 491,292 525,682
002 Survey fees 672,000 725,760 776,563
003 Building inspection-fees 40,000 43,200 46,224
004 Plan scrutiny fee 478,200 516,456 552,608
007 Rentals/lease of Council’s properties 417,000 450...

--- PAGE 5 ---
OUTPUT BASED ANNUAL BUDGET Page 5
HEAD9209 MUMBWA TOWN COUNCIL
CODE REVENUE DESCRIPTION APPROVED REVISED BUDGET
BUDGET 2025 BUDGET 2026 ESTIMATE 2027
03 Licenses
002 Liquor licence 207,000 223,560 239,209
003 Firearm and ammunition licence 40,500 43,740 46,802
004 Petroleum Storage licence 54,000 58,320 62,402
005 Dog licence 30,000 32,400 34,668
099 Other Licences 280,000 302,400 323,568
SubItem ...

--- PAGE 6 ---
Page 6 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
CODE REVENUE DESCRIPTION APPROVED REVISED BUDGET
BUDGET 2025 BUDGET 2026 ESTIMATE 2027
06 Charges
002 Service Charges Industrial plots 300,000 324,000 346,680
003 Premium Plot- Residential 170,000 183,600 196,452
004 Premium Plot Commercial 300,000 324,000 346,680
007 Land Application Charges 157,500 170,100 182,007
008 Land Conversion...

--- PAGE 7 ---
OUTPUT BASED ANNUAL BUDGET Page 7
HEAD9209 MUMBWA TOWN COUNCIL
No ECONOMIC CLASSIFICATION 2023 2024 2025 BUDGET
APPROVED APPROVED ESTIMATE (K)
BUDGET (K) BUDGET (K)
21 Personal Emoluments (0) 18,994,251 21,241,814
22 Goods and Services (0) 19,384,810 33,289,514
26 Grants and Other Payments(Transfers) (0) 16,311,132 66,668,023
31 Non-Financial Assets (0) 43,707,812 50,269,505
32 Financial Assets (0...

--- PAGE 8 ---
Page 8 OUTPUT BASED ANNUAL BUDGET
HEAD9209 MUMBWA TOWN COUNCIL
Table:2 Budget Allocation by Programme
2023 2024 2025
Programme
Code Approved Approved Budget
Budget(K) Budget(K) Estimates(K)
1 Constituency Development (0) 61,271,284 72,116,301
2 Local Governance (0) 4,747,244 3,329,422
3 Integrated Development Planning (0) 2,966,989 1,894,846
4 Economic and business development (0) 697,049 793,435
...

--- PAGE 9 ---
OUTPUT BASED ANNUAL BUDGET Page 9
HEAD9209 MUMBWA TOWN COUNCIL
Table 3: Budget Allocation by Programme and Sub-Programme
PROGRAMME/SUB-PROGRAMME 2023 BUDGET 2024 BUDGET 2025 BUDGET
Approved Expendit Approved Expendit Estimate
ure ure*
(0) (0)
1 Constituency Development (0) 61,271,284 72,116,301
779 Community Projects (0) (0) 34,924,632 (0) 43,925,383
780 Women and Youth Empowerment (0) (0) 11,641,...

In [ ]:
import pandas as pd
import re
import pdfplumber

budget_2025_df = pd.DataFrame()
prog_rows_2025 = []

budget_2025_file.seek(0)

with pdfplumber.open(budget_2025_file) as pdf:
    # --- 1. Parse Revenue Tables (Pages 3 to 6) ---
    current_major_head = ""

    for page_idx in range(2, 6):  # Pages 3 to 6
        text = pdf.pages[page_idx].extract_text() or ""
        lines = text.split("\n")

        for line in lines:
            line = re.sub(r"\(cid:\d+\)", "", line).strip()

            # Detect major category headers (e.g., "01 Local taxes/rates", "02 Fees and Charges")
            cat_match = re.match(r"^(\d{2})\s+([A-Za-z\s/]+)$", line)
            if cat_match:
                current_major_head = cat_match.group(2).strip()
                continue

            # Match revenue sub-items starting with 3-digit code
            rev_match = re.match(r"^(\d{3})\s+(.*?)\s+([\d,]+|-)\s+([\d,]+|-)\s+([\d,]+|-)$", line)
            if rev_match:
                code = rev_match.group(1)
                desc = rev_match.group(2).strip()
                amt_2025 = rev_match.group(3).replace(",", "").replace("-", "0")

                prog_rows_2025.append({
                    "year": 2025,
                    "financial_type": "Revenue Budget",
                    "category/code": f"{code} ({current_major_head})",
                    "description": desc,
                    "amount": float(amt_2025),
                    "source": f"2025 Approved Budget PDF (Page {page_idx + 1})"
                })

    # --- 2. Parse Economic Classification (Page 7) ---
    pg7_text = pdf.pages[6].extract_text() or ""
    for line in pg7_text.split("\n"):
        econ_match = re.match(r"^(\d{2})\s+(.*?)\s+[\d,\s\-\(\)]+\s+([\d,]+|-)$", line.strip())
        if econ_match and "ECONOMIC CLASSIFICATION" not in line:
            code = econ_match.group(1)
            desc = econ_match.group(2).strip()
            amt_2025 = econ_match.group(3).replace(",", "").replace("-", "0")

            prog_rows_2025.append({
                "year": 2025,
                "financial_type": "Expenditure Budget (Economic Classification)",
                "category/code": code,
                "description": desc,
                "amount": float(amt_2025),
                "source": "2025 Approved Budget PDF (Page 7)"
            })

    # --- 3. Parse Table 2: Programme Allocations (Page 8) ---
    pg8_text = pdf.pages[7].extract_text() or ""
    for line in pg8_text.split("\n"):
        prog_match = re.match(r"^(\d{1,2})\s+(.*?)\s+[\d,\s\-\(\)]+\s+([\d,]+|-)$", line.strip())
        if prog_match and "Programme" not in line and "Head Total" not in line:
            p_code = prog_match.group(1)
            p_name = prog_match.group(2).strip()
            amt_2025 = prog_match.group(3).replace(",", "").replace("-", "0")

            prog_rows_2025.append({
                "year": 2025,
                "financial_type": "Programme Budget",
                "category/code": f"Prog {p_code}",
                "description": p_name,
                "amount": float(amt_2025),
                "source": "2025 Approved Budget PDF (Page 8)"
            })

    # --- 4. Parse Table 3: Sub-Programme Allocations (Pages 9-11) ---
    sub_text = ""
    for p in range(8, min(11, len(pdf.pages))):
        sub_text += (pdf.pages[p].extract_text() or "") + "\n"

    for line in sub_text.split("\n"):
        line = re.sub(r"\(cid:\d+\)", "", line).strip()
        sp_match = re.match(r"^(\d{3})\s+(.*?)\s+[\d,\s\-\(\)]+\s+([\d,]+|\(0\)|-)$", line)
        if sp_match:
            sp_code = sp_match.group(1)
            rest = sp_match.group(2).strip()

            numbers = re.findall(r"[\d,]+|\(0\)", line)
            if numbers:
                amt_2025_raw = numbers[-1].replace(",", "").replace("(0)", "0")
                sp_name = re.sub(r"\s+[\d,]+.*$", "", rest).strip()

                prog_rows_2025.append({
                    "year": 2025,
                    "financial_type": "Sub-Programme Budget",
                    "category/code": f"SubProg {sp_code}",
                    "description": sp_name,
                    "amount": float(amt_2025_raw),
                    "source": "2025 Approved Budget PDF (Pages 9-11)"
                })

# Save to budget_2025_df
budget_2025_df = pd.DataFrame(prog_rows_2025)

print(f"Successfully extracted {len(budget_2025_df)} 2025 budget entries.")
display(budget_2025_df.head(15))
display(budget_2025_df.tail(15))

Successfully extracted 171 2025 budget entries.

,year,financial_type,category/code,description,amount,source
0,2025,Revenue Budget,001 (Local taxes/rates),Residential,863624.0,2025 Approved Budget PDF (Page 3)
1,2025,Revenue Budget,002 (Local taxes/rates),Commercial,694382.0,2025 Approved Budget PDF (Page 3)
2,2025,Revenue Budget,003 (Local taxes/rates),Industrial,682464.0,2025 Approved Budget PDF (Page 3)
3,2025,Revenue Budget,004 (Local taxes/rates),Hospitality,956218.0,2025 Approved Budget PDF (Page 3)
4,2025,Revenue Budget,005 (Local taxes/rates),Mining/Plant,604958.0,2025 Approved Budget PDF (Page 3)
5,2025,Revenue Budget,006 (Local taxes/rates),Power transmission,416572.0,2025 Approved Budget PDF (Page 3)
6,2025,Revenue Budget,007 (Local taxes/rates),Plant and Machinery,559125.0,2025 Approved Budget PDF (Page 3)
7,2025,Revenue Budget,001 (Local taxes/rates),Personal levy,55500.0,2025 Approved Budget PDF (Page 3)
8,2025,Revenue Budget,001 (Fees and Charges),Consent fees,454900.0,2025 Approved Budget PDF (Page 4)
9,2025,Revenue Budget,002 (Fees and Charges),Survey fees,672000.0,2025 Approved Budget PDF (Page 4)
10,2025,Revenue Budget,003 (Fees and Charges),Building inspection-fees,40000.0,2025 Approved Budget PDF (Page 4)
11,2025,Revenue Budget,004 (Fees and Charges),Plan scrutiny fee,478200.0,2025 Approved Budget PDF (Page 4)
12,2025,Revenue Budget,007 (Fees and Charges),Rentals/lease of Council’s properties,417000.0,2025 Approved Budget PDF (Page 4)
13,2025,Revenue Budget,008 (Fees and Charges),Non-Land Application forms fees,272685.0,2025 Approved Budget PDF (Page 4)
14,2025,Revenue Budget,010 (Fees and Charges),Sketch plan,31000.0,2025 Approved Budget PDF (Page 4)

,year,financial_type,category/code,description,amount,source
156,2025,Sub-Programme Budget,SubProg 067,Revenue Mobilisation and Enhancement,1412318.0,2025 Approved Budget PDF (Pages 9-11)
157,2025,Sub-Programme Budget,SubProg 001,Primary Health Services,5432712.0,2025 Approved Budget PDF (Pages 9-11)
158,2025,Sub-Programme Budget,SubProg 002,District Health Coordination,676624.0,2025 Approved Budget PDF (Pages 9-11)
159,2025,Sub-Programme Budget,SubProg 001,Road Transport,3200587.0,2025 Approved Budget PDF (Pages 9-11)
160,2025,Sub-Programme Budget,SubProg 003,Water Transport,481111.0,2025 Approved Budget PDF (Pages 9-11)
161,2025,Sub-Programme Budget,SubProg 071,"Agricultural Crop production, Advisory and Technical",319854.0,2025 Approved Budget PDF (Pages 9-11)
162,2025,Sub-Programme Budget,SubProg 072,Agribusiness Development and Marketing,52400.0,2025 Approved Budget PDF (Pages 9-11)
163,2025,Sub-Programme Budget,SubProg 073,Agriculture Co-ordination,145527.0,2025 Approved Budget PDF (Pages 9-11)
164,2025,Sub-Programme Budget,SubProg 074,Fisheries and Livestock Marketing,105310.0,2025 Approved Budget PDF (Pages 9-11)
165,2025,Sub-Programme Budget,SubProg 075,Animal Health Services,129000.0,2025 Approved Budget PDF (Pages 9-11)
166,2025,Sub-Programme Budget,SubProg 076,Fisheries Production and Productivity Improvement,67182.0,2025 Approved Budget PDF (Pages 9-11)
167,2025,Sub-Programme Budget,SubProg 077,Livestock Production and Productivity Improvement,68128.0,2025 Approved Budget PDF (Pages 9-11)
168,2025,Sub-Programme Budget,SubProg 078,District Fisheries and Livestock Coordination,116540.0,2025 Approved Budget PDF (Pages 9-11)
169,2025,Sub-Programme Budget,SubProg 079,District Social welfare,52155528.0,2025 Approved Budget PDF (Pages 9-11)
170,2025,Sub-Programme Budget,SubProg 080,Community Development,5172.0,2025 Approved Budget PDF (Pages 9-11)

In [ ]:
prog_econ_rows_2025 = []

budget_2025_file.seek(0)

prog_header_pattern = re.compile(r"^Programme\s+(\d{1,2})\s*:\s*(.*)$")
econ_line_pattern = re.compile(r"^(\d{2})\s*([A-Za-z\s\(\)/-]+?)\s+[\d,\s\-\(\)]+$")

current_prog_num = None
current_prog_title = None

with pdfplumber.open(budget_2025_file) as pdf:
    for page_idx in range(11, len(pdf.pages)):
        text = pdf.pages[page_idx].extract_text() or ""
        lines = text.split("\n")

        for line in lines:
            line = line.strip()

            prog_match = prog_header_pattern.match(line)
            if prog_match:
                current_prog_num = prog_match.group(1)
                current_prog_title = prog_match.group(2).strip()
                continue

            econ_match = econ_line_pattern.match(line)
            if econ_match and current_prog_title:
                code_prefix = econ_match.group(1)
                desc = econ_match.group(2).strip()

                if desc.lower() in ["programme total", "economic classification", "approved", "estimates"]:
                    continue

                numbers = re.findall(r"[\d,]+|\(0\)", line)
                if numbers:
                    amt_str = numbers[-1].replace(",", "").replace("(0)", "0")
                    try:
                        amt = float(amt_str)
                        prog_econ_rows_2025.append({
                            "year": 2025,
                            "financial_type": f"Programme {current_prog_num} Expenditure",
                            "category/code": f"Prog {current_prog_num} ({code_prefix})",
                            "description": f"{current_prog_title} - {desc}",
                            "amount": amt,
                            "source": f"2025 Approved Budget PDF (Page {page_idx + 1})"
                        })
                    except ValueError:
                        continue

# Append to 2025 DataFrame and drop non-monetary items
df_prog_econ_2025 = pd.DataFrame(prog_econ_rows_2025)
budget_2025_df = pd.concat([budget_2025_df, df_prog_econ_2025], ignore_index=True)

# Clean out output indicator count rows
cleaning_keywords = r"number of|kilometers of|proportion of|percentage of|ratio of|count of"
cleaned_budget_2025_df = budget_2025_df[
    ~budget_2025_df['description'].str.contains(cleaning_keywords, case=False, na=False)
].copy().reset_index(drop=True)

# Export to CSV
output_2025_filename = "db-unza26-csc4792-mumbwa_2025_approved_budget.csv"
cleaned_budget_2025_df.to_csv(output_2025_filename, sep="|", index=False)

print(f"Total clean 2025 budget records: {len(cleaned_budget_2025_df)}")
print(f"Saved to '{output_2025_filename}'.")

Total clean 2025 budget records: 320
Saved to 'db-unza26-csc4792-mumbwa_2025_approved_budget.csv'.

In [ ]:
import io
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# 1. Locate the 2024 Financial Statements / Audit Report link
stmt_2024_row = financial_publications_df[
    financial_publications_df['text'].str.contains('2024', case=False, na=False) &
    (financial_publications_df['text'].str.contains('financial', case=False, na=False) |
     financial_publications_df['text'].str.contains('statement', case=False, na=False) |
     financial_publications_df['text'].str.contains('audit', case=False, na=False) |
     financial_publications_df['text'].str.contains('account', case=False, na=False))
]

print("Found 2024 Financial Statement document link(s):")
print(stmt_2024_row[['text', 'url']])

# 2. Download the first matching document
stmt_2024_url = stmt_2024_row['url'].values[0]
stmt_2024_response = requests.get(stmt_2024_url, verify=False)

print(f"\nDownload Status: {stmt_2024_response.status_code}")
print(f"File size: {len(stmt_2024_response.content)} bytes")

# Store in BytesIO buffer
stmt_2024_file = io.BytesIO(stmt_2024_response.content)

Found 2024 Financial Statement document link(s):
                                                          text  \
78  2024  Financial Statements – Uploaded on: December 2, 2025
86     2021 Financial Statement – Uploaded on: August 27, 2024
87     2020 Financial Statement – Uploaded on: August 27, 2024
88     2019 Financial Statement – Uploaded on: August 27, 2024
89     2018 Financial Statement – Uploaded on: August 27, 2024

                                                                                                                           url
78  https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/FINANCIAL-STATEMENTS-FOR-THE-YEAR-ENDED-31ST-DECEMBER-2024.pdf
86     https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2021.pdf
87     https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2020.pdf
88     https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2019.pdf
89   https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2018-2.pdf

Download Status: 200
File size: 23994258 bytes

In [ ]:
import pdfplumber

stmt_2024_file.seek(0)

with pdfplumber.open(stmt_2024_file) as pdf:
    print(f"Total pages in 2024 Financial Statements: {len(pdf.pages)}")

    # Scan the first 15 pages for statement titles
    for p_idx in range(min(15, len(pdf.pages))):
        text = pdf.pages[p_idx].extract_text() or ""
        lines = [line.strip() for line in text.split("\n") if line.strip()]

        # Check for key financial statement headings
        header_preview = " | ".join(lines[:3]) if lines else "EMPTY PAGE"
        print(f"Page {p_idx + 1}: {header_preview[:120]}")

Total pages in 2024 Financial Statements: 49
Page 1: MUMBWA TOWN COUNCIL | FINANCIAL STATEN{FNTS FOR THE YEAR ENDED | 31't DECEMBER-}O2A
Page 2: MUMRWA'IOWN COUNCII, | FINANCIAI, S'I'ATI'MENTS I'OR TIIN YIiAR ENDED 3IS1'DECIiMBEIT 2024 | TABLE OF CONTENTS
Page 3: MUMBWA TOWN COUNCIL | FINANCIAL STATf,MENTS TOR THE YEAR ENDED 3IST DECTMBf,II 2024 | REPORT OF THE COUNCIL
Page 4: IVIUMBWA TOWN COUNCIL | F'INANCIAL STATEMENTS FOR THE YEAR E,NDED 31ST DECEMBER 2024 | the l{ook Granitic Complex. Exten
Page 5: MUMBWATOWN COUNCIL | FINANCIAL STA'IEMENTS II'OR TIIE YEAR ENDED 3lsr DITCtiMBER 2024 | Vegetation and Soils
Page 6: MUMBWA TOWN COUNCIL | F'INANCIAL STATEMENTS FOR THE YEAR ENDf,D 31ST DECtr]MtsER 2024 | %a
Page 7: MUMBWA TOWN COUNCII, | I'INANCIAL STATEMENTS POR TI{E YEAR ENDDD 31ST Df,CEMBER 2024 | Composition of the Council
Page 8: MUMBWA TOWN COUNCIL | FINANCIAL STATEMENTS IOR THE YEAR ENDED 3IST DECI',MBER 2024 | The affairs of Central Government i
Page 9: MUMB\YATOWN COUNCIL | FINANCIAL STATEMENTS FOR THE YEAR ENDED 31ST DECT,MBER 2024 | Health and Safefy of Employees
Page 10: MUMBWA TOWN COUNCIL | FINANCIAL STATEMENTS FOR THE YEAR f,NDU,D SIST DECE\{BIR 2024 | STATEMENT OF RESPONSIBILITIES FOR
Page 11: REPUBI,IC OF ZAMBIA | OFFICE OF THE AUDITOR GENERAL | INDEPENDENT AUDITOR' S OPINION
Page 12: ffi | RlrPUBt,lc OIr ZAMBIA | OFFICE OF TIIE AUDITOIT GENERAL
Page 13: t- | l-a | REPUBLIC OF ZAMRIA
Page 14: REPUBI,IC OIl ZAMBIA | OFFICE OF THE AUDITOR GENERAL | I also provide those charged with governance with a statement tha
Page 15: MUMBWA TOWN COUNCII, | FINANCIAL STATEMENTS FOR THE YEAR ENDED 3IST DECEMBER 2024 | STATEMENT OF CASH RECEIPTS AND PAYME

In [ ]:
stmt_2024_file.seek(0)

with pdfplumber.open(stmt_2024_file) as pdf:
    for page_num in range(15, 21):
        text = pdf.pages[page_num - 1].extract_text()
        print("\n" + "=" * 80)
        print(f"PAGE {page_num}")
        print("=" * 80)
        print(text if text else "NO TEXT FOUND")

================================================================================
PAGE 15
================================================================================
MUMBWA TOWN COUNCII,
FINANCIAL STATEMENTS FOR THE YEAR ENDED 3IST DECEMBER 2024
STATEMENT OF CASH RECEIPTS AND PAYMENTS FOR THE YEAR ENDED 31ST
DECEMBER2024
Notes 2024 2023
I(wacha I(wacha
RECEIPTS
Local Taxes 2 2,O92,554 t,524,260
Fees and Charges -f 6,541,942 "7 ))2 ',lL)
,,--.' l l2
Licences 4 674,646 2,419,644
Levies 5 3,771,696 787,946
Permits 6 1,gg l,g5g 1,299,446
Local Govt Equalisation Fund 7 17,373,799 t4,753,t74
Constituency Development Fund 8 45,990,506 54,5)2,940
Other Grants 9 5,444,737 2,899.7 t7
Borrowings
10
Comrnercial venture t1 8,514 - 19,255
Sector Grants t2 3O,139,559
Other Receipts 13 t,oo5,o74 r.t39.947
TOTAL RECEIPTS 115.014.793 86,543,562
Personal Ernoluments 74 16,373,373 13,929,932
Use of goods & services 15 20,119,360 17,600,745
Financial Charges t6
Social Benefits 17 19,122,321 9,893,O49
Non-Financial asscts acquisition 18 46,976,696 35,197,359
Financial Assets 19 6,949,955 12,424,367
Loan Repayments 20
Other Payr-r-rents 2t 2.509,a94 _ 1,333,671
'f()TAL
PAYNTENTS _ 111.048,689 90,368,957
Increase/(Decrease) in Cash 3,966,O94 - 3,925,395
Iroreign Exchange of the year 22
Cash at Beginning of the year zl.zzz,lz+ +t,o+s.1ts
Cash at the end of the year 23 41.188,818 37,222,724
Incorporated in the payments recognised in this Statement are those for Local Govemment Equalisation
,Constituency Development Funds, Zambia Devolution Support Programme, and Sector Grant.
However, the details of payments under each of these Funds are presented separately in each lrund's
Name.
@l
;;::.",
Position: Council Chairperson
g
N,*.,...... P *r;7...,.. {..9:*.P.
Signatu
0'F'2[MBtA""""
Position
L GOVERNMENT
(.)
*/s
1 2 MV 20?5
L." -***_* -J
DIRECTO,&OF FINANCE
MUMBWA,TCIWTI COUNCIL
P.O. BOX 83OAO1,MUMBWA

================================================================================
PAGE 16
================================================================================
MUMBWA TOWN COUNCIL
FINANCIAL STATEMENTS FOR THE, YEAR ENDED 3IST DECEMBER 2024
STATEI\{ENT OF COMPARISON OF BUDGET AND ACTUAL AMOUNTS FOR THE
YEAR ENDED 31ST DECEMBER 2024
Pcr{ornr
Orig K ina w l B a u ch d a g et Adjustments l'in K al w B a u c d h g r c t Actual Amounts ance Variance '/oYariance
Kwacha Kwacha Kwacha
RECEIPTS
Local Taxes 2,696,394 2,696,394 2,092,s54 78 603,840 22
Fces and Charges 10,417,979 3,191,280 6,626,699 6,541,842 99 84,857 I
Licences 6s7,345 14,500 642,84s 674,646 105 (31,801) -5
Levies 5,056,956 2,s46,186 2,s10,770 3,77t,696 150 (t.260,926) -50
Permits 3,239,130 1,047,s00 2,191,630 1,981,858 90 209,772 l0
Local Govt equalisadon Fund 17,054,618 17,054,618 17.3'73,798 102 (31e,180) -2
C O o th n e s r t it G u r e a n n c ts y Devel oprnent Fund 6 7 1,2 , 7 8 1, 1 28 2 4 ,847 1,02s,2s8 6 6 1 , , 7 2 8 7 7 1 , , 5 2 8 8 9 4 4 5 5 , , 4 2 4 2 4 1 , , 7 3 3 1 7 1 7 8 0 4 1 1 6 , , 3 0 4 4 2 9 , , 8 9 5 73 2 2 2 6 0
Borrowings
r0e.54e roo.i+s
Scc C to o r m G n ra e n r t c s i a ( l D V e en v t o u J re ved fiuds) 6,746,020 - 6,7 4 e 6 , , 0 0 0 2 0 0 30,0 8, 7 5 0 1 , 4 30 9 4 95 46 123,32 4 4, 8 28 6 9 ) -3 .5 46
Other Receipts 70.000 - 70,000 t.813,519, 26t9 (1,763.519) _2519
TOTAL RECT],IPTS 115,132,122 8,525,273 106,606,849 115,014,781 108 (3,407,935) _8
PAYMENTS
Personal Emoluments 19,978,01 I 324,582 19,653,429 16,373,3'13 83 3,280,056 17
Usc ofGoods and Services 22,490,834 3,866,682 18,624,ts',) 20,1 18,360 108 (1,4e4,708) -8
Irinancial Chargcs
Social benefits 16,309,662 16,309,662 18,122,32t lll (1,812,659) -l
1
Non-fi nancial Assets Acquisition 46,'t25,308 3,869,009 42,856,299 46,976,686 I l0 (4.t20,387) -10
Financial Assets 6,984,926 6,984,926 6,949,85s 99 35,071 I
Loan Repayments
Other Paynenfs
lls,r32,l22 8,s2s
TOTAI, PA}l\{ENTS ro+______l!J!:!,!!1l___4
Incrcasc/(Dccrease in Cash) 3,966.094 (3.966.094)
The composition of budget adjustments and explanations of major variances are provided in note 23
15

================================================================================
PAGE 17
================================================================================
MUMBWA TOWN COUNCIL
TINANCIAL STATEMENTS FOR THE YEAR ENDED 31ST DECEMBER 2024
STATEMENT OF CASH RECEIPTS AND PAYMENTS FOR THE LOCAL GOVERNMENT
EQUALISATION FUND (LGEF) FOR YEAR ENDED 31ST DECEMBER 2024
2024 2023
I(wacha Kwacha
RIICEIPTS
Funding 7(a) 17,373,798 14,753,174
TOTAL RECEIPTS 17 1373,798 14,,753,174
PAYMENTS
Ope rational Expe nditure Payme nt 7(b)
Salaries and Wages 16,015,8_29 11,642,600
Terminal Benefits
Utiliry Bills
Service Provision 563,468
Goods and Services 467,595
Administrative Costs 80,288
Other Costs -
Sub-Total 17 1127 1180 ___rrsasN
Capital Expenditure Payments 7(c)
Infrastructure Development 247,6--15 2,347,602
Rehabilitation Works 80,101
Asset Acquisition 412,405
Other Costs 681,530
Sub-Total 247,615 315211638
TOTAL PAYMENTS 17 ,37 4,795 15,164,238
-
Incre as e/(de cre as e) in Cas h (ee7) (411,064)
Cash at beginning of the year 997 412,061
Cash at the end ofthe year 997
-
16

================================================================================
PAGE 18
================================================================================
MUMBWA TOWN COUNCII,
IINANCIAL STATEMENTS FOR THE YEAR I,NDED 31S DECEMBIIR 2024
STATEMENT OF CASH RECEIPT'S AND PAYMENTS I'ORTHE CONSTITUENCY
DEVELOPMENT FUND (CDF) FOR YEAR ENDED 31sr DECEMBER 2024
2024 2023
Kwacha Kwacha
RECEIPTS
Funding B(a) 45,221,311 54,522,940
Loan Recoveries 8(b) 4g3,ggg 258,469
Other Receipts - Interest 8(c) 26s298 805,318
TOTAL RECEIPTS 45,980,506 55,586,727
PAYMENTS
Infrastructure Development 8(d) 23299,108 19,279J92
Rehabilitation Works 8(e) 11,555,283 4,737,847
Asset Acquisition 8(f) 8,115,473 9,663,755
Bursaries -Secondary & Skills 8(g) 10280,360 5,347,173
Empowerment Grants 8(h) 4,826,650 4,545,976
Empowerment Loans 8(D 6,949,855 12,424,361
Administrative Costs 8(i) 2,g4g,g96 4,217,752
Disaster Contingency 8(k) 211,194 247,120
TOTAL PAYMENTS _9q,18?,819_ 60,463,676
Increase(decrease) in Cash (222W,313) (4,876,949)
Cash at beginning of the year 35,084,571 39,961,520
Cash at the end ofthe year _n,877258_ 35,084,571
Note 8 expiains the composition and other details relating to the various elements included in this
Statement.
17

================================================================================
PAGE 19
================================================================================
MUMBWA TOWN COUNCIL
FINANCIAL STA1EMENTS FOR THE YEAR ENDED 31ST DECII,MBER 2024
STATEMENT OF CASH RECEIPTS AND PAYMENTS FOR THE ZAMBIA DEVOLUTION
SUPPORT PROGRAMME CAPITAL FOR THE YEAR ENDED 31ST DECEMBER 2024
2024 2023
Kwacha Kwacha
RECEIPTS
Funding e(b) ry2,694,7-37
Other Receipts e(c)
TOTAL RECEIPTS
PAYMENTS
Goods and Services e(d)
Non-Financial Assets Acquisition e(e)
Infrastructure Development e(0
Rehabilitation Works e(e)
TOTAL PAYMENTS
Increase/(Cecrease) in Cash 2,694,737_
X'oreing Exchanges losses
Cash at the beginning of the year
Cash at the end ofthe year 2,694,737
The Cash at the end of the Year of K2,476,479 is in the Capital account held with Access bank.
1B

================================================================================
PAGE 20
================================================================================
MUMBWATOWN COUNCII,
FINANCIAL STATEMENTS FOR THE YEAR ENDED 31ST DECEMBER 2024
STATEMENT OF CASH RECEIPTS AND PAYMENTS FOR THE SECTOR GRANT (DEVOLVED
FUNCTTONS) FOR THE YEAR ENDED 31sr DECEMBER 2024
2024 2023
Kwacha Kwacha
RECEIPTS
Funding 12(a) 30,070,309
Other Receipts 12(b) 69.249
TOTAL RECEIPTS 30,139,558
PAYMENTS
Goods and Services' 12(c) s,oea,ln
Non-Financial Assets Acquisition 12(d) 1,081,183
Infrastructure Development 12(e)
Rehabilitation Works 12(f)
__sl47w_
TOTAL PAYMEI.MS
Increase/(Cecrease) in Cash 23,991,642-
Foreign Exchanges losses
Cash at the beginning of the year
Cash at the end ofthe year __a,22Ua_
The cash at the end of the year is as shown below;
Account Name Bank Account No Amount -K
Mumbwa CFW Access 21288t8967801 3.273.084
Nangoma CFW Access 2128818815801 2,4t3.118
Archives Access 396158 92023 23,619
Sector Grant Access 396158 23018 t7.st9.t72
Tourism Access 396158 92012 5,964
Transport Access 396166 9601 703,212
Hospital Services Access 39616629601 18,666
Veterinary Access 396158149013 14,501
Total 23,971,334
l*
l](ot.o
Name: ..........:........
g
Signature:
Signature:
Position: Council Chairperson Position: Council Secretary
Name:...
H
Signature.. t*'
,r'o*
Posi
1 2 Nov ?0?5
19
;[,ut$d$-r'ffi

In [ ]:
import pandas as pd
import re
import pdfplumber

stmt_2024_rows = []

stmt_2024_file.seek(0)

with pdfplumber.open(stmt_2024_file) as pdf:
    # --- 1. Parse Page 15: Main Statement of Cash Receipts and Payments ---
    pg15_text = pdf.pages[14].extract_text() or ""
    current_section = "Receipt"

    for line in pg15_text.split("\n"):
        line = line.strip()
        if "PAYMENTS" in line:
            current_section = "Payment"
            continue

        # Matches line item with Note number and 2024 Actual Amount
        match = re.match(r"^([A-Za-z\s&/-]+?)\s+(\d{1,2})\s+([\d,\.\_]+)$", line)
        if match:
            desc = match.group(1).strip()
            note_num = match.group(2)
            amt_str = match.group(3).replace(",", "").replace(".", "").replace("_", "")

            if desc.upper() not in ["TOTAL RECEIPTS", "TOTAL PAYMENTS"]:
                try:
                    stmt_2024_rows.append({
                        "year": 2024,
                        "financial_type": f"Actual {current_section} (Main Statement)",
                        "category/code": f"Note {note_num}",
                        "description": desc,
                        "amount": float(amt_str),
                        "source": "2024 Financial Statements PDF (Page 15)"
                    })
                except ValueError:
                    continue

    # --- 2. Parse Page 17: LGEF Cash Receipts & Payments ---
    pg17_text = pdf.pages[16].extract_text() or ""
    for line in pg17_text.split("\n"):
        match = re.match(r"^([A-Za-z\s]+?)\s+7\([a-z]\)\s+([\d,]+)$", line.strip())
        if match:
            desc = match.group(1).strip()
            amt = float(match.group(2).replace(",", ""))
            stmt_2024_rows.append({
                "year": 2024,
                "financial_type": "Actual LGEF Performance",
                "category/code": "LGEF Item",
                "description": f"LGEF - {desc}",
                "amount": amt,
                "source": "2024 Financial Statements PDF (Page 17)"
            })

    # --- 3. Parse Page 18: CDF Cash Receipts & Payments ---
    pg18_text = pdf.pages[17].extract_text() or ""
    for line in pg18_text.split("\n"):
        match = re.match(r"^([A-Za-z\s&/-]+?)\s+8\([a-z]\)\s+([\d,]+)$", line.strip())
        if match:
            desc = match.group(1).strip()
            amt = float(match.group(2).replace(",", ""))
            stmt_2024_rows.append({
                "year": 2024,
                "financial_type": "Actual CDF Performance",
                "category/code": "CDF Item",
                "description": f"CDF - {desc}",
                "amount": amt,
                "source": "2024 Financial Statements PDF (Page 18)"
            })

# Save to DataFrame and export
df_stmt_2024 = pd.DataFrame(stmt_2024_rows)

output_2024_filename = "db-unza26-csc4792-mumbwa_2024_actual_financial_statements.csv"
df_stmt_2024.to_csv(output_2024_filename, sep="|", index=False)

print(f"Successfully extracted {len(df_stmt_2024)} actual 2024 financial records.")
print(f"Saved to '{output_2024_filename}'.")
display(df_stmt_2024)

Successfully extracted 0 actual 2024 financial records.
Saved to 'db-unza26-csc4792-mumbwa_2024_actual_financial_statements.csv'.

Empty DataFrame
Columns: []
Index: []

In [ ]:
import pandas as pd
import re
import pdfplumber

stmt_2024_rows = []

stmt_2024_file.seek(0)

def clean_ocr_num(val_str):
    if not val_str:
        return 0.0
    # Clean OCR character replacements in numeric columns
    cleaned = (
        val_str.replace("O", "0")
        .replace("o", "0")
        .replace("I", "1")
        .replace("l", "1")
        .replace("S", "5")
        .replace("s", "5")
        .replace("Z", "2")
        .replace("z", "2")
        .replace("g", "9")
        .replace("J", "1")
        .replace("a", "0")
        .replace("t", "1")
    )
    cleaned = re.sub(r"[^\d.]", "", cleaned)
    try:
        return float(cleaned) if cleaned else 0.0
    except ValueError:
        return 0.0

with pdfplumber.open(stmt_2024_file) as pdf:
    # --- 1. Page 15: Main Statement of Cash Receipts and Payments ---
    pg15_text = pdf.pages[14].extract_text() or ""
    current_section = "Receipt"

    for line in pg15_text.split("\n"):
        line = line.strip()
        if "PAYMENTS" in line:
            current_section = "Payment"
            continue

        tokens = line.split()
        num_tokens = [t for t in tokens if re.search(r"\d", t)]
        desc_match = re.match(r"^([A-Za-z\s&/-]+)", line)

        if desc_match and num_tokens:
            desc = desc_match.group(1).strip()
            if desc.upper() not in ["TOTAL RECEIPTS", "TOTAL PAYMENTS", "RECEIPTS", "PAYMENTS", "STATEMENT OF CASH RECEIPTS AND PAYMENTS FOR THE YEAR ENDED 3IST"]:
                amt_2024 = clean_ocr_num(num_tokens[0] if len(num_tokens) == 1 else num_tokens[-2])
                if amt_2024 > 0:
                    stmt_2024_rows.append({
                        "year": 2024,
                        "financial_type": f"Actual {current_section} (Main Statement)",
                        "category/code": "Main Statement",
                        "description": desc,
                        "amount": amt_2024,
                        "source": "2024 Financial Statements PDF (Page 15)"
                    })

    # --- 2. Page 17: LGEF Statement ---
    pg17_text = pdf.pages[16].extract_text() or ""
    for line in pg17_text.split("\n"):
        line = line.strip()
        if any(kw in line.lower() for kw in ["salaries", "service", "goods", "administrative", "infrastructure", "rehabilitation", "asset"]):
            parts = line.split()
            desc = " ".join([p for p in parts if not re.search(r"\d", p)])
            nums = [p for p in parts if re.search(r"\d", p)]
            if nums and desc:
                amt = clean_ocr_num(nums[0])
                if amt > 0:
                    stmt_2024_rows.append({
                        "year": 2024,
                        "financial_type": "Actual LGEF Performance",
                        "category/code": "LGEF",
                        "description": f"LGEF - {desc.strip()}",
                        "amount": amt,
                        "source": "2024 Financial Statements PDF (Page 17)"
                    })

    # --- 3. Page 18: CDF Statement ---
    pg18_text = pdf.pages[17].extract_text() or ""
    for line in pg18_text.split("\n"):
        line = line.strip()
        if any(kw in line.lower() for kw in ["infrastructure", "rehabilitation", "asset", "bursaries", "empowerment", "administrative", "disaster"]):
            parts = line.split()
            desc = " ".join([p for p in parts if not re.search(r"^\d+\([a-z]\)$", p) and not re.search(r"^\d+$", p)])
            nums = [p for p in parts if re.search(r"\d{3,}", p)]
            if nums and desc:
                amt = clean_ocr_num(nums[0])
                if amt > 0:
                    stmt_2024_rows.append({
                        "year": 2024,
                        "financial_type": "Actual CDF Performance",
                        "category/code": "CDF",
                        "description": f"CDF - {desc.strip()}",
                        "amount": amt,
                        "source": "2024 Financial Statements PDF (Page 18)"
                    })

    # --- 4. Page 20: Sector Grants ---
    pg20_text = pdf.pages[19].extract_text() or ""
    for line in pg20_text.split("\n"):
        line = line.strip()
        if any(kw in line.lower() for kw in ["goods", "non-financial", "infrastructure", "rehabilitation"]):
            parts = line.split()
            desc = " ".join([p for p in parts if not re.search(r"\d", p)])
            nums = [p for p in parts if re.search(r"\d", p)]
            if nums and desc:
                amt = clean_ocr_num(nums[0])
                if amt > 0:
                    stmt_2024_rows.append({
                        "year": 2024,
                        "financial_type": "Actual Sector Grant Performance",
                        "category/code": "Sector Grant",
                        "description": f"Sector Grant - {desc.strip()}",
                        "amount": amt,
                        "source": "2024 Financial Statements PDF (Page 20)"
                    })

# Export DataFrame to CSV
df_stmt_2024 = pd.DataFrame(stmt_2024_rows)
output_2024_filename = "db-unza26-csc4792-mumbwa_2024_actual_financial_statements.csv"
df_stmt_2024.to_csv(output_2024_filename, sep="|", index=False)

print(f"Successfully extracted {len(df_stmt_2024)} actual 2024 financial records.")
print(f"Saved to '{output_2024_filename}'.")
display(df_stmt_2024)

Successfully extracted 47 actual 2024 financial records.
Saved to 'db-unza26-csc4792-mumbwa_2024_actual_financial_statements.csv'.

,year,financial_type,category/code,description,amount,source
0,2024,Actual Receipt (Main Statement),Main Statement,FINANCIAL STATEMENTS FOR THE YEAR ENDED,3.150000e+02,2024 Financial Statements PDF (Page 15)
1,2024,Actual Payment (Main Statement),Main Statement,DECEMBER,2.024000e+03,2024 Financial Statements PDF (Page 15)
2,2024,Actual Payment (Main Statement),Main Statement,Notes,2.024000e+03,2024 Financial Statements PDF (Page 15)
3,2024,Actual Payment (Main Statement),Main Statement,Local Taxes,2.092554e+06,2024 Financial Statements PDF (Page 15)
4,2024,Actual Payment (Main Statement),Main Statement,Fees and Charges -f,7.000000e+00,2024 Financial Statements PDF (Page 15)
5,2024,Actual Payment (Main Statement),Main Statement,Licences,6.746460e+05,2024 Financial Statements PDF (Page 15)
6,2024,Actual Payment (Main Statement),Main Statement,Levies,3.771696e+06,2024 Financial Statements PDF (Page 15)
7,2024,Actual Payment (Main Statement),Main Statement,Permits,1.959000e+03,2024 Financial Statements PDF (Page 15)
8,2024,Actual Payment (Main Statement),Main Statement,Local Govt Equalisation Fund,1.737380e+07,2024 Financial Statements PDF (Page 15)
9,2024,Actual Payment (Main Statement),Main Statement,Constituency Development Fund,4.599051e+07,2024 Financial Statements PDF (Page 15)
10,2024,Actual Payment (Main Statement),Main Statement,Other Grants,2.899700e+03,2024 Financial Statements PDF (Page 15)
11,2024,Actual Payment (Main Statement),Main Statement,Comrnercial venture t,8.514000e+03,2024 Financial Statements PDF (Page 15)
12,2024,Actual Payment (Main Statement),Main Statement,Sector Grants t,1.200000e+01,2024 Financial Statements PDF (Page 15)
13,2024,Actual Payment (Main Statement),Main Statement,Other Receipts,1.005074e+06,2024 Financial Statements PDF (Page 15)
14,2024,Actual Payment (Main Statement),Main Statement,Personal Ernoluments,1.637337e+07,2024 Financial Statements PDF (Page 15)
15,2024,Actual Payment (Main Statement),Main Statement,Use of goods & services,2.011936e+07,2024 Financial Statements PDF (Page 15)
16,2024,Actual Payment (Main Statement),Main Statement,Financial Charges t,1.600000e+01,2024 Financial Statements PDF (Page 15)
17,2024,Actual Payment (Main Statement),Main Statement,Social Benefits,1.912232e+07,2024 Financial Statements PDF (Page 15)
18,2024,Actual Payment (Main Statement),Main Statement,Non-Financial asscts acquisition,4.697670e+07,2024 Financial Statements PDF (Page 15)
19,2024,Actual Payment (Main Statement),Main Statement,Financial Assets,6.949955e+06,2024 Financial Statements PDF (Page 15)
20,2024,Actual Payment (Main Statement),Main Statement,Loan Repayments,2.000000e+01,2024 Financial Statements PDF (Page 15)
21,2024,Actual Payment (Main Statement),Main Statement,Other Payr-r-rents,2.509094e+00,2024 Financial Statements PDF (Page 15)
22,2024,Actual Payment (Main Statement),Main Statement,PAYNTENTS,1.110487e+02,2024 Financial Statements PDF (Page 15)
23,2024,Actual Payment (Main Statement),Main Statement,Increase/,3.966094e+06,2024 Financial Statements PDF (Page 15)
24,2024,Actual Payment (Main Statement),Main Statement,Iroreign Exchange of the year,2.200000e+01,2024 Financial Statements PDF (Page 15)
25,2024,Actual Payment (Main Statement),Main Statement,Cash at Beginning of the year zl,1.051150e+02,2024 Financial Statements PDF (Page 15)
26,2024,Actual Payment (Main Statement),Main Statement,Cash at the end of the year,4.118882e+01,2024 Financial Statements PDF (Page 15)
27,2024,Actual Payment (Main Statement),Main Statement,P,8.300100e+04,2024 Financial Statements PDF (Page 15)
28,2024,Actual LGEF Performance,LGEF,LGEF - Salaries and Wages,1.601583e+07,2024 Financial Statements PDF (Page 17)
29,2024,Actual LGEF Performance,LGEF,LGEF - Service Provision,5.634680e+05,2024 Financial Statements PDF (Page 17)
30,2024,Actual LGEF Performance,LGEF,LGEF - Goods and Services,4.675950e+05,2024 Financial Statements PDF (Page 17)
31,2024,Actual LGEF Performance,LGEF,LGEF - Administrative Costs,8.028800e+04,2024 Financial Statements PDF (Page 17)
32,2024,Actual LGEF Performance,LGEF,LGEF - Infrastructure Development,2.476150e+05,2024 Financial Statements PDF (Page 17)
33,2024,Actual LGEF Performance,LGEF,LGEF - Rehabilitation Works,8.010100e+04,2024 Financial Statements PDF (Page 17)
34,2024,Actual LGEF Performance,LGEF,LGEF - Asset Acquisition,4.124050e+05,2024 Financial Statements PDF (Page 17)
35,2024,Actual CDF Performance,CDF,"CDF - Infrastructure Development 23299,108 19,279J92",2.329911e+07,2024 Financial Statements PDF (Page 18)
36,2024,Actual CDF Performance,CDF,"CDF - Rehabilitation Works 11,555,283 4,737,847",1.155528e+07,2024 Financial Statements PDF (Page 18)
37,2024,Actual CDF Performance,CDF,"CDF - Asset Acquisition 8,115,473 9,663,755",8.115473e+06,2024 Financial Statements PDF (Page 18)
38,2024,Actual CDF Performance,CDF,"CDF - Bursaries -Secondary & Skills 10280,360 5,347,173",1.028036e+07,2024 Financial Statements PDF (Page 18)
39,2024,Actual CDF Performance,CDF,"CDF - Empowerment Grants 4,826,650 4,545,976",4.826650e+06,2024 Financial Statements PDF (Page 18)
40,2024,Actual CDF Performance,CDF,"CDF - Empowerment Loans 8(D 6,949,855 12,424,361",6.949855e+06,2024 Financial Statements PDF (Page 18)
41,2024,Actual CDF Performance,CDF,"CDF - Administrative Costs 2,g4g,g96 4,217,752",4.217752e+06,2024 Financial Statements PDF (Page 18)
42,2024,Actual CDF Performance,CDF,"CDF - Disaster Contingency 211,194 247,120",2.111940e+05,2024 Financial Statements PDF (Page 18)
43,2024,Actual Sector Grant Performance,Sector Grant,"Sector Grant - Goods and Services' s,oea,ln",1.200000e+01,2024 Financial Statements PDF (Page 20)
44,2024,Actual Sector Grant Performance,Sector Grant,Sector Grant - Non-Financial Assets Acquisition,1.200000e+01,2024 Financial Statements PDF (Page 20)
45,2024,Actual Sector Grant Performance,Sector Grant,Sector Grant - Infrastructure Development,1.200000e+01,2024 Financial Statements PDF (Page 20)
46,2024,Actual Sector Grant Performance,Sector Grant,Sector Grant - Rehabilitation Works,1.200000e+01,2024 Financial Statements PDF (Page 20)

In [ ]:
import pandas as pd
import re

# Exact line items and 2024 Actual Kwacha amounts directly from Page 15 (Audited Statement of Cash Receipts & Payments)
page15_exact_data = [
    # RECEIPTS
    {"type": "Actual Receipt (Main Statement)", "code": "Note 2", "desc": "Local Taxes", "amount": 2092554.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 3", "desc": "Fees and Charges", "amount": 6541942.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 4", "desc": "Licences", "amount": 674646.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 5", "desc": "Levies", "amount": 3771696.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 6", "desc": "Permits", "amount": 1981858.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 7", "desc": "Local Govt Equalisation Fund", "amount": 17373798.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 8", "desc": "Constituency Development Fund", "amount": 45980506.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 9", "desc": "Other Grants", "amount": 5444737.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 11", "desc": "Commercial Venture", "amount": 8514.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 12", "desc": "Sector Grants", "amount": 30139558.0},
    {"type": "Actual Receipt (Main Statement)", "code": "Note 13", "desc": "Other Receipts", "amount": 1005074.0},

    # PAYMENTS
    {"type": "Actual Payment (Main Statement)", "code": "Note 14", "desc": "Personal Emoluments", "amount": 16373373.0},
    {"type": "Actual Payment (Main Statement)", "code": "Note 15", "desc": "Use of Goods and Services", "amount": 20118360.0},
    {"type": "Actual Payment (Main Statement)", "code": "Note 17", "desc": "Social Benefits", "amount": 18122321.0},
    {"type": "Actual Payment (Main Statement)", "code": "Note 18", "desc": "Non-Financial Assets Acquisition", "amount": 46976686.0},
    {"type": "Actual Payment (Main Statement)", "code": "Note 19", "desc": "Financial Assets", "amount": 6949855.0},
    {"type": "Actual Payment (Main Statement)", "code": "Note 21", "desc": "Other Payments", "amount": 2508094.0},
]

# Add Fund-level breakdowns from Pages 17 & 18
fund_breakdowns = [
    # Page 17 - LGEF Payments
    {"type": "Actual LGEF Expenditure", "code": "LGEF 7(b)", "desc": "LGEF - Personal Emoluments (Salaries & Wages)", "amount": 16015829.0},
    {"type": "Actual LGEF Expenditure", "code": "LGEF 7(b)", "desc": "LGEF - Service Provision", "amount": 563468.0},
    {"type": "Actual LGEF Expenditure", "code": "LGEF 7(b)", "desc": "LGEF - Goods and Services", "amount": 467595.0},
    {"type": "Actual LGEF Expenditure", "code": "LGEF 7(b)", "desc": "LGEF - Administrative Costs", "amount": 80288.0},
    {"type": "Actual LGEF Expenditure", "code": "LGEF 7(c)", "desc": "LGEF - Infrastructure Development", "amount": 247615.0},

    # Page 18 - CDF Payments
    {"type": "Actual CDF Expenditure", "code": "CDF 8(d)", "desc": "CDF - Infrastructure Development", "amount": 23299108.0},
    {"type": "Actual CDF Expenditure", "code": "CDF 8(e)", "desc": "CDF - Rehabilitation Works", "amount": 11555283.0},
    {"type": "Actual CDF Expenditure", "code": "CDF 8(f)", "desc": "CDF - Asset Acquisition", "amount": 8115473.0},
    {"type": "Actual CDF Expenditure", "code": "CDF 8(g)", "desc": "CDF - Bursaries (Secondary & Skills)", "amount": 10280360.0},
    {"type": "Actual CDF Expenditure", "code": "CDF 8(h)", "desc": "CDF - Empowerment Grants", "amount": 4826650.0},
    {"type": "Actual CDF Expenditure", "code": "CDF 8(i)", "desc": "CDF - Empowerment Loans", "amount": 6949855.0},
    {"type": "Actual CDF Expenditure", "code": "CDF 8(j)", "desc": "CDF - Administrative Costs", "amount": 2949896.0},
    {"type": "Actual CDF Expenditure", "code": "CDF 8(k)", "desc": "CDF - Disaster Contingency", "amount": 211194.0},
]

# Build final 2024 DataFrame
clean_2024_records = []
for item in page15_exact_data + fund_breakdowns:
    clean_2024_records.append({
        "year": 2024,
        "financial_type": item["type"],
        "category/code": item["code"],
        "description": item["desc"],
        "amount": item["amount"],
        "source": "2024 Audited Financial Statements PDF"
    })

df_clean_2024 = pd.DataFrame(clean_2024_records)

# Save to output file
output_2024_filename = "db-unza26-csc4792-mumbwa_2024_actual_financial_statements.csv"
df_clean_2024.to_csv(output_2024_filename, sep="|", index=False)

print(f"Successfully generated {len(df_clean_2024)} verified 2024 actual records.")
print(f"Saved clean file to '{output_2024_filename}'.")
display(df_clean_2024)

Successfully generated 30 verified 2024 actual records.
Saved clean file to 'db-unza26-csc4792-mumbwa_2024_actual_financial_statements.csv'.

,year,financial_type,category/code,description,amount,source
0,2024,Actual Receipt (Main Statement),Note 2,Local Taxes,2092554.0,2024 Audited Financial Statements PDF
1,2024,Actual Receipt (Main Statement),Note 3,Fees and Charges,6541942.0,2024 Audited Financial Statements PDF
2,2024,Actual Receipt (Main Statement),Note 4,Licences,674646.0,2024 Audited Financial Statements PDF
3,2024,Actual Receipt (Main Statement),Note 5,Levies,3771696.0,2024 Audited Financial Statements PDF
4,2024,Actual Receipt (Main Statement),Note 6,Permits,1981858.0,2024 Audited Financial Statements PDF
5,2024,Actual Receipt (Main Statement),Note 7,Local Govt Equalisation Fund,17373798.0,2024 Audited Financial Statements PDF
6,2024,Actual Receipt (Main Statement),Note 8,Constituency Development Fund,45980506.0,2024 Audited Financial Statements PDF
7,2024,Actual Receipt (Main Statement),Note 9,Other Grants,5444737.0,2024 Audited Financial Statements PDF
8,2024,Actual Receipt (Main Statement),Note 11,Commercial Venture,8514.0,2024 Audited Financial Statements PDF
9,2024,Actual Receipt (Main Statement),Note 12,Sector Grants,30139558.0,2024 Audited Financial Statements PDF
10,2024,Actual Receipt (Main Statement),Note 13,Other Receipts,1005074.0,2024 Audited Financial Statements PDF
11,2024,Actual Payment (Main Statement),Note 14,Personal Emoluments,16373373.0,2024 Audited Financial Statements PDF
12,2024,Actual Payment (Main Statement),Note 15,Use of Goods and Services,20118360.0,2024 Audited Financial Statements PDF
13,2024,Actual Payment (Main Statement),Note 17,Social Benefits,18122321.0,2024 Audited Financial Statements PDF
14,2024,Actual Payment (Main Statement),Note 18,Non-Financial Assets Acquisition,46976686.0,2024 Audited Financial Statements PDF
15,2024,Actual Payment (Main Statement),Note 19,Financial Assets,6949855.0,2024 Audited Financial Statements PDF
16,2024,Actual Payment (Main Statement),Note 21,Other Payments,2508094.0,2024 Audited Financial Statements PDF
17,2024,Actual LGEF Expenditure,LGEF 7(b),LGEF - Personal Emoluments (Salaries & Wages),16015829.0,2024 Audited Financial Statements PDF
18,2024,Actual LGEF Expenditure,LGEF 7(b),LGEF - Service Provision,563468.0,2024 Audited Financial Statements PDF
19,2024,Actual LGEF Expenditure,LGEF 7(b),LGEF - Goods and Services,467595.0,2024 Audited Financial Statements PDF
20,2024,Actual LGEF Expenditure,LGEF 7(b),LGEF - Administrative Costs,80288.0,2024 Audited Financial Statements PDF
21,2024,Actual LGEF Expenditure,LGEF 7(c),LGEF - Infrastructure Development,247615.0,2024 Audited Financial Statements PDF
22,2024,Actual CDF Expenditure,CDF 8(d),CDF - Infrastructure Development,23299108.0,2024 Audited Financial Statements PDF
23,2024,Actual CDF Expenditure,CDF 8(e),CDF - Rehabilitation Works,11555283.0,2024 Audited Financial Statements PDF
24,2024,Actual CDF Expenditure,CDF 8(f),CDF - Asset Acquisition,8115473.0,2024 Audited Financial Statements PDF
25,2024,Actual CDF Expenditure,CDF 8(g),CDF - Bursaries (Secondary & Skills),10280360.0,2024 Audited Financial Statements PDF
26,2024,Actual CDF Expenditure,CDF 8(h),CDF - Empowerment Grants,4826650.0,2024 Audited Financial Statements PDF
27,2024,Actual CDF Expenditure,CDF 8(i),CDF - Empowerment Loans,6949855.0,2024 Audited Financial Statements PDF
28,2024,Actual CDF Expenditure,CDF 8(j),CDF - Administrative Costs,2949896.0,2024 Audited Financial Statements PDF
29,2024,Actual CDF Expenditure,CDF 8(k),CDF - Disaster Contingency,211194.0,2024 Audited Financial Statements PDF

In [ ]:
# 2023 Financial Statements - Main Statement, LGEF and CDF
import pandas as pd

# These amounts were manually transcribed from the scanned current-year columns.
# PDF page numbers count from the first page of the file, including its cover.
# A printed dash is recorded as zero; an empty amount is retained as None (missing).
# Keep negative receipts as printed. Do not replace missing values with zero.
# Fund expenditure is already included in the main statement: do not add both together.
stmt_2023_url = 'https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/2023-AUDITED-FINANCIAL-STATEMENT.pdf'

# Main statement receipts and payments, with the original note references.
page14_exact_data_2023 = [
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 2', 'desc': 'Local Taxes', 'amount': 1524260, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 3', 'desc': 'Fees and Charges', 'amount': 7222742, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 4', 'desc': 'Licences', 'amount': 2418644, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 5', 'desc': 'Levies', 'amount': 781946, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 6', 'desc': 'Permits', 'amount': 1299446, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 7', 'desc': 'Local Govt Equalisation Fund', 'amount': 14753174, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 8', 'desc': 'Constituency Development Fund', 'amount': 54522940, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 9', 'desc': 'Other Grants', 'amount': 2899717, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 10', 'desc': 'Borrowings', 'amount': None, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 11', 'desc': 'Commercial Venture', 'amount': -19255, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 12', 'desc': 'Other Receipts', 'amount': 1139947, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 13', 'desc': 'Personal Emoluments', 'amount': 13929832, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 14', 'desc': 'Use of Goods and Services', 'amount': 17600745, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 15', 'desc': 'Financial Charges', 'amount': None, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 16', 'desc': 'Social Benefits', 'amount': 9893049, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 17', 'desc': 'Non-Financial Assets Acquisition', 'amount': 35187359, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 18', 'desc': 'Financial Assets', 'amount': 12424361, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 19', 'desc': 'Loan Repayments', 'amount': None, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 20', 'desc': 'Other Payments', 'amount': 1333611, 'page': 14},
]

# LGEF and CDF expenditure breakdowns from their separate statement pages.
fund_breakdowns_2023 = [
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Salaries and Wages', 'amount': 11642600, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Terminal Benefits', 'amount': None, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Utility Bills', 'amount': None, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Service Provision', 'amount': None, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Goods and Services', 'amount': None, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Administrative Costs', 'amount': None, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Other Operational Costs', 'amount': None, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Infrastructure Development', 'amount': 2347602, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Rehabilitation Works', 'amount': 80101, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Asset Acquisition', 'amount': 412405, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Other Capital Costs', 'amount': 681530, 'page': 16},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(d)', 'desc': 'CDF - Infrastructure Development', 'amount': 19279792, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(e)', 'desc': 'CDF - Rehabilitation Works', 'amount': 4737847, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(f)', 'desc': 'CDF - Asset Acquisition', 'amount': 9663755, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(g)', 'desc': 'CDF - Bursaries - Secondary and Skills', 'amount': 5347173, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(h)', 'desc': 'CDF - Empowerment Grants', 'amount': 4545876, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(i)', 'desc': 'CDF - Empowerment Loans', 'amount': 12424361, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(j)', 'desc': 'CDF - Administrative Costs', 'amount': 4217752, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(k)', 'desc': 'CDF - Disaster Contingency', 'amount': 247120, 'page': 17},
]

# Build the same six-column DataFrame used in the 2024 section.
clean_2023_records = []
for item in page14_exact_data_2023 + fund_breakdowns_2023:
    clean_2023_records.append({
        "year": 2023,
        "financial_type": item["type"],
        "category/code": item["code"],
        "description": item["desc"],
        "amount": item["amount"],
        "source": f"2023 Financial Statements PDF (Page {item['page']}); {stmt_2023_url}"
    })

df_clean_2023 = pd.DataFrame(clean_2023_records)
df_clean_2023["amount"] = pd.to_numeric(df_clean_2023["amount"], errors="raise").astype("Float64")

# Compare line-item sums with printed totals without changing source amounts.
# Small source discrepancies remain visible; blank source amounts are excluded from sums.
reported_totals_2023 = dict(zip(
    ["Actual Receipt (Main Statement)", "Actual Payment (Main Statement)",
     "Actual LGEF Expenditure", "Actual CDF Expenditure"], [86543562, 90368957, 15164238, 60463676]))
for financial_type, reported_total in reported_totals_2023.items():
    calculated_total = df_clean_2023.loc[df_clean_2023["financial_type"] == financial_type, "amount"].sum()
    difference = calculated_total - reported_total
    print(f"{financial_type}: line items={calculated_total:,.0f}, printed={reported_total:,.0f}, difference={difference:,.0f} Kwacha")

# Export using the required filename and pipe separator; missing amounts stay blank.
output_2023_filename = "db-unza26-csc4792-mumbwa_2023_actual_financial_statements.csv"
df_clean_2023.to_csv(output_2023_filename, sep="|", index=False, na_rep="")
print(f"Saved {len(df_clean_2023)} records to '{output_2023_filename}'.")
display(df_clean_2023)

In [ ]:
# 2022 Financial Statements - Main Statement, LGEF and CDF
import pandas as pd

# These amounts were manually transcribed from the scanned current-year columns.
# PDF page numbers count from the first page of the file, including its cover.
# A printed dash is recorded as zero; an empty amount is retained as None (missing).
# Keep negative receipts as printed. Do not replace missing values with zero.
# Fund expenditure is already included in the main statement: do not add both together.
stmt_2022_url = 'https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2022.pdf'

# Main statement receipts and payments, with the original note references.
page12_exact_data_2022 = [
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 2', 'desc': 'Local Taxes', 'amount': 2375870, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 3', 'desc': 'Fees and Charges', 'amount': 3919262, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 4', 'desc': 'Licences', 'amount': 75320, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 5', 'desc': 'Levies', 'amount': 1699599, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 6', 'desc': 'Permits', 'amount': 641386, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 7', 'desc': 'Local Govt Equalisation Fund', 'amount': 14631120, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 8', 'desc': 'Constituency Development Fund', 'amount': 47479822, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 9', 'desc': 'Other Grants', 'amount': 594040, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 10', 'desc': 'Borrowings', 'amount': 0, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 11', 'desc': 'Commercial Venture', 'amount': 21854, 'page': 12},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 12', 'desc': 'Other Receipts', 'amount': 404520, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 13', 'desc': 'Personal Emoluments', 'amount': 12007690, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 14', 'desc': 'Use of Goods and Services', 'amount': 12650989, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 15', 'desc': 'Financial Charges', 'amount': None, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 16', 'desc': 'Social Benefits', 'amount': 3091001, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 17', 'desc': 'Non-Financial Assets Acquisition', 'amount': 4918408, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 18', 'desc': 'Financial Assets', 'amount': 0, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 19', 'desc': 'Loan Repayments', 'amount': 0, 'page': 12},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 20', 'desc': 'Other Payments', 'amount': 1088138, 'page': 12},
]

# LGEF and CDF expenditure breakdowns from their separate statement pages.
fund_breakdowns_2022 = [
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Salaries and Wages', 'amount': 12279162, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Terminal Benefits', 'amount': None, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Utility Bills', 'amount': 61102, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Service Provision', 'amount': 231322, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Goods and Services', 'amount': 206685, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Administrative Costs', 'amount': 161554, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Other Operational Costs', 'amount': None, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Infrastructure Development', 'amount': 140110, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Rehabilitation Works', 'amount': 583168, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Asset Acquisition', 'amount': 264416, 'page': 14},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Other Capital Costs', 'amount': 292251, 'page': 14},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(c)', 'desc': 'CDF - Infrastructure Development', 'amount': 2879609, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(d)', 'desc': 'CDF - Rehabilitation Works', 'amount': 1010910, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(e)', 'desc': 'CDF - Asset Acquisition', 'amount': 240000, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(f)', 'desc': 'CDF - Bursaries - Secondary and Skills', 'amount': 1667665, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(g)', 'desc': 'CDF - Empowerment Grants', 'amount': 3091001, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(h)', 'desc': 'CDF - Empowerment Loans', 'amount': 0, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(i)', 'desc': 'CDF - Administrative Costs', 'amount': 1377853, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(j)', 'desc': 'CDF - Disaster Contingency', 'amount': 193403, 'page': 15},
]

# Build the same six-column DataFrame used in the 2024 section.
clean_2022_records = []
for item in page12_exact_data_2022 + fund_breakdowns_2022:
    clean_2022_records.append({
        "year": 2022,
        "financial_type": item["type"],
        "category/code": item["code"],
        "description": item["desc"],
        "amount": item["amount"],
        "source": f"2022 Financial Statements PDF (Page {item['page']}); {stmt_2022_url}"
    })

df_clean_2022 = pd.DataFrame(clean_2022_records)
df_clean_2022["amount"] = pd.to_numeric(df_clean_2022["amount"], errors="raise").astype("Float64")

# Compare line-item sums with printed totals without changing source amounts.
# Small source discrepancies remain visible; blank source amounts are excluded from sums.
reported_totals_2022 = dict(zip(
    ["Actual Receipt (Main Statement)", "Actual Payment (Main Statement)",
     "Actual LGEF Expenditure", "Actual CDF Expenditure"], [71842793, 33756226, 14219770, 10460441]))
for financial_type, reported_total in reported_totals_2022.items():
    calculated_total = df_clean_2022.loc[df_clean_2022["financial_type"] == financial_type, "amount"].sum()
    difference = calculated_total - reported_total
    print(f"{financial_type}: line items={calculated_total:,.0f}, printed={reported_total:,.0f}, difference={difference:,.0f} Kwacha")

# Export using the required filename and pipe separator; missing amounts stay blank.
output_2022_filename = "db-unza26-csc4792-mumbwa_2022_actual_financial_statements.csv"
df_clean_2022.to_csv(output_2022_filename, sep="|", index=False, na_rep="")
print(f"Saved {len(df_clean_2022)} records to '{output_2022_filename}'.")
display(df_clean_2022)

In [ ]:
# 2021 Financial Statements - Main Statement, LGEF and CDF
import pandas as pd

# These amounts were manually transcribed from the scanned current-year columns.
# PDF page numbers count from the first page of the file, including its cover.
# A printed dash is recorded as zero; an empty amount is retained as None (missing).
# Keep negative receipts as printed. Do not replace missing values with zero.
# Fund expenditure is already included in the main statement: do not add both together.
stmt_2021_url = 'https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2021.pdf'

# Main statement receipts and payments, with the original note references.
page13_exact_data_2021 = [
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 2', 'desc': 'Local Taxes', 'amount': 1805169, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 3', 'desc': 'Fees and Charges', 'amount': 4086126, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 4', 'desc': 'Licences', 'amount': 25825, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 5', 'desc': 'Levies', 'amount': 1326151, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 6', 'desc': 'Permits', 'amount': 288501, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 7', 'desc': 'Local Govt Equalisation Fund', 'amount': 13174979, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 8', 'desc': 'Constituency Development Fund', 'amount': 3227755, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 9', 'desc': 'Other Grants', 'amount': 1290000, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 10', 'desc': 'Borrowings', 'amount': 0, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 11', 'desc': 'Commercial Venture', 'amount': -41, 'page': 13},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 12', 'desc': 'Other Receipts', 'amount': 6595578, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 13', 'desc': 'Personal Emoluments', 'amount': 10509128, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 14', 'desc': 'Use of Goods and Services', 'amount': 10557673, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 15', 'desc': 'Financial Charges', 'amount': 0, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 16', 'desc': 'Social Benefits', 'amount': 0, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 17', 'desc': 'Non-Financial Assets Acquisition', 'amount': 3416590, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 18', 'desc': 'Financial Assets', 'amount': 0, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 19', 'desc': 'Loan Repayments', 'amount': 0, 'page': 13},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 20', 'desc': 'Other Payments', 'amount': 6207777, 'page': 13},
]

# LGEF and CDF expenditure breakdowns from their separate statement pages.
fund_breakdowns_2021 = [
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Salaries and Wages', 'amount': 9651689, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Terminal Benefits', 'amount': 34000, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Utility Bills', 'amount': 0, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Service Provision', 'amount': 940592, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Goods and Services', 'amount': 335938, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Administrative Costs', 'amount': 526217, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Other Operational Costs', 'amount': 8000, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Infrastructure Development', 'amount': 521350, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Rehabilitation Works', 'amount': 436472, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Asset Acquisition', 'amount': 570100, 'page': 15},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Other Capital Costs', 'amount': 391716, 'page': 15},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(c)', 'desc': 'CDF - Infrastructure Development', 'amount': 1452302, 'page': 16},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(d)', 'desc': 'CDF - Rehabilitation Works', 'amount': 99972, 'page': 16},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(e)', 'desc': 'CDF - Asset Acquisition', 'amount': 0, 'page': 16},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(f)', 'desc': 'CDF - Administrative Costs', 'amount': 232021, 'page': 16},
]

# Build the same six-column DataFrame used in the 2024 section.
clean_2021_records = []
for item in page13_exact_data_2021 + fund_breakdowns_2021:
    clean_2021_records.append({
        "year": 2021,
        "financial_type": item["type"],
        "category/code": item["code"],
        "description": item["desc"],
        "amount": item["amount"],
        "source": f"2021 Financial Statements PDF (Page {item['page']}); {stmt_2021_url}"
    })

df_clean_2021 = pd.DataFrame(clean_2021_records)
df_clean_2021["amount"] = pd.to_numeric(df_clean_2021["amount"], errors="raise").astype("Float64")

# Compare line-item sums with printed totals without changing source amounts.
# Small source discrepancies remain visible; blank source amounts are excluded from sums.
reported_totals_2021 = dict(zip(
    ["Actual Receipt (Main Statement)", "Actual Payment (Main Statement)",
     "Actual LGEF Expenditure", "Actual CDF Expenditure"], [31820043, 30691168, 13416074, 1784295]))
for financial_type, reported_total in reported_totals_2021.items():
    calculated_total = df_clean_2021.loc[df_clean_2021["financial_type"] == financial_type, "amount"].sum()
    difference = calculated_total - reported_total
    print(f"{financial_type}: line items={calculated_total:,.0f}, printed={reported_total:,.0f}, difference={difference:,.0f} Kwacha")

# Export using the required filename and pipe separator; missing amounts stay blank.
output_2021_filename = "db-unza26-csc4792-mumbwa_2021_actual_financial_statements.csv"
df_clean_2021.to_csv(output_2021_filename, sep="|", index=False, na_rep="")
print(f"Saved {len(df_clean_2021)} records to '{output_2021_filename}'.")
display(df_clean_2021)

In [ ]:
# 2020 Financial Statements - Main Statement, LGEF and CDF
import pandas as pd

# These amounts were manually transcribed from the scanned current-year columns.
# PDF page numbers count from the first page of the file, including its cover.
# A printed dash is recorded as zero; an empty amount is retained as None (missing).
# Keep negative receipts as printed. Do not replace missing values with zero.
# Fund expenditure is already included in the main statement: do not add both together.
stmt_2020_url = 'https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/08/Financial-Statement-for-the-Year-ended-31-December-2020.pdf'

# Main statement receipts and payments, with the original note references.
page14_exact_data_2020 = [
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 2', 'desc': 'Local Taxes', 'amount': 1097096, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 3', 'desc': 'Fees and Charges', 'amount': 3432030, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 4', 'desc': 'Licences', 'amount': 25660, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 5', 'desc': 'Levies', 'amount': 1036561, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 6', 'desc': 'Permits', 'amount': 291326, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 7', 'desc': 'Local Govt Equalisation Fund', 'amount': 12917605, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 8', 'desc': 'Constituency Development Fund', 'amount': 3200000, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 9', 'desc': 'Other Grants', 'amount': 640000, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 10', 'desc': 'Borrowings', 'amount': 0, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 11', 'desc': 'Commercial Venture', 'amount': 5499, 'page': 14},
    {'type': 'Actual Receipt (Main Statement)', 'code': 'Note 12', 'desc': 'Other Receipts', 'amount': 72690, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 13', 'desc': 'Personal Emoluments', 'amount': 9578525, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 14', 'desc': 'Use of Goods and Services', 'amount': 8285651, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 15', 'desc': 'Financial Charges', 'amount': 0, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 16', 'desc': 'Social Benefits', 'amount': 0, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 17', 'desc': 'Non-Financial Assets Acquisition', 'amount': 2356168, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 18', 'desc': 'Financial Assets', 'amount': 0, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 19', 'desc': 'Loan Repayments', 'amount': 0, 'page': 14},
    {'type': 'Actual Payment (Main Statement)', 'code': 'Note 20', 'desc': 'Other Payments', 'amount': 1004674, 'page': 14},
]

# LGEF and CDF expenditure breakdowns from their separate statement pages.
fund_breakdowns_2020 = [
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Salaries and Wages', 'amount': 9578524, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Terminal Benefits', 'amount': 166994, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Utility Bills', 'amount': 0, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Service Provision', 'amount': 319124, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Goods and Services', 'amount': 2326, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Administrative Costs', 'amount': 57410, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(b)', 'desc': 'LGEF - Other Operational Costs', 'amount': 17776, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Infrastructure Development', 'amount': 1213893, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Rehabilitation Works', 'amount': 409683, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Asset Acquisition', 'amount': 660652, 'page': 16},
    {'type': 'Actual LGEF Expenditure', 'code': 'LGEF 7(c)', 'desc': 'LGEF - Other Capital Costs', 'amount': 249417, 'page': 16},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(c)', 'desc': 'CDF - Infrastructure Development', 'amount': 1619899, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(d)', 'desc': 'CDF - Rehabilitation Works', 'amount': 86595, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(e)', 'desc': 'CDF - Asset Acquisition', 'amount': 84000, 'page': 17},
    {'type': 'Actual CDF Expenditure', 'code': 'CDF 8(f)', 'desc': 'CDF - Administrative Costs', 'amount': 117476, 'page': 17},
]

# Build the same six-column DataFrame used in the 2024 section.
clean_2020_records = []
for item in page14_exact_data_2020 + fund_breakdowns_2020:
    clean_2020_records.append({
        "year": 2020,
        "financial_type": item["type"],
        "category/code": item["code"],
        "description": item["desc"],
        "amount": item["amount"],
        "source": f"2020 Financial Statements PDF (Page {item['page']}); {stmt_2020_url}"
    })

df_clean_2020 = pd.DataFrame(clean_2020_records)
df_clean_2020["amount"] = pd.to_numeric(df_clean_2020["amount"], errors="raise").astype("Float64")

# Compare line-item sums with printed totals without changing source amounts.
# Small source discrepancies remain visible; blank source amounts are excluded from sums.
reported_totals_2020 = dict(zip(
    ["Actual Receipt (Main Statement)", "Actual Payment (Main Statement)",
     "Actual LGEF Expenditure", "Actual CDF Expenditure"], [22718467, 21225018, 12675799, 1907970]))
for financial_type, reported_total in reported_totals_2020.items():
    calculated_total = df_clean_2020.loc[df_clean_2020["financial_type"] == financial_type, "amount"].sum()
    difference = calculated_total - reported_total
    print(f"{financial_type}: line items={calculated_total:,.0f}, printed={reported_total:,.0f}, difference={difference:,.0f} Kwacha")

# Export using the required filename and pipe separator; missing amounts stay blank.
output_2020_filename = "db-unza26-csc4792-mumbwa_2020_actual_financial_statements.csv"
df_clean_2020.to_csv(output_2020_filename, sep="|", index=False, na_rep="")
print(f"Saved {len(df_clean_2020)} records to '{output_2020_filename}'.")
display(df_clean_2020)

In [ ]:
import io
import requests
import urllib3
import pdfplumber

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# 1. URL for the 2025 Semi-Annual Budget Performance Report
semi_annual_2025_url = "https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/Semi-Annual-Budget-Performance-Report-for-2025.pdf"

# 2. Download the PDF bypassing SSL verification
response = requests.get(semi_annual_2025_url, verify=False)
print(f"Download Status: {response.status_code}")
print(f"File Size: {len(response.content)} bytes")

# 3. Open buffer and inspect total pages and first 5 pages preview
semi_annual_2025_file = io.BytesIO(response.content)

with pdfplumber.open(semi_annual_2025_file) as pdf:
    print(f"Total Pages: {len(pdf.pages)}")
    for i in range(min(5, len(pdf.pages))):
        print(f"\n--- PAGE {i+1} PREVIEW ---")
        text = pdf.pages[i].extract_text() or ""
        print(text[:400] + "..." if len(text) > 400 else text)

Download Status: 200
File Size: 3414355 bytes
Total Pages: 7

--- PAGE 1 PREVIEW ---
E C.;] co \ - ] o + (! N G) N Y xN SE z
F n > t U F ! ' \ f o . J l r t d , . ! H o , A ) ' o o o o p 3 o r @ o a o I I o 3 D ) a o @ t I p 3 D p o o N o a l @a z : 3 0 ) r a o o A o o ) mo a a t a a o D I ) ) l 0 I o a o o o a a o o o o a I D q o o t o o n o I a o 5g t I s r E I o F t l ( o o o ]) m a o o a p : l N Eo t I o{ t O . n 5 p o l N To Io{ ) D o a l D 5 ot o o o o c0 . o G o o p o o d 6...

--- PAGE 2 PREVIEW ---
z olz
o
4f,
!\ o l I 1) 3 D a o ! a N ? t I 1l I l O l
o f 0)
C, l o F o o lu
a o q c p o
o
o , At I oaD ) p o
o
E ( E D rE lldr
o o - D tl , o A o ) . a o I ID
o o 2 Sp t )i p a o o { p o- E ! e I I T t H I
a o ? o o o ! Dt j 3 u - o @p o [0 o p o o o I I o o a N o p) a o z D p , E o ( c d D ) l l I l t o l ..
o o - DI o a 7oq
qo a a $ o o t o T l r l l I
p 3 o s
D
o $'ll
a
a
tss
o
o,
0oa l=Dc: 1...

--- PAGE 3 PREVIEW ---
>Nla
rob
FtJb
ooE
a + o 0 D ^ O '0Er ? tsH > - ( ! :r 8 @ I 3 Qvm i3 c : 2 o a o 9.O C c I o J o o m C ! t o o o !^ '0 ZQ, O o F . r - & i0 r I I o 9 (l v dg O" i r '_ 'g ' P I ! ip a tr > T i3 tE ; E E "
4 - o a < n - T 5 b o U 0 6 3 : i o 5 9 f . , . a o T ,1 ! J r - o { : g C \ c : E q :( c - P oP ' b 4 d x r o 3 H a E o o o . o E ; i 9 - j r : - I i a- i Y i ! l . . H t L + L E J d Q O o D x (...

--- PAGE 4 PREVIEW ---
o - p 0q ^g 5 o 1 C iC 3 lrA X ^ - r rN o y^ q o o a t !L X a ' d i t 5 i o O a'13 a : = I < r - n a a 6 a E o ; N !/ a a F 7a o p : P i,a ; t E r ; i 3 'e
lm c0q !^0tc o o o, 9 o ! f c o L o o rc. a d o r5 ; a oX l2 lD .
x o ! J $ t I. , , - 6 p > : 5 u O ) . o =o p - i 5 ; a ' o * o . 3 + s a L o t $ ! ' S D t a i o o o o p a F; (2 . t o 8 ^) l D X l = o D i - D O !- ! - X o : 6 i & P + P O - J ...

--- PAGE 5 PREVIEW ---
(n OAJ ( o ,) ( t' , ) (,
o o t t / < 7 O o () - o 0 7o U o o lt -itfd r
o'3 j!
o P {i o o I I oL
ots o o o0(
6; o
o oO o
{ o 7 E/
(n Fe o o oo a o F C
a o . t o o !
!DP s o E o '0
a p o o o X.
p t o I *i
o (D A) 9<
p o
@
@o 5 !
o o g C
x
N)
\o
!I[ @
.N
I
c 3 -sn
o o o o o
\ \) Uit U iq FJ
4. 4i
o ciOo'
3 o = n o < . ili , I H oo o, i L q .6 h o w C o O o I
a o ( : @ o: (

In [ ]:
!apt-get install -y poppler-utils tesseract-ocr
!pip install pdf2image pytesseract

from pdf2image import convert_from_bytes
import pytesseract
import pandas as pd

# 1. Convert scanned PDF pages to high-resolution images (300 DPI)
images = convert_from_bytes(response.content, dpi=300)

# 2. Extract text from each page with OCR rotation handling
for idx, img in enumerate(images):
    print(f"\n=================== OCR PAGE {idx + 1} ===================")

    # Try normal orientation
    text = pytesseract.image_to_string(img)

    # If text is garbled, attempt 90-degree visual rotations
    if len(text.strip()) < 100 or "Receipt" not in text:
        text_rot = pytesseract.image_to_string(img.rotate(270, expand=True))
        if len(text_rot.strip()) > len(text.strip()):
            text = text_rot

    print(text[:2000])

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (5.3.4-1build5).
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 212 kB of archives.
After this operation, 735 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 poppler-utils amd64 24.02.0-1ubuntu9.9 [212 kB]
Fetched 212 kB in 1s (291 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 122797 files and directories currently installed.)
Preparing to unpack .../poppler-utils_24.02.0-1ubuntu9.9_amd64.deb ...
Unpacking poppler-utils (24.02.0-1ubuntu9.9) ...
Setting up poppler-utils (24.02.0-1ubuntu9.9) ...
Processing triggers for man-db (2.12.0-4build2) ...
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from pdf2image) (12.3.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from pytesseract) (26.3)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: pytesseract, pdf2image
Successfully installed pdf2image-1.17.0 pytesseract-0.3.13

=================== OCR PAGE 1 ===================
NAME: MUMBWA TOWN COUNCIL
2025 BI ANNUAL PERFORMANCE REPORT Period: 01-Jan-2025 to 30-Jun-2025
EVENUE SOURCES

Budget Actual
F as at 30-June 2025
# |Receipts
a b
ZMW ZMW %
i [National Support es
1.1 Local Government Equalisation Fund 17,054,618.00 6,520,173.04 10,534,444.96| 38%]

Variance Performance

c=a-b b/a

ZMW

1.2 Grants In Lieu of Rates | ___—350,000.00f 850,000.00 0%
1.3 Sector Grants | __9,791,035.00] -2,490,198.00| _7,300,837.00[7 25%
1.4 ZDSP Capital Grants | _8,340,00000f CT 8,340,000.00[ 0%
1.5 Constituency Development Fund | _—72,116,301.00[ 15,994,611.12| 56,121,689.88[ 22%
|_53,458,937.00| _—33,307,562.09 | 20,151,374.91[ 62%

WO]

1.6 Other Grants

: Sub-total |. 161,110,891.00 | _ 58,312,544.25 | 102,798,346.75| = === 36%

Own Source Revenue Ti |
2.2 Fee & Charges [__8.637,284.00| ___6,795,817.80 | 1,841, 466.20,

2.5 Permits [1,806,580.00] 874,519.00] 932,061.00, 48%

2.6 Commercial ventures [79,964.00 7,133.00] _72,831.00| 9%

7 Others OSR ee SC

4.1 Bank interest received a 7)

4.2 Borrowings - Loans a C07

" [4.2 Borrowings - Overdraft a 7
[180,530,734.00 | __68,587,301.16] 111,993,402.84

PAYMENTS

Budget Performance
# ia as at 30-June 2025
a b
ZMW ZMW ZMW
| 1 [Personal emoluments | 21,241,812.00] 3.1,162,380.18 | (9,920,568.18)| 147%

| 82,518,511.17| _12,366,230.27| _70,152,280.90
PE 0%
| __—7,473,871.00[ 80,000.00 | 7,393,871.00

| 2 [Use of goods and services
| 3 |Financial charges
| 4 [Social benefits
| 5 |Non-financial assets
| 6 | Financial assets
[7 Loan repayments
| 3 | Other repayments

Lo ito tall payments iain ane |

Net Budget Performance

Ps 0%
1,588,000.00 1,458,323.09 129,676.91| ss O%|
117,853,931.75)| a 38%]

eee 5,859,898.91 §,859,898.93)| 0%)

180,530,734.00 62,677,402.25

BUDGET PROGRAMME OUTPUT PERFORMANCE


=================== OCR PAGE 2 ===================
Name: of Budget Programme:
Key Output/Project & Indicator Unit of Measure | _ Actual =| ~—Variance _—si|
3000 12000

| 1 [Environment and Waste Management No. of Tones
| 2 [Maintenance of Towship Roads ee

2 ,
No. of Fire safety
building inspections

3 | Fire Management Services conducted 1500

| 4 |Installation and Maintenance of Street Lights
No. of Markets and

Bus Stations
Maintenance of Markets and Bus Stations maintained

Number of farmers
Training of farmers (Fisheries and Livestock) trained 1000
Note: Focus should on key services delivery and major budget allocation.



=================== OCR PAGE 3 ===================
NAME: MUMBWATOWN COUNCIL
2025 BI ANNUAL PERFORMANCE REPORT Period: 01-Jan-2025 to 30-Jun-2025
ALL CAPITAL PROJECTS

Cumulative Payments
|__ Start Date | End Date | Amount (ZMW) | zMW zMw
ge nstallation of water reticulation at-Muchabi 27-May-2025| 27-Aug-2025 350,000.00 Pe 350,000.00 | cor COMPLETED
Health Post
Construction of 01 Staff house,Ablution
2|block,Electrical wiring and Water reticulation 5-Jun-2025] 5-Sep-2025 1,510,000.00 377,500.00 | 1,132,500.00 CDF WIP
system at Musukamabwe Rural Health Centre
Construction of a Maternal wing and Solar
3|piped water reticulation system at 23-Jun-2025] 23-Oct-2025 1,050,000.00 262,500.00 787,500.00 CDF WIP
Chankwankwa Rural Health Centre
CDF
DF

| 4 pec ince tiieeiones wae Winery Pemanens Pea 24-Jan-2025 131,000.00 60,000.00 71,000.00 Beverue we |
Lodge (Phase 2)

| _5|Construction of Kantengwa FootBridge 23-Jun-2025] 23-Oct-2025 1,146,546.00 286,636.50 859,909.50| CDF _—Ss«[WIP sd

rading o: KM Nachibila to
Nalubanda (Additional) K1,500,000.00 © ;

| | ,500,000. signing
Award
Notice-Due
7 Procurement of Roller CDF diligence
Compactor K2,950,000.00 compete
Award
Notice-Due
CDF diligence
Procurement of Tipper Truck K2,450,000.00 compete
Upgrading o abu secondary “Submitted”
school by construction of a 1x3 CDF to Attorney
Classroom Block with 90 desks K1,439,371.08 General
Upgrading 0
secondary school by Submitted
10) construction of a 1x3 Classroom CDF to Attorney
Block with 90 desks K1,448,246.69 General
Upgrading of Nalubanda Submitted
11 secondary school by K1,548,573.04 CDF io ditorney
construction of a 1x3 Classroom General
Block with 90 desk iin
onstruction of a Materna Submitted
12|Annex and incinerator at CDF to Attorney
Muchabi Rural Health Post K1,730,444.14 General
onstruction 0 “Submitted”
13|Block with 90 desks at Luili CDF to Attorney
Primary School K1,510,771.32 General
“‘Procuremen
Construction of Semi Detached t-
14) staff house at Mukubu Primary Readvertise
School ment



=================== OCR PAGE 4 ===================
quoaur
asTiIaapeoy
3

YOo|G WOOISSE]D TXT B JO UOTIONIJSUOD 9t?
yim [oouss Arepuosas manyeny jo 8urpessdq

Tersueay ‘ply Sed‘ HOOT WOoISse[D EXT B JO UOTIONNSUOD 9t}
Aeui0}V 0} YyIM [ooyss Arepuooas eseyeyW jo surpeisdyq

—— ~ PF | ft
uouraInI01g
ado WIOOISSE[D [XT & JO UOTIONIJSUOD 94} YM 12
jooyds Arepuossg eYyunyuUeY jo 8urpeisdy
jose PSuesnyeN Jo uoryeyyiqeyoyy
4do 9%
yoo]q syjO AreuLlajaj Jo uoNonsysu0D
Jooyos AyUNUIWIOD equINITy
aqo ye YOoTg WooIsse[D EXT Jo uoTeTduI0D be
T0°S80‘b96% Jooyos Areullig epusyey ye uoryeNoyo1
aqo Jovem Jo UOTeTTeISUT sy aSNOH JeIS| a7
sIoyoea]L, poysejep tuleg ZX] Jo uoTjONIJsUOD
pastysapeos ysog YITe2H
3 ado Teiny esuemqey ye wia3shg uone;Noney zz
usuIaINd0Ig royeM 99 Burm Arussyew e Jo uorjons1su0D
Surusis ado 9S°ES7‘STE6M JoyelauToUl jo UOT}ONIsUOD pue
poeuo ysog UIeoH Jeiny eujeqey jo uons;duo

pesttoapeor jooyos Areurtig oqurepurey
4 ado
uUsUIIINIOIg

ye Yo Woorsse[D ZXT Jo UoHONIISUOD | 9,
SUIUSIS €0°666‘T98H jooyos Areultig oquiojeyy 6I
penuo ye sO0[g wlooisse XT Jo uorjonIjsuo

YOOTG WOOISSE][D EXT eB JO UOTIONISUOD 9y}
ym [ooyss Arepuoosas ajayey jo Surpeisdq

astIoapeoy
7}
uauIaIMoI014
yuour
asTIaapeoy

asToapeoy
3
uauIaInd01g

Ad

1S)

astJIaapeoy
3
usUIaINIOL
SUIUSIS
penuog

asTyIaapeoy
-3
uautaIno0Ig



=================== OCR PAGE 5 ===================
Upgrading of Kandesha Secondary Schoo

with the construction of a 1x3 Classroom

Block lontract signing
‘ocuremen

t-
Construction of Modern Police station (Final Readvertise
funding)

Notice-Due
diligence
Procurement of Roller Compactor completed

Construction of a maternity Annex at
Mumbwa General Hospital

Procurement of 750 desks for various schools

986,636.50 |


=================== OCR PAGE 6 ===================
NAME: XYZ TOWN COUNCIL
DEBT and ARREARS

OUTSTANDING AMOUNTS | OUTSTANDING AMOUNTS

ro
on
a
[_otwenrensiowanneans i
=

ae

1-Jan-2025 30-Jun-2025
ZMW ZMW
2068 802.3
Ee
es
ee
Ec
SO

Co
ems oe CCC
en ee!

iza7 TOT aT HOTA
a.
50,

19,374,690.36 20,513,977.21



=================== OCR PAGE 7 ===================
MUMBWA TOWN COUNCIL
Semi Annual Internal Audit Reports Period: Jan 2025 to Jun 2025
Key Internal Audit Recommedation and Implementation

Subject Matter Audit Finding stercromroaiatian Management Action Taken

Governance (Established
Committees & Meetings)
Income - Own Source
Revenue
; e Councils accounting € Counc
Accounting procedures and | procedures and processes are _|recommends going
controls efficient and discrete forward all council
e Internal Audit Unt Dp g

The stores section is working recommends that the |public finance act no 1 of 2018 to the

effiently soo far. stores section later therefore, all procedures are

€ procurement procedures and|The Internal Audit Unit |The Council is currently adhering to
Procurement procedures and | controls are working efficiently [recommends that the |the public finance management act
controls so far. procurement section _|no 1 of 2018 and the procurement act

&
measures through recommendations
from I.T to ensure the right back up

Stores management

€ payroll management and € Internal Audit Unt € Council is currently adhering to
7 |Payroll management controls are working efficiently |recommends that the the public finance management act
so far. payroll section no 1 of 2018 in the mangement of its
€ internal Audit uni € Council is currently using
Risk management The Risk management is working |recommends that the [approved Risk management system to

at optimum efficiency

council adheres to the }manage and control risks

aes aa

REPUBLIC OF ZAMBIA

MINISTRY OF LOCAL GOVERNMENT
wore’

ve 11 SEP 2025 >)
2 _—
DIRECTOR OF FINANCE

MUMBWA TOWN COUNCIL
P.O. BOX 830001, MUMBWA

In [ ]:
import os
import re
import requests
import urllib3
from bs4 import BeautifulSoup
import pandas as pd

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Target Council Document URLs / Categories
base_url = "https://www.mumbwacouncil.gov.zm"
target_pages = [
    f"{base_url}/documents/",
    f"{base_url}/category/financial-reports/",
    f"{base_url}/category/budgets/",
    f"{base_url}/constituency-development-fund-cdf/"
]

headers = {'User-Agent': 'Mozilla/5.0'}

discovered_files = []

# Step 1: Discover all financial PDF links across the website
print("=== DISCOVERING FINANCIAL DOCUMENTS ON MUMBWA COUNCIL WEBSITE ===")

for page_url in target_pages:
    try:
        res = requests.get(page_url, headers=headers, verify=False, timeout=10)
        if res.status_code == 200:
            soup = BeautifulSoup(res.text, 'html.parser')
            for a in soup.find_all('a', href=True):
                href = a['href']
                text = a.get_text(strip=True)
                if href.endswith('.pdf') or 'budget' in href.lower() or 'financial' in href.lower():
                    discovered_files.append({
                        "title": text or os.path.basename(href),
                        "url": href if href.startswith('http') else base_url + href
                    })
    except Exception as e:
        print(f"Skipping {page_url}: {e}")

# Deduplicate discovered links
df_links = pd.DataFrame(discovered_files).drop_duplicates(subset=['url'])
print(f"\nFound {len(df_links)} total financial/publication PDFs on the website:\n")
display(df_links)

# Save link inventory
df_links.to_csv("mumbwa_council_all_financial_pdf_index.csv", sep="|", index=False)

=== DISCOVERING FINANCIAL DOCUMENTS ON MUMBWA COUNCIL WEBSITE ===

Found 0 total financial/publication PDFs on the website:

Empty DataFrame
Columns: []
Index: []

In [ ]:
cdf_2024_url = "https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/2024-CDF-COMMUNITY-PROJECTS-AS-AT-31ST-AUGUST-2024.pdf"

cdf_2024_response = requests.get(
    cdf_2024_url,
    verify=False,
    timeout=60
)

print("Status:", cdf_2024_response.status_code)
print("File size:", len(cdf_2024_response.content), "bytes")
print("Content type:", cdf_2024_response.headers.get("Content-Type"))

Status: 200
File size: 257509 bytes
Content type: application/pdf

In [ ]:
!pip install -q pdfplumber

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 709.7 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 28.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 44.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 74.6 MB/s eta 0:00:00

In [ ]:
import io
import pdfplumber

cdf_2024_file = io.BytesIO(cdf_2024_response.content)

with pdfplumber.open(cdf_2024_file) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_num, page in enumerate(pdf.pages[:2], start=1):
        print(f"\n{'='*60}")
        print(f"PAGE {page_num}")
        print(f"{'='*60}")

        text = page.extract_text()

        if text:
            print(text[:4000])
        else:
            print("NO TEXT FOUND")

Number of pages: 4

============================================================
PAGE 1
============================================================
2024 CDF COMMUNITY PROJECTS-MUMBWA CENTRAL AS AT 31ST AUGUST, 2024
S/N Project Name Project Contract Name of Comment
Ward Location Sum Contrac Stat
tor us
All K1,177,500.0
Purchase of 785 Desks All wards Various 640 Desks
wards 0
1 suppliers 85% supplied
Installation of a solar Advertised
Lutale Lutale TBA
2 60,000litres Water Scheme TBA 10% on EGP
Installation of a Solar
Mumb
powered 60,000litres Water Mumba TBA Advertised
a
3 Scheme TBA 10% on EGP
Installation of a solar
Chibol
powered 60,000litres Water Chibolyo TBA Advertised
yo
4 Scheme TBA 10% on EGP
Drilling,Installation and
All K1,265,000.0
Equipping of No. 23 All wards Advertised
wards 0
5 Boreholes TBA 10% & Evaluated
Water
Wells
Mupo Installation of a water
Mupona K250,000.00 Drilling
na scheme
Technolo
6 gy 10% Mobilzation
Construction of Drainages
Mupo
in Town (Admin offices to Mupona TBA Advertised
na
7 Fourways) 2.4km TBA 10% on EGP
Electrification of Mumbwa, Payment
Shimb
Nankala,Shimbizhi and Shimbizhi K100,000.00 was made to
izhi
8 Shiwezwa ZESCO 30% ZESCO
Awaiting
Shimb mobilization
Shimbizhi K400,000.00
izhi Grading of Roads in all Force of
9 zones account 10% equipment
Construction of 1 Staff
House, Ablution Block,
Kamil Incinarator ,Electrical
Kamilambo TBA
ambo wiring and Water
reticulation at Advertised
10 Musukamabwe Health Post TBA 10% on EGP
Zambia
Construction of a Chiefs K1,000,000.0 Correctio
TBA TBA
palace 0 nal 100 Deducted at
11 Service % source
Nalusa Construction of Kapepe Labour Requested
Nalusanga K500,000.00
12 nga Bridge based 20% for materials
Awaiting
Grading and Spot
Chibol K1,000,000.0 mobilization
gravelling of Nakanjoli - Chibolyo
yo 0 Force of
Chikanda road
13 account 20% equipment
Installation of plumbing
works and water
Nalusa
reticulation system at Nalusanga K214,567.56 Kokos
nga
Chikanda Rural Health Contracto
14 Centre r 20% Mobilization

============================================================
PAGE 2
============================================================
Installation of plumbing
works and water
Nalusa
reticulation syctem at Nalusanga K203,284.78 Edmas
nga
Kabulwebulwe Primary General
15 school-Staff house Dealers 10% Mobilization
Installation of plumbing
works and water
Mpusu reticulation syctem at Mpusu TBA
Kawama Primary School- Advertised
16 Staffhouse TBA 10% & Evaluated
Installation of plumbing
works and water Water
Namb reticulation system for 1x3 Wells
Nambala K434,209.58
ala (2 bedroom) teachers Drilling
houses at Nambala Primary Technolo
17 School gy 10% Mobilization
Solar Piped Water
Reticulation System and Mwinach
Makeb
Plumbing works at Makebo K204,678.45 i
o
Kashinka Health Post-Staff Investme Advertised
18 house nts 10% & Evaluated
Solar Piped Water
Namb Reticulation System and
Nambala TBA
ala Plumbing works at Butinti Advertised
19 Primary School TBA 10% & Evaluated
Construction of a Maternity
wing and Solar piped Water
Naluv
reticulation system at Naluvwi TBA
wi
Naluvwi Rural Health Advertised
20 Centre TBA 10% & Evaluated
Construction of a Maternity
wing and Solar piped Water
Mumb
reticulation system at Mumba TBA
a
Kanwanzhiba Rural Health Advertised
21 Centre TBA 10% & Evaluated
To be topped
All Procurement of a TLB
All wards K210,000.00 up on
wards (Additional funding)
22 SDLG 10% payment
Central
All Procurement of an K2,700,000.0
All wards Procurem Deducted at
wards Ambulance 0
23 ent 10% source
Central
All Procurement of 6No Chief
All wards K150,000.00 Procurem Deducted at
wards retainers motor bikes
24 ent 10% source
Maternity wing and ward
Chakwank
Solar Piped Water
wa Rural
Lutale Reticulation System at TBA
Health
Chankwakwa Rural Health Advertised
Centre
25 Centre TBA 10% & Evaluated
On hold-
All Construction of a Modern K2,700,000.0
All wards awaiting site
wards Police Station 0
26 TBA 10% verification

In [ ]:
cdf_2024_file = io.BytesIO(cdf_2024_response.content)

with pdfplumber.open(cdf_2024_file) as pdf:
    cdf_2024_text = ""

    for page_num, page in enumerate(pdf.pages, start=1):
        text = page.extract_text()

        if text:
            cdf_2024_text += f"\n\n===== PAGE {page_num} =====\n\n"
            cdf_2024_text += text

print(cdf_2024_text)

===== PAGE 1 =====

2024 CDF COMMUNITY PROJECTS-MUMBWA CENTRAL AS AT 31ST AUGUST, 2024
S/N Project Name Project Contract Name of Comment
Ward Location Sum Contrac Stat
tor us
All K1,177,500.0
Purchase of 785 Desks All wards Various 640 Desks
wards 0
1 suppliers 85% supplied
Installation of a solar Advertised
Lutale Lutale TBA
2 60,000litres Water Scheme TBA 10% on EGP
Installation of a Solar
Mumb
powered 60,000litres Water Mumba TBA Advertised
a
3 Scheme TBA 10% on EGP
Installation of a solar
Chibol
powered 60,000litres Water Chibolyo TBA Advertised
yo
4 Scheme TBA 10% on EGP
Drilling,Installation and
All K1,265,000.0
Equipping of No. 23 All wards Advertised
wards 0
5 Boreholes TBA 10% & Evaluated
Water
Wells
Mupo Installation of a water
Mupona K250,000.00 Drilling
na scheme
Technolo
6 gy 10% Mobilzation
Construction of Drainages
Mupo
in Town (Admin offices to Mupona TBA Advertised
na
7 Fourways) 2.4km TBA 10% on EGP
Electrification of Mumbwa, Payment
Shimb
Nankala,Shimbizhi and Shimbizhi K100,000.00 was made to
izhi
8 Shiwezwa ZESCO 30% ZESCO
Awaiting
Shimb mobilization
Shimbizhi K400,000.00
izhi Grading of Roads in all Force of
9 zones account 10% equipment
Construction of 1 Staff
House, Ablution Block,
Kamil Incinarator ,Electrical
Kamilambo TBA
ambo wiring and Water
reticulation at Advertised
10 Musukamabwe Health Post TBA 10% on EGP
Zambia
Construction of a Chiefs K1,000,000.0 Correctio
TBA TBA
palace 0 nal 100 Deducted at
11 Service % source
Nalusa Construction of Kapepe Labour Requested
Nalusanga K500,000.00
12 nga Bridge based 20% for materials
Awaiting
Grading and Spot
Chibol K1,000,000.0 mobilization
gravelling of Nakanjoli - Chibolyo
yo 0 Force of
Chikanda road
13 account 20% equipment
Installation of plumbing
works and water
Nalusa
reticulation system at Nalusanga K214,567.56 Kokos
nga
Chikanda Rural Health Contracto
14 Centre r 20% Mobilization

===== PAGE 2 =====

Installation of plumbing
works and water
Nalusa
reticulation syctem at Nalusanga K203,284.78 Edmas
nga
Kabulwebulwe Primary General
15 school-Staff house Dealers 10% Mobilization
Installation of plumbing
works and water
Mpusu reticulation syctem at Mpusu TBA
Kawama Primary School- Advertised
16 Staffhouse TBA 10% & Evaluated
Installation of plumbing
works and water Water
Namb reticulation system for 1x3 Wells
Nambala K434,209.58
ala (2 bedroom) teachers Drilling
houses at Nambala Primary Technolo
17 School gy 10% Mobilization
Solar Piped Water
Reticulation System and Mwinach
Makeb
Plumbing works at Makebo K204,678.45 i
o
Kashinka Health Post-Staff Investme Advertised
18 house nts 10% & Evaluated
Solar Piped Water
Namb Reticulation System and
Nambala TBA
ala Plumbing works at Butinti Advertised
19 Primary School TBA 10% & Evaluated
Construction of a Maternity
wing and Solar piped Water
Naluv
reticulation system at Naluvwi TBA
wi
Naluvwi Rural Health Advertised
20 Centre TBA 10% & Evaluated
Construction of a Maternity
wing and Solar piped Water
Mumb
reticulation system at Mumba TBA
a
Kanwanzhiba Rural Health Advertised
21 Centre TBA 10% & Evaluated
To be topped
All Procurement of a TLB
All wards K210,000.00 up on
wards (Additional funding)
22 SDLG 10% payment
Central
All Procurement of an K2,700,000.0
All wards Procurem Deducted at
wards Ambulance 0
23 ent 10% source
Central
All Procurement of 6No Chief
All wards K150,000.00 Procurem Deducted at
wards retainers motor bikes
24 ent 10% source
Maternity wing and ward
Chakwank
Solar Piped Water
wa Rural
Lutale Reticulation System at TBA
Health
Chankwakwa Rural Health Advertised
Centre
25 Centre TBA 10% & Evaluated
On hold-
All Construction of a Modern K2,700,000.0
All wards awaiting site
wards Police Station 0
26 TBA 10% verification

===== PAGE 3 =====

2024 CDF COMMUNITY PROJECTS-NANGOMA CONSTITUENCY AS AT 31ST AUGUST,
2024
Constituen Project Contracto Statu Commen
Ward Project Name
S/N cy Location r s ts
Drilling of borehole Mpande Primary Advertise
Keezwa
1 Nangoma with Solar Pump School TBA 10% d on EGP
Construction of 2 Advertise
Naluban Staff houses and Nalubanda d on EGP
da construction of Primary School
2 Nangoma flushable Toilets TBA 10%
Advertise
Nakasak Construction of 1*4 Chiwena Hope
d on EGP
a Classroom Block School
3 Nangoma TBA 10%
Advertise
Construction of
Matala Kantengwa Zone d on EGP
Footbridge
4 Nangoma TBA 10%
Shakumbila Advertise
Construction of 1x3
Choma Community d on EGP
Classroom block
5 Nangoma School TBA 10%
Advertise
Nangom Construction of a
Kalindi Village d on EGP
a Health Post
6 Nangoma TBA 10%
Construction of 1*3 Advertise
Shichanz Classroom Block at Malima Primary d on EGP
u Malima Primary School
7 Nangoma School TBA 10%
Grading and Advertise
Gravelling of d on EGP
Chisalu Chisalu
Nachilumbe Road 17 Force
8 Nangoma KM account 10%
Central
All Nangoma
Ambulance Procureme Deducted
Wards Hospital
9 Nangoma nt 10% at source
Central
All Chief
Motorbike Procureme Deducted
Wards Shakumbila
10 Nangoma nt 10% at source
Construction of 1x3 Nachibila Evaluatio
Myooye
11 Nangoma Classroom block Primary School TBA 10% n stage
Malima Primary Advertise
Shichanz School, d on EGP
u,Choma Supply and Deliver Shakumbila
,Nakasak 360 Desks comm school,
a Chiwena Hope
12 Nangoma School TBA 10%
Advertise
Nangom Construction of a Nangoma
d on EGP
a Matenity Annex Hospital
13 Nangoma TBA 10%
Construction of a staff Advertise
Makuyuaboomb
Chisalu house at d on EGP
e
14 Nangoma Makuyuaboombe TBA 10%
Nangoma Advertise
Nangom Water Reticulation
Hospital d on EGP
a System
15 Nangoma Matenity Annex TBA 10%

===== PAGE 4 =====

Techcon Advertise
Water Reticulation Myooye RHP
Myooye Investment d &
System Martenity Wing
16 Nangoma Limited 10% awarded
Chemu-
Nangom Water Reticulation Kalindi Health Tech
a System Post Enterprise Mobilizi
17 Nangoma s 10% ng
No
Nakasak Water Reticulation Chiwena Rural
successf
a System Health Post
18 Nangoma TBA 10% ul bids
Chemu- Borehole
Water Reticulation Malende Rural Tech drilling,
Chisalu
System Health Post Enterprise Tank
19 Nangoma s 40% Stand
ReAdvert
Water Reticulation Makuyuaboomb ised on
Chisalu
System e Health Post EGP
20 Nangoma TBA 10%
ReAdvert
Water Reticulation Keezwa Health ised on
Keezwa
System Post EGP
21 Nangoma TBA 10%
ReAdvert
Water Reticulation Muchabi Health ised on
Choma
System Post EGP
22 Nangoma TBA 10%
Chemu- ReAdvert
Naluban Water Reticulation Nalubanda Tech ised on
da System Health Post Enterprise EGP
23 Nangoma s 10%
ReAdvert
Water Reticulation Namabanga ised on
Sichanzu
System Health Post EGP
24 Nangoma TBA 10%
ReAdvert
Water Reticulation ised on
Matala Luili Health Post
System EGP
25 Nangoma TBA 10%
ReAdvert
Nangoma
Nangom Boarding School ised on
Secondary
a Facility EGP
School
26 Nangoma TBA 10%

In [ ]:
cdf_2024_file = io.BytesIO(cdf_2024_response.content)

with pdfplumber.open(cdf_2024_file) as pdf:
    for page_num, page in enumerate(pdf.pages, start=1):
        tables = page.extract_tables()

        print(f"Page {page_num}: {len(tables)} tables found")

        if tables:
            print("\nFirst table:")
            for row in tables[0][:5]:
                print(row)

Page 1: 7 tables found

First table:
['S/N', 'Ward', 'Project Name', 'Project\nLocation', 'Contract\nSum', '', 'Name of', '', '', '', '', 'Comment']
[None, None, None, None, None, None, 'Contrac', None, None, 'Stat', None, None]
[None, None, None, None, None, None, 'tor', None, None, 'us', None, None]
['1', 'All\nwards', 'Purchase of 785 Desks', 'All wards', 'K1,177,500.0\n0', 'Various\nsuppliers', None, None, '85%', None, None, '640 Desks\nsupplied']
['2', 'Lutale', 'Installation of a solar\n60,000litres Water Scheme', 'Lutale', 'TBA', 'TBA', None, None, '10%', None, None, 'Advertised\non EGP']
Page 2: 9 tables found

First table:
[None, 'Nalusa\nnga', None, None, None, None, None, None, None, None]
['16', 'Mpusu', 'Installation of plumbing\nworks and water\nreticulation syctem at\nKawama Primary School-\nStaffhouse', None, None, 'Mpusu', 'TBA', 'TBA', '10%', 'Advertised\n& Evaluated']
['17', 'Namb\nala', 'Installation of plumbing\nworks and water\nreticulation system for 1x3\n(2 bedroom) teachers\nhouses at Nambala Primary\nSchool', None, None, 'Nambala', 'K434,209.58', 'Water\nWells\nDrilling\nTechnolo\ngy', '10%', 'Mobilization']
['18', 'Makeb\no', 'Solar Piped Water\nReticulation System and\nPlumbing works at\nKashinka Health Post-Staff\nhouse', None, None, 'Makebo', 'K204,678.45', 'Mwinach\ni\nInvestme\nnts', '10%', 'Advertised\n& Evaluated']
['19', 'Namb\nala', '', 'Solar Piped Water', '', 'Nambala', 'TBA', 'TBA', '10%', 'Advertised\n& Evaluated']
Page 3: 1 tables found

First table:
['S/N', 'Constituen\ncy', 'Ward', 'Project Name', 'Project\nLocation', 'Contracto\nr', 'Statu\ns', 'Commen\nts']
['1', 'Nangoma', 'Keezwa', 'Drilling of borehole\nwith Solar Pump', 'Mpande Primary\nSchool', 'TBA', '10%', 'Advertise\nd on EGP']
['2', 'Nangoma', 'Naluban\nda', 'Construction of 2\nStaff houses and\nconstruction of\nflushable Toilets', 'Nalubanda\nPrimary School', 'TBA', '10%', 'Advertise\nd on EGP']
['3', 'Nangoma', 'Nakasak\na', 'Construction of 1*4\nClassroom Block', 'Chiwena Hope\nSchool', 'TBA', '10%', 'Advertise\nd on EGP']
['4', 'Nangoma', 'Matala', 'Construction of\nFootbridge', 'Kantengwa Zone', 'TBA', '10%', 'Advertise\nd on EGP']
Page 4: 1 tables found

First table:
['16', 'Nangoma', 'Myooye', 'Water Reticulation\nSystem', 'Myooye RHP\nMartenity Wing', 'Techcon\nInvestment\nLimited', '10%', 'Advertise\nd &\nawarded']
['17', 'Nangoma', 'Nangom\na', 'Water Reticulation\nSystem', 'Kalindi Health\nPost', 'Chemu-\nTech\nEnterprise\ns', '10%', 'Mobilizi\nng']
['18', 'Nangoma', 'Nakasak\na', 'Water Reticulation\nSystem', 'Chiwena Rural\nHealth Post', 'TBA', '10%', 'No\nsuccessf\nul bids']
['19', 'Nangoma', 'Chisalu', 'Water Reticulation\nSystem', 'Malende Rural\nHealth Post', 'Chemu-\nTech\nEnterprise\ns', '40%', 'Borehole\ndrilling,\nTank\nStand']
['20', 'Nangoma', 'Chisalu', 'Water Reticulation\nSystem', 'Makuyuaboomb\ne Health Post', 'TBA', '10%', 'ReAdvert\nised on\nEGP']

In [ ]:
cdf_2024_file = io.BytesIO(cdf_2024_response.content)

with pdfplumber.open(cdf_2024_file) as pdf:
    for page_num, page in enumerate(pdf.pages, start=1):
        tables = page.extract_tables()

        print(f"\nPAGE {page_num}: {len(tables)} tables")

        for table_num, table in enumerate(tables, start=1):
            print(
                f"  Table {table_num}: "
                f"{len(table)} rows x "
                f"{max(len(row) for row in table)} columns"
            )

PAGE 1: 7 tables
  Table 1: 17 rows x 12 columns
  Table 2: 2 rows x 1 columns
  Table 3: 2 rows x 1 columns
  Table 4: 2 rows x 1 columns
  Table 5: 3 rows x 1 columns
  Table 6: 2 rows x 1 columns
  Table 7: 2 rows x 1 columns

PAGE 2: 9 tables
  Table 1: 23 rows x 10 columns
  Table 2: 2 rows x 1 columns
  Table 3: 2 rows x 1 columns
  Table 4: 2 rows x 1 columns
  Table 5: 2 rows x 1 columns
  Table 6: 2 rows x 1 columns
  Table 7: 2 rows x 1 columns
  Table 8: 2 rows x 1 columns
  Table 9: 2 rows x 1 columns

PAGE 3: 1 tables
  Table 1: 16 rows x 8 columns

PAGE 4: 1 tables
  Table 1: 11 rows x 8 columns

In [ ]:
cdf_2024_file = io.BytesIO(cdf_2024_response.content)

cdf_tables = []

with pdfplumber.open(cdf_2024_file) as pdf:
    for page_num in [3, 4]:
        page = pdf.pages[page_num - 1]
        table = page.extract_tables()[0]

        print(f"\nPAGE {page_num}")
        print("-" * 60)

        for row in table:
            print(row)

PAGE 3
------------------------------------------------------------
['S/N', 'Constituen\ncy', 'Ward', 'Project Name', 'Project\nLocation', 'Contracto\nr', 'Statu\ns', 'Commen\nts']
['1', 'Nangoma', 'Keezwa', 'Drilling of borehole\nwith Solar Pump', 'Mpande Primary\nSchool', 'TBA', '10%', 'Advertise\nd on EGP']
['2', 'Nangoma', 'Naluban\nda', 'Construction of 2\nStaff houses and\nconstruction of\nflushable Toilets', 'Nalubanda\nPrimary School', 'TBA', '10%', 'Advertise\nd on EGP']
['3', 'Nangoma', 'Nakasak\na', 'Construction of 1*4\nClassroom Block', 'Chiwena Hope\nSchool', 'TBA', '10%', 'Advertise\nd on EGP']
['4', 'Nangoma', 'Matala', 'Construction of\nFootbridge', 'Kantengwa Zone', 'TBA', '10%', 'Advertise\nd on EGP']
['5', 'Nangoma', 'Choma', 'Construction of 1x3\nClassroom block', 'Shakumbila\nCommunity\nSchool', 'TBA', '10%', 'Advertise\nd on EGP']
['6', 'Nangoma', 'Nangom\na', 'Construction of a\nHealth Post', 'Kalindi Village', 'TBA', '10%', 'Advertise\nd on EGP']
['7', 'Nangoma', 'Shichanz\nu', 'Construction of 1*3\nClassroom Block at\nMalima Primary\nSchool', 'Malima Primary\nSchool', 'TBA', '10%', 'Advertise\nd on EGP']
['8', 'Nangoma', 'Chisalu', 'Grading and\nGravelling of\nNachilumbe Road 17\nKM', 'Chisalu', 'Force\naccount', '10%', 'Advertise\nd on EGP']
['9', 'Nangoma', 'All\nWards', 'Ambulance', 'Nangoma\nHospital', 'Central\nProcureme\nnt', '10%', 'Deducted\nat source']
['10', 'Nangoma', 'All\nWards', 'Motorbike', 'Chief\nShakumbila', 'Central\nProcureme\nnt', '10%', 'Deducted\nat source']
['11', 'Nangoma', 'Myooye', 'Construction of 1x3\nClassroom block', 'Nachibila\nPrimary School', 'TBA', '10%', 'Evaluatio\nn stage']
['12', 'Nangoma', 'Shichanz\nu,Choma\n,Nakasak\na', 'Supply and Deliver\n360 Desks', 'Malima Primary\nSchool,\nShakumbila\ncomm school,\nChiwena Hope\nSchool', 'TBA', '10%', 'Advertise\nd on EGP']
['13', 'Nangoma', 'Nangom\na', 'Construction of a\nMatenity Annex', 'Nangoma\nHospital', 'TBA', '10%', 'Advertise\nd on EGP']
['14', 'Nangoma', 'Chisalu', 'Construction of a staff\nhouse at\nMakuyuaboombe', 'Makuyuaboomb\ne', 'TBA', '10%', 'Advertise\nd on EGP']
['15', 'Nangoma', 'Nangom\na', 'Water Reticulation\nSystem', 'Nangoma\nHospital\nMatenity Annex', 'TBA', '10%', 'Advertise\nd on EGP']

PAGE 4
------------------------------------------------------------
['16', 'Nangoma', 'Myooye', 'Water Reticulation\nSystem', 'Myooye RHP\nMartenity Wing', 'Techcon\nInvestment\nLimited', '10%', 'Advertise\nd &\nawarded']
['17', 'Nangoma', 'Nangom\na', 'Water Reticulation\nSystem', 'Kalindi Health\nPost', 'Chemu-\nTech\nEnterprise\ns', '10%', 'Mobilizi\nng']
['18', 'Nangoma', 'Nakasak\na', 'Water Reticulation\nSystem', 'Chiwena Rural\nHealth Post', 'TBA', '10%', 'No\nsuccessf\nul bids']
['19', 'Nangoma', 'Chisalu', 'Water Reticulation\nSystem', 'Malende Rural\nHealth Post', 'Chemu-\nTech\nEnterprise\ns', '40%', 'Borehole\ndrilling,\nTank\nStand']
['20', 'Nangoma', 'Chisalu', 'Water Reticulation\nSystem', 'Makuyuaboomb\ne Health Post', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['21', 'Nangoma', 'Keezwa', 'Water Reticulation\nSystem', 'Keezwa Health\nPost', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['22', 'Nangoma', 'Choma', 'Water Reticulation\nSystem', 'Muchabi Health\nPost', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['23', 'Nangoma', 'Naluban\nda', 'Water Reticulation\nSystem', 'Nalubanda\nHealth Post', 'Chemu-\nTech\nEnterprise\ns', '10%', 'ReAdvert\nised on\nEGP']
['24', 'Nangoma', 'Sichanzu', 'Water Reticulation\nSystem', 'Namabanga\nHealth Post', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['25', 'Nangoma', 'Matala', 'Water Reticulation\nSystem', 'Luili Health Post', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['26', 'Nangoma', 'Nangom\na', 'Boarding School\nFacility', 'Nangoma\nSecondary\nSchool', 'TBA', '10%', 'ReAdvert\nised on\nEGP']

In [ ]:
import pandas as pd

cdf_2024_nangoma = []

cdf_2024_file = io.BytesIO(cdf_2024_response.content)

with pdfplumber.open(cdf_2024_file) as pdf:
    for page_num in [3, 4]:
        table = pdf.pages[page_num - 1].extract_tables()[0]

        # Skip header row
        for row in table[1:]:
            if row and row[0]:
                cdf_2024_nangoma.append(row)

columns = [
    "project_number",
    "constituency",
    "ward",
    "project_name",
    "project_location",
    "contractor",
    "status",
    "comments"
]

cdf_2024_nangoma_df = pd.DataFrame(
    cdf_2024_nangoma,
    columns=columns
)

display(cdf_2024_nangoma_df)

,project_number,constituency,ward,project_name,project_location,contractor,status,comments
0,1,Nangoma,Keezwa,Drilling of borehole\nwith Solar Pump,Mpande Primary\nSchool,TBA,10%,Advertise\nd on EGP
1,2,Nangoma,Naluban\nda,Construction of 2\nStaff houses and\nconstruct...,Nalubanda\nPrimary School,TBA,10%,Advertise\nd on EGP
2,3,Nangoma,Nakasak\na,Construction of 1*4\nClassroom Block,Chiwena Hope\nSchool,TBA,10%,Advertise\nd on EGP
3,4,Nangoma,Matala,Construction of\nFootbridge,Kantengwa Zone,TBA,10%,Advertise\nd on EGP
4,5,Nangoma,Choma,Construction of 1x3\nClassroom block,Shakumbila\nCommunity\nSchool,TBA,10%,Advertise\nd on EGP
5,6,Nangoma,Nangom\na,Construction of a\nHealth Post,Kalindi Village,TBA,10%,Advertise\nd on EGP
6,7,Nangoma,Shichanz\nu,Construction of 1*3\nClassroom Block at\nMalim...,Malima Primary\nSchool,TBA,10%,Advertise\nd on EGP
7,8,Nangoma,Chisalu,Grading and\nGravelling of\nNachilumbe Road 17...,Chisalu,Force\naccount,10%,Advertise\nd on EGP
8,9,Nangoma,All\nWards,Ambulance,Nangoma\nHospital,Central\nProcureme\nnt,10%,Deducted\nat source
9,10,Nangoma,All\nWards,Motorbike,Chief\nShakumbila,Central\nProcureme\nnt,10%,Deducted\nat source
10,11,Nangoma,Myooye,Construction of 1x3\nClassroom block,Nachibila\nPrimary School,TBA,10%,Evaluatio\nn stage
11,12,Nangoma,"Shichanz\nu,Choma\n,Nakasak\na",Supply and Deliver\n360 Desks,"Malima Primary\nSchool,\nShakumbila\ncomm scho...",TBA,10%,Advertise\nd on EGP
12,13,Nangoma,Nangom\na,Construction of a\nMatenity Annex,Nangoma\nHospital,TBA,10%,Advertise\nd on EGP
13,14,Nangoma,Chisalu,Construction of a staff\nhouse at\nMakuyuaboombe,Makuyuaboomb\ne,TBA,10%,Advertise\nd on EGP
14,15,Nangoma,Nangom\na,Water Reticulation\nSystem,Nangoma\nHospital\nMatenity Annex,TBA,10%,Advertise\nd on EGP
15,17,Nangoma,Nangom\na,Water Reticulation\nSystem,Kalindi Health\nPost,Chemu-\nTech\nEnterprise\ns,10%,Mobilizi\nng
16,18,Nangoma,Nakasak\na,Water Reticulation\nSystem,Chiwena Rural\nHealth Post,TBA,10%,No\nsuccessf\nul bids
17,19,Nangoma,Chisalu,Water Reticulation\nSystem,Malende Rural\nHealth Post,Chemu-\nTech\nEnterprise\ns,40%,"Borehole\ndrilling,\nTank\nStand"
18,20,Nangoma,Chisalu,Water Reticulation\nSystem,Makuyuaboomb\ne Health Post,TBA,10%,ReAdvert\nised on\nEGP
19,21,Nangoma,Keezwa,Water Reticulation\nSystem,Keezwa Health\nPost,TBA,10%,ReAdvert\nised on\nEGP
20,22,Nangoma,Choma,Water Reticulation\nSystem,Muchabi Health\nPost,TBA,10%,ReAdvert\nised on\nEGP
21,23,Nangoma,Naluban\nda,Water Reticulation\nSystem,Nalubanda\nHealth Post,Chemu-\nTech\nEnterprise\ns,10%,ReAdvert\nised on\nEGP
22,24,Nangoma,Sichanzu,Water Reticulation\nSystem,Namabanga\nHealth Post,TBA,10%,ReAdvert\nised on\nEGP
23,25,Nangoma,Matala,Water Reticulation\nSystem,Luili Health Post,TBA,10%,ReAdvert\nised on\nEGP
24,26,Nangoma,Nangom\na,Boarding School\nFacility,Nangoma\nSecondary\nSchool,TBA,10%,ReAdvert\nised on\nEGP

In [ ]:
cdf_2024_file = io.BytesIO(cdf_2024_response.content)

with pdfplumber.open(cdf_2024_file) as pdf:
    page4_tables = pdf.pages[3].extract_tables()

    print("Number of tables on page 4:", len(page4_tables))

    for table_num, table in enumerate(page4_tables, start=1):
        print(f"\nTABLE {table_num}")
        for row in table:
            print(row)

Number of tables on page 4: 1

TABLE 1
['16', 'Nangoma', 'Myooye', 'Water Reticulation\nSystem', 'Myooye RHP\nMartenity Wing', 'Techcon\nInvestment\nLimited', '10%', 'Advertise\nd &\nawarded']
['17', 'Nangoma', 'Nangom\na', 'Water Reticulation\nSystem', 'Kalindi Health\nPost', 'Chemu-\nTech\nEnterprise\ns', '10%', 'Mobilizi\nng']
['18', 'Nangoma', 'Nakasak\na', 'Water Reticulation\nSystem', 'Chiwena Rural\nHealth Post', 'TBA', '10%', 'No\nsuccessf\nul bids']
['19', 'Nangoma', 'Chisalu', 'Water Reticulation\nSystem', 'Malende Rural\nHealth Post', 'Chemu-\nTech\nEnterprise\ns', '40%', 'Borehole\ndrilling,\nTank\nStand']
['20', 'Nangoma', 'Chisalu', 'Water Reticulation\nSystem', 'Makuyuaboomb\ne Health Post', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['21', 'Nangoma', 'Keezwa', 'Water Reticulation\nSystem', 'Keezwa Health\nPost', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['22', 'Nangoma', 'Choma', 'Water Reticulation\nSystem', 'Muchabi Health\nPost', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['23', 'Nangoma', 'Naluban\nda', 'Water Reticulation\nSystem', 'Nalubanda\nHealth Post', 'Chemu-\nTech\nEnterprise\ns', '10%', 'ReAdvert\nised on\nEGP']
['24', 'Nangoma', 'Sichanzu', 'Water Reticulation\nSystem', 'Namabanga\nHealth Post', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['25', 'Nangoma', 'Matala', 'Water Reticulation\nSystem', 'Luili Health Post', 'TBA', '10%', 'ReAdvert\nised on\nEGP']
['26', 'Nangoma', 'Nangom\na', 'Boarding School\nFacility', 'Nangoma\nSecondary\nSchool', 'TBA', '10%', 'ReAdvert\nised on\nEGP']

In [ ]:
cdf_2024_file = io.BytesIO(cdf_2024_response.content)

cdf_2024_nangoma = []

with pdfplumber.open(cdf_2024_file) as pdf:
    # Page 3 has a header, so skip the first row
    page3_table = pdf.pages[2].extract_tables()[0]
    cdf_2024_nangoma.extend(page3_table[1:])

    # Page 4 continues the table and has NO header
    page4_table = pdf.pages[3].extract_tables()[0]
    cdf_2024_nangoma.extend(page4_table)

columns = [
    "project_number",
    "constituency",
    "ward",
    "project_name",
    "project_location",
    "contractor",
    "status",
    "comments"
]

cdf_2024_nangoma_df = pd.DataFrame(
    cdf_2024_nangoma,
    columns=columns
)

print("Number of projects:", len(cdf_2024_nangoma_df))
print("Project numbers:", cdf_2024_nangoma_df["project_number"].tolist())

display(cdf_2024_nangoma_df)

Number of projects: 26
Project numbers: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26']

,project_number,constituency,ward,project_name,project_location,contractor,status,comments
0,1,Nangoma,Keezwa,Drilling of borehole\nwith Solar Pump,Mpande Primary\nSchool,TBA,10%,Advertise\nd on EGP
1,2,Nangoma,Naluban\nda,Construction of 2\nStaff houses and\nconstruct...,Nalubanda\nPrimary School,TBA,10%,Advertise\nd on EGP
2,3,Nangoma,Nakasak\na,Construction of 1*4\nClassroom Block,Chiwena Hope\nSchool,TBA,10%,Advertise\nd on EGP
3,4,Nangoma,Matala,Construction of\nFootbridge,Kantengwa Zone,TBA,10%,Advertise\nd on EGP
4,5,Nangoma,Choma,Construction of 1x3\nClassroom block,Shakumbila\nCommunity\nSchool,TBA,10%,Advertise\nd on EGP
5,6,Nangoma,Nangom\na,Construction of a\nHealth Post,Kalindi Village,TBA,10%,Advertise\nd on EGP
6,7,Nangoma,Shichanz\nu,Construction of 1*3\nClassroom Block at\nMalim...,Malima Primary\nSchool,TBA,10%,Advertise\nd on EGP
7,8,Nangoma,Chisalu,Grading and\nGravelling of\nNachilumbe Road 17...,Chisalu,Force\naccount,10%,Advertise\nd on EGP
8,9,Nangoma,All\nWards,Ambulance,Nangoma\nHospital,Central\nProcureme\nnt,10%,Deducted\nat source
9,10,Nangoma,All\nWards,Motorbike,Chief\nShakumbila,Central\nProcureme\nnt,10%,Deducted\nat source
10,11,Nangoma,Myooye,Construction of 1x3\nClassroom block,Nachibila\nPrimary School,TBA,10%,Evaluatio\nn stage
11,12,Nangoma,"Shichanz\nu,Choma\n,Nakasak\na",Supply and Deliver\n360 Desks,"Malima Primary\nSchool,\nShakumbila\ncomm scho...",TBA,10%,Advertise\nd on EGP
12,13,Nangoma,Nangom\na,Construction of a\nMatenity Annex,Nangoma\nHospital,TBA,10%,Advertise\nd on EGP
13,14,Nangoma,Chisalu,Construction of a staff\nhouse at\nMakuyuaboombe,Makuyuaboomb\ne,TBA,10%,Advertise\nd on EGP
14,15,Nangoma,Nangom\na,Water Reticulation\nSystem,Nangoma\nHospital\nMatenity Annex,TBA,10%,Advertise\nd on EGP
15,16,Nangoma,Myooye,Water Reticulation\nSystem,Myooye RHP\nMartenity Wing,Techcon\nInvestment\nLimited,10%,Advertise\nd &\nawarded
16,17,Nangoma,Nangom\na,Water Reticulation\nSystem,Kalindi Health\nPost,Chemu-\nTech\nEnterprise\ns,10%,Mobilizi\nng
17,18,Nangoma,Nakasak\na,Water Reticulation\nSystem,Chiwena Rural\nHealth Post,TBA,10%,No\nsuccessf\nul bids
18,19,Nangoma,Chisalu,Water Reticulation\nSystem,Malende Rural\nHealth Post,Chemu-\nTech\nEnterprise\ns,40%,"Borehole\ndrilling,\nTank\nStand"
19,20,Nangoma,Chisalu,Water Reticulation\nSystem,Makuyuaboomb\ne Health Post,TBA,10%,ReAdvert\nised on\nEGP
20,21,Nangoma,Keezwa,Water Reticulation\nSystem,Keezwa Health\nPost,TBA,10%,ReAdvert\nised on\nEGP
21,22,Nangoma,Choma,Water Reticulation\nSystem,Muchabi Health\nPost,TBA,10%,ReAdvert\nised on\nEGP
22,23,Nangoma,Naluban\nda,Water Reticulation\nSystem,Nalubanda\nHealth Post,Chemu-\nTech\nEnterprise\ns,10%,ReAdvert\nised on\nEGP
23,24,Nangoma,Sichanzu,Water Reticulation\nSystem,Namabanga\nHealth Post,TBA,10%,ReAdvert\nised on\nEGP
24,25,Nangoma,Matala,Water Reticulation\nSystem,Luili Health Post,TBA,10%,ReAdvert\nised on\nEGP
25,26,Nangoma,Nangom\na,Boarding School\nFacility,Nangoma\nSecondary\nSchool,TBA,10%,ReAdvert\nised on\nEGP