In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO
from urllib.parse import urljoin
from urllib.parse import urlparse
import os
from pathlib import Path
import pdfplumber

project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

raw_pdf_dir = project_root / "data" / "raw" / "pdfs"
reconstructed_pdf_dir = project_root / "data" / "intermediate" / "reconstructed_pdfs"
extracted_dir = project_root / "data" / "extracted"
processed_dir = project_root / "data" / "processed"
final_dir = project_root / "data" / "final"

raw_pdf_dir.mkdir(parents=True, exist_ok=True)
extracted_dir.mkdir(parents=True, exist_ok=True)
processed_dir.mkdir(parents=True, exist_ok=True)
final_dir.mkdir(parents=True, exist_ok=True)

In [3]:
## %pip install --upgrade certifi requests urllib3

Requirement already satisfied: certifi in C:\Users\Moses Chaswala\AppData\Local\Programs\Python\Python314\Lib\site-packages (2026.7.22)
Requirement already satisfied: requests in C:\Users\Moses Chaswala\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.34.2)
Requirement already satisfied: urllib3 in C:\Users\Moses Chaswala\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.7.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Moses Chaswala\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Moses Chaswala\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.18)
Note: you may need to restart the kernel to use updated packages.

In [2]:
url = "https://www.mumbwacouncil.gov.zm/"

In [3]:
response = requests.get(url,timeout=30 ,verify=False)

C:\Users\Moses Chaswala\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [4]:
print(response.status_code)
print(response.url)
print(response.text[:2000])

200
https://www.mumbwacouncil.gov.zm/
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />		<title>Mumbwa Town Council &#8211; Mumbwa</title>
<meta name='robots' content='max-image-preview:large' />
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="Mumbwa Town Council &raquo; Feed" href="https://www.mumbwacouncil.gov.zm/?feed=rss2" />
<link rel="alternate" type="application/rss+xml" title="Mumbwa Town Council &raquo; Comments Feed" href="https://www.mumbwacouncil.gov.zm/?feed=comments-rss2" />
<script>
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/www.mumbwacouncil.gov.zm\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.9"}};
/*! This file is auto-generated */
!function(e,a,t){var n,r,o,i=a.createElement("canvas"),p=i.getContext&&i.getContext("2d");function s(e,t){var a=String.fromCharCode;p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,e),0,0);e=i.toDataURL();return p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,t),0,0),e===i.toDataURL()}function c(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(o=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},r=0;r<o.length;r++)t.supports[o[r]]=function(e){if(!p||!p.fillText)return!1;switch(p.textBaseline="top",p.font="600 32px Arial",e){case"flag":return s([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])?!1:!s([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!s([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]);case"emoji":return!s([10084,

In [5]:
print("<table" in response.text.lower())

False

In [6]:
soup = BeautifulSoup(response.text, "html.parser")

print("Tables:", len(soup.find_all("table")))
print("Scripts:", len(soup.find_all("script")))
print("Links:", len(soup.find_all("a")))

Tables: 0
Scripts: 50
Links: 80

In [ ]:
# %pip install --upgrade certifi requests urllib3

In [10]:

soup = BeautifulSoup(response.text, "html.parser")

print("Tables found:", len(soup.find_all("table")))
print("Links found:", len(soup.find_all("a")))
print("Scripts found:", len(soup.find_all("script")))

Tables found: 0
Links found: 80
Scripts found: 50

In [7]:
links = []

for link in soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(url, link["href"])

    links.append({
        "text": text,
        "url": href
    })

links_df = pd.DataFrame(links)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

display(links_df)

,text,url
0,,https://www.mumbwacouncil.gov.zm/
1,Home,https://www.mumbwacouncil.gov.zm/
2,About,https://www.mumbwacouncil.gov.zm/#
3,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
6,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
7,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
8,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
9,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
10,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
11,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
13,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
14,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
15,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
16,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
17,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
18,Media Center,https://www.mumbwacouncil.gov.zm/#
19,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
20,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
21,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
22,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
23,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
24,Home,https://www.mumbwacouncil.gov.zm/
25,About,https://www.mumbwacouncil.gov.zm/#
26,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
29,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
30,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
31,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
32,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
33,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
34,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
36,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
37,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
38,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
39,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
40,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
41,Media Center,https://www.mumbwacouncil.gov.zm/#
42,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
43,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
44,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
45,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
46,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
47,,https://www.facebook.com/mumbwacouncil?mibextid=LQQJ4d
48,Learn More,https://greensafaris.com/ila/
49,Learn More,https://www.bing.com/travel/hotels/detail?q=Ila+Safari+Lodge+by+Green+Safaris&id=YN8203x13069317605180350720&hname=Ila+Safari+Lodge+by+Green+Safaris&loc=Mumbwa%2C+ZM&displaytext=Mumbwa%2C+ZM&lat=-14.973811&lon=25.925482&cin=2025-03-02&cout=2025-03-03&guests=2A0C&age=&hotellistid=YN8203x13069317605180350720&type=hotel&form=HTSEST&entrypoint=HTSEST
50,Learn More,https://www.bing.com/travel/hotels/detail?q=Ila+Safari+Lodge+by+Green+Safaris&id=YN8203x13069317605180350720&hname=Ila+Safari+Lodge+by+Green+Safaris&loc=Mumbwa%2C+ZM&displaytext=Mumbwa%2C+ZM&lat=-14.973811&lon=25.925482&cin=2025-03-02&cout=2025-03-03&guests=2A0C&age=&hotellistid=YN8203x13069317605180350720&type=hotel&form=HTSEST&entrypoint=HTSEST
51,Learn More,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/01/Shiwezwa-1-by-3-class-room-Block-1.jpg
52,Readmore,https://www.mumbwacouncil.gov.zm/?page_id=1479
53,View Tracker,https://www.mumbwacouncil.gov.zm/?page_id=932
54,CDF Skills Bursaries Applicants,http://www.lusangazicouncil.gov.zm/wp-content/uploads/2023/05/1647006602-1.pdf
55,Download Latest Statement,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/08/Press-Statement-CDF-1.pdf
56,View Previous Statements,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/08/CDF-STATEMENT-previous.pdf
57,Download Guidelines,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2023/08/FINAL-CDF-GUIDELINES-FEBRUARY-2022-1.pdf
58,,https://www.mumbwacouncil.gov.zm/?p=3959
59,MUMBWA TOWN COUNCIL REAFFIRMS COMMITMENT TO EXPANDING WATER ACCESS AND PROMOTING GENDER EQUALITY,https://www.mumbwacouncil.gov.zm/?p=3959
60,Read More »,https://www.mumbwacouncil.gov.zm/?p=3959
61,,https://www.mumbwacouncil.gov.zm/?p=3722
62,APPROVAL OF 2026 COUNCIL BUDGET,https://www.mumbwacouncil.gov.zm/?p=3722
63,Read More »,https://www.mumbwacouncil.gov.zm/?p=3722
64,,https://www.mumbwacouncil.gov.zm/?p=3715
65,COUNCIL CHAIRPERSON CELEBRATES NEW YEAR BABIES IN MUMBWA DISTRICT,https://www.mumbwacouncil.gov.zm/?p=3715
66,Read More »,https://www.mumbwacouncil.gov.zm/?p=3715
67,,https://www.mumbwacouncil.gov.zm/?p=3690
68,MUMBWA CENTRAL MP COMMISSIONS CHIKANDA RURAL HEALTH POST IN NALUSANGA WARD,https://www.mumbwacouncil.gov.zm/?p=3690
69,Read More »,https://www.mumbwacouncil.gov.zm/?p=3690
70,COMPLAINTS,https://www.mumbwacouncil.gov.zm/?page_id=1935
71,,https://www.facebook.com/mumbwacouncil?mibextid=LQQJ4d
72,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/
73,Local Government Service Comission,https://www.lgsc.gov.zm/
74,Ministry of Finance and National Planning,https://www.mofnp.gov.zm/
75,Ministry of Agriculture,https://www.agriculture.gov.zm/
76,National Assembly of Zambia,https://www.parliament.gov.zm/
77,Local Government Training Institute,http://www.clgti.co.zm/
78,Local Government Association of Zambia Knowledge and Learning Hub,https://www.lgazambia.org.zm/hub/about
79,SMART Zambia,https://www.szi.gov.zm/

In [5]:
tracker_url = "https://www.mumbwacouncil.gov.zm/?page_id=932"

tracker_response = requests.get(
    tracker_url,
    verify=False,
    timeout=30
)

tracker_soup = BeautifulSoup(tracker_response.text, "html.parser")

print("Status:", tracker_response.status_code)
print("Tables:", len(tracker_soup.find_all("table")))
print("Links:", len(tracker_soup.find_all("a")))

C:\Users\Moses Chaswala\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
Tables: 0
Links: 114

In [6]:
tracker_links = []

for link in tracker_soup.find_all("a", href=True):
    text = link.get_text(" ", strip=True)
    href = urljoin(tracker_url, link["href"])

    tracker_links.append({
        "text": text,
        "url": href
    })

tracker_links_df = pd.DataFrame(tracker_links)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

display(tracker_links_df)

,text,url
0,,https://www.mumbwacouncil.gov.zm/
1,Home,https://www.mumbwacouncil.gov.zm/
2,About,https://www.mumbwacouncil.gov.zm/?page_id=932#
3,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
4,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
5,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
6,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
7,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
8,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
9,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
10,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
11,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
12,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
13,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
14,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
15,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
16,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
17,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
18,Media Center,https://www.mumbwacouncil.gov.zm/?page_id=932#
19,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
20,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
21,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
22,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
23,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
24,Home,https://www.mumbwacouncil.gov.zm/
25,About,https://www.mumbwacouncil.gov.zm/?page_id=932#
26,Who we are,https://www.mumbwacouncil.gov.zm/?page_id=118
27,Senior Management,https://www.mumbwacouncil.gov.zm/?page_id=2877
28,Departments,https://www.mumbwacouncil.gov.zm/?page_id=770
29,Civic Leaders,https://www.mumbwacouncil.gov.zm/?page_id=2868
30,Council Chairman,https://www.mumbwacouncil.gov.zm/?page_id=2879
31,Nangoma,https://www.mumbwacouncil.gov.zm/?page_id=2873
32,Mumbwa Central,https://www.mumbwacouncil.gov.zm/?page_id=2871
33,Standing Committees,https://www.mumbwacouncil.gov.zm/?page_id=2881
34,Mandate,https://www.mumbwacouncil.gov.zm/?page_id=169
35,Services,https://www.mumbwacouncil.gov.zm/?page_id=792
36,CDF,https://www.mumbwacouncil.gov.zm/?page_id=2210
37,ZDSP,https://www.mumbwacouncil.gov.zm/?page_id=2247
38,Projects,https://www.mumbwacouncil.gov.zm/?page_id=2244
39,Cash for work,https://www.mumbwacouncil.gov.zm/?page_id=2883
40,News Updates,https://www.mumbwacouncil.gov.zm/?page_id=187
41,Media Center,https://www.mumbwacouncil.gov.zm/?page_id=932#
42,Publications,https://www.mumbwacouncil.gov.zm/?page_id=195
43,Photo Gallery,https://www.mumbwacouncil.gov.zm/?page_id=971
44,Application Forms,https://www.mumbwacouncil.gov.zm/?page_id=1559
45,Contact Us,https://www.mumbwacouncil.gov.zm/?page_id=275
46,FAQs,https://www.mumbwacouncil.gov.zm/?page_id=1914
47,Mumbwa District CDF Tracker,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-a9139946aa7320645aad
48,Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-f138f186aa7320647258
49,2022,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-e3349586aa7320648a36
50,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
51,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
52,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
53,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
54,2023,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-23160756aa7320648a36
55,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
56,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
57,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
58,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
59,2024,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-0cd37796aa7320648a36
60,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
61,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
62,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
63,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
64,2025,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-ba4cca96aa7320648a36
65,Community Projects,https://www.mumbwacouncil.gov.zm/?page_id=932
66,2025 Approved Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Mumbwa-Central.pdf
67,2025 Proposed Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-MUMBWA.pdf
68,Skills Development,https://www.mumbwacouncil.gov.zm/?page_id=932
69,2025 Approved CDF Skills Development Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Mumbwa-Constituency.pdf
70,Secondary Boarding Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
71,2025 Approved CDF Secondary Boarding School Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Mumbwa-Constituency.pdf
72,Empowerment Grants,https://www.mumbwacouncil.gov.zm/?page_id=932
73,2025 Approved CDF Empowerment Grants for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Grants-for-Mumbwa-Constituency.pdf
74,Empowerment Loans,https://www.mumbwacouncil.gov.zm/?page_id=932
75,Disaster,https://www.mumbwacouncil.gov.zm/?page_id=932
76,Nangoma Constituency,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-9d5391e6aa7320647258
77,2022,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-fefae236aa73206518e7
78,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
79,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
80,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
81,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
82,2023,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-29af4b16aa73206518e7
83,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
84,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
85,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
86,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
87,2024,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-1aca2996aa73206518e7
88,1st Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
89,2nd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
90,3rd Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
91,4th Quarter,https://www.mumbwacouncil.gov.zm/?page_id=932
92,2025,https://www.mumbwacouncil.gov.zm/?page_id=932#collapse-23ac2676aa73206518e7
93,Community Projects,https://www.mumbwacouncil.gov.zm/?page_id=932
94,2025 Approved Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Nangoma-Constituency.pdf
95,2025 Proposed Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-NANGOMA.pdf
96,Empowerment Grants,https://www.mumbwacouncil.gov.zm/?page_id=932
97,2025 Approved CDF Empowerment Grants for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approve-CDF-Grants-for-Nangoma-Constituency.pdf
98,Empowerment Loans,https://www.mumbwacouncil.gov.zm/?page_id=932
99,Skills Development Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
100,2025 Approved CDF Skills Development Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Nangoma-Constituency.pdf
101,Secondary Bursaries,https://www.mumbwacouncil.gov.zm/?page_id=932
102,2025 Approved CDF Secondary Boarding School Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Nangoma-Constituency.pdf
103,Disaster,https://www.mumbwacouncil.gov.zm/?page_id=932
104,COMPLAINTS,https://www.mumbwacouncil.gov.zm/?page_id=1935
105,,https://www.facebook.com/mumbwacouncil?mibextid=LQQJ4d
106,Ministry of Local Government and Rural Development,https://www.mlgrd.gov.zm/
107,Local Government Service Comission,https://www.lgsc.gov.zm/
108,Ministry of Finance and National Planning,https://www.mofnp.gov.zm/
109,Ministry of Agriculture,https://www.agriculture.gov.zm/
110,National Assembly of Zambia,https://www.parliament.gov.zm/
111,Local Government Training Institute,http://www.clgti.co.zm/
112,Local Government Association of Zambia Knowledge and Learning Hub,https://www.lgazambia.org.zm/hub/about
113,SMART Zambia,https://www.szi.gov.zm/

In [7]:
cdf_pdfs = tracker_links_df[
    tracker_links_df["url"].str.contains(
        r"\.pdf",
        case=False,
        na=False
    )
].copy()

display(cdf_pdfs)

,text,url
66,2025 Approved Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Mumbwa-Central.pdf
67,2025 Proposed Community Projects-Mumbwa Central,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-MUMBWA.pdf
69,2025 Approved CDF Skills Development Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Mumbwa-Constituency.pdf
71,2025 Approved CDF Secondary Boarding School Bursaries for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Mumbwa-Constituency.pdf
73,2025 Approved CDF Empowerment Grants for Mumbwa Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Grants-for-Mumbwa-Constituency.pdf
94,2025 Approved Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/06/2025-Approved-Community-Projects-Nangoma-Constituency.pdf
95,2025 Proposed Community Projects-Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/12/NOT-APPROVED-COMMUNITY-PROJECTS-NANGOMA.pdf
97,2025 Approved CDF Empowerment Grants for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approve-CDF-Grants-for-Nangoma-Constituency.pdf
100,2025 Approved CDF Skills Development Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Skills-Development-Bursaries-for-Nangoma-Constituency.pdf
102,2025 Approved CDF Secondary Boarding School Bursaries for Nangoma Constituency,https://www.mumbwacouncil.gov.zm/wp-content/uploads/2025/09/2025-Approved-CDF-Secondary-Boarding-School-Bursaries-for-Nangoma-Constituency.pdf

In [ ]:
mumbwa_cdf_pdfs = raw_pdf_dir
download_folder = raw_pdf_dir
os.makedirs(download_folder, exist_ok=True)

for _, row in cdf_pdfs.iterrows():

    url = row["url"]

    filename = os.path.basename(
        urlparse(url).path
    )

    filepath = os.path.join(
        download_folder,
        filename
    )

    print(f"Downloading: {filename}")

    pdf_response = requests.get(
        url,
        verify=False,
        timeout=100
    )

    print("Status:", pdf_response.status_code)

    if pdf_response.status_code == 200:
        with open(filepath, "wb") as f:
            f.write(pdf_response.content)

        print("Saved:", filepath)
    else:
        print("FAILED:", url)

    print("-" * 80)

In [ ]:
pdf_files = [
    str(pdf_file)
    for pdf_file in sorted(mumbwa_cdf_pdfs.glob("*.pdf"))
]

print("PDFs found:", len(pdf_files))

for pdf in pdf_files:
    print(os.path.basename(pdf))

In [ ]:
for pdf_file in pdf_files:

    print("\n" + "#" * 100)
    print(os.path.basename(pdf_file))
    print("#" * 100)

    with pdfplumber.open(pdf_file) as pdf:

        total_tables = 0

        for page_number, page in enumerate(pdf.pages, start=1):

            tables = page.extract_tables()

            if tables:
                print(
                    f"Page {page_number}: "
                    f"{len(tables)} table(s)"
                )

                total_tables += len(tables)

        print("TOTAL TABLES:", total_tables)

In [ ]:
first_pdf = pdf_files[0]

with pdfplumber.open(first_pdf) as pdf:

    print("File:", os.path.basename(first_pdf))
    print("Pages:", len(pdf.pages))

    for page_number, page in enumerate(pdf.pages[:3], start=1):

        text = page.extract_text()

        print("\n" + "=" * 80)
        print("PAGE", page_number)
        print("=" * 80)

        if text:
            print(text[:5000])
        else:
            print("NO TEXT FOUND")

In [ ]:
pdf1_path = raw_pdf_dir / "2025-Approve-CDF-Grants-for-Nangoma-Constituency.pdf"

In [18]:
all_tables = []

with pdfplumber.open(pdf1_path) as pdf:
    for page_num, page in enumerate(pdf.pages, start=1):
        table = page.extract_tables()[0]

        # Page 1 has title + blank row before headers
        header_row = 2 if page_num == 1 else 0
        data_start = 3 if page_num == 1 else 1

        df_page = pd.DataFrame(
            table[data_start:],
            columns=table[header_row]
        )
          
        all_tables.append(df_page)

df = pd.concat(all_tables, ignore_index=True)
df

,No.,Name of Group,Type,District,Constituency,Ward,Zone,Contact Person,Type of Venture,Sector
0,1,Intalisho Women's Club,Women,Mumbwa,Nangoma,Matala,Kantengwa,Markson Ngweluka,Gardening,Agriculture
1,2,Luyandano Multi-purpose Co-operative,Community,Mumbwa,Nangoma,Matala,Kantengwa,Prosper Malupande,Gardening,Agriculture
2,3,Kunumfwana Women's Club,Women,Mumbwa,Nangoma,Matala,Kantengwa,Rhoda Lumashi,Gardening,Agriculture
3,4,Kayuni Multi-Purpose Co-operative,Community,Mumbwa,Nangoma,Matala,Kantengwa,Chola Willard,Goat Keeping,Livestock
4,5,Faith Chibwe Club,Community,Mumbwa,Nangoma,Matala,Kantengwa,Elizabeth Musonko,Goat Keeping,Livestock
5,6,Twazuma Youth Club,Youth,Mumbwa,Nangoma,Matala,Kantengwa,Clever Kakwele,Goat Keeping,Livestock
6,7,Luili S.D.A Church Multi-purpose\nCooperative,Community,Mumbwa,Nangoma,Matala,Luili,Filner Kantini,Farming,Agriculture
7,8,Smart Climate Muliti - Purpose Cooperative,Community,Mumbwa,Nangoma,Matala,Luili,Weagan Muleka,Cattle Keeping,Agriculture
8,9,Makuyu Aboombe Youth Club,Youth,Mumbwa,Nangoma,Chisalu,Chilonga,Havi Mweemba,Goats,Livestock
9,10,Prefa Youth Club,Youth,Mumbwa,Nangoma,Chisalu,Chilonga,Fabian Mweendela,Goats,Livestock
10,11,Ing'ombe Ilede Women's Club,Women,Mumbwa,Nangoma,Chisalu,Malende,Esther Kazwiti,Gardening,Agriculture
11,12,Malende Women's Club,Women,Mumbwa,Nangoma,Chisalu,Kayanza,Trust Hamooya,Gardening,Agriculture
12,13,Shimuyandi Youth Club,Youth,Mumbwa,Nangoma,Chisalu,Chisalu,Maxwell Chisani,Goat Keeping,Livestock
13,14,Makunki Youth Club,Youth,Mumbwa,Nangoma,Chisalu,Chisalu,Malvin Chitenka,Goat Keeping,Livestock
14,15,Chisalu Selected Group,Community,Mumbwa,Nangoma,Chisalu,Chilonga,Prince Lupiya,Goat Keeping,Livestock
15,16,Tukakatile Multi Purpose Cooperative\nSociety Limited,Community,Mumbwa,Nangoma,Chisalu,Chilonga,Chaambwa Fides,Piggery,Livestock
16,17,Lwamutatama Niluna Youth Club,Youth,Mumbwa,Nangoma,Myooye,Shimunungu,Priscar Mulela,Goat Keeping,Livestock
17,18,Shichaabu Women's Club,Women,Mumbwa,Nangoma,Myooye,Nachibila,Getrude Makwala,Village Banking,Finance
18,19,Chibaba Agricultural Co-operative Society\nLimited,Community,Mumbwa,Nangoma,Myooye,Nachibila,Misheck Kalimanzila,Mobile Money,Finance
19,20,Second Time Multi-purpose Co-operative\nLimited,Community,Mumbwa,Nangoma,Myooye,Mukupi,Chester Nyirongo,Vegetable Plantat,Agriculture
20,21,Myooye Forward Club,Community,Mumbwa,Nangoma,Myooye,Myooye,Sikale Kerby,Goat Rearing,Livestock
21,22,Katuzuma Women's Club,Women,Mumbwa,Nangoma,Myooye,Nachibila,Rosemary Mazengwe,Goat Rearing,Livestock
22,23,Chinyona Balima Women's Club,Women,Mumbwa,Nangoma,Myooye,Shimumbu,Mildred Shachele,Sheep Keeping,Livestock
23,24,Myooye Multi-purpose Co-operative Society\nLimited,Community,Mumbwa,Nangoma,Myooye,Nachibila,Sostinah Jama,Goat Farming,Livestock
24,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,Manga Womens Club,Women,Mumbwa,Nangoma,Nalubanda,Chaangwe,Liwety Chizuma,Goat Keeping,Livestock
26,26,Nalubanda Central Youth,Youth,Mumbwa,Nangoma,Nalubanda,Nalubanda,Ignatius Muchabi,Saving,Finance
27,27,Nalubanda Marketeer Women's Club,Women,Mumbwa,Nangoma,Nalubanda,Nalubanda,Regina Zambwe,Village Banking,Finance
28,28,Mweempe Marketeer Women's Club,Women,Mumbwa,Nangoma,Nalubanda,Mweempe,Caroline Munamavwi,Village Banking,Finance
29,29,Lushomo Women's Club,Women,Mumbwa,Nangoma,Nalubanda,Chifwembe,Merocious Namukuzy,Goat Keeping,Livestock
30,30,Chifwembe Marketeer Women's Club,Women,Mumbwa,Nangoma,Nalubanda,Chifwembe,Chintanda Rose,Saving,Finance
31,31,Shamboze Marketeer Women's Club,Women,Mumbwa,Nangoma,Nalubanda,Shamboze,Hichintu Survoy,Saving,Finance
32,32,Myoongo Multi Purpose Co-operative\nSociety Limited,Community,Mumbwa,Nangoma,Nalubanda,Mweempe,Fredrick Moonga,Goat Keeping,Livestock
33,33,Twakalicheeledwe Women's Club,Women,Mumbwa,Nangoma,Keezwa,Luumpe,Florence Nsuma,Goat Keeping,Livestock
34,34,Shimpuwe Youth Club,Youth,Mumbwa,Nangoma,Keezwa,Luumpe,Mweemba Ashyle,Cattle Keeping,Livestock
35,35,Sun-Beam Women's Club,Women,Mumbwa,Nangoma,Keezwa,Luumpe,Mwiinga Ivy,Cattle Keeping,Livestock
36,36,Mushanzo Multpurpose Co-operative\nSociety Limited,Community,Mumbwa,Nangoma,Keezwa,Mukubu,Patricia Kalambwe,Piggery,Livestock
37,37,Chibanda Women's Club,Women,Mumbwa,Nangoma,Keezwa,Mukubu,Lizzy Chinzana,Goat Keeping,Livestock
38,38,Mpokoso Youth Co-operative,Youth,Mumbwa,Nangoma,Keezwa,Keezwa,Chamana Atrody,Goat Keeping,Livestock
39,39,Mukuyu Youth Club,Youth,Mumbwa,Nangoma,Keezwa,Keezwa,Red Mweendo,Goat Keeping,Livestock
40,40,Njanji Women's Club,Women,Mumbwa,Nangoma,Keezwa,Keezwa,Less Chepa,Goat Keeping,Livestock
41,41,Kasumpa Mango Womens Club,Women,Mumbwa,Nangoma,Choma,Nguzu,Naulube Bentia,Goat Keeping,Livestock
42,42,Munkalazya Mult-purpose Co-operative,Community,Mumbwa,Nangoma,Choma,Muchabi,Mauzwe Clement,Livestock & Poultry,Livestock
43,43,Natasha Women's Club,Women,Mumbwa,Nangoma,Choma,Nguzu,Petronella Tembo,Gardening,Agriculture
44,44,Mubanga Women's Club,Women,Mumbwa,Nangoma,Choma,Nguzu,Costance Kahyata,Gardening,Agriculture
45,45,Hamain General Dealers,Community,Mumbwa,Nangoma,Choma,Muchabi,Sondo Stain,Livestock Farming,Livestock
46,46,Katutu Youth Club,Youth,Mumbwa,Nangoma,Choma,Nguzu,Oswell Kalusa,Gardening,Agriculture
47,47,Kasamu Youth Club,Youth,Mumbwa,Nangoma,Choma,Muchabi,Kabunda Dilax,Livestock,Livestock
48,48,Kalala Women's Club,Women,Mumbwa,Nangoma,Choma,Nguzu,Muuka Malambo,Livestock,Livestock
49,49,Mulundu Multi- Purpose Cooperative,Community,Mumbwa,Nangoma,Nangoma,Kasalu,Evaristo Muchindu,Poultry,Livestock
50,50,Ndeenda Multi-purpose Co-operative\nSociety Limited,Community,Mumbwa,Nangoma,Nangoma,Nakabu,Peter Njamba,Goat Rearing,Livestock
51,51,Shoma Multi-purpose Co-operative Society\nLimited,Community,Mumbwa,Nangoma,Nangoma,Kasalu,Beene Hamududu,Agriculture,Agriculture
52,52,,Community,Mumbwa,Nangoma,Nangoma,Nabuyuni,Thomas Moonga,Goat Keeping,Livestock
53,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,,Mulinga Multi-purpose Co-operative\nSociety,,,,,,,,
55,53,Tushomeke Women's Club,Women,Mumbwa,Nangoma,Nangoma,Kasalu,Lucky Hachibola,Poultry,Livestock
56,54,Nkuyanda Nkuyanda Women's Club,Women,Mumbwa,Nangoma,Nangoma,Kasalu,Petronella Phiri,Village Banking,Finance
57,55,Yesako Women's Club,Women,Mumbwa,Nangoma,Nangoma,Nakabu,Jesika Chookwa,Goat Keeping,Livestock
58,56,Lubanze Women's Club,Women,Mumbwa,Nangoma,Nangoma,Kasalu,Fennie Chimena,Poultry,Livestock
59,57,Pompi Youth Club,Youth,Mumbwa,Nangoma,Shichanzu,Munkolo,Simon Pompi,Goat Keeping,Livestock
60,58,Chinyaka Women's Club,Women,Mumbwa,Nangoma,Shichanzu,Namabanga,Franco Nakooba,Goat Keeping,Livestock
61,59,Musweela Co-operative Club,Community,Mumbwa,Nangoma,Shichanzu,Malima,Chrispin Mwiya Kafa,Piggery,Livestock
62,60,Coolwe Kubantu Youth Club,Youth,Mumbwa,Nangoma,Shichanzu,Namabanga,Shintu Mainza,Goat Production,Livestock
63,61,Malima Youth Club,Youth,Mumbwa,Nangoma,Shichanzu,Choombwa,Fostina Milumbe,Goats,Livestock
64,62,Sichanzu Eden Club,Community,Mumbwa,Nangoma,Shichanzu,Choombwa,Trywell Mwangu,Goat Keeping,Livestock
65,63,Shabwando Youth Club,Youth,Mumbwa,Nangoma,Shichanzu,Malima,Argus Maingala,Goat Keeping,Livestock
66,64,Kapulanga Women's Club,Women,Mumbwa,Nangoma,Shichanzu,Malima,Bridget Muswela,Pig Production,Livestock
67,65,Butotelo Women's Club,Women,Mumbwa,Nangoma,Nakasaka,Torno,Sylvia Mulenga,Poultry,Livestock
68,66,Nakasaka Young Youth Club,Youth,Mumbwa,Nangoma,Nakasaka,Muyoba,Grace Gomani,Goat Keeping,Livestock
69,67,Mumba Chiefdom Bee Keepers Association,Community,Mumbwa,Nangoma,Nakasaka,Mimwene,Kabika Kabika,Bee Keeping,Agriculture
70,68,Chilundu Mult-purpose Co-operative\nSociety Limited,Community,Mumbwa,Nangoma,Nakasaka,Mimwene,Jackson Chilundu,Goat Keeping,Livestock
71,69,Lushomo Club,Community,Mumbwa,Nangoma,Nakasaka,Torno,Haundu Elizabeth,Poultry,Livestock
72,70,Lwanguluko Youth Club,Youth,Mumbwa,Nangoma,Nakasaka,Muyoba,Cathrine Mapili,Poultry,Livestock
73,71,Mwenzyachimbole Women's Club,Women,Mumbwa,Nangoma,Nakasaka,Muyoba,Annah Manguba,Goat Keeping,Livestock
74,72,Tuzubuke Club,Youth,Mumbwa,Nangoma,Nakasaka,Chiwena,Mumpande Clement,Poultry,Livestock
75,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pdf2_path = raw_pdf_dir / "2025-Approved-CDF-Grants-for-Mumbwa-Constituency.pdf"

In [ ]:
all_tables = []

with pdfplumber.open(pdf2_path) as pdf:
    for page_num, page in enumerate(pdf.pages, start=1):
        table = page.extract_tables()[0]

        # Page 1 has title + blank row before headers
        header_row = 2 if page_num == 1 else 0
        data_start = 3 if page_num == 1 else 1

        df_page = pd.DataFrame(
            table[data_start:],
            columns=table[header_row]
        )
          
        all_tables.append(df_page)

df2 = pd.concat(all_tables, ignore_index=True)
df2