In [735]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [736]:
PROJECTS_URL = "https://www.mumbwacouncil.gov.zm/?page_id=2247"

print(PROJECTS_URL)

https://www.mumbwacouncil.gov.zm/?page_id=2247

In [737]:
import requests

response = requests.get(
    PROJECTS_URL,
    timeout=100,
    verify=False
)

print("Status code:", response.status_code)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.mumbwacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status code: 200

In [738]:
soup = BeautifulSoup(response.text, "html.parser")

print("Webpage parsed successfully.")
print("Page title:", soup.title.get_text(strip=True))

Webpage parsed successfully.
Page title: ZDSP – Mumbwa Town Council

In [739]:
page_text = soup.get_text("\n", strip=True)

print(page_text[:5000])

ZDSP – Mumbwa Town Council
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Menu
Home
About
Open menu
Who we are
Senior Management
Departments
Civic Leaders
Council Chairman
Nangoma
Mumbwa Central
Standing Committees
Mandate
Services
CDF
ZDSP
Projects
Open menu
Cash for work
News Updates
Media Center
Open menu
Publications
Photo Gallery
Application Forms
Contact Us
FAQs
Search
ZAMBIA DEVOLUTION SUPPORT PROGRAM
ABOUT ZDSP
The Zambia Devolution Support Programme (ZDSP) is a USD 210 million hybrid program designed to accelerate the Government of the Republic of Zambia’s Decentralization agenda. The program aims to strengthen both the financial and institutional capacities of Local Authorities (LAs) across the country, enabling them to effectively deliver public services, promote local development, and enhance citizen participation in governance.

Launched in alignment with Zambia's Decentralization Policy, the ZDSP provides targeted support to local governments by incentivizing performance and accountability. Over a five-year implementation period, eligible Local Authorities receive additional performance-based grants, which are meant to supplement existing resources and promote effective, efficient, and transparent service delivery.
Learn more
PROJECTS
ZDSP – Mumbwa Bus Station
The Zambia Devolution Support Programme (ZDSP) is funding the construction of a new Mumbwa District Bus Station, aimed at improving transport efficiency, safety, and revenue collection for the Council. The project will enhance passenger movement, organize traffic flow, and create better trading spaces for local vendors.

Project Location:
Latitude: 14.990618°
Longitude: 27.051910°
Previous
Next
View Coordinates
Contact Information
Mumbwa Town Council
Mumbwa District
Central Province
Tel: 260211800074
P.O. Box: 830001
Email; councilmumbwa@yahoo.com
COMPLAINTS
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
Local Government Association of Zambia Knowledge and Learning Hub
SMART Zambia
©2025. SMART Zambia Institute. All Rights Reserved.

In [740]:
headings = soup.find_all(["h1", "h2", "h3", "h4", "h5", "h6"])

for heading in headings:
    text = heading.get_text(" ", strip=True)

    if "Bus Station" in text:
        print("Project name:", text)

Project name: ZDSP – Mumbwa Bus Station

In [741]:
for paragraph in soup.find_all("p"):
    text = paragraph.get_text(" ", strip=True)

    if "Zambia Devolution Support Programme" in text:
        print(text)

The Zambia Devolution Support Programme (ZDSP) is a USD 210 million hybrid program designed to accelerate the Government of the Republic of Zambia’s Decentralization agenda. The program aims to strengthen both the financial and institutional capacities of Local Authorities (LAs) across the country, enabling them to effectively deliver public services, promote local development, and enhance citizen participation in governance.

Launched in alignment with Zambia's Decentralization Policy, the ZDSP provides targeted support to local governments by incentivizing performance and accountability. Over a five-year implementation period, eligible Local Authorities receive additional performance-based grants, which are meant to supplement existing resources and promote effective, efficient, and transparent service delivery.
The Zambia Devolution Support Programme (ZDSP) is funding the construction of a new Mumbwa District Bus Station, aimed at improving transport efficiency, safety, and revenue collection for the Council. The project will enhance passenger movement, organize traffic flow, and create better trading spaces for local vendors.

Project Location:
Latitude: 14.990618°
Longitude: 27.051910°

In [742]:
latitude_match = re.search(
    r"Latitude:\s*([0-9.]+)",
    page_text,
    re.IGNORECASE
)

longitude_match = re.search(
    r"Longitude:\s*([0-9.]+)",
    page_text,
    re.IGNORECASE
)

latitude = latitude_match.group(1) if latitude_match else None
longitude = longitude_match.group(1) if longitude_match else None

print("Latitude:", latitude)
print("Longitude:", longitude)

Latitude: 14.990618
Longitude: 27.051910

In [743]:
project_record = {
    "project_name": "ZDSP – Mumbwa Bus Station",
    "funding_programme": "Zambia Devolution Support Programme (ZDSP)",
    "project_description": (
        "Construction of a new Mumbwa District Bus Station "
        "to improve transport efficiency, safety and revenue collection."
    ),
    "community_benefit": (
        "Improved passenger movement, organized traffic flow "
        "and better trading spaces for local vendors."
    ),
    "latitude": latitude,
    "longitude": longitude,
    "source": PROJECTS_URL
}

project_record

{'project_name': 'ZDSP – Mumbwa Bus Station',
 'funding_programme': 'Zambia Devolution Support Programme (ZDSP)',
 'project_description': 'Construction of a new Mumbwa District Bus Station to improve transport efficiency, safety and revenue collection.',
 'community_benefit': 'Improved passenger movement, organized traffic flow and better trading spaces for local vendors.',
 'latitude': '14.990618',
 'longitude': '27.051910',
 'source': 'https://www.mumbwacouncil.gov.zm/?page_id=2247'}

In [744]:
projects_df = pd.DataFrame([project_record])

display(projects_df)

,project_name,funding_programme,project_description,community_benefit,latitude,longitude,source
0,ZDSP – Mumbwa Bus Station,Zambia Devolution Support Programme (ZDSP),Construction of a new Mumbwa District Bus Stat...,"Improved passenger movement, organized traffic...",14.990618,27.051910,https://www.mumbwacouncil.gov.zm/?page_id=2247

In [745]:
website_raw_folder = Path("../output/raw")
website_raw_folder.mkdir(parents=True, exist_ok=True)

website_raw_path = (
    website_raw_folder /
    "db-unza26-csc4792-mumbwa_strategic_community_projects_website_raw.csv"
)

projects_df.to_csv(
    website_raw_path,
    sep="|",
    index=False
)

print("Raw website project data saved successfully!")
print("Saved at:", website_raw_path.resolve())
print("File exists:", website_raw_path.exists())

NameError: name 'Path' is not defined

In [ ]:
from pathlib import Path

In [ ]:
from pathlib import Path

saved_file = Path("../output/raw/db-unza26-csc4792-mumbwa_strategic_community_projects_website_raw.csv").resolve()

print("Full file location:")
print(saved_file)

print("\nDoes the file exist?")
print(saved_file.exists())

In [ ]:
from pathlib import Path

print("Notebook working directory:")
print(Path.cwd())

In [ ]:
import pandas as pd

project_sources = [
    {
        "source_name": "Council Projects / ZDSP",
        "source_type": "Webpage",
        "url": "https://www.mumbwacouncil.gov.zm/?page_id=2247",
        "description": "Council development projects, including the ZDSP Mumbwa Bus Station"
    },
    {
        "source_name": "Cash for Work",
        "source_type": "Webpage",
        "url": "https://www.mumbwacouncil.gov.zm/?page_id=2883",
        "description": "Community employment and labour-based development programme"
    },
    {
        "source_name": "CDF Tracker",
        "source_type": "Webpage",
        "url": "https://www.mumbwacouncil.gov.zm/?page_id=932",
        "description": "Approved and proposed CDF community projects"
    },
    {
        "source_name": "2024 Approved CDF Community Projects",
        "source_type": "PDF",
        "url": "https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/09/2024-CDF-COMMUNITY-PROJECTS-AS-AT-31ST-AUGUST-2024.pdf",
        "description": "Approved community projects with ward, location, cost, contractor and status"
    },
    {
        "source_name": "2024 Proposed CDF Projects",
        "source_type": "PDF",
        "url": "https://www.mumbwacouncil.gov.zm/wp-content/uploads/2024/10/2024-CDF-Proposed-Projects-All-Components-Mumbwa-and-Nangoma-Constituencies.pdf",
        "description": "Proposed projects with location, estimates, proposed amounts and year funded"
    }
]

project_sources_df = pd.DataFrame(project_sources)

display(project_sources_df)

In [ ]:
from pathlib import Path

raw_folder = Path("../output/raw")
raw_folder.mkdir(parents=True, exist_ok=True)

source_catalogue_path = raw_folder / "strategic_project_source_catalogue.csv"

project_sources_df.to_csv(
    source_catalogue_path,
    sep="|",
    index=False
)

print("Source catalogue saved successfully!")
print(source_catalogue_path.resolve())
print("File exists:", source_catalogue_path.exists())

In [ ]:
import requests
from bs4 import BeautifulSoup

projects_url = "https://www.mumbwacouncil.gov.zm/?page_id=2247"

response = requests.get(
    projects_url,
    timeout=100,
    verify=False
)

print("Status code:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

print("Page title:", soup.title.get_text(strip=True))

In [ ]:
headings = soup.find_all(["h1", "h2", "h3", "h4", "h5", "h6"])

for heading in headings:
    text = heading.get_text(" ", strip=True)

    if text:
        print(text)

In [ ]:
links = soup.find_all("a", href=True)

for link in links:
    text = link.get_text(" ", strip=True)
    url = link["href"]

    if text or url:
        print("TEXT:", text)
        print("URL:", url)
        print("-" * 60)

In [ ]:
cash_url = "https://www.mumbwacouncil.gov.zm/?page_id=2883"

cash_response = requests.get(
    cash_url,
    timeout=30,
    verify=False
)

print("Status code:", cash_response.status_code)

cash_soup = BeautifulSoup(
    cash_response.text,
    "html.parser"
)

cash_text = cash_soup.get_text(
    "\n",
    strip=True
)

print(cash_text[:5000])

In [ ]:
import pandas as pd
from google.colab import files
from IPython.display import display

In [ ]:
columns = [
    "project_id", "project_name", "category", "phase", "start_year",
    "end_year", "priority", "status_2023", "location", "description",
    "estimated_unit_cost_zmw", "estimated_total_cost_zmw",
    "available_quantity_2023", "proposed_quantity", "quantity_shortfall",
    "verification_status",
]

rows = [
    ["MTC-DS-001", "Site identification", "Planning", "Short term", 0, 10, "Immediate", "Proposed", "Shilimatanga Village, Chief Mumba", "Identify and confirm the landfill site.", None, None, None, None, None, "Narrative-confirmed"],
    ["MTC-DS-002", "Documentation and regulatory approvals", "Planning", "Short term", 0, 10, "Immediate", "Proposed", "Mumbwa District", "Prepare relevant documentation and obtain approvals.", None, None, None, None, None, "Narrative-confirmed"],
    ["MTC-DS-003", "Dump-site boundary fencing", "Civil works", "Short term", 0, 10, "Immediate", "Proposed", "Kamilambo Road dump site", "Fence the facility to control access and encroachment.", 300000, 300000, 0, 1, 1, "Cost-needs-source-check"],
    ["MTC-DS-004", "Waste segregation bays", "Civil works", "Short term", 0, 10, "Immediate", "Proposed", "Primary and secondary collection points", "Construct segregation sections for controlled separation at source.", 100000, 200000, 2, 4, 2, "Cost-needs-source-check"],
    ["MTC-DS-005", "TLB/front-end loader/excavator", "Equipment", "Short term", 0, 10, "Immediate", "Not available", "Dump site", "Acquire earth-moving equipment for landfill operations.", 2000000, 2000000, 0, 1, 1, "Cost-needs-source-check"],
    ["MTC-DS-006", "Compactor/roller", "Equipment", "Short term", 0, 10, "Immediate", "Not available", "Dump site", "Acquire equipment to compact deposited waste.", 3000000, 3000000, 0, 1, 1, "Cost-needs-source-check"],
    ["MTC-DS-007", "Controlled spreading, compacting and soil cover", "Operations", "Short term", 0, 10, "Immediate", "Proposed", "Active dump area", "Spread, compact and cover waste with a thin soil layer.", None, None, None, None, None, "Narrative-confirmed"],
    ["MTC-DS-008", "Engineered landfill cells", "Civil works", "Medium term", 10, 30, "Planned", "Proposed", "Dump site", "Clear land and excavate approximately 100 m by 100 m cells.", None, None, None, 10, None, "Narrative-confirmed"],
    ["MTC-DS-009", "Leachate ponds", "Environmental protection", "Medium term", 10, 30, "Planned", "Proposed", "Dump site", "Collect and store leachate to reduce contamination.", None, None, None, None, None, "Narrative-confirmed"],
    ["MTC-DS-010", "Landfill gas breather-pipe network", "Environmental protection", "Medium term", 10, 30, "Planned", "Proposed", "Engineered landfill cells", "Install UPVC breather pipes to mitigate gas hazards.", None, None, None, None, None, "Narrative-confirmed"],
    ["MTC-DS-011", "Guard house", "Buildings", "Medium term", 10, 30, "Planned", "Proposed", "Facility entrance", "Provide security and regulate entry and exit.", None, None, None, 1, None, "Narrative-confirmed"],
    ["MTC-DS-012", "Revenue office", "Buildings", "Medium term", 10, 30, "Planned", "Proposed", "Facility entrance", "Collect authorized facility fees.", None, None, None, 1, None, "Narrative-confirmed"],
    ["MTC-DS-013", "Ablution block", "Buildings", "Medium term", 10, 30, "Planned", "Proposed", "Dump site", "Provide sanitation for staff and visitors.", None, None, None, 1, None, "Narrative-confirmed"],
    ["MTC-DS-014", "Water-quality monitoring boreholes", "Environmental monitoring", "Medium term", 10, 30, "Planned", "Proposed", "Boreholes A and B", "Monitor surface-water and groundwater contamination.", None, None, None, 2, None, "Narrative-confirmed"],
    ["MTC-DS-015", "Landfill decommissioning and land reclamation", "Closure and rehabilitation", "Long term", 30, 50, "Future", "Proposed", "Entire facility", "Decommission, reclaim and revegetate the filled facility.", None, None, None, None, None, "Narrative-confirmed"],
    ["MTC-DS-016", "Waste-management staff attachment", "Capacity building", "Short term", 0, 10, "Recommended", "Proposed", "Successful council or institution", "Sponsor staff for a one-to-three-month attachment.", None, None, None, None, None, "Narrative-confirmed"],
    ["MTC-DS-017", "Waste-management short courses and refresher training", "Capacity building", "Short term", 0, 10, "Recommended", "Proposed", "Reputable training institution", "Provide training in modern waste-management methods.", None, None, None, None, None, "Narrative-confirmed"],
]

In [ ]:
df = pd.DataFrame(rows, columns=columns)

# Add the source information to every record.
df.insert(1, "council", "Mumbwa Town Council")
df["currency"] = "ZMW"
df["source_document"] = "Mumbwa Town Council Dump Site Profile – 2023"
df["source_year"] = 2023

# Keep whole numbers while allowing blank values.
numeric_columns = [
    "start_year", "end_year", "estimated_unit_cost_zmw",
    "estimated_total_cost_zmw", "available_quantity_2023",
    "proposed_quantity", "quantity_shortfall", "source_year",
]
for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce").astype("Int64")

# Remove spaces accidentally typed before or after text.
for column in df.select_dtypes(include="object").columns:
    df[column] = df[column].str.strip()

display(df)

In [ ]:
assert len(df) == 17, "The table should contain 17 projects."
assert df["project_id"].notna().all(), "A project ID is missing."
assert df["project_id"].is_unique, "A project ID is duplicated."
assert df["project_name"].fillna("").str.strip().ne("").all(), "A project name is missing."
assert df["phase"].isin(["Short term", "Medium term", "Long term"]).all(), "A phase is invalid."
assert (df["start_year"] <= df["end_year"]).all(), "A start year is after its end year."

quantity_rows = df.dropna(subset=[
    "available_quantity_2023", "proposed_quantity", "quantity_shortfall"
])
assert (
    quantity_rows["proposed_quantity"]
    - quantity_rows["available_quantity_2023"]
    == quantity_rows["quantity_shortfall"]
).all(), "A quantity shortfall is incorrect."

print("All checks passed.")

In [ ]:
display(df.groupby(["phase", "category"]).size().rename("project_count").reset_index())

display(
    df.dropna(subset=["estimated_total_cost_zmw"])
      .groupby("phase", as_index=False)["estimated_total_cost_zmw"]
      .sum()
)

In [ ]:
file_name = " db-unza26-csc4792-mumbwa_council_projects_2023.csv"
df.to_csv(file_name, index=False, encoding="utf-8-sig")

# Check that Colab can read the saved file before downloading it.
saved_df = pd.read_csv(file_name)
assert saved_df.shape == df.shape

files.download(file_name)

In [ ]:
!pip install -q camelot-py[cv]
!pip install -q pdfplumber
!pip install -q pandas
!pip install -q pypdf

In [ ]:
import os
import re
import pandas as pd
import camelot
import pdfplumber

from google.colab import files
from IPython.display import display

In [ ]:
uploaded = files.upload()
PDF_PATH = "mumbwa_idp.pdf"

print("PDF:", PDF_PATH)
print("Exists:", os.path.exists(PDF_PATH))

In [ ]:
def clean_cell(value):
    if pd.isna(value):
        return ""

    value = str(value)
    value = value.replace("\n", " ")

    value = re.sub(r"\s+", " ", value)

    return value.strip()
def clean_dataframe(df):
    df = df.copy()

    # Clean every cell
    df = df.map(clean_cell)

    # Remove completely empty rows
    df = df.replace("", pd.NA)
    df = df.dropna(how="all")

    # Remove completely empty columns
    df = df.dropna(axis=1, how="all")

    # Convert NaN back to empty strings
    df = df.fillna("")

    # Reset index
    df = df.reset_index(drop=True)

    return df

In [ ]:
def to_snake_case(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = re.sub(r"_+", "_", text)
    return text.strip("_")
print(
    to_snake_case(
        "Status of Implementation of Existing Plans and Strategies"
    )
)

In [ ]:
def save_table_csv(df, table_name):
    snake_name = to_snake_case(table_name)

    filename = f"db-unza26-csc4792_{snake_name}.csv"

    df.to_csv(
        filename,
        index=False,
        encoding="utf-8-sig"
    )

    print(f"Saved: {filename}")
    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")

    return filename

In [ ]:
def extract_pdf_tables(pdf_path, pages):
    print(f"Extracting PDF page(s): {pages}")

    tables = camelot.read_pdf(
        pdf_path,
        pages=str(pages),
        flavor="lattice"
    )

    print("Tables detected:", tables.n)

    return tables

In [ ]:
def inspect_tables(tables):
    for i, table in enumerate(tables):
        print("\n" + "=" * 70)
        print(f"Detected table index: {i}")
        print("Shape:", table.df.shape)
        print("=" * 70)

        display(table.df.head(10))

In [ ]:
tables = extract_pdf_tables(
    PDF_PATH,
    "50-51"
)

inspect_tables(tables)

In [ ]:
table5_part1 = clean_dataframe(tables[0].df)
table5_part2 = clean_dataframe(tables[1].df)

display(table5_part1.head())
display(table5_part2.head())

In [ ]:
headers = table5_part1.iloc[0].tolist()

table5_part1 = table5_part1.iloc[1:].copy()
table5_part1.columns = headers

In [ ]:
table5_part2.columns = headers

In [ ]:
table5_df = pd.concat(
    [table5_part1, table5_part2],
    ignore_index=True
)

display(table5_df)

In [ ]:
table5_file = save_table_csv(
    table5_df,
    "status_of_implementation_of_existing_plans_and_strategies"
)

In [ ]:
tables = extract_pdf_tables(
    PDF_PATH,
    "56"
)

inspect_tables(tables)

In [ ]:
table8_df = clean_dataframe(
    tables[0].df
)

display(table8_df)
table8_df.columns = table8_df.iloc[0]
table8_df = table8_df.iloc[1:].reset_index(drop=True)
save_table_csv(
    table8_df,
    "number_of_schools_in_mumbwa_district"
)

In [ ]:
tables = extract_pdf_tables(
    PDF_PATH,
    "57"
)

inspect_tables(tables)

In [ ]:
table10_df = clean_dataframe(
    tables[0].df
)

display(table10_df)
table10_df.columns = table10_df.iloc[0]
table10_df = table10_df.iloc[1:].reset_index(drop=True)
save_table_csv(
    table10_df,
    "number_of_facilities_connected_to_electrical_grid_and_solar_power"
)

In [ ]:
table11_df = clean_dataframe(
    tables[1].df
)

display(table11_df)
table11_df.columns = table11_df.iloc[0]
table11_df = table11_df.iloc[1:].reset_index(drop=True)
save_table_csv(
    table11_df,
    "number_of_available_classrooms_and_toilets"
)

In [ ]:
tables = extract_pdf_tables(
    PDF_PATH,
    "60-61"
)

inspect_tables(tables)

In [ ]:
parts = []

for table in tables:
    temp = clean_dataframe(table.df)
    parts.append(temp)

In [ ]:
for part in parts:
    display(part)

In [ ]:
table11_df = clean_dataframe(
    tables[1].df
)

display(table11_df)
table11_df.columns = table11_df.iloc[0]
table11_df = table11_df.iloc[1:].reset_index(drop=True)
save_table_csv(
    table11_df,
    "future_demand_for_services"
)

In [ ]:
tables = extract_pdf_tables(
    PDF_PATH,
    "67"
)

inspect_tables(tables)

In [ ]:
table14_df = clean_dataframe(
    tables[0].df
)

display(table14_df)

In [ ]:
table14_df.columns = table14_df.iloc[0]
table14_df = table14_df.iloc[1:].reset_index(drop=True)

In [ ]:
save_table_csv(
    table14_df,
    "Availability_of_water_supply_services"
)

In [ ]:
tables = extract_pdf_tables(
    PDF_PATH,
    "67"
)

inspect_tables(tables)

In [ ]:
table16_df = clean_dataframe(
    tables[0].df
)

display(table16_df)

In [ ]:
table16_df.columns = table16_df.iloc[0]
table16_df = table16_df.iloc[1:].reset_index(drop=True)

In [ ]:
save_table_csv(
    table16_df,
    "production_trend_in_mumbwa"
)

In [ ]:
save_table_csv(
    table8_df,
    "number_of_schools_in_mumbwa_district"
)

In [ ]:
crop_names = [
    "Maize",
    "Cotton",
    "Soya beans",
    "Sunflower"
]

rows = []

current_crop = None

for _, row in table16_raw.iterrows():

    first_value = str(
        row["crop_or_measure"]
    ).strip()

    if first_value in crop_names:
        current_crop = first_value
        continue

    if current_crop is not None:

        rows.append({
            "crop": current_crop,
            "measure": first_value,
            "2018_2019": row["2018_2019"],
            "2019_2020": row["2019_2020"],
            "2020_2021": row["2020_2021"],
            "2021_2022": row["2021_2022"],
            "2022_2023": row["2022_2023"]
        })


table16_df = pd.DataFrame(
    rows
)

display(table16_df)

In [ ]:
year_columns = [
    "2018_2019",
    "2019_2020",
    "2020_2021",
    "2021_2022",
    "2022_2023"
]

for column in year_columns:

    table16_df[column] = (
        table16_df[column]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    table16_df[column] = pd.to_numeric(
        table16_df[column],
        errors="coerce"
    )

In [ ]:
print(
    table16_df.dtypes
)

display(table16_df)

In [ ]:
table16_file = save_csv(
    table16_df,
    "db-unza26-csc4792_production_trend_in_mumbwa_district.csv"
)

In [ ]:
save_table_csv(
    table16_df,
    "db-unza26-csc4792_production_trend_in_mumbwa_district.csv"
)

In [ ]:
tables_17 = camelot.read_pdf(
    PDF_PATH,
    pages="75-76",
    flavor="lattice"
)

print(
    "Table sections detected:",
    tables_17.n
)

for i, table in enumerate(tables_17):

    print(
        "\nSection:",
        i
    )

    print(
        "Shape:",
        table.df.shape
    )

    display(table.df)

In [ ]:
table17_part1 = clean_dataframe(
    tables_17[0].df
)

table17_part2 = clean_dataframe(
    tables_17[1].df
)

print("PART 1")
display(table17_part1)

print("PART 2")
display(table17_part2)

In [ ]:
table17_columns = [
    "block",
    "camp",
    "number_of_staff",
    "standard_farmers_per_staff",
    "total_number_of_farmers",
    "farmers_without_staff_service",
    "percent_farmers_without_staff_service"
]

In [ ]:
table17_part1.columns = (
    table17_columns
)

# Remove repeated original header
header_text = str(
    table17_part1.iloc[0].tolist()
).lower()

if (
    "block" in header_text
    and "camp" in header_text
):

    table17_part1 = (
        table17_part1
        .iloc[1:]
        .reset_index(drop=True)
    )

display(table17_part1)

In [ ]:
print("Part 1 shape:", table17_part1.shape)
print("Part 2 shape:", table17_part2.shape)

print("\nPart 1 columns:")
print(table17_part1.columns)

print("\nPart 2 columns:")
print(table17_part2.columns)

display(table17_part2)

In [ ]:
table17_part2.columns = [
    "camp",
    "number_of_staff",
    "standard_farmers_per_staff",
    "total_number_of_farmers",
    "farmers_without_staff_service",
    "percent_farmers_without_staff_service"
]

display(table17_part2)

In [ ]:
table17_part2.insert(
    0,
    "block",
    ""
)

display(table17_part2)

In [ ]:
print(table17_part2.shape)
print(table17_part2.columns)

In [ ]:
table17_df = pd.concat(
    [
        table17_part1,
        table17_part2
    ],
    ignore_index=True
)

display(table17_df)

In [ ]:
table17_df = pd.concat(
    [
        table17_part1,
        table17_part2
    ],
    ignore_index=True
)

display(table17_df)

In [ ]:
table17_df["block"] = (
    table17_df["block"]
    .replace("", pd.NA)
    .ffill()
)

In [ ]:
display(
    table17_df[
        [
            "block",
            "camp",
            "number_of_staff",
            "standard_farmers_per_staff",
            "total_number_of_farmers",
            "farmers_without_staff_service",
            "percent_farmers_without_staff_service"
        ]
    ]
)

In [ ]:
save_table_csv(
    table17_df,
    "db-unza26-csc4792_production_trend_in_mumbwa_district.csv"
)

In [ ]:
tables_18 = camelot.read_pdf(
    PDF_PATH,
    pages="78-79",
    flavor="lattice"
)

print("Sections detected:", tables_18.n)

for i, table in enumerate(tables_18):
    print("\nSECTION:", i)
    print("Shape:", table.df.shape)
    display(table.df)

In [ ]:
table18_part1 = clean_dataframe(
    tables_18[0].df
)

table18_part2 = clean_dataframe(
    tables_18[1].df
)

print("PART 1")
display(table18_part1)

print("PART 2")
display(table18_part2)

In [ ]:
table18_columns = [
    "priority_area",
    "baseline",
    "target"
]

table18_part1.columns = table18_columns

# Remove header row if Camelot included it as data
first_row = " ".join(
    table18_part1.iloc[0].astype(str).tolist()
).lower()

if "priority area" in first_row:
    table18_part1 = (
        table18_part1
        .iloc[1:]
        .reset_index(drop=True)
    )

display(table18_part1)

In [ ]:
print("Part 2 shape:", table18_part2.shape)
display(table18_part2)

In [ ]:
table18_part2.columns = table18_columns

In [ ]:
if table18_part2.shape[1] == 2:

    table18_part2.columns = [
        "baseline",
        "target"
    ]

    table18_part2.insert(
        0,
        "priority_area",
        ""
    )

elif table18_part2.shape[1] == 3:

    table18_part2.columns = table18_columns

In [746]:
display(table18_part2)

,priority_area,baseline,target
0,,1,Establish 1 Permanent Biosecurity Checkpoints ...
1,Coordinated marketing of livestock products,0,Construction of 1 Slaughter slab and livestock...
2,Entrepreneurial skills training in fish and li...,0,Conduct Entrepreneurial trainings in fish and ...

In [747]:
table18_df = pd.concat(
    [
        table18_part1,
        table18_part2
    ],
    ignore_index=True
)

display(table18_df)

,priority_area,baseline,target
0,Effective Survelaince and Law Enforcement patr...,25,Increase effeictve Surveillance and Law Enforc...
1,Staff accomodation at district and camp level,10,Rehabilitate 5 staff houses Construct 12 house...
2,Fingerling production,0,Establishment of fish hatchery that will see t...
3,Transport system for extension services,1,Procurement of 2 motor vehicles
4,,13,Procurement of 40 motor bikes
5,Animal health and livestock production extensi...,8,30 more extension officers required
6,Animal disease control and livestock infrastru...,11,10 dip tanks to be completed and operationalised
7,,0,"Establishment of 3 AI Centers in Keezwa, Mucha..."
8,,0,Construction of 1 District Laboratory
9,,1,Establish 1 Permanent Biosecurity Checkpoints ...
10,Coordinated marketing of livestock products,0,Construction of 1 Slaughter slab and livestock...
11,Entrepreneurial skills training in fish and li...,0,Conduct Entrepreneurial trainings in fish and ...

In [748]:
table18_df["priority_area"] = (
    table18_df["priority_area"]
    .replace("", pd.NA)
    .ffill()
)
display(table18_df)

,priority_area,baseline,target
0,Effective Survelaince and Law Enforcement patr...,25,Increase effeictve Surveillance and Law Enforc...
1,Staff accomodation at district and camp level,10,Rehabilitate 5 staff houses Construct 12 house...
2,Fingerling production,0,Establishment of fish hatchery that will see t...
3,Transport system for extension services,1,Procurement of 2 motor vehicles
4,Transport system for extension services,13,Procurement of 40 motor bikes
5,Animal health and livestock production extensi...,8,30 more extension officers required
6,Animal disease control and livestock infrastru...,11,10 dip tanks to be completed and operationalised
7,Animal disease control and livestock infrastru...,0,"Establishment of 3 AI Centers in Keezwa, Mucha..."
8,Animal disease control and livestock infrastru...,0,Construction of 1 District Laboratory
9,Animal disease control and livestock infrastru...,1,Establish 1 Permanent Biosecurity Checkpoints ...
10,Coordinated marketing of livestock products,0,Construction of 1 Slaughter slab and livestock...
11,Entrepreneurial skills training in fish and li...,0,Conduct Entrepreneurial trainings in fish and ...

In [749]:
table18_df["baseline"] = (
    table18_df["baseline"]
    .astype(str)
    .str.strip()
)

table18_df["baseline"] = pd.to_numeric(
    table18_df["baseline"],
    errors="coerce"
)
print(table18_df.dtypes)
display(table18_df)

priority_area    object
baseline          int64
target           object
dtype: object

,priority_area,baseline,target
0,Effective Survelaince and Law Enforcement patr...,25,Increase effeictve Surveillance and Law Enforc...
1,Staff accomodation at district and camp level,10,Rehabilitate 5 staff houses Construct 12 house...
2,Fingerling production,0,Establishment of fish hatchery that will see t...
3,Transport system for extension services,1,Procurement of 2 motor vehicles
4,Transport system for extension services,13,Procurement of 40 motor bikes
5,Animal health and livestock production extensi...,8,30 more extension officers required
6,Animal disease control and livestock infrastru...,11,10 dip tanks to be completed and operationalised
7,Animal disease control and livestock infrastru...,0,"Establishment of 3 AI Centers in Keezwa, Mucha..."
8,Animal disease control and livestock infrastru...,0,Construction of 1 District Laboratory
9,Animal disease control and livestock infrastru...,1,Establish 1 Permanent Biosecurity Checkpoints ...
10,Coordinated marketing of livestock products,0,Construction of 1 Slaughter slab and livestock...
11,Entrepreneurial skills training in fish and li...,0,Conduct Entrepreneurial trainings in fish and ...

In [750]:
save_table_csv(
    table18_df,
    "db-unza26-csc4792_key_implementation_sector_priorities.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_key_implementation_sector_priorities_csv.csv
Rows: 12
Columns: 3

'db-unza26-csc4792_db_unza26_csc4792_key_implementation_sector_priorities_csv.csv'

In [751]:
tables_19 = camelot.read_pdf(
    PDF_PATH,
    pages="88",
    flavor="lattice"
)

print("Tables detected:", tables_19.n)

for i, table in enumerate(tables_19):
    print("\nIndex:", i)
    print("Shape:", table.df.shape)
    display(table.df)

Tables detected: 1

Index: 0
Shape: (9, 4)

     0             1                   2          3
0  S/N  Name of CFMG               Place   Hectares
1    1      Kalunzyu     Chief Chibulama      4,900
2    2  Kabulwebulwe  Chief Kabulwebulwe        500
3    3        Kaindu        Chief Kaindu     48,436
4    4      Namwanja     Chief Chibuluma   6,375.12
5    5         Chipa     Chief Chibuluma    8.234.6
6    6         Moono         Chief Moono     15,735
7    7    Shakumbila    Chief Shakumbila  12,983.99
8    8     Mulendema     Chief Mulendema   16,469.6

In [752]:
tables_19 = camelot.read_pdf(
    PDF_PATH,
    pages="88",
    flavor="lattice"
)

print("Tables detected:", tables_19.n)

for i, table in enumerate(tables_19):
    print("\nIndex:", i)
    print("Shape:", table.df.shape)
    display(table.df)

Tables detected: 1

Index: 0
Shape: (9, 4)

     0             1                   2          3
0  S/N  Name of CFMG               Place   Hectares
1    1      Kalunzyu     Chief Chibulama      4,900
2    2  Kabulwebulwe  Chief Kabulwebulwe        500
3    3        Kaindu        Chief Kaindu     48,436
4    4      Namwanja     Chief Chibuluma   6,375.12
5    5         Chipa     Chief Chibuluma    8.234.6
6    6         Moono         Chief Moono     15,735
7    7    Shakumbila    Chief Shakumbila  12,983.99
8    8     Mulendema     Chief Mulendema   16,469.6

In [753]:
table19_df = clean_dataframe(
    tables_19[0].df
)

display(table19_df)

     0             1                   2          3
0  S/N  Name of CFMG               Place   Hectares
1    1      Kalunzyu     Chief Chibulama      4,900
2    2  Kabulwebulwe  Chief Kabulwebulwe        500
3    3        Kaindu        Chief Kaindu     48,436
4    4      Namwanja     Chief Chibuluma   6,375.12
5    5         Chipa     Chief Chibuluma    8.234.6
6    6         Moono         Chief Moono     15,735
7    7    Shakumbila    Chief Shakumbila  12,983.99
8    8     Mulendema     Chief Mulendema   16,469.6

In [754]:
table19_df.columns = [
    "serial_number",
    "name_of_cfmg",
    "place",
    "hectares"
]

first_row = " ".join(
    table19_df.iloc[0].astype(str).tolist()
).lower()

if "name of cfmg" in first_row:
    table19_df = (
        table19_df
        .iloc[1:]
        .reset_index(drop=True)
    )

In [755]:
display(table19_df)

  serial_number  name_of_cfmg               place   hectares
0             1      Kalunzyu     Chief Chibulama      4,900
1             2  Kabulwebulwe  Chief Kabulwebulwe        500
2             3        Kaindu        Chief Kaindu     48,436
3             4      Namwanja     Chief Chibuluma   6,375.12
4             5         Chipa     Chief Chibuluma    8.234.6
5             6         Moono         Chief Moono     15,735
6             7    Shakumbila    Chief Shakumbila  12,983.99
7             8     Mulendema     Chief Mulendema   16,469.6

In [756]:
table19_df["hectares"] = pd.to_numeric(
    table19_df["hectares"],
    errors="coerce"
)

In [757]:
save_table_csv(
    table19_df,
    "db-unza26-csc4792_cfmgs_established_protected_areas_and_open_areas.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_cfmgs_established_protected_areas_and_open_areas_csv.csv
Rows: 8
Columns: 4

'db-unza26-csc4792_db_unza26_csc4792_cfmgs_established_protected_areas_and_open_areas_csv.csv'

In [758]:
tables_20 = camelot.read_pdf(
    PDF_PATH,
    pages="89-90",
    flavor="lattice"
)

print("Sections detected:", tables_20.n)

for i, table in enumerate(tables_20):
    print("\nSECTION:", i)
    print("Shape:", table.df.shape)
    display(table.df)

Sections detected: 2

SECTION: 0
Shape: (8, 6)

,0,1,2,3,4,5
0,S/N,Name of \nForest,Area \n(HA),Location,Distance from Mumbwa \nTown Center (KM),Status
1,1.,Sanje PFA 100,"10,864",Chimoto/ZAF,15,Not encroached
2,2.,Lutale \nPFA \n350,"2,725",Mulendema,15,Slightly encroached
3,3.,Mumba \nPFA \n60,"13,152",Mumba,40,Slightly encroached
4,4.,Nambala PFA \n43,"15,289",Nambala,45,Slightly encroached
5,5.,Mushingashi \nPFA 351,"11,500",Mumba East,40,Heavily encroached
6,6.,Luba \nnorth \nPFA 225,"4,812",GMA \n(MUMBWA \nGMA),100,Slightly encroached
7,7.,Luba \nsouth \nPFA 224,"21,052",GMA \n(MUMBWA \nGMA),100,Not encroached

SECTION: 1
Shape: (1, 6)

   0                   1       2             3    4               5
0  8  Kasanga  PFA \n226  10,065  GMA (KAINDU)  120  Not encroached

In [759]:
tables_20 = camelot.read_pdf(
    PDF_PATH,
    pages="89-90",
    flavor="lattice"
)

print("Sections detected:", tables_20.n)

for i, table in enumerate(tables_20):
    print("\nSECTION:", i)
    print("Shape:", table.df.shape)
    display(table.df)

Sections detected: 2

SECTION: 0
Shape: (8, 6)

,0,1,2,3,4,5
0,S/N,Name of \nForest,Area \n(HA),Location,Distance from Mumbwa \nTown Center (KM),Status
1,1.,Sanje PFA 100,"10,864",Chimoto/ZAF,15,Not encroached
2,2.,Lutale \nPFA \n350,"2,725",Mulendema,15,Slightly encroached
3,3.,Mumba \nPFA \n60,"13,152",Mumba,40,Slightly encroached
4,4.,Nambala PFA \n43,"15,289",Nambala,45,Slightly encroached
5,5.,Mushingashi \nPFA 351,"11,500",Mumba East,40,Heavily encroached
6,6.,Luba \nnorth \nPFA 225,"4,812",GMA \n(MUMBWA \nGMA),100,Slightly encroached
7,7.,Luba \nsouth \nPFA 224,"21,052",GMA \n(MUMBWA \nGMA),100,Not encroached

SECTION: 1
Shape: (1, 6)

   0                   1       2             3    4               5
0  8  Kasanga  PFA \n226  10,065  GMA (KAINDU)  120  Not encroached

In [760]:
table20_columns = [
    "serial_number",
    "name_of_forest",
    "area_ha",
    "location",
    "distance_from_mumbwa_town_center_km",
    "status"
]

In [761]:
table20_part1 = clean_dataframe(
    tables_20[0].df
)

display(table20_part1)

,0,1,2,3,4,5
0,S/N,Name of Forest,Area (HA),Location,Distance from Mumbwa Town Center (KM),Status
1,1.,Sanje PFA 100,"10,864",Chimoto/ZAF,15,Not encroached
2,2.,Lutale PFA 350,"2,725",Mulendema,15,Slightly encroached
3,3.,Mumba PFA 60,"13,152",Mumba,40,Slightly encroached
4,4.,Nambala PFA 43,"15,289",Nambala,45,Slightly encroached
5,5.,Mushingashi PFA 351,"11,500",Mumba East,40,Heavily encroached
6,6.,Luba north PFA 225,"4,812",GMA (MUMBWA GMA),100,Slightly encroached
7,7.,Luba south PFA 224,"21,052",GMA (MUMBWA GMA),100,Not encroached

In [762]:
print("Shape:", table20_part1.shape)
print("Number of extracted columns:", table20_part1.shape[1])

display(table20_part1)

Shape: (8, 6)
Number of extracted columns: 6

,0,1,2,3,4,5
0,S/N,Name of Forest,Area (HA),Location,Distance from Mumbwa Town Center (KM),Status
1,1.,Sanje PFA 100,"10,864",Chimoto/ZAF,15,Not encroached
2,2.,Lutale PFA 350,"2,725",Mulendema,15,Slightly encroached
3,3.,Mumba PFA 60,"13,152",Mumba,40,Slightly encroached
4,4.,Nambala PFA 43,"15,289",Nambala,45,Slightly encroached
5,5.,Mushingashi PFA 351,"11,500",Mumba East,40,Heavily encroached
6,6.,Luba north PFA 225,"4,812",GMA (MUMBWA GMA),100,Slightly encroached
7,7.,Luba south PFA 224,"21,052",GMA (MUMBWA GMA),100,Not encroached

In [763]:
table20_part1.columns = table20_columns

first_row = " ".join(
    table20_part1.iloc[0].astype(str).tolist()
).lower()

if "name of forest" in first_row:
    table20_part1 = (
        table20_part1
        .iloc[1:]
        .reset_index(drop=True)
    )

display(table20_part1)

,serial_number,name_of_forest,area_ha,location,distance_from_mumbwa_town_center_km,status
0,1.,Sanje PFA 100,"10,864",Chimoto/ZAF,15,Not encroached
1,2.,Lutale PFA 350,"2,725",Mulendema,15,Slightly encroached
2,3.,Mumba PFA 60,"13,152",Mumba,40,Slightly encroached
3,4.,Nambala PFA 43,"15,289",Nambala,45,Slightly encroached
4,5.,Mushingashi PFA 351,"11,500",Mumba East,40,Heavily encroached
5,6.,Luba north PFA 225,"4,812",GMA (MUMBWA GMA),100,Slightly encroached
6,7.,Luba south PFA 224,"21,052",GMA (MUMBWA GMA),100,Not encroached

In [764]:
table20_part2 = clean_dataframe(
    tables_20[1].df
)

print(table20_part2.shape)
display(table20_part2)

(1, 6)

   0                1       2             3    4               5
0  8  Kasanga PFA 226  10,065  GMA (KAINDU)  120  Not encroached

In [765]:
table20_df = pd.concat(
    [
        table20_part1,
        table20_part2
    ],
    ignore_index=True
)

display(table20_df)

,serial_number,name_of_forest,area_ha,location,distance_from_mumbwa_town_center_km,status,0,1,2,3,4,5
0,1.,Sanje PFA 100,"10,864",Chimoto/ZAF,15,Not encroached,NaN,NaN,NaN,NaN,NaN,NaN
1,2.,Lutale PFA 350,"2,725",Mulendema,15,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
2,3.,Mumba PFA 60,"13,152",Mumba,40,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
3,4.,Nambala PFA 43,"15,289",Nambala,45,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
4,5.,Mushingashi PFA 351,"11,500",Mumba East,40,Heavily encroached,NaN,NaN,NaN,NaN,NaN,NaN
5,6.,Luba north PFA 225,"4,812",GMA (MUMBWA GMA),100,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
6,7.,Luba south PFA 224,"21,052",GMA (MUMBWA GMA),100,Not encroached,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,8,Kasanga PFA 226,"10,065",GMA (KAINDU),120,Not encroached

In [766]:
print("Rows:", len(table20_df))

Rows: 8

In [767]:
table20_df["serial_number"] = pd.to_numeric(
    table20_df["serial_number"],
    errors="coerce"
)

table20_df["area_ha"] = (
    table20_df["area_ha"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

table20_df["area_ha"] = pd.to_numeric(
    table20_df["area_ha"],
    errors="coerce"
)

table20_df[
    "distance_from_mumbwa_town_center_km"
] = pd.to_numeric(
    table20_df[
        "distance_from_mumbwa_town_center_km"
    ],
    errors="coerce"
)

In [768]:
print(table20_df.dtypes)
display(table20_df)

serial_number                          float64
name_of_forest                          object
area_ha                                float64
location                                object
distance_from_mumbwa_town_center_km    float64
status                                  object
0                                       object
1                                       object
2                                       object
3                                       object
4                                       object
5                                       object
dtype: object

,serial_number,name_of_forest,area_ha,location,distance_from_mumbwa_town_center_km,status,0,1,2,3,4,5
0,1.0,Sanje PFA 100,10864.0,Chimoto/ZAF,15.0,Not encroached,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Lutale PFA 350,2725.0,Mulendema,15.0,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mumba PFA 60,13152.0,Mumba,40.0,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Nambala PFA 43,15289.0,Nambala,45.0,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Mushingashi PFA 351,11500.0,Mumba East,40.0,Heavily encroached,NaN,NaN,NaN,NaN,NaN,NaN
5,6.0,Luba north PFA 225,4812.0,GMA (MUMBWA GMA),100.0,Slightly encroached,NaN,NaN,NaN,NaN,NaN,NaN
6,7.0,Luba south PFA 224,21052.0,GMA (MUMBWA GMA),100.0,Not encroached,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,8,Kasanga PFA 226,"10,065",GMA (KAINDU),120,Not encroached

In [769]:
save_table_csv(
    table20_df,
    "db-unza26-csc4792_status_of_forest_reserves_in_mumbwa_district.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_status_of_forest_reserves_in_mumbwa_district_csv.csv
Rows: 8
Columns: 12

'db-unza26-csc4792_db_unza26_csc4792_status_of_forest_reserves_in_mumbwa_district_csv.csv'

In [770]:
tables_21 = camelot.read_pdf(
    PDF_PATH,
    pages="93",
    flavor="lattice"
)

print("Tables detected:", tables_21.n)

for i, table in enumerate(tables_21):
    print("\nIndex:", i)
    print("Shape:", table.df.shape)
    display(table.df)

Tables detected: 1

Index: 0
Shape: (5, 3)

,0,1,2
0,Location,% of Facilities Connected,% of Facilities Pending \nConnection
1,Mumbwa Urban,45,55
2,Mumbwa Peri-Urban,45,55
3,Mumbwa Rural,55,45
4,Average,40,60

In [771]:
table21_df = clean_dataframe(
    tables_21[0].df
)

display(table21_df)

,0,1,2
0,Location,% of Facilities Connected,% of Facilities Pending Connection
1,Mumbwa Urban,45,55
2,Mumbwa Peri-Urban,45,55
3,Mumbwa Rural,55,45
4,Average,40,60

In [772]:
table21_df.columns = [
    "location",
    "percent_facilities_connected",
    "percent_facilities_pending_connection"
]

first_row = " ".join(
    table21_df.iloc[0].astype(str).tolist()
).lower()

if "location" in first_row:
    table21_df = (
        table21_df
        .iloc[1:]
        .reset_index(drop=True)
    )

display(table21_df)

,location,percent_facilities_connected,percent_facilities_pending_connection
0,Mumbwa Urban,45,55
1,Mumbwa Peri-Urban,45,55
2,Mumbwa Rural,55,45
3,Average,40,60

In [773]:
numeric_columns = [
    "percent_facilities_connected",
    "percent_facilities_pending_connection"
]

for column in numeric_columns:

    table21_df[column] = (
        table21_df[column]
        .astype(str)
        .str.replace("%", "", regex=False)
        .str.strip()
    )

    table21_df[column] = pd.to_numeric(
        table21_df[column],
        errors="coerce"
    )

In [774]:
print(table21_df.dtypes)
display(table21_df)

location                                 object
percent_facilities_connected              int64
percent_facilities_pending_connection     int64
dtype: object

,location,percent_facilities_connected,percent_facilities_pending_connection
0,Mumbwa Urban,45,55
1,Mumbwa Peri-Urban,45,55
2,Mumbwa Rural,55,45
3,Average,40,60

In [775]:
save_table_csv(
    table21_df,
    "db-unza26-csc4792_district_electricity_supply.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_district_electricity_supply_csv.csv
Rows: 4
Columns: 3

'db-unza26-csc4792_db_unza26_csc4792_district_electricity_supply_csv.csv'

In [776]:
tables_22 = camelot.read_pdf(
    PDF_PATH,
    pages="108-121",
    flavor="lattice"
)

print("Sections detected:", tables_22.n)

for i, table in enumerate(tables_22):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df.head(10))

Sections detected: 14

SECTION: 0
Page: 108
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 1: To become an industrialised and diver...,,,,,,,,,
1,Objective 1: The Ministry of Agriculture will ...,,,,,,,,,
2,Strategy,Programme,Activity,Location (By Priority),Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,Responsible \nAgency
3,Increase \nAgricultural \nProduction \nand \nP...,Infrastructure \nDevelopment,Construct 25 camp \nhouses \nfor \nextension...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",5,5,5,5,5,"MoA, Local \nauthority, \nWorks and \nSupply"
4,,,Rehabilitate \nexisting \ncamp houses,"Mpusu, Muchabi, Kalwanyembe \nand \nNaluband...",0,2,2,0,0,"MoA, Town \ncouncil, \nWorks and \nSupply"
5,,,Provide \nadequate \naccommodation \nfor \nExt...,"Kaindu, Nalubanda, Nambala, Nangoma, \nMumbwa ...",1,1,1,2,1,"MoA, Local \nAuthority, \nWorks and \nSupply"
6,,,Construct \nOffice \nBlocks,District offices,0,0,2,0,0,"MoA, Local \nAuthority,"

SECTION: 1
Page: 109
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,,,,,,,Works and \nSupply
1,,,Construction \nof \nOffice \nBlocks \nfor \nEx...,"Kaindu, Nalubanda, Nambala, Nangoma, \nMumbwa ...",3,3,3,3,3,"MoA, Local \nAuthority, \nWorks and \nSupply"
2,,,Construction \nof \nFarmer \nTraining \nCenter,Mumba Scheme Camp,0,0,1,0,0,"Agriculture, \nLocal \nAuthority, \nWorks and ..."
3,,,Construction of Grain \nStorage Sheds,"Nangoma, Kaindu, Nalusanga, Chiwena, \nMuchabi",1,1,1,1,1,"Agriculture, \nLocal \nAuthority, \nWorks and ..."
4,,,Upgrade \nGrain \nStorage \ncapacity \nto \nre...,"Kamilambo, \nMumba, \nNambala, \nChibolyo, Cho...",0,1,1,2,1,"MoA, Local \nAuthority, \nWorks and \nSupply"
5,Objective 2: The Ministry of Agriculture will ...,,,,,,,,,
6,Improve \nagricultural \nproduction \nand \npr...,Agri-Business \nDevelopment,Establishment \nof \n5 \ncommercial \nagro-\np...,"Mumbwa central, Nambala, Nalubanda, \nKaind...",0,2,1,1,1,MoA/PPP
7,,,Increase \nthe number \nof farmers accessin...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...","15,942","16,925","18,925","20,925","22,000",MoA

SECTION: 2
Page: 110
Shape: (5, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"Moono, \nMulendema, \nChibuluma \ncamps",,,,,,
1,Objective 3: The Ministry of Agriculture will ...,,,,,,,,,
2,Improve \nagricultural \nproduction \nand \npr...,Agricultual \nMechanization,Increase \nthe number \nof \nfarmers \nowning...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",45,50,55,60,65,MoA
3,,,Increase \nthe number \nof \nfarmers \nowning...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",0,"1,150","1,150","1,150","1,150",MoA
4,,,Increase \nthe number \nof \nfarmers \nowning...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",25,25,25,25,25,MoA

SECTION: 3
Page: 111
Shape: (4, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Increase \nthe number \nof farmers accessin...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",764,839,836,835,837,MoA
1,,,Increase \nthe number \nof farmers accessin...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...","5,000","5,000","5,000","5,000","5,000",MoA
2,,,Increase \nthe number \nof farmers accessin...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",213,234,284,320,500,MoA
3,,,Increase \nthe number \nof \nmechanization \n...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",38,41,56,61,70,MoA

SECTION: 4
Page: 112
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,from 38 to 70 in five \nyears,"Matala, \nNalusanga, \nMupona, \nKabwanga, \nC...",,,,,,
1,Objective 4: The Ministry of Agriculture will ...,,,,,,,,,
2,Improve \nagricultural \nproduction \nand \npr...,Farm Block \nand \nResettlement \nSchemes \nD...,Conduct land audit of \nthe farm Block,Big Concession Area,1,1,1,1,1,MoA
3,,,Conduct a land audit \nof \nthe Resettleme...,"Maimwene, Mumba Scheme",2,1,1,1,1,MoA
4,,,Prepare a database of \nland \nunder \nagric...,All Wards,1,1,1,1,1,MoA
5,,,Create a new Farm \nBlock,Kaindu block,0,0,0,1,0,MoA
6,Objective 5: The Ministry of Agriculture will ...,,,,,,,,,
7,Improve \nagricultural \nproduction \nand \npr...,Enhance \nExtension Service \nSupport,Increase \nExtension \nService Support,"6 District, 6 Camps, 3 blocks",1 camp \nofficer,"6 district, \n2 camp, \n2block \nofficers","5 camp, \n2 block \nofficers",0,0,MoA
8,,,Procurement \nof \n37 \nMotor Bikes,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",0,9,9,10,9,MoA and \nLocal \nauthority

SECTION: 5
Page: 113
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"Moono, \nMulendema, \nChibuluma \ncamps",,,,,,
1,,,Procurement \nof \n1 \nLand Cruiser,District Agriculture Office,0,1,0,0,0,MoA and \nLocal \nauthority
2,,,Subdivide the camps \nin order \nto create...,"Matala, Mumba, Chipa, Kabulwebulwe \ncamps,...",0,5,0,0,0,MoA
3,,,"Training of 27, 131 \nfarmers \nin Climate...","Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...","5,427","5,427","5,427","5,427","5,427",MoA
4,,,Conduct 2 \nrefresher \ntrainings \nin \nAgri...,All camp officers,,2,2,2,2,MoA
5,,,Implement \ncrop \ndiversification \npractices...,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",34,34,34,34,34,MoA
6,,,Prepare \ntraining \nmaterials,District Agriculture Office,0,5,5,5,5,MoA

SECTION: 6
Page: 114
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Operationalize \nthe \nelectronic \nextension ...,District Agriculture Office,0,0,1,0,0,MoA
1,,,Periodic \nupdate \nof \nfarmer register,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",1,1,1,1,1,MoA
2,,,Prepare \nFarmer \nMarketing Bulletins,"Choombwa, Kamilambo, Kawama, \nKafwikamo, \n...",0,4,4,4,4,MoA
3,Objective 6: The Ministry of Agriculture will ...,,,,,,,,,
4,Improve \nagricultural \nproduction \nand \npr...,Early warning and \nsurveillance \nsystems,Procure \n18 \nCamp \nTents,"Choombwa, \nKamilambo, \nKawama, \nChipa, \nCh...",0,5,5,5,3,MoA
5,,,Procure \n100 \npheromon \ntraps \nand \nacces...,District Agriculture Office,12,24,24,20,20,MoA
6,,,Procure 225 PPEs,District Agriculture Office,25,50,50,50,50,MoA

SECTION: 7
Page: 115
Shape: (13, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Procure \n136 \nrain \nguages,District Agriculture Office,0,34,34,34,34,MoA
1,Objective 7: The Ministry of Agriculture will ...,,,,,,,,,
2,Improve \nagricultural \nproduction \nand \npr...,Irrigation \nDevelopment,Establish 4 irrigation \nschemes,"Mumba \nscheme, \nNalubanda, \nChipa, \nChikan...",0,1,1,1,1,MoA and \nDWRD
3,,,Construct 6 dams,"Nakasaka, Mumba, Choombwa, Naluvwi \nand Chipa",0,1,1,2,1,MoA and \nDWRD
4,,,Rehabilitate 5 dams,"Kabwanga, Kandesha, Mwambanabantu, \nNangoma...",0,1,2,1,1,MoA and \nDWRD
5,,,Construct 25 Weirs,"Mupona, Nakasaka, Makebo, Chibolyo \nand Mu...",5,5,5,5,5,MoA and \nDWRD
6,,,Rehabilitate \n5 \nexisting Weirs,"Luzani, \nMolodoni, \nKalayambunda, \nshimbizh...",0,5,0,0,0,MoA and \nDWRD
7,,,Prepare a database of \nland under irrigation,All the camps,0,1,1,1,1,MoA
8,,,"Train 24,500 farmers \nin \nin Climate Sma...",All camps,4213,"5,000","5,000","5,387","5,000",MoA
9,,,Link \nfarmers \nto \nirrigation \ncredit \nfa...,All camps,"1,800","1,800","1,800","1,800","1,800",MoA

SECTION: 8
Page: 116
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Establish 4 Permanent \nBiosecurity \ncheck \n...,"Naleza, Nambwa, Kapyanga, and Lutale",0,2,2,0,0,MFL
1,,,Increase Vaccination \nSchedules to twice ...,"shimbizhi, \nlutale, \nchoma, \nmumba, \nnamba...",2,2,2,2,2,MFL/LA
2,,,Facilitate \nthe \nestablishment \nof \na \nne...,Mumbwa Central,0,1,0,0,0,MFL/LA
3,,,Rehabilitate \nof \nthe \nexisting \nLivestock...,Nalusanga,0,1,0,0,0,MFL/LA
4,,,Increase \ndisease \nsurveillance \nthrough \n...,"shimbizhi, \nlutale, \nchoma, \nmumba, \nnamba...",9,9,9,9,9,MFL
5,,,Establishment of 100 \nragelands and fodde...,"Muchabi, Keezwa, Nalubanda, Lutale, \nNalus...",5,20,25,25,25,MFL
6,,,Facilitate community \nstocking \nand \nresto...,"Muchabi, Keezwa, Nalubanda, Lutale, \nNalus...",0,5000,5000,5000,10000,MFL/LA/CO\nM-DEV
7,,,Establishment \nof \nlivestock \nand \nbreedin...,Lutale,0,1,,0,0,MFL/LA

SECTION: 9
Page: 117
Shape: (11, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Rehabilitation \nof \n6 \ndams,"Kabwanga, Kandesha, Mwambanabantu, \nNangoma...",0,0,2,2,2,MFL/MOA/D\nWRD/LA
1,,,Construct 15 dams,"shimbizhi, \nlutale, \nchoma, \nmumba, \nnamba...",0,0,5,5,5,MFL/MOA/D\nWRD/LA
2,Objective 9: The Ministry of Fisheries and Liv...,,,,,,,,,
3,Improve \nagricultural \nproduction \nand \npr...,Fisheries \nDevelopment,Form \n16 \nvillage \nmanagement \ncommittees,Kaindu and Blue – lagoon,4,4,4,4,4,MFL
4,,,Issue \n1000 \nfishing \nlicenses for farmers,kaindu and Blue-lagoon,200,200,200,200,200,MFL
5,,,Train \n1000 \nfish \nfarmers in sustainable \...,Kaindu and Blue – lagoon,200,200,200,200,200,MFL
6,,,Sensitize 500 farmers \non sustainable fishing...,Kaindu and Blue – lagoon,100,100,100,100,100,MFL
7,,,Install \n3 \nice \nplants \nnear fishing camps,"Choma \nWard, \nShimbizhi \nand \nKalwanyembe ...",0,1,1,0,1,MFL/LA
8,,,"Restoke \n420,000 \nfingerlings","shimbizhi, \nlutale, \nchoma, \nmumba, \nnamba...",84000,84000,84000,84000,84000,MFL
9,,,Establishment \nof \n3 \nHatcheries,"Kalwanyembe ward, Choma Ward and \nshimbiz...",,1,1,0,1,MFL

SECTION: 10
Page: 118
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"nalusanga, mupona, nangoma, keezwa, \nnaluv...",,,,,,
1,,Establishment of 3 \nAI satellite centers,Establishment of 3 AI \nsatellite centers,"Nalubanda, Kaindu, Mumbwa Central",0,1,,1,1,MFL/LA
2,Objective 10: The Ministry of Fisheries and Li...,,,,,,,,,
3,Improve \nagricultural \nproduction \nand \npr...,Infrastructure \nDevelopment,Improve the presence \nof \nofficers \nin \n...,"shimbizhi, \nlutale, \nchoma, \nmumba, \nnamba...",0,6,8,9,5,MFL/LA
4,,,Improve the presence \nof officers \nin ca...,"District, Nalusanga, Kaindu, Muchabi, \nKee...",0,3,3,3,,MFL/LA
5,,,"Recruitment \nof \n35 \nFisheries, \nLivestock...","District office, Shimbizhi, lutale, choma, \nm...",0,7,7,7,14,MFL
6,,,Establishment of E-\nextension platforms at ...,"District office, shimbizhi, lutale, choma,...",1,0,0,1,0,MFL
7,,,Improvement \nof \ntransport logistics for \...,"District office, shimbizhi, lutale, choma,...",0,10,10,10,10,MFL/LA/Priv\nate \nStakeholders

SECTION: 11
Page: 119
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,procurement \nof \n40 \nbikes,"naluvwi, \nmakebo, \nsichanzu, \nkalwanyembe, ...",,,,,,
1,,,Enhancement \nof \nefficient \ndisease \noutbr...,District Office,0,1,0,1,0,MFL/LA
2,,,Improvement \non \ninformation \ndisemination ...,District office,0,5,0,5,0,MFL
3,,,Facilitae Demarcation \nand alignment of th...,"shimbizhi, \nlutale, \nchoma, \nmumba, \nnamba...",0,21,0,0,0,MFL/LA
4,Objective 11: The Ministry of Fisheries and Li...,,,,,,,,,
5,Promote \nvalue \naddition \nand \nmanufacturing,Value \nchain \ndevelopment,Establishment \nof \na \nBulking \nCentre \nto...,Moono,0,0,1,0,0,MFL/LA
6,,,Faciliate \nthe \nestablishment of Milk \nColl...,"Keezwa, Mumbwa Central",1,0,1,0,0,MFL/LA

SECTION: 12
Page: 120
Shape: (11, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Market linkages,Establishment \nof \na \nFisheries Market,Nangoma,0,1,0,0,0,MFL
1,Objective 12: Zesco will collaborate with stak...,,,,,,,,,
2,Improve \npower \nsupply \n \nto \nhouseholds,Connection \nof \nhouseholds \nto \nreliable \...,Electricity \nConnection \nof \nHouseholds,Mumbwa and Nangoma Constituencies,600,600,600,600,600,ZESCO/LA/R\nEA
3,,,Promotion of Off-grid \nEnergy Solutions,Mumbwa and Nangoma Constituencies,1000,1000,1000,1000,1000,ZESCO/LA/R\nEA
4,Objective 13: Objective: The Local Authority w...,,,,,,,,,
5,Improve \nTransport \nand \nLogistics,"Road \nInfrastructure \ndevelopment, \nMainte...",Rehabilitation \nand \nUpgrading roads,D 181 \nRD 185 \nRD 186 \nN 20 \nD 810,0,5Km,5Km,5Km,5Km,Local \nAuthority & \nNRFA
6,,,,D 166 \nD 180 \nD 183,0,10Km,10Km,10Km,10Km,Local \nAuthority & \nNRFA
7,,,,M 9 \nRD 490 \nD 808,4Km,8Km,10Km,10Km,8Km,Local \nAuthority & \nNRFA
8,,,,RD 194 \nRD 184,4Km,8Km,10Km,10Km,8Km,Local \nAuthority & \nNRFA
9,Enhance Digital \nCapacity,ICT infrastructure \ndevelopment,Improve \non \ncommunication in the \ndistrict,"Mpusu, \nKamilambo, \nNalubanda, \nNakasaka, \...",0,2,2,2,2,Ministry of \nTechnology \nand Science

SECTION: 13
Page: 121
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Ensure \nproper \ncommunication in the \ndistrict,"Nangoma, Mumbwa",0,1,0,1,0,Ministry of \nTechnology \nand Science
1,Objective 14: National Parks and Wildlife will...,,,,,,,,,
2,Promote \nTourism \nDiversification,Wildlife \nmanagement,Implementation \nof \nLand Use Plans that \nwi...,"Keezwa, \nNalusanga, \nMiyoye, \nChoombwa, \nS...",70%,60%,40%,30%,10%,DNPW
3,Objective 15: National Parks and Wildlife will...,,,,,,,,,
4,Promote \nTourism \nDiversification,Tourism \npromotion \nand \nmarketing,Identification \nand \nMapping \nof \n24 \nTou...,"Nalusanga, \nChoma, \nKeezwa, \nMupona, Nambal...",6 sites,10 sites,4 sites,2 sites,2 sites,DNPW/ \nNHCC
5,,,Conduct \n30 \nTourism \nPromotions,"Nalusanga, \nChoma, \nKeezwa, \nMupona, Nambal...",4 Local \nShows,8 Local \nShows,6 Local \nShows,6 Local \nShows,6 Local \nShows,DNPW/ \nNHCC/ \nZANIS
6,,,Conduct \n50 \nTourism Marketing \nAdverts,"Nalusanga, \nChoma, \nKeezwa, \nMupona, Nambal...",5 \nAdverts,15 \nAdverts,10 \nAdverts,10 \nAdverts,10 \nAdverts,DNPW/NHC\nC/ ZANIS
7,Objective 16: The Ministry of Tourism will inv...,,,,,,,,,
8,Promote \nTourism \nDiversification,Infrastructure \nDevelopment,Construction \nof \nTwo \nCommunity \nWildlife...,Mupona and Nalusanga,0,1,0,1,0,MOT/ \nNTMB

In [777]:
implementation_columns = [
    "strategy",
    "programme",
    "activity",
    "location_by_priority",
    "target_2024",
    "target_2025",
    "target_2026",
    "target_2027",
    "target_2028",
    "responsible_agency"
]

In [778]:
def normalize_implementation_section(df):

    df = clean_dataframe(df)

    print("Original shape:", df.shape)

    # Perfect case
    if df.shape[1] == 10:
        df.columns = implementation_columns
        return df

    # Sometimes Camelot creates an extra blank column
    if df.shape[1] == 11:
        empty_counts = (
            df.replace("", pd.NA)
              .isna()
              .sum()
        )

        emptiest_column = empty_counts.idxmax()

        df = df.drop(
            columns=[emptiest_column]
        )

        df = df.reset_index(drop=True)

        if df.shape[1] == 10:
            df.columns = implementation_columns
            return df

    # Sometimes merged Strategy/Programme gives only 9
    if df.shape[1] == 9:

        df.insert(
            0,
            "strategy",
            ""
        )

        df.columns = implementation_columns
        return df

    print(
        "Could not automatically normalize section:",
        df.shape
    )

    display(df)

    return None

In [779]:
table22_parts = []

for i, table in enumerate(tables_22):

    print("\nProcessing section:", i)

    part = normalize_implementation_section(
        table.df
    )

    if part is not None:
        table22_parts.append(part)

Processing section: 0
Original shape: (7, 10)

Processing section: 1
Original shape: (8, 10)

Processing section: 2
Original shape: (5, 10)

Processing section: 3
Original shape: (4, 8)
Could not automatically normalize section: (4, 8)

,2,3,4,5,6,7,8,9
0,Increase the number of farmers accessing tract...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",764,839,836,835,837,MoA
1,Increase the number of farmers accessing anima...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...","5,000","5,000","5,000","5,000","5,000",MoA
2,Increase the number of farmers accessing post-...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",213,234,284,320,500,MoA
3,Increase the number of mechanization service p...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",38,41,56,61,70,MoA

Processing section: 4
Original shape: (9, 10)

Processing section: 5
Original shape: (7, 8)
Could not automatically normalize section: (7, 8)

,2,3,4,5,6,7,8,9
0,,"Moono, Mulendema, Chibuluma camps",,,,,,
1,Procurement of 1 Land Cruiser,District Agriculture Office,0,1,0,0,0,MoA and Local authority
2,Subdivide the camps in order to create 5 more ...,"Matala, Mumba, Chipa, Kabulwebulwe camps, Namb...",0,5,0,0,0,MoA
3,"Training of 27, 131 farmers in Climate- Smart ...","Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...","5,427","5,427","5,427","5,427","5,427",MoA
4,Conduct 2 refresher trainings in Agriculture f...,All camp officers,,2,2,2,2,MoA
5,Implement crop diversification practices in 34...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",34,34,34,34,34,MoA
6,Prepare training materials,District Agriculture Office,0,5,5,5,5,MoA

Processing section: 6
Original shape: (7, 10)

Processing section: 7
Original shape: (13, 10)

Processing section: 8
Original shape: (8, 8)
Could not automatically normalize section: (8, 8)

,2,3,4,5,6,7,8,9
0,Establish 4 Permanent Biosecurity check points,"Naleza, Nambwa, Kapyanga, and Lutale",0,2,2,0,0,MFL
1,Increase Vaccination Schedules to twice a year,"shimbizhi, lutale, choma, mumba, nambala, kami...",2,2,2,2,2,MFL/LA
2,Facilitate the establishment of a new quaranti...,Mumbwa Central,0,1,0,0,0,MFL/LA
3,Rehabilitate of the existing Livestock Quarant...,Nalusanga,0,1,0,0,0,MFL/LA
4,Increase disease surveillance through Active a...,"shimbizhi, lutale, choma, mumba, nambala, kami...",9,9,9,9,9,MFL
5,Establishment of 100 ragelands and fodder banks,"Muchabi, Keezwa, Nalubanda, Lutale, Nalusanga,...",5,20,25,25,25,MFL
6,Facilitate community stocking and restocking o...,"Muchabi, Keezwa, Nalubanda, Lutale, Nalusanga,...",0,5000,5000,5000,10000,MFL/LA/CO M-DEV
7,Establishment of livestock and breeding centers,Lutale,0,1,,0,0,MFL/LA

Processing section: 9
Original shape: (11, 10)

Processing section: 10
Original shape: (8, 10)

Processing section: 11
Original shape: (7, 10)

Processing section: 12
Original shape: (11, 10)

Processing section: 13
Original shape: (9, 10)

In [780]:
print(
    "Usable sections:",
    len(table22_parts)
)

Usable sections: 11

In [781]:
table22_df = pd.concat(
    table22_parts,
    ignore_index=True
)

print(table22_df.shape)

display(
    table22_df.head(20)
)

(95, 10)

,strategy,programme,activity,location_by_priority,target_2024,target_2025,target_2026,target_2027,target_2028,responsible_agency
0,Goal 1: To become an industrialised and divers...,,,,,,,,,
1,Objective 1: The Ministry of Agriculture will ...,,,,,,,,,
2,Strategy,Programme,Activity,Location (By Priority),Target 2024,Target 2025,Target 2026,Target 2027,Target 2028,Responsible Agency
3,Increase Agricultural Production and Productivity,Infrastructure Development,Construct 25 camp houses for extension officers,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",5,5,5,5,5,"MoA, Local authority, Works and Supply"
4,,,Rehabilitate existing camp houses,"Mpusu, Muchabi, Kalwanyembe and Nalubanda camps",0,2,2,0,0,"MoA, Town council, Works and Supply"
5,,,Provide adequate accommodation for Extension o...,"Kaindu, Nalubanda, Nambala, Nangoma, Mumbwa ce...",1,1,1,2,1,"MoA, Local Authority, Works and Supply"
6,,,Construct Office Blocks,District offices,0,0,2,0,0,"MoA, Local Authority,"
7,,,,,,,,,,Works and Supply
8,,,Construction of Office Blocks for Extension Of...,"Kaindu, Nalubanda, Nambala, Nangoma, Mumbwa ce...",3,3,3,3,3,"MoA, Local Authority, Works and Supply"
9,,,Construction of Farmer Training Center,Mumba Scheme Camp,0,0,1,0,0,"Agriculture, Local Authority, Works and Supply"
10,,,Construction of Grain Storage Sheds,"Nangoma, Kaindu, Nalusanga, Chiwena, Muchabi",1,1,1,1,1,"Agriculture, Local Authority, Works and Supply"
11,,,Upgrade Grain Storage capacity to reduce on po...,"Kamilambo, Mumba, Nambala, Chibolyo, Choma wards",0,1,1,2,1,"MoA, Local Authority, Works and Supply"
12,Objective 2: The Ministry of Agriculture will ...,,,,,,,,,
13,Improve agricultural production and productivity,Agri-Business Development,Establishment of 5 commercial agro- processing...,"Mumbwa central, Nambala, Nalubanda, Kaindu and...",0,2,1,1,1,MoA/PPP
14,,,Increase the number of farmers accessing affor...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...","15,942","16,925","18,925","20,925","22,000",MoA
15,,,,"Moono, Mulendema, Chibuluma camps",,,,,,
16,Objective 3: The Ministry of Agriculture will ...,,,,,,,,,
17,Improve agricultural production and productivity,Agricultual Mechanization,Increase the number of farmers owning tractors...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",45,50,55,60,65,MoA
18,,,Increase the number of farmers owning animal d...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",0,"1,150","1,150","1,150","1,150",MoA
19,,,Increase the number of farmers owning post-har...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",25,25,25,25,25,MoA

In [782]:
def remove_implementation_headers(df):

    df = df.copy()

    combined = (
        df.astype(str)
          .agg(" ".join, axis=1)
          .str.lower()
    )

    header_mask = (
        combined.str.contains("strategy")
        & combined.str.contains("programme")
        & combined.str.contains("activity")
    )

    df = df[
        ~header_mask
    ].reset_index(drop=True)

    return df

In [783]:
table22_df = remove_implementation_headers(
    table22_df
)

display(table22_df.head(20))

,strategy,programme,activity,location_by_priority,target_2024,target_2025,target_2026,target_2027,target_2028,responsible_agency
0,Goal 1: To become an industrialised and divers...,,,,,,,,,
1,Objective 1: The Ministry of Agriculture will ...,,,,,,,,,
2,Increase Agricultural Production and Productivity,Infrastructure Development,Construct 25 camp houses for extension officers,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",5,5,5,5,5,"MoA, Local authority, Works and Supply"
3,,,Rehabilitate existing camp houses,"Mpusu, Muchabi, Kalwanyembe and Nalubanda camps",0,2,2,0,0,"MoA, Town council, Works and Supply"
4,,,Provide adequate accommodation for Extension o...,"Kaindu, Nalubanda, Nambala, Nangoma, Mumbwa ce...",1,1,1,2,1,"MoA, Local Authority, Works and Supply"
5,,,Construct Office Blocks,District offices,0,0,2,0,0,"MoA, Local Authority,"
6,,,,,,,,,,Works and Supply
7,,,Construction of Office Blocks for Extension Of...,"Kaindu, Nalubanda, Nambala, Nangoma, Mumbwa ce...",3,3,3,3,3,"MoA, Local Authority, Works and Supply"
8,,,Construction of Farmer Training Center,Mumba Scheme Camp,0,0,1,0,0,"Agriculture, Local Authority, Works and Supply"
9,,,Construction of Grain Storage Sheds,"Nangoma, Kaindu, Nalusanga, Chiwena, Muchabi",1,1,1,1,1,"Agriculture, Local Authority, Works and Supply"
10,,,Upgrade Grain Storage capacity to reduce on po...,"Kamilambo, Mumba, Nambala, Chibolyo, Choma wards",0,1,1,2,1,"MoA, Local Authority, Works and Supply"
11,Objective 2: The Ministry of Agriculture will ...,,,,,,,,,
12,Improve agricultural production and productivity,Agri-Business Development,Establishment of 5 commercial agro- processing...,"Mumbwa central, Nambala, Nalubanda, Kaindu and...",0,2,1,1,1,MoA/PPP
13,,,Increase the number of farmers accessing affor...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...","15,942","16,925","18,925","20,925","22,000",MoA
14,,,,"Moono, Mulendema, Chibuluma camps",,,,,,
15,Objective 3: The Ministry of Agriculture will ...,,,,,,,,,
16,Improve agricultural production and productivity,Agricultual Mechanization,Increase the number of farmers owning tractors...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",45,50,55,60,65,MoA
17,,,Increase the number of farmers owning animal d...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",0,"1,150","1,150","1,150","1,150",MoA
18,,,Increase the number of farmers owning post-har...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",25,25,25,25,25,MoA
19,,,from 38 to 70 in five years,"Matala, Nalusanga, Mupona, Kabwanga, Chibila, ...",,,,,,

In [784]:
combined_text = (
    table22_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

objective_mask = (
    combined_text.str.startswith("objective")
    | combined_text.str.startswith("goal")
)

table22_df = table22_df[
    ~objective_mask
].reset_index(drop=True)

In [785]:
for column in [
    "strategy",
    "programme"
]:

    table22_df[column] = (
        table22_df[column]
        .replace("", pd.NA)
        .ffill()
    )

In [786]:
for column in table22_df.columns:

    table22_df[column] = (
        table22_df[column]
        .astype(str)
        .str.replace(
            r"\s+",
            " ",
            regex=True
        )
        .str.strip()
    )

In [787]:
print(
    table22_df.shape
)

display(
    table22_df.head(30)
)

display(
    table22_df.tail(20)
)

(77, 10)

,strategy,programme,activity,location_by_priority,target_2024,target_2025,target_2026,target_2027,target_2028,responsible_agency
0,Increase Agricultural Production and Productivity,Infrastructure Development,Construct 25 camp houses for extension officers,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",5,5,5,5,5,"MoA, Local authority, Works and Supply"
1,Increase Agricultural Production and Productivity,Infrastructure Development,Rehabilitate existing camp houses,"Mpusu, Muchabi, Kalwanyembe and Nalubanda camps",0,2,2,0,0,"MoA, Town council, Works and Supply"
2,Increase Agricultural Production and Productivity,Infrastructure Development,Provide adequate accommodation for Extension o...,"Kaindu, Nalubanda, Nambala, Nangoma, Mumbwa ce...",1,1,1,2,1,"MoA, Local Authority, Works and Supply"
3,Increase Agricultural Production and Productivity,Infrastructure Development,Construct Office Blocks,District offices,0,0,2,0,0,"MoA, Local Authority,"
4,Increase Agricultural Production and Productivity,Infrastructure Development,,,,,,,,Works and Supply
5,Increase Agricultural Production and Productivity,Infrastructure Development,Construction of Office Blocks for Extension Of...,"Kaindu, Nalubanda, Nambala, Nangoma, Mumbwa ce...",3,3,3,3,3,"MoA, Local Authority, Works and Supply"
6,Increase Agricultural Production and Productivity,Infrastructure Development,Construction of Farmer Training Center,Mumba Scheme Camp,0,0,1,0,0,"Agriculture, Local Authority, Works and Supply"
7,Increase Agricultural Production and Productivity,Infrastructure Development,Construction of Grain Storage Sheds,"Nangoma, Kaindu, Nalusanga, Chiwena, Muchabi",1,1,1,1,1,"Agriculture, Local Authority, Works and Supply"
8,Increase Agricultural Production and Productivity,Infrastructure Development,Upgrade Grain Storage capacity to reduce on po...,"Kamilambo, Mumba, Nambala, Chibolyo, Choma wards",0,1,1,2,1,"MoA, Local Authority, Works and Supply"
9,Improve agricultural production and productivity,Agri-Business Development,Establishment of 5 commercial agro- processing...,"Mumbwa central, Nambala, Nalubanda, Kaindu and...",0,2,1,1,1,MoA/PPP
10,Improve agricultural production and productivity,Agri-Business Development,Increase the number of farmers accessing affor...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...","15,942","16,925","18,925","20,925","22,000",MoA
11,Improve agricultural production and productivity,Agri-Business Development,,"Moono, Mulendema, Chibuluma camps",,,,,,
12,Improve agricultural production and productivity,Agricultual Mechanization,Increase the number of farmers owning tractors...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",45,50,55,60,65,MoA
13,Improve agricultural production and productivity,Agricultual Mechanization,Increase the number of farmers owning animal d...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",0,"1,150","1,150","1,150","1,150",MoA
14,Improve agricultural production and productivity,Agricultual Mechanization,Increase the number of farmers owning post-har...,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",25,25,25,25,25,MoA
15,Improve agricultural production and productivity,Agricultual Mechanization,from 38 to 70 in five years,"Matala, Nalusanga, Mupona, Kabwanga, Chibila, ...",,,,,,
16,Improve agricultural production and productivity,Farm Block and Resettlement Schemes Development,Conduct land audit of the farm Block,Big Concession Area,1,1,1,1,1,MoA
17,Improve agricultural production and productivity,Farm Block and Resettlement Schemes Development,Conduct a land audit of the Resettlement Schemes,"Maimwene, Mumba Scheme",2,1,1,1,1,MoA
18,Improve agricultural production and productivity,Farm Block and Resettlement Schemes Development,Prepare a database of land under agricultural ...,All Wards,1,1,1,1,1,MoA
19,Improve agricultural production and productivity,Farm Block and Resettlement Schemes Development,Create a new Farm Block,Kaindu block,0,0,0,1,0,MoA
20,Improve agricultural production and productivity,Enhance Extension Service Support,Increase Extension Service Support,"6 District, 6 Camps, 3 blocks",1 camp officer,"6 district, 2 camp, 2block officers","5 camp, 2 block officers",0,0,MoA
21,Improve agricultural production and productivity,Enhance Extension Service Support,Procurement of 37 Motor Bikes,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",0,9,9,10,9,MoA and Local authority
22,Improve agricultural production and productivity,Enhance Extension Service Support,Operationalize the electronic extension platform,District Agriculture Office,0,0,1,0,0,MoA
23,Improve agricultural production and productivity,Enhance Extension Service Support,Periodic update of farmer register,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",1,1,1,1,1,MoA
24,Improve agricultural production and productivity,Enhance Extension Service Support,Prepare Farmer Marketing Bulletins,"Choombwa, Kamilambo, Kawama, Kafwikamo, Chipa,...",0,4,4,4,4,MoA
25,Improve agricultural production and productivity,Early warning and surveillance systems,Procure 18 Camp Tents,"Choombwa, Kamilambo, Kawama, Chipa, Chikanda, ...",0,5,5,5,3,MoA
26,Improve agricultural production and productivity,Early warning and surveillance systems,Procure 100 pheromon traps and accessories,District Agriculture Office,12,24,24,20,20,MoA
27,Improve agricultural production and productivity,Early warning and surveillance systems,Procure 225 PPEs,District Agriculture Office,25,50,50,50,50,MoA
28,Improve agricultural production and productivity,Early warning and surveillance systems,Procure 136 rain guages,District Agriculture Office,0,34,34,34,34,MoA
29,Improve agricultural production and productivity,Irrigation Development,Establish 4 irrigation schemes,"Mumba scheme, Nalubanda, Chipa, Chikanda and M...",0,1,1,1,1,MoA and DWRD

,strategy,programme,activity,location_by_priority,target_2024,target_2025,target_2026,target_2027,target_2028,responsible_agency
57,Improve agricultural production and productivity,Infrastructure Development,Enhancement of efficient disease outbreak resp...,District Office,0,1,0,1,0,MFL/LA
58,Improve agricultural production and productivity,Infrastructure Development,Improvement on information disemination by Dev...,District office,0,5,0,5,0,MFL
59,Improve agricultural production and productivity,Infrastructure Development,Facilitae Demarcation and alignment of the cur...,"shimbizhi, lutale, choma, mumba, nambala, kami...",0,21,0,0,0,MFL/LA
60,Promote value addition and manufacturing,Value chain development,Establishment of a Bulking Centre to Localise ...,Moono,0,0,1,0,0,MFL/LA
61,Promote value addition and manufacturing,Value chain development,Faciliate the establishment of Milk Collection...,"Keezwa, Mumbwa Central",1,0,1,0,0,MFL/LA
62,Promote value addition and manufacturing,Market linkages,Establishment of a Fisheries Market,Nangoma,0,1,0,0,0,MFL
63,Improve power supply to households,Connection of households to reliable power supply,Electricity Connection of Households,Mumbwa and Nangoma Constituencies,600,600,600,600,600,ZESCO/LA/R EA
64,Improve power supply to households,Connection of households to reliable power supply,Promotion of Off-grid Energy Solutions,Mumbwa and Nangoma Constituencies,1000,1000,1000,1000,1000,ZESCO/LA/R EA
65,Improve Transport and Logistics,"Road Infrastructure development, Maintenance",Rehabilitation and Upgrading roads,D 181 RD 185 RD 186 N 20 D 810,0,5Km,5Km,5Km,5Km,Local Authority & NRFA
66,Improve Transport and Logistics,"Road Infrastructure development, Maintenance",,D 166 D 180 D 183,0,10Km,10Km,10Km,10Km,Local Authority & NRFA
67,Improve Transport and Logistics,"Road Infrastructure development, Maintenance",,M 9 RD 490 D 808,4Km,8Km,10Km,10Km,8Km,Local Authority & NRFA
68,Improve Transport and Logistics,"Road Infrastructure development, Maintenance",,RD 194 RD 184,4Km,8Km,10Km,10Km,8Km,Local Authority & NRFA
69,Enhance Digital Capacity,ICT infrastructure development,Improve on communication in the district,"Mpusu, Kamilambo, Nalubanda, Nakasaka, Shichan...",0,2,2,2,2,Ministry of Technology and Science
70,Enhance Digital Capacity,ICT infrastructure development,Installation of radio and television towers,"Kalwanyembe, Naluwvi, Chibolyo, Nangoma, Shich...",0,0,2,2,2,Ministry of Technology and Science
71,Enhance Digital Capacity,ICT infrastructure development,Ensure proper communication in the district,"Nangoma, Mumbwa",0,1,0,1,0,Ministry of Technology and Science
72,Promote Tourism Diversification,Wildlife management,Implementation of Land Use Plans that will gui...,"Keezwa, Nalusanga, Miyoye, Choombwa, Shimbinji...",70%,60%,40%,30%,10%,DNPW
73,Promote Tourism Diversification,Tourism promotion and marketing,Identification and Mapping of 24 Tourism Inves...,"Nalusanga, Choma, Keezwa, Mupona, Nambala and ...",6 sites,10 sites,4 sites,2 sites,2 sites,DNPW/ NHCC
74,Promote Tourism Diversification,Tourism promotion and marketing,Conduct 30 Tourism Promotions,"Nalusanga, Choma, Keezwa, Mupona, Nambala and ...",4 Local Shows,8 Local Shows,6 Local Shows,6 Local Shows,6 Local Shows,DNPW/ NHCC/ ZANIS
75,Promote Tourism Diversification,Tourism promotion and marketing,Conduct 50 Tourism Marketing Adverts,"Nalusanga, Choma, Keezwa, Mupona, Nambala and ...",5 Adverts,15 Adverts,10 Adverts,10 Adverts,10 Adverts,DNPW/NHC C/ ZANIS
76,Promote Tourism Diversification,Infrastructure Development,Construction of Two Community Wildlife Museums,Mupona and Nalusanga,0,1,0,1,0,MOT/ NTMB

In [788]:
save_table_csv(
    table22_df,
    "db-unza26-csc4792_economic_transformation_and_job_creation_implementation_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_economic_transformation_and_job_creation_implementation_plan_csv.csv
Rows: 77
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_economic_transformation_and_job_creation_implementation_plan_csv.csv'

In [789]:
tables_23 = camelot.read_pdf(
    PDF_PATH,
    pages="122-133",
    flavor="lattice"
)

print("Sections detected:", tables_23.n)

for i, table in enumerate(tables_23):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df.head())

Sections detected: 13

SECTION: 0
Page: 122
Shape: (4, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Construction of two \nCommunity Lodges,"Mupona, Nambala,",0,0,1 Lodge,0,1 Lodge,MOT/ \nDNPW/LA/\nWS/CDF
1,,,Construction \nFour \nCamp Sites,"Miyoye, \nNambala, \nMatala \nand \nNalusanga",0,2 Camp \nSites,0,2 Camp \nSites,0,
2,,,Rehabilitation \nand \nmaintenance \nof \n6 \n...,Mupona and Kalyanyembo,0,2,2,2,0,MOT/DNPW\n/NHCC
3,,,Establishment of 2 \nCommunity Game \nRanches,Mupona and Nakasaka,0,1,0,1,0,MOT/DNPW\n/WWF

SECTION: 1
Page: 122
Shape: (4, 10)

,0,1,2,3,4,5,6,7,8,9
0,"Goal 2: To Provide Universal Coverage Health, ...",,,,,,,,,
1,Objective 1: The Ministry of Health will work ...,,,,,,,,,
2,Strategies,Programme,Activities,Location (By Priority),Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,Responsible \nInstitution
3,Increase access \nto \nquality \nhealth care,Infrastructure \ndevelopment,Construction of 21 \nHealth \nService \nAcce...,"Mwanamango, Mapoko, Kasumpa, \nMituntu, \nKa...",1,5,5,5,5,MOH/LA

SECTION: 2
Page: 123
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Expand \nInfrastructure of 1st \nLevel Hospital,Mumbwa District Hospital,0,1,0,0,0,MOH/LA
1,,,Rehabilitate \nHospital,Mumbwa District Hospital,0,0,0,1,0,MOH/LA
2,,,Expansion \nof \n4 \nExisting \nHealth \nCentr...,"Kaindu, Lungobe, Keezwa, Naluvwi",0,1,1,1,1,MOH/LA
3,,,Rehabilitation of 2 \nShelter \nfor \nMourners,"Mumbwa District Hospital, Nangoma \nMission ho...",0,1,1,0,0,MOH/LA
4,,,Securing \nDistrict \nHospital Boundary,Mumbwa District Hospital,0,1,0,0,0,MOH/LA

SECTION: 3
Page: 124
Shape: (5, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Expand \nInfrastructure \nof \nMaternity Annexes,"Shakumbila, \nKeezwa, \nMuchabi, \nNambala, \n...",0,4,4,4,4,MOH/LA
1,,,Rehabilitate \n18 \nShelters for Waiting \nMot...,"Shakumbila, \nKeezwa, \nMuchabi, \nNakanjoli,...",0,4,4,4,6,MOH/LA
2,,,Connection \nof \n17 \nHealth Facilities to ...,"Nalubanda, Lutale, Kapepe, Lungobe, \nShakumbi...",2,4,4,4,4,MOH/LA
3,,,Connect of Water \nReticulation \nto \nHealt...,"Myooye, \nShakumbila, \nNaluvwi, \nNambala, L...",0,4,4,4,4,MOH/LA
4,,Equipment \nand \nTransport \nProcurement,Provision \nof \nTransport Services,"Mumbwa District Hospital, Nangoma \nMission H...",1,2,2,0,0,MOH/LA

SECTION: 4
Page: 125
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,and \nMaintenance,,,,,,,,
1,Objective 2: The Ministry of Health will colla...,,,,,,,,,
2,Strengthen \nPublic Health,Provision \nof \nAdolescent \nYouth Friendly ...,Provide Adolescent \nYouth \nFriendly \nSpaces,"Nalubanda, Myooye, Lutale, Kapepe, \nLungobe, ...",0,5,5,5,5,MOH/LA
3,,Mental Health \nand Substance \nAbuse \nManage...,Increase Health \nFacility Capacity to \nProvi...,Mumbwa District Hospital,0,0,1,0,0,MOH/LA
4,,Family planning \npromotion,Capacity \nStrengthening of \nFP Service \nDel...,All Health Facilities,0,12,12,12,12,MOH/LA

SECTION: 5
Page: 126
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Provision \nof \nSterilization \nServices,All Health Facilities,0,5,5,5,5,MOH/LA
1,,,Provision \nof \nLaboratory Services,Mumbwa and Nangoma Hospital,0,2,0,0,0,MOH/LA
2,,Health \nEducation \nPromotion,Conduct \nRadio \nProgrammes,District Health Office,12,12,12,12,12,MOH/LA
3,,,Provide \nOutreach \nProgrammes,All health facilities,12,12,12,12,12,MOH/LA
4,,,Strengthen \nthe \nstructures \nand \nfunction...,All health facilities,12,12,12,12,12,MOH/LA

SECTION: 6
Page: 127
Shape: (5, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,Moola \nand Kalisowe \ncommunity \nschools an...,,,,,,
1,,,Construction of 30 \nHouses in Schools,"Mafwele, Muyaya, Shalom, Mayovu, \nChungu, \nK...",6,6,6,6,6,MOE/LA
2,,,Construct 4 Weekly \nBoarding Facilities \nin...,"Kaindu, Myooye, Moobe, Muchabi, \nKalenda, ...",8,8,8,8,8,MOE/LA
3,Enhance \nAccess \nto \nQuality \nEducation,Equipment \nand \nTransport \nProcurement \nan...,Procurement of 498 \nOffice \ntables \nand \n4...,"All schools in Nalubanda, Nambala, \nSanje...",100,100,100,100,98,MOE/LA
4,,,Procurment of ICT \nSpecialised \nMatrials \...,"Mumbwa Boarding, Bulungu Day, \nNkulumazhib...",10,20,20,20,20,MOE/LA

SECTION: 7
Page: 128
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"Nalusanga, \nKalenda, \nShakumbila, \nChibulum...",,,,,,
1,,Human \nDevelopment,Recruitment \nof \n2000 Teachers \nin \nthe D...,"ALL schools in Nalubanda, Nambala, \nSanje, M...",300,600,600,250,250,MOE
2,,Infrastructure \nDevelopment,Construction \nof \n1 \nCollege \nof \nEducation,Shakumbila Chiefdom,0,0,0,0,1,MOE/LA
3,,,Adjust \n10 \nClasssroom \nStairs \nto \nAccom...,"Mumbwa boarding, Bulungu dayand \nprimary, ...",2,2,2,2,2,MOE/LA
4,,,Construction \nof \n3 \nSchools,"Mukuki in Keezwa, Shikatundwe and \nKatele in ...",0,1,1,0,0,MOELA

SECTION: 8
Page: 129
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"Nalusanga, \nKalenda, \nShakumbila, \nChibulum...",,,,,,
1,,,Procurement \nof \n2 \nUtility Vehicles,District Education Board Secretary \nOffice,0,1,1,0,0,MOE/LA
2,Objective 5: The Ministry of Education will co...,,,,,,,,,
3,"Enhance access \nto \nquality, \nequitable, \n...",Promotion \nof \nthe the Re-entry \nPolicy,Promotion \nof \nthe \nRe-entry Policy and \nE...,"All schools in Nalubanda, Nambala, \nSanje...",40,40,40,40,40,MOE/LA
4,,,Conduct \n120 \nSensitization \nMeetings \non ...,"All schools in Nalubanda, Nambala, \nSanje...",40,40,40,38,0,MOE/LA

SECTION: 9
Page: 130
Shape: (10, 10)

,0,1,2,3,4,5,6,7,8,9
0,Improve access \nto \nclean \nand \nsafe \nwat...,Infrastructure \nDevelopment \nand \nMaintenance,Drilling \nof \nBoreholes,"Mpusu, Kalwanyembe, Kamilambo, \nMumba, Mak...",20,20,20,20,20,LA
1,,,Borehole \nRehabilitation,"Kabulwebulwe, \nMulendema, \nChibuluma, \nKain...",200,200,200,200,200,LA
2,,,Borehole \nMechanisation,"Keezwa, Mpusu, Kaindu, Choma, \nChisalu, Ka...",10,10,10,10,10,LA
3,,,Construction \nof \nDams,"Mulendema, \nMumba, \nKaindu, \nNamabanga, Muc...",0,1,2,2,1,LA
4,,,Rehabilitation \nand \nMaintenance \nof \nDams,Kandesha \nMwambanabantu \nKabwanga Myooye Nam...,0,2,1,1,1,LA

SECTION: 10
Page: 131
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"Chibuluma, Shakumbila, Nangoma, \nKalenda a...",,,,,,
1,Objective 9: The Department of Social Welfare ...,,,,,,,,,
2,Enhance \nwelfare \nand \nlivelihoods \nof \np...,Social \nCash \nTransfer,Increase the number \nof beneficiaries on \n...,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",1915,2000,2000,2000,2000,Social \nWelfare
3,,Public Welfare \nAssistance \nScheme,Enhance Welfare \nand Livelihood of \nthe Poor...,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",231,200,200,200,200,Social \nWelfare
4,,Disability \nServices,Increase \nthe \nNumber of Person \nwith Di...,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",356,500,500,500,500,Social \nWelfare

SECTION: 11
Page: 132
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"Nalubanda, \nNalusanga, \nMupona, \nNangoma, \...",,,,,,
1,Objective 10: The Department of Community Deve...,,,,,,,,,
2,Enhanced \nWelfare \nand \nLivelihood \nof \nP...,Livelihood \nand \nEmpowerment \nSchemes \nDec...,Increase \nthe \nNumber \nof \nBeneficiaries \...,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",80,120,240,360,480,Department \nof \nCommunity \nDevelopmen\nt
3,,,Women and Youth \nEmpowerment \nGrants,Mupona and Nangoma Wards,61,75,150,300,450,Department \nof \nCommunity \nDevelopmen\nt
4,,Disability \nServices,Increase \nthe \nNumber of People \nwith Di...,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",72,144,216,288,360,Department \nof \nCommunity \nDevelopmen\nt

SECTION: 12
Page: 133
Shape: (5, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,,"Makebo, \nSichanzu, Kalwanyembe, \nMpusu, Chi...",,,,,,
1,,Food \nSecurity \nSupport,Increase \nthe \nNumber \nof \nBeneficiaries \...,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",1441,2882,4323,5764,7205,Department \nof \nCommunity \nDevelopmen\nt
2,Reduce \nDevelopmental \nInequalities,Gender Equality,Increase the number \nof Economic \nand \nSoc...,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",6,12,24,36,48,Department \nof \nCommunity \nDevelopmen\nt
3,,Life \nSkills \nDevelopment \nand \nResilience...,Train Women \nin \nLife \nSkills \nDevelopmen...,"Nakasaka, Nalubanda, Nalusanga, \nMupona, \n...",3,6,9,12,15,Department \nof \nCommunity \nDevelopmen\nt
4,,,Train \nGBV \nSurvivors \nin \nEntrepreneurship,"Shimbizhi, Lutale, Choma, Mumba, \nNambala,...",70,80,100,120,150,Department \nof \nCommunity \nDevelopmen\nt

In [790]:
table23_parts = []

for i, table in enumerate(tables_23):

    print("\nProcessing section:", i)

    part = normalize_implementation_section(
        table.df
    )

    if part is not None:
        table23_parts.append(part)

Processing section: 0
Original shape: (4, 8)
Could not automatically normalize section: (4, 8)

,2,3,4,5,6,7,8,9
0,Construction of two Community Lodges,"Mupona, Nambala,",0,0,1 Lodge,0,1 Lodge,MOT/ DNPW/LA/ WS/CDF
1,Construction Four Camp Sites,"Miyoye, Nambala, Matala and Nalusanga",0,2 Camp Sites,0,2 Camp Sites,0,
2,Rehabilitation and maintenance of 6 heritage s...,Mupona and Kalyanyembo,0,2,2,2,0,MOT/DNPW /NHCC
3,Establishment of 2 Community Game Ranches,Mupona and Nakasaka,0,1,0,1,0,MOT/DNPW /WWF

Processing section: 1
Original shape: (4, 10)

Processing section: 2
Original shape: (7, 8)
Could not automatically normalize section: (7, 8)

,2,3,4,5,6,7,8,9
0,Expand Infrastructure of 1st Level Hospital,Mumbwa District Hospital,0,1,0,0,0,MOH/LA
1,Rehabilitate Hospital,Mumbwa District Hospital,0,0,0,1,0,MOH/LA
2,Expansion of 4 Existing Health Centres to Mini...,"Kaindu, Lungobe, Keezwa, Naluvwi",0,1,1,1,1,MOH/LA
3,Rehabilitation of 2 Shelter for Mourners,"Mumbwa District Hospital, Nangoma Mission hosp...",0,1,1,0,0,MOH/LA
4,Securing District Hospital Boundary,Mumbwa District Hospital,0,1,0,0,0,MOH/LA
5,Completion of Existing Health Post Structures,"Tepula, Chikanda, Kanwanziba, Kantegwa, Chakwa...",0,2,2,2,2,MOH/LA
6,Rehabilitation of Housing Infrastructure,Nalubanda Myooye Lutale Kapepe Lungobe Shakumb...,2,5,5,5,5,MOH/LA

Processing section: 3
Original shape: (5, 9)

Processing section: 4
Original shape: (8, 10)

Processing section: 5
Original shape: (8, 10)

Processing section: 6
Original shape: (5, 10)

Processing section: 7
Original shape: (8, 10)

Processing section: 8
Original shape: (9, 10)

Processing section: 9
Original shape: (10, 10)

Processing section: 10
Original shape: (6, 10)

Processing section: 11
Original shape: (6, 10)

Processing section: 12
Original shape: (5, 10)

In [791]:
table23_df = pd.concat(
    table23_parts,
    ignore_index=True
)

In [792]:
table23_df = pd.concat(
    table23_parts,
    ignore_index=True
)

In [793]:
table23_df = remove_implementation_headers(
    table23_df
)

In [794]:
combined_text = (
    table23_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table23_df = table23_df[
    ~(
        combined_text.str.startswith("objective")
        | combined_text.str.startswith("goal")
    )
].reset_index(drop=True)

In [795]:
for column in [
    "strategy",
    "programme"
]:

    table23_df[column] = (
        table23_df[column]
        .replace("", pd.NA)
        .ffill()
    )

In [796]:
for column in table23_df.columns:

    table23_df[column] = (
        table23_df[column]
        .astype(str)
        .str.replace(
            r"\s+",
            " ",
            regex=True
        )
        .str.strip()
    )

In [797]:
for column in table23_df.columns:

    table23_df[column] = (
        table23_df[column]
        .astype(str)
        .str.replace(
            r"\s+",
            " ",
            regex=True
        )
        .str.strip()
    )

In [798]:
save_table_csv(
    table23_df,
    "db-unza26-csc4792_human_and_social_development_implementation_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_human_and_social_development_implementation_plan_csv.csv
Rows: 63
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_human_and_social_development_implementation_plan_csv.csv'

In [799]:
tables_24 = camelot.read_pdf(
    PDF_PATH,
    pages="134-136",
    flavor="lattice"
)

print(
    "Sections detected:",
    tables_24.n
)

for i, table in enumerate(tables_24):

    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)

    display(
        table.df
    )

Sections detected: 3

SECTION: 0
Page: 134
Shape: (5, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 3: To Promote Sustainable Management of N...,,,,,,,,,
1,Objective 1: The Ministry of Green Economy and...,,,,,,,,,
2,Strategies,Programme,Activities,Location (By Priority),2024,2025,2026,2027,2028,Responsible \nAgency
3,Strengthen \nClimate \nChange \nMitigation,Sustainable Forest \nManagement,Conduct 30 \nEducation and \nawareness \nmeeti...,"Chief Kabulwebulwe, Chief \nMumba, chief Chibu...",2 \nMeeting\ns,6 \nMeeting\ns,8 \nMeeting\ns,7 \nMeeting\ns,7 \nMeeting\ns,MGEE/DNP\nW
4,,,"To secure \n1,000,000 \nhectarage on \nCommuni...","Mumba, Sanje, Lutale, Nambala, \nMushingashi, ...","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors",MGEE/DNP\nW

SECTION: 1
Page: 135
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,Plantation \nestablishment \nand \nrehabilitat...,"Chief Kabulwebulwe, chief \nMumba, chief Chibu...","12,000 \nPlants","15,000 \nPlants","17,000 \nPlants","19,000 \nPlants","20,000 \nPlants",MGEE/DNP\nW
1,Objective 2: The Ministry of Green Economy and...,,,,,,,,,
2,Strengthen \nClimate \nChange \nMitigation,"Sustainable land, \nForest and Water \nManage...",Increase \nExtension \nServices,"Lutale, Mumba, Sanje, Nambala, \nNalusanga, Ka...",25%,50%,60%,70%,80%,MGEE
3,Objective 3: The Ministry of Green Economy and...,,,,,,,,,
4,Strengthen \nClimate \nChange \nMitigation,Sustainable Forest \nManagement,Increase \nParticipation \nand \nInvolvement o...,"Lutale, Mumba, Sanje, Nambala, \nNalusanga, Ka...",20%,50%,60%,70%,85%,MGEE/DNP\nW/WWF/TN\nC/COMACO
5,Objective 4: The Ministry of Green Economy and...,,,,,,,,,

SECTION: 2
Page: 136
Shape: (4, 10)

,0,1,2,3,4,5,6,7,8,9
0,Enhance \nNatural \nResources \nManageme\nnt,Sustainable \nWildlife and \nFisheries \nManag...,"Conduct 2,500 \nForest and \nWildlife Patrols ...","Lutale, Mumba, Sanje, Nambala, \nNalusanga, Ka...",500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,MGEE/DNP\nW
1,,,To conduct 600 \nLaw \nEnforcement \npatrols a...,Lusaka-Kaoma Road,100 \nPatrols,140 \nPatrols,120 \nPatrols,120 \nPatrols,120 \nPatrols,MGEE/DNP\nW
2,,,Recruit and \ndeploy 1000 \ncommunity \nforest...,"Lutale, Mumba, Sanje, Nambala, \nNalusanga, Ka...",200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,MGEE/DNP\nW
3,,,"Conduct 2,500 \nForest and \nWildlife Patrols ...","Lutale, Mumba, Sanje, Nambala, \nNalusanga, Ka...",500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,MGEE/DNP\nW

In [800]:
table24_parts = []

for i, table in enumerate(tables_24):

    part = normalize_implementation_section(
        table.df
    )

    if part is not None:
        table24_parts.append(part)

Original shape: (5, 10)
Original shape: (6, 10)
Original shape: (4, 10)

In [801]:
table24_parts = []

for i, table in enumerate(tables_24):

    part = normalize_implementation_section(
        table.df
    )

    if part is not None:
        table24_parts.append(part)

Original shape: (5, 10)
Original shape: (6, 10)
Original shape: (4, 10)

In [802]:
table24_parts = []

for i, table in enumerate(tables_24):

    part = normalize_implementation_section(
        table.df
    )

    if part is not None:
        table24_parts.append(part)

Original shape: (5, 10)
Original shape: (6, 10)
Original shape: (4, 10)

In [803]:
table24_df = pd.concat(
    table24_parts,
    ignore_index=True
)

In [804]:
table24_df = remove_implementation_headers(
    table24_df
)

combined_text = (
    table24_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table24_df = table24_df[
    ~(
        combined_text.str.startswith("objective")
        | combined_text.str.startswith("goal")
    )
].reset_index(drop=True)

In [805]:
for column in [
    "strategy",
    "programme"
]:

    table24_df[column] = (
        table24_df[column]
        .replace("", pd.NA)
        .ffill()
    )

In [806]:
for column in [
    "strategy",
    "programme"
]:

    table24_df[column] = (
        table24_df[column]
        .replace("", pd.NA)
        .ffill()
    )

In [807]:
display(table24_df)

,strategy,programme,activity,location_by_priority,target_2024,target_2025,target_2026,target_2027,target_2028,responsible_agency
0,Strategies,Programme,Activities,Location (By Priority),2024,2025,2026,2027,2028,Responsible Agency
1,Strengthen Climate Change Mitigation,Sustainable Forest Management,Conduct 30 Education and awareness meetings in...,"Chief Kabulwebulwe, Chief Mumba, chief Chibulu...",2 Meeting s,6 Meeting s,8 Meeting s,7 Meeting s,7 Meeting s,MGEE/DNP W
2,Strengthen Climate Change Mitigation,Sustainable Forest Management,"To secure 1,000,000 hectarage on Community For...","Mumba, Sanje, Lutale, Nambala, Mushingashi, Lu...","200,000 Hectors","200,000 Hectors","200,000 Hectors","200,000 Hectors","200,000 Hectors",MGEE/DNP W
3,Strengthen Climate Change Mitigation,Sustainable Forest Management,Plantation establishment and rehabilitation of...,"Chief Kabulwebulwe, chief Mumba, chief Chibulu...","12,000 Plants","15,000 Plants","17,000 Plants","19,000 Plants","20,000 Plants",MGEE/DNP W
4,Strengthen Climate Change Mitigation,"Sustainable land, Forest and Water Management",Increase Extension Services,"Lutale, Mumba, Sanje, Nambala, Nalusanga, Kasa...",25%,50%,60%,70%,80%,MGEE
5,Strengthen Climate Change Mitigation,Sustainable Forest Management,Increase Participation and Involvement of Trad...,"Lutale, Mumba, Sanje, Nambala, Nalusanga, Kasa...",20%,50%,60%,70%,85%,MGEE/DNP W/WWF/TN C/COMACO
6,Enhance Natural Resources Manageme nt,Sustainable Wildlife and Fisheries Management,"Conduct 2,500 Forest and Wildlife Patrols in a...","Lutale, Mumba, Sanje, Nambala, Nalusanga, Kasa...",500 Patrols,500 Patrols,500 Patrols,500 Patrols,500 Patrols,MGEE/DNP W
7,Enhance Natural Resources Manageme nt,Sustainable Wildlife and Fisheries Management,To conduct 600 Law Enforcement patrols along L...,Lusaka-Kaoma Road,100 Patrols,140 Patrols,120 Patrols,120 Patrols,120 Patrols,MGEE/DNP W
8,Enhance Natural Resources Manageme nt,Sustainable Wildlife and Fisheries Management,Recruit and deploy 1000 community forest and w...,"Lutale, Mumba, Sanje, Nambala, Nalusanga, Kasa...",200 Rangers,200 Rangers,200 Rangers,200 Rangers,200 Rangers,MGEE/DNP W
9,Enhance Natural Resources Manageme nt,Sustainable Wildlife and Fisheries Management,"Conduct 2,500 Forest and Wildlife Patrols in a...","Lutale, Mumba, Sanje, Nambala, Nalusanga, Kasa...",500 Patrols,500 Patrols,500 Patrols,500 Patrols,500 Patrols,MGEE/DNP W

In [808]:
save_table_csv(
    table24_df,
    "db-unza26-csc4792_environmental_sustainability_implementation_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_environmental_sustainability_implementation_plan_csv.csv
Rows: 10
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_environmental_sustainability_implementation_plan_csv.csv'

In [809]:
tables_25 = camelot.read_pdf(
    PDF_PATH,
    pages="137-138",
    flavor="lattice"
)

print(
    "Sections detected:",
    tables_25.n
)

for i, table in enumerate(tables_25):

    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)

    display(table.df)

Sections detected: 2

SECTION: 0
Page: 137
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 4: To Promote a Peaceful and Secure Envir...,,,,,,,,,
1,Objective 1: Zambia Police will work in collab...,,,,,,,,,
2,Strategies,Programme,Activities,Location (By Priority),Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,Responsible \nAgency
3,Strengthen \nthe Criminal \nand Justice \nSyst...,Infrastructure \nDevelopment,Costruct 6 \nPolice Posts,"Nalusanga, Nalubanda, Muchabi, \nKamilambo, ...",2,1,1,1,1,Zambia \nPolice/ LA
4,,,Rehabilitate 2 \nPolice Posts,Nambwa and Kaindu,0,1,1,0,0,Zambia \nPolice/ LA
5,,,Construct 8 \nStaff houses at \nthe Police Post,"Nalusanga, Nalubanda, Muchabi, \nKamilambo, ...",0,2,2,2,2,Zambia \nPolice/ LA
6,,,Construct 2 \nAdministration \nBlocks,Mumbwa and Nangoma \nConstituency,0,1,1,0,0,Zambia \nPolice/ LA
7,,,Procure 3 Motor \nVehicles,Mumbwa and Nangoma Police \nstation,0,1,1,1,0,Zambia \nPolice/ LA
8,,,Procure 21 \nMotor bikes for \neach station,Mumbwa and Nangoma Police \nStation,4,4,4,4,5,Zambia \nPolice/ LA

SECTION: 1
Page: 138
Shape: (2, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Human \nResource \nDevelopment,Train 100 \nofficers under \nthe Community \nC...,"Nalusanga, Nalubanda, Muchabi, \nKamilambo, Ch...",20,20,20,20,20,Zambia \nPolice/ LA
1,Strengthen \nHuman Rights \nand \nConstitution...,Capacity \nBuidling,Conduct 100 \nCommunity \nSensitisations \non ...,"Nalusanga, Nalubanda, Muchabi, \nKamilambo, ...",20,20,20,20,20,Zambia \nPolice/ LA

In [810]:
table25_parts = []

for i, table in enumerate(tables_25):

    part = normalize_implementation_section(
        table.df
    )

    if part is not None:
        table25_parts.append(part)
table25_df = pd.concat(
    table25_parts,
    ignore_index=True
)

Original shape: (9, 10)
Original shape: (2, 10)

In [811]:
table25_df = remove_implementation_headers(
    table25_df
)

combined_text = (
    table25_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table25_df = table25_df[
    ~(
        combined_text.str.startswith("objective")
        | combined_text.str.startswith("goal")
    )
].reset_index(drop=True)

In [812]:
for column in [
    "strategy",
    "programme"
]:

    table25_df[column] = (
        table25_df[column]
        .replace("", pd.NA)
        .ffill()
    )

In [813]:
for column in [
    "strategy",
    "programme"
]:

    table25_df[column] = (
        table25_df[column]
        .replace("", pd.NA)
        .ffill()
    )

In [814]:
display(table25_df)

,strategy,programme,activity,location_by_priority,target_2024,target_2025,target_2026,target_2027,target_2028,responsible_agency
0,Strategies,Programme,Activities,Location (By Priority),Target 2024,Target 2025,Target 2026,Target 2027,Target 2028,Responsible Agency
1,Strengthen the Criminal and Justice System and...,Infrastructure Development,Costruct 6 Police Posts,"Nalusanga, Nalubanda, Muchabi, Kamilambo, Chib...",2,1,1,1,1,Zambia Police/ LA
2,Strengthen the Criminal and Justice System and...,Infrastructure Development,Rehabilitate 2 Police Posts,Nambwa and Kaindu,0,1,1,0,0,Zambia Police/ LA
3,Strengthen the Criminal and Justice System and...,Infrastructure Development,Construct 8 Staff houses at the Police Post,"Nalusanga, Nalubanda, Muchabi, Kamilambo, Chib...",0,2,2,2,2,Zambia Police/ LA
4,Strengthen the Criminal and Justice System and...,Infrastructure Development,Construct 2 Administration Blocks,Mumbwa and Nangoma Constituency,0,1,1,0,0,Zambia Police/ LA
5,Strengthen the Criminal and Justice System and...,Infrastructure Development,Procure 3 Motor Vehicles,Mumbwa and Nangoma Police station,0,1,1,1,0,Zambia Police/ LA
6,Strengthen the Criminal and Justice System and...,Infrastructure Development,Procure 21 Motor bikes for each station,Mumbwa and Nangoma Police Station,4,4,4,4,5,Zambia Police/ LA
7,Strengthen the Criminal and Justice System and...,Human Resource Development,Train 100 officers under the Community Crime a...,"Nalusanga, Nalubanda, Muchabi, Kamilambo, Chib...",20,20,20,20,20,Zambia Police/ LA
8,Strengthen Human Rights and Constitutionalis m,Capacity Buidling,Conduct 100 Community Sensitisations on GBV an...,"Nalusanga, Nalubanda, Muchabi, Kamilambo, Chib...",20,20,20,20,20,Zambia Police/ LA

In [815]:
save_table_csv(
    table25_df,
    "db-unza26-csc4792_good_governance_implementation_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_good_governance_implementation_plan_csv.csv
Rows: 9
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_good_governance_implementation_plan_csv.csv'

In [816]:
files_to_check = [
    "db-unza26-csc4792_economic_transformation_and_job_creation_implementation_plan.csv",
    "db-unza26-csc4792_human_and_social_development_implementation_plan.csv",
    "db-unza26-csc4792_environmental_sustainability_implementation_plan.csv",
    "db-unza26-csc4792_good_governance_implementation_plan.csv"
]

for filename in files_to_check:

    path = os.path.join(
        OUTPUT_DIR,
        filename
    )

    print("\n" + "=" * 100)

    if not os.path.exists(path):

        print("❌ MISSING:", filename)
        continue

    df = pd.read_csv(path)

    print("✅", filename)
    print("Shape:", df.shape)

    display(df.head(5))

====================================================================================================
❌ MISSING: db-unza26-csc4792_economic_transformation_and_job_creation_implementation_plan.csv

====================================================================================================
❌ MISSING: db-unza26-csc4792_human_and_social_development_implementation_plan.csv

====================================================================================================
❌ MISSING: db-unza26-csc4792_environmental_sustainability_implementation_plan.csv

====================================================================================================
❌ MISSING: db-unza26-csc4792_good_governance_implementation_plan.csv

In [817]:
import os

OUTPUT_DIR = "/content/csv_output"

# Create the folder if it doesn't already exist
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("CSV output folder:", OUTPUT_DIR)

CSV output folder: /content/csv_output

In [818]:
tables_26 = camelot.read_pdf(
    PDF_PATH,
    pages="160",
    flavor="lattice"
)

print("Tables detected:", tables_26.n)

for i, table in enumerate(tables_26):
    print("\nINDEX:", i)
    print("Shape:", table.df.shape)
    display(table.df)

Tables detected: 1

INDEX: 0
Shape: (12, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,S/N,Details,Annual \nBudget \n2020,Annual \nRevenue \nCollected,%,Annual \nBudget \n2020,Annual \nRevenue \nCollected,%,Annual \nBudget \n2020,Annual \nRevenue \nCollected,%
1,1,Owner’s Rates,"2,699,838.00","1,029,742.00",38,"2,169,041.00","1737,342.00",80,"2,028,062.00","1,724,334.98",85
2,2,Local Taxes,"120,300.00","67,354.00",56,"140,010.00","67,827.00",48,"45,000.00","47,103.50",105
3,3,Fees And \nCharges,"3,535,060.00","2,735,679.00",77,"4,623,733.00","3,852,416.00",83,"3,879,548.00","3,510,756.75",90
4,4,Licences,"128,700.00","25,660.00",20,"188,250.00","25,825.00",14,"34,849.00","66,070.00",190
5,5,Levies,"788,200.00","1,036,561.00",132,"978,500.00","1,326,151.00",136,"1,326,500.00","1,699,599.00",128
6,6,Permits,"833,250.00","291,326.00",35,"914,269.00","288,501.00",32,"260,686.00","611,971.20",235
7,7,Charges \n(Development),"4,871,000.00","696,350.00",14,"4,960,000.00","233,710.00",5,"6,159,400.00","48,050.00",1
8,8,Other Income,0,"61,707.00",,"864,341.00","778,454.00",90,"1,159,961.00","909,590.14",78
9,9,National \nSupport,"13,182,137.00","16,757,605.00",127,"13,182,138.00","13,174,979.00",100,"13,182,133.00","11,051,041.04",84
10,10,Grant in Liue \nof Rates,0,,0,0,0,0,"880,000.00",0,0
11,,Grand Total,"26,158,485.00","23,257,984.00",89,"28,020,282.00","21,485,205.00",77,"29,981,701.74","22,989,169.35",77

In [819]:
tables_26 = camelot.read_pdf(
    PDF_PATH,
    pages="160",
    flavor="lattice"
)

print("Tables detected:", tables_26.n)

for i, table in enumerate(tables_26):
    print("\nINDEX:", i)
    print("Shape:", table.df.shape)
    display(table.df)

Tables detected: 1

INDEX: 0
Shape: (12, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,S/N,Details,Annual \nBudget \n2020,Annual \nRevenue \nCollected,%,Annual \nBudget \n2020,Annual \nRevenue \nCollected,%,Annual \nBudget \n2020,Annual \nRevenue \nCollected,%
1,1,Owner’s Rates,"2,699,838.00","1,029,742.00",38,"2,169,041.00","1737,342.00",80,"2,028,062.00","1,724,334.98",85
2,2,Local Taxes,"120,300.00","67,354.00",56,"140,010.00","67,827.00",48,"45,000.00","47,103.50",105
3,3,Fees And \nCharges,"3,535,060.00","2,735,679.00",77,"4,623,733.00","3,852,416.00",83,"3,879,548.00","3,510,756.75",90
4,4,Licences,"128,700.00","25,660.00",20,"188,250.00","25,825.00",14,"34,849.00","66,070.00",190
5,5,Levies,"788,200.00","1,036,561.00",132,"978,500.00","1,326,151.00",136,"1,326,500.00","1,699,599.00",128
6,6,Permits,"833,250.00","291,326.00",35,"914,269.00","288,501.00",32,"260,686.00","611,971.20",235
7,7,Charges \n(Development),"4,871,000.00","696,350.00",14,"4,960,000.00","233,710.00",5,"6,159,400.00","48,050.00",1
8,8,Other Income,0,"61,707.00",,"864,341.00","778,454.00",90,"1,159,961.00","909,590.14",78
9,9,National \nSupport,"13,182,137.00","16,757,605.00",127,"13,182,138.00","13,174,979.00",100,"13,182,133.00","11,051,041.04",84
10,10,Grant in Liue \nof Rates,0,,0,0,0,0,"880,000.00",0,0
11,,Grand Total,"26,158,485.00","23,257,984.00",89,"28,020,282.00","21,485,205.00",77,"29,981,701.74","22,989,169.35",77

In [820]:
table26_df = clean_dataframe(
    tables_26[0].df
)

display(table26_df)
print(table26_df.shape)

,0,1,2,3,4,5,6,7,8,9,10
0,S/N,Details,Annual Budget 2020,Annual Revenue Collected,%,Annual Budget 2020,Annual Revenue Collected,%,Annual Budget 2020,Annual Revenue Collected,%
1,1,Owner’s Rates,"2,699,838.00","1,029,742.00",38,"2,169,041.00","1737,342.00",80,"2,028,062.00","1,724,334.98",85
2,2,Local Taxes,"120,300.00","67,354.00",56,"140,010.00","67,827.00",48,"45,000.00","47,103.50",105
3,3,Fees And Charges,"3,535,060.00","2,735,679.00",77,"4,623,733.00","3,852,416.00",83,"3,879,548.00","3,510,756.75",90
4,4,Licences,"128,700.00","25,660.00",20,"188,250.00","25,825.00",14,"34,849.00","66,070.00",190
5,5,Levies,"788,200.00","1,036,561.00",132,"978,500.00","1,326,151.00",136,"1,326,500.00","1,699,599.00",128
6,6,Permits,"833,250.00","291,326.00",35,"914,269.00","288,501.00",32,"260,686.00","611,971.20",235
7,7,Charges (Development),"4,871,000.00","696,350.00",14,"4,960,000.00","233,710.00",5,"6,159,400.00","48,050.00",1
8,8,Other Income,0,"61,707.00",,"864,341.00","778,454.00",90,"1,159,961.00","909,590.14",78
9,9,National Support,"13,182,137.00","16,757,605.00",127,"13,182,138.00","13,174,979.00",100,"13,182,133.00","11,051,041.04",84
10,10,Grant in Liue of Rates,0,,0,0,0,0,"880,000.00",0,0
11,,Grand Total,"26,158,485.00","23,257,984.00",89,"28,020,282.00","21,485,205.00",77,"29,981,701.74","22,989,169.35",77

(12, 11)

In [821]:
table26_columns = [
    "serial_number",
    "details",
    "annual_budget_2020",
    "annual_revenue_collected_2020",
    "percent_2020",
    "annual_budget_2021",
    "annual_revenue_collected_2021",
    "percent_2021",
    "annual_budget_2022",
    "annual_revenue_collected_2022",
    "percent_2022"
]

In [822]:
if table26_df.shape[1] == 11:
    table26_df.columns = table26_columns
else:
    print("Unexpected shape:", table26_df.shape)
    display(table26_df)
table26_df = table26_df[
    ~table26_df["details"]
    .astype(str)
    .str.lower()
    .isin(["details", ""])
].reset_index(drop=True)

In [823]:
numeric_cols_26 = [
    "annual_budget_2020",
    "annual_revenue_collected_2020",
    "percent_2020",
    "annual_budget_2021",
    "annual_revenue_collected_2021",
    "percent_2021",
    "annual_budget_2022",
    "annual_revenue_collected_2022",
    "percent_2022"
]

for col in numeric_cols_26:
    table26_df[col] = (
        table26_df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    table26_df[col] = pd.to_numeric(
        table26_df[col],
        errors="coerce"
    )

In [824]:
save_table_csv(
    table26_df,
    "db-unza26-csc4792_revenue_collection_for_mumbwa_town_council.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_revenue_collection_for_mumbwa_town_council_csv.csv
Rows: 11
Columns: 11

'db-unza26-csc4792_db_unza26_csc4792_revenue_collection_for_mumbwa_town_council_csv.csv'

In [825]:
tables_27 = camelot.read_pdf(
    PDF_PATH,
    pages="162",
    flavor="lattice"
)

print("Tables detected:", tables_27.n)

for i, table in enumerate(tables_27):
    print(i, table.df.shape)
    display(table.df)

Tables detected: 1
0 (11, 6)

,0,1,2,3,4,5
0,Income Details/Period,Year 1,Year 2,Year 3,Year 4,Year 5
1,Owners Rates,"2,028,062.00","2,621,394.00","2,732,200.00","3,100,000.00","3,520,000.00"
2,Local Tax,"45,000.00","75,000.00","105,000.00","120,000.00","152,000.00"
3,Fees & Charges,"3,879,548.00","5,500,269.00","7,240,000.00","8,200,000.00","10,120,000.00"
4,License,"66,070.00","2,380,300.00","1,280,100.00","1,500,000.00","2,500,000.00"
5,Levies,"1,326,500.00","2,361,156.00","2,420,000.00","2,500,100.00","2,600,000.00"
6,Permits,"260,686.00","5,125,403.00","3,200,000.00","3,500,000.00","3,700,000.00"
7,Charges,"6,159,400.00","4,415,300.00","4,200,000.00","4,500,000.00","4,800,000.00"
8,National Support,"13,182,133.00","15,204,954.00","15,830,000.00","16,200,000.00","17,340,000.00"
9,Local Development Fund - CDF,"47,479,821.82","56,627,804.02","56,627,804.02","56,627,804.02","56,627,804.00"
10,Total,"74,427,220.82","94,311,580.00","93,635,104.02","96,247,904.02","101,359,804.00"

In [826]:
table27_df = clean_dataframe(
    tables_27[0].df
)

table27_df.columns = [
    "income_details",
    "year_1",
    "year_2",
    "year_3",
    "year_4",
    "year_5"
]

if "income" in str(table27_df.iloc[0, 0]).lower():
    table27_df = table27_df.iloc[1:].reset_index(drop=True)

In [827]:
year_cols = [
    "year_1",
    "year_2",
    "year_3",
    "year_4",
    "year_5"
]

for col in year_cols:
    table27_df[col] = (
        table27_df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    table27_df[col] = pd.to_numeric(
        table27_df[col],
        errors="coerce"
    )

In [828]:
save_table_csv(
    table27_df,
    "db-unza26-csc4792_revenue_projection_for_first_five_years_of_implementation_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_revenue_projection_for_first_five_years_of_implementation_plan_csv.csv
Rows: 10
Columns: 6

'db-unza26-csc4792_db_unza26_csc4792_revenue_projection_for_first_five_years_of_implementation_plan_csv.csv'

In [829]:
tables_28 = camelot.read_pdf(
    PDF_PATH,
    pages="163",
    flavor="lattice"
)

print("Tables detected:", tables_28.n)

for i, table in enumerate(tables_28):
    print(i, table.df.shape)
    display(table.df)

Tables detected: 1
0 (9, 6)

,0,1,2,3,4,5
0,Income \nDetails/Period,Year 1,Year 2,Year 3,Year 4,Year 5
1,Owners Rates,"2,028,062.00","2,621,394.00","2,732,200.00","3,100,000.00","3,520,000.00"
2,Local Tax,"45,000.00","75,000.00","105,000.00","120,000.00","152,000.00"
3,Fees & Charges,"3,879,548.00","5,500,269.00","7,240,000.00","8,200,000.00","10,120,000.00"
4,License,"66,070.00","2,380,300.00","1,280,100.00","1,500,000.00","2,500,000.00"
5,Levies,"1,326,500.00","2,361,156.00","2,420,000.00","2,500,100.00","2,600,000.00"
6,Permits,"260,686.00","5,125,403.00","3,200,000.00","3,500,000.00","3,700,000.00"
7,Charges,"6,159,400.00","4,415,300.00","4,200,000.00","4,500,000.00","4,800,000.00"
8,Total,"13,765,266.00","22,478,822.00","21,177,300.00","23,420,100.00","27,392,000.00"

In [830]:
tables_28 = camelot.read_pdf(
    PDF_PATH,
    pages="163",
    flavor="lattice"
)

print("Tables detected:", tables_28.n)

for i, table in enumerate(tables_28):
    print(i, table.df.shape)
    display(table.df)

Tables detected: 1
0 (9, 6)

,0,1,2,3,4,5
0,Income \nDetails/Period,Year 1,Year 2,Year 3,Year 4,Year 5
1,Owners Rates,"2,028,062.00","2,621,394.00","2,732,200.00","3,100,000.00","3,520,000.00"
2,Local Tax,"45,000.00","75,000.00","105,000.00","120,000.00","152,000.00"
3,Fees & Charges,"3,879,548.00","5,500,269.00","7,240,000.00","8,200,000.00","10,120,000.00"
4,License,"66,070.00","2,380,300.00","1,280,100.00","1,500,000.00","2,500,000.00"
5,Levies,"1,326,500.00","2,361,156.00","2,420,000.00","2,500,100.00","2,600,000.00"
6,Permits,"260,686.00","5,125,403.00","3,200,000.00","3,500,000.00","3,700,000.00"
7,Charges,"6,159,400.00","4,415,300.00","4,200,000.00","4,500,000.00","4,800,000.00"
8,Total,"13,765,266.00","22,478,822.00","21,177,300.00","23,420,100.00","27,392,000.00"

In [831]:
table28_df = clean_dataframe(
    tables_28[0].df
)

table28_df.columns = [
    "income_details",
    "year_1",
    "year_2",
    "year_3",
    "year_4",
    "year_5"
]

if "income" in str(table28_df.iloc[0, 0]).lower():
    table28_df = table28_df.iloc[1:].reset_index(drop=True)

In [832]:
for col in year_cols:
    table28_df[col] = (
        table28_df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    table28_df[col] = pd.to_numeric(
        table28_df[col],
        errors="coerce"
    )

In [833]:
save_table_csv(
    table28_df,
    "db-unza26-csc4792_locally_generated_revenue.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_locally_generated_revenue_csv.csv
Rows: 8
Columns: 6

'db-unza26-csc4792_db_unza26_csc4792_locally_generated_revenue_csv.csv'

In [834]:
tables_29 = camelot.read_pdf(
    PDF_PATH,
    pages="164",
    flavor="lattice"
)

print("Tables detected:", tables_29.n)

for i, table in enumerate(tables_29):
    display(table.df)

Tables detected: 1

,0,1,2,3,4,5
0,Years,2021,2022,2023,2024,2025
1,Capital \n(20% \nof \nLGEF),"2,753,053.20","4,495,764.40","4,235,460.00","4,684,020.00","5,478,400.00"

In [835]:
tables_29 = camelot.read_pdf(
    PDF_PATH,
    pages="164",
    flavor="lattice"
)

print("Tables detected:", tables_29.n)

for i, table in enumerate(tables_29):
    display(table.df)

Tables detected: 1

,0,1,2,3,4,5
0,Years,2021,2022,2023,2024,2025
1,Capital \n(20% \nof \nLGEF),"2,753,053.20","4,495,764.40","4,235,460.00","4,684,020.00","5,478,400.00"

In [836]:
table29_df = clean_dataframe(
    tables_29[0].df
)

display(table29_df)
table29_df.columns = [
    "category",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025"
]

if "years" in str(table29_df.iloc[0, 0]).lower():
    table29_df = table29_df.iloc[1:].reset_index(drop=True)

,0,1,2,3,4,5
0,Years,2021,2022,2023,2024,2025
1,Capital (20% of LGEF),"2,753,053.20","4,495,764.40","4,235,460.00","4,684,020.00","5,478,400.00"

In [837]:
table29_df.columns = [
    "category",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025"
]

if "years" in str(table29_df.iloc[0, 0]).lower():
    table29_df = table29_df.iloc[1:].reset_index(drop=True)

In [838]:
table29_long["capital_20_percent_lgef"] = (
    table29_long["capital_20_percent_lgef"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

table29_long["capital_20_percent_lgef"] = pd.to_numeric(
    table29_long["capital_20_percent_lgef"],
    errors="coerce"
)
save_table_csv(
    table29_long,
    "db-unza26-csc4792_local_government_equalization_fund_20_percent_capital_projects.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_local_government_equalization_fund_20_percent_capital_projects_csv.csv
Rows: 5
Columns: 2

'db-unza26-csc4792_db_unza26_csc4792_local_government_equalization_fund_20_percent_capital_projects_csv.csv'

In [839]:
table29_long = pd.DataFrame({
    "year": [2021, 2022, 2023, 2024, 2025],
    "capital_20_percent_lgef": [
        table29_df.loc[0, "2021"],
        table29_df.loc[0, "2022"],
        table29_df.loc[0, "2023"],
        table29_df.loc[0, "2024"],
        table29_df.loc[0, "2025"]
    ]
})

In [840]:
tables_30 = camelot.read_pdf(
    PDF_PATH,
    pages="165-185",
    flavor="lattice"
)

print("Sections detected:", tables_30.n)

for i, table in enumerate(tables_30):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df.head())

Sections detected: 21

SECTION: 0
Page: 165
Shape: (10, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 1: To become an industrialized and diver...,,,,,,,,,
1,Objective 1: The Ministry of Agriculture will ...,,,,,,,,,
2,Strategies,Activities,Input,Cost (ZMK),,,,,Proposed source of \nfunding,Source of \nInformation
3,,,,2024,2025,2026,2027,2028,,
4,Increase \nAgricultural \nProduction \nand \nP...,Construct 25 \nCamp houses,Human \nresource,"8,750,000","9,625,000","10,587,500","11,646,250","12,810,875",LA/MoA,MoA

SECTION: 1
Page: 166
Shape: (8, 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,,Construct 5 \nGrain Storage \nSheds,,Human \nresource,,"1,000,000","1,100,000","1,210,000","1,331,000","1,464,100","MoA, Local \nauthority (CDF) & \ndonor",MoA
1,,,,TOTAL,,"12,095,000","12,204,500","14,624,950","14,767,445","15,975,537",,
2,Objective 2: The Ministry of Agriculture will ...,,,,,,,,,,,
3,Improve \nagricultural \nproduction \nand \npr...,Construct and \noperationalize \n5 commercial ...,Human \nresource,,"1,300,000",,"1,430,000","1,573,000","1,730,300","1,903,330","MoA, Local \nauthority (CDF) & \nprivate sector",MoA
4,,Increase the \nnumber of \nbeneficiaries \nin ...,Human \nresource,,"350,000",,"385,000","423,500","465,850","512,435",MoA,MoA

SECTION: 2
Page: 167
Shape: (9, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,,acquire \nprocessing \nequipment,,,,,,,,,
1,,Farmer \nsensitizations \non tractor \nmechani...,Human \nresource,"20,000",,"22,000","24,200","26,620","29,282",MoA & private \nsector,MoA
2,,Farmer \nsensitizations \non animal \ndraught ...,Human \nresource,"20,000",,"22,000","24,200","26,620","29,282",MoA & private \nsector,MoA
3,,Farmer \nsensitizations \non crop \nprocessing...,Human \nresource,"20,000",,"22,000","24,200","26,620","29,282",MoA & private \nsector,MoA
4,Objective 3: The Ministry of Agriculture will ...,,,,,,,,,,

SECTION: 3
Page: 168
Shape: (10, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,,Schemes land \naudit,,,,,,,,,
1,,Conduct \nInventory of \nhectares \nunder \npr...,Human \nresource,"80,000",,"88,000","96,800","106,480","117,128",MoA & Private \nsector,MoA
2,,Establish a \nnew farm \nblock,Human \nresource,"200,000",,"220,000","242,000","266,200","292,820",MoA & Private \nsector,MoA
3,,,TOTAL,"2,362,000",,"2,598,200","2,858,020","3,143,822","3,458,204",,
4,Objective 5: The Ministry of Agriculture will ...,,,,,,,,,,

SECTION: 4
Page: 169
Shape: (12, 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,,Refresher \nTrainings,,,,,,,,,,,
1,,Set \ndemonstration \nplots on crop \ndiversif...,Human \nresource,"50,000","55,000",,"60,500","66,550","73,205",MoA,,MoA,
2,,Training \nMaterials \ndevelopment,Human \nresource,"36,000","39,600",,"43,560","47,916","52,708",MoA,,MoA,
3,,Electronic \nExtension \nPlatform \noperationa...,Human \nresource,"30,000","33,000",,"36,300","39,930","43,923",MoA,,MoA,
4,,Farmer \nRegistration,Human \nresource,"40,000","44,000",,"48,400","53,240","58,564",MoA,,MoA,

SECTION: 5
Page: 170
Shape: (10, 10)

,0,1,2,3,4,5,6,7,8,9
0,and \nproductivity,Estalishment \nof 4 Irrigation \nSchemes,Human \nresource,0,"4,500,000","4,950,000","5,445,000","5,989,500","MoA, Local \nauthority (CDF) \n& private sector",MoA
1,,Construct 6 \nDams,Human \nresource,"5,000,000","5,500,000","6,050,000","6,655,000","7,320,500","MoA, Local \nauthority (CDF) \n& private sector",MoA
2,,Rehabilitate 5 \nDams,Human \nresource,"4,000,000","4,400,000","4,840,000","5,324,000","5,856,400","MoA, Local \nauthority (CDF) \n& private sector",MoA
3,,Construction \nof Weirs,Human \nresource,0,0,"760,000",0,0,"MoA, Local \nauthority (CDF) \n& private sector",MoA
4,,Rehabilitation \nof Weirs,Human \nresource,0,"50,000",0,0,0,"MoA, Local \nauthority (CDF) \n& private sector",MoA

SECTION: 6
Page: 171
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,Objective 8: The Ministry of Fisheries and Liv...,,,,,,,,,
1,Improve \nagricultural \nproduction \nand \npr...,Construction \nof 10 plunge \ndip tanks with \...,Human \nResource,"1,280,000","1,408,000","1,548,800","1,703,680","1,874,048",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
2,,Construction \nof 1 District \nLaboratory,Human \nResource,0,0,0,"1,000,000",0,Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
3,,Establishment \nand \nConstruction \nof 4 \nBi...,Human \nResource,"187,500","206,250","226,875","249,563",0,Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
4,,"Vaccination \nof 130, 000 \ncattle against \nF...",Human \nResource,"400,000","440,000","484,000","532,400","585,640",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock

SECTION: 7
Page: 172
Shape: (5, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Rehabilitation \nof the \nexisting \nquarantin...,Human \nResource,0,0,"600,000",0,0,Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
1,,"Foot and \nMouth \nDisease, \nContagious \nBov...",Human \nResource,"100,000","110,000","121,000","133,100","146,410",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
2,,Mobile \nPatrols,Human \nResource,"100,000","110,000","121,000","133,100","146,410",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
3,,Trypanosomi\nasis and \nTsetse fly \nsurveilla...,Human \nResource,"200,000","220,000","242,000","266,200","292,820",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
4,,Formation 16 \nVillage \nMangement \nCommittees,Human \nResource,"37,500","41,250","45,375","49,913","54,904",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock

SECTION: 8
Page: 173
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Issuance of \n1000 Fishing \nLicenses,Human \nResource,"20,000","22,000","24,200","26,620","29,282",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
1,,Sensitization \nof 500 \nfarmers on \nsustaina...,Human \nResource,"40,000","44,000","48,400","53,240","58,564",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
2,,Installation of \n3 ice plants,Human \nResource,0,0,"100,000","110,000","121,000",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
3,,"420,000 \nFingerling \nStocking in \ndams",Human \nResource,"84,000","92,400","101,640","111,804","122,984",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
4,,Construction \nof 3 Fish \nHatcheries,Human \nResource,0,"833,333",0,"1,000,000","1,100,000",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock

SECTION: 9
Page: 174
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Establishment \nand \nimprovement \nof 100 \nr...,Human \nResource,"80,000","K88,000","96,800","106,480","117,128",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
1,,stocking and \nrestocking of \nsmall \nlivestock,Human \nResource,"2,000,000","2,200,000","2,420,000","2,662,000","2.928,200",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
2,,Establishment \nof 3 AI \nsatelite \ncenters,Human \nResource,"616,667",0,"740,000",0,"814,000",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
3,,Establishment \nof a livestock \nservice and \...,Human \nResource,"1,100,000","1,210,000","1,331,000","1,464,100","1,610,510",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
4,,Rehabilitation \nOf 6 Dams,Human \nResource,"3,333,333","3,666,667","4,033,333","4,436,667","4,880,333",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock

SECTION: 10
Page: 175
Shape: (7, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,,,TOTAL,"K12,121,85\n7","K13,489,043",,"K15,361,280","K19,423,409","K18,605,231",,
1,Objective 10: The Ministry of Fisheries and Li...,,,,,,,,,,
2,Improve \nagricultural \nproduction \nand \npr...,Construction \nof 20 morden \ncamp houses,Human \nResource,"3,120,000",,"3,432,000","3,775,200","4,152,720","4,567,992",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
3,,Construction \nof 12 office \nblocks,Human \nResource,"1,360,000",,"1,496,000","1,645,600","1,810,160","1,991,176",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
4,,Rehabilitation \nOf 6 Camp \nHouses,Human \nResource,"350,000",,"385,000","423,500","465,850","512,435",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock

SECTION: 11
Page: 176
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,,outbreak \nresponse,,,,,,,,
1,,procurement \nof 40 motor \nbikes,Human \nResource,"960,000","1,056,000","1,161,600","1,277,760","1,405,536",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
2,,procurement \nof 2 motor \nvehicles for \nDist...,Human \nResource,"2,800,000",0,"1,400,000",0,"1,540,000",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
3,,Development \nand printing \nof 2500 \nExtensi...,Human \nResource,"100,000","110,000","121,000","133,100","146,410",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
4,,Trainings in \nAnimal \nHealth and \nLivestock...,Human \nResource,"20,000","22,000","24,200","26,620","29,282",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock

SECTION: 12
Page: 177
Shape: (7, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,,"Conduct \n10,000 meat \ninspections \nand 20 \...",Human \nResource,"200,000",,"K220,000","K242,000","K266,200","K292,820",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
1,,,TOTAL,"9,275,000",,"6,820,000","9,232,000","8,252,200","11,013,420",,
2,Objective 11: The Ministry of Fisheries and Li...,,,,,,,,,,
3,Promote \nvalue \naddition and \nmanufacturi\nng,Establishment \nof a Bulking \nCentre and \nsl...,Human \nResource,"350,000",,"385,000","423,500","465,850","512,435",Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock
4,,Construction \nof Milk \ncollection \ncenter,Human \nResource,0,,0,"1,750,000",0,0,Local \nGovernment \n(CDF)/ Ministry \nof Fish...,Local \nMinistry of \nFisheries and \nLivestock

SECTION: 13
Page: 178
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,,,TOTAL,"400,000","440,000","2,234,000","1,032,400","585,640",,
1,Objective 12: ZESCO will collaborate with stak...,,,,,,,,,
2,To enhance \nimproved \nelectricity \naccess t...,Connection \nto national \ngrid,Human \nResource,"4,800,000","5,280,000","5,808,000","6,388,800","7,027,680",Local \nAuthority/ZESCO,ZESCO
3,,Connection \nof residences \nto off grid \nenergy,Human \nResource,"4,400,000","4,840,000","5,324,000","5,856,400","6,442,040",Local \nAuthority/ZESCO,ZESCO
4,,,TOTAL,"K9,200,000","K10,120,000","K11,132,000","K12,245,200","K13,469,720",,

SECTION: 14
Page: 179
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Construction \nof gravel \ntownship \nroads,Human \nResource,"8,000,000","8,800,000","9,680,000","10,648,000","11,712,800",Local Authority & \nNRFA,LA
1,,Rehabilitatio\nn and \nmaintenance \nof inter ...,Human \nResource,"420,000,00\n0","462,000,000","508,200,000","559,020,000","614,922,000",Local Authority & \nNRFA,LA
2,,Rehabilitatio\nn and \nmaintenance \nof feeder...,Human \nResource,"150,000,00\n0","165,000,000","181,500,000","199,650,000","219,615,000","Local Authority, \nRDA & NRFA",LA
3,,Construction \nof feeder \nroads,Human \nResource,"150,000,00\n0","165,000,000","181,500,000","199,650,000","219,615,000","Local Authority, \nRDA & NRFA",LA
4,,Purchase of \nroad \nconstruction \nequipment,Human \nResource,"5,000,000","5,500,000","6,050,000","6,655,000","7,320,500",Local Authority,LA

SECTION: 15
Page: 180
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Upgrading of \nearth and \ngravel rural \nroad...,Human \nResource,"120,000,00\n0","132,000,000","145,200,000","159,720,000","175,692,000","Local Authority, \nRDA & NRFA",LA
1,,Rehabilitatio\nn and \nMaintenance \nof rural ...,Human \nResource,"80,000,000","88,000,000","96,800,000","106,480,000","117,128,000","Local Authority, \nRDA & NRFA",LA
2,Enhance \nDigital \nCapacity,Installation \nof \ntelecommuni\ncation towers...,Human \nResource,"1,600,000","1,760,000","1,936,000","2,129,600","2,342,560 Ministry of",Technology and \nScience,LA
3,,Installation \nof radio and \ntelevision \ntra...,Human \nResource,"1,200,000","1,320,000","1,452,000","1,597,200","1,756,920 Ministry of",Technology and \nScience & \nTelecomunication ...,Ministry of \nTechnology \nand Science \n& ZICTA
4,,Construction \nand \nestablishment \nof a loca...,Human \nResource,"8,000,000","8,800,000","9,680,000","10,648,000","11,712,800 Ministry of",Technology and \nScience & \nTelecomunication ...,"Ministry of \nTechnology \nand Science, \nZICT..."

SECTION: 16
Page: 181
Shape: (3, 10)

,0,1,2,3,4,5,6,7,8,9
0,Promote \nTourism \nDiversifica\ntion,clearing and \nbecon \nerection to \ndermacate...,,,,,,,,
1,,Translation \nof the \nGeneral \nManagement \n...,Human \nResource,"2,000,000","2,200,000","2,420,000","2,662,000","2,928,200",DNPW/WWF/ICF\n/USAID/TNC,MOT/DNPW
2,,Sensitization \nmeetings on \nland \nallocatio...,Human \nResource,"15,000,000","16,500,000","18,150,000","19,965,000","21,961,500",DNPW/WWF/ICF\n/USAID/TNC,MOT/DNPW

SECTION: 17
Page: 182
Shape: (3, 10)

,0,1,2,3,4,5,6,7,8,9
0,,of Wildlife \nCorridor \nsigns to \navoid \nco...,,,,,,,,
1,,Installation \nof Elephant \nRestraining \nLin...,Human \nResource,"6,000,000","6,600,000","7,260,000","7,986,000","8,784,600",DNPW/WWF/ICF\n/USAID/TNC,MOT/DNPW
2,,Conducting \nConservation \nEducation \nclubs ...,Human \nResource,"1,600,000","1,760,000","1,936,000","2,129,600","2,342,560",DNPW/WWF/ICF\n/USAID/TNC,MOT/DNPW

SECTION: 18
Page: 183
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,,"existance, \ntraining \nmaterials and \nlogistics",,,,,,,,
1,Objective 15: National Parks and Wildlife will...,,,,,,,,,
2,Promote \nTourism \nDiversifica\ntion,Construction \nof a \ncommunity \nWildlife \nM...,Human \nResource,"30,000,000","33,000,000","36,300,000","39,930,000","43,923,000",CDF/NMB/WWF/\nDNPW,MOT/DNPW
3,,Lobbying \nNHCC for \nfinancial \nsupport to \...,Human \nResource,"40,000,000","44,000,000","48,400,000","53,240,000","K58,564,000",MOT/NHCC/CDF,MOT/DNPW
4,,Upgrading of \ndistrict \ncouncil lodge \nto h...,Human \nResource,"20,000,000","22,000,000","24,200,000","26,620,000","29,282,000",CDF/WS,LA

SECTION: 19
Page: 184
Shape: (5, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Construction \nof \ncommunity \nCamp sites \n...,Human \nResource,"160,000,00","176,000,000","193,600,000","212,960,000","234,256,000",CDF/NMB/WWF/\nDNPW,MOT/DNPW
1,,,TOTAL,"300,000,000","K30,000,000","363,000,000","399,300,000","439,230,000",,
2,,Development \nof Tourism \nmaps that \nwill be...,Human \nResource,"2,000,000","2,200,000","2,420,000","2,662,000","2,928,200",MOT/ZTA/DNP\nW/CRBs,MOT/DNPW
3,,Conduct \nTourism \nlocal events \nshows in th...,Human \nResource,"5,000,000","5,500,000","6,050,000","6,655,000","7,320,500",MOT/ZTA/DNP\nW/CRBs,MOT/DNPW
4,,Airing of \nradio and TV \nprograms to \nmarke...,Human \nResource,"20,000,000","22,000,000","24,200,000","26,620,000","29,282,000",MOT/ZTA/DNP\nW/NHCC,MOT/DNPW

SECTION: 20
Page: 185
Shape: (2, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Setting up of \nart markets \nand curios in \n...,Human \nResource,"5,000,000","5,500,000","6,050,000","6,655,000","7,320,500",MOT/ZTA/DNP\nW,MOT/DNPW
1,,,TOTAL,"32,000,000","35,200,000","38,720,000","42,592,000","46,851,200",,

In [841]:
capital_columns = [
    "strategy",
    "activity",
    "input",
    "cost_2024",
    "cost_2025",
    "cost_2026",
    "cost_2027",
    "cost_2028",
    "proposed_source_of_funding",
    "source_of_information"
]

In [842]:
def normalize_capital_section(df):

    df = clean_dataframe(df)

    print("Original shape:", df.shape)

    if df.shape[1] == 10:
        df.columns = capital_columns
        return df

    if df.shape[1] == 11:
        empty_counts = (
            df.replace("", pd.NA)
            .isna()
            .sum()
        )

        emptiest_col = empty_counts.idxmax()

        df = df.drop(columns=[emptiest_col])

        if df.shape[1] == 10:
            df.columns = capital_columns
            return df

    if df.shape[1] == 9:
        df.insert(
            0,
            "strategy",
            ""
        )

        df.columns = capital_columns
        return df

    print("⚠ Could not normalize:", df.shape)
    display(df)

    return None

In [843]:
table30_parts = []

for i, table in enumerate(tables_30):

    print("\nProcessing:", i)

    part = normalize_capital_section(
        table.df
    )

    if part is not None:
        table30_parts.append(part)

Processing: 0
Original shape: (10, 10)

Processing: 1
Original shape: (8, 12)
⚠ Could not normalize: (8, 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,,Construct 5 Grain Storage Sheds,,Human resource,,"1,000,000","1,100,000","1,210,000","1,331,000","1,464,100","MoA, Local authority (CDF) & donor",MoA
1,,,,TOTAL,,"12,095,000","12,204,500","14,624,950","14,767,445","15,975,537",,
2,Objective 2: The Ministry of Agriculture will ...,,,,,,,,,,,
3,Improve agricultural production and productivity,Construct and operationalize 5 commercial agro...,Human resource,,"1,300,000",,"1,430,000","1,573,000","1,730,300","1,903,330","MoA, Local authority (CDF) & private sector",MoA
4,,Increase the number of beneficiaries in the FI...,Human resource,,"350,000",,"385,000","423,500","465,850","512,435",MoA,MoA
5,,Link more farmers to machinery leasing institu...,Human resource,,"20,000",,"22,000","24,200","26,620","29,282",MoA & private sector,MoA
6,,Link farmers to credit facilities for them to ...,Human resource,,"20,000",,"22,000","24,200","26,620","29,282",MoA & private sector,MoA
7,,Link farmers to credit facilities to enable them,Human resource,,"20,000",,"22,000","24,200","26,620","29,282",MoA & private sector,MoA

Processing: 2
Original shape: (9, 11)

Processing: 3
Original shape: (10, 11)

Processing: 4
Original shape: (12, 13)
⚠ Could not normalize: (12, 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,,Refresher Trainings,,,,,,,,,,,
1,,Set demonstration plots on crop diversificatio n,Human resource,"50,000","55,000",,"60,500","66,550","73,205",MoA,,MoA,
2,,Training Materials development,Human resource,"36,000","39,600",,"43,560","47,916","52,708",MoA,,MoA,
3,,Electronic Extension Platform operationaliza tion,Human resource,"30,000","33,000",,"36,300","39,930","43,923",MoA,,MoA,
4,,Farmer Registration,Human resource,"40,000","44,000",,"48,400","53,240","58,564",MoA,,MoA,
5,,Procure 18 Camp Tents,Human resource,"94,444","103,889",,"114,278","125,706","138,276",MoA,,MoA,
6,,Procurement of Pheromone Traps and accessories,Human resource,"20,000","22,000",,"24,200","26,620","29,282",MoA,,MoA,
7,,Procure 225 PPEs,Human resource,"36,000","39,600",,"43,560","47,916","52,708",MoA,,MoA,
8,,Procure 136 Rain gauges,Human resource,"15,882","17,471",,"19,218","21,139","23,253",MoA,,MoA,
9,,,TOTAL,"1,202,327","1,322,559",,"2,854,815","1,700,297","1,870,327",,,,
10,Objective 7: The Ministry of Agriculture will ...,,,,,,,,,,,,
11,Improve agricultural production,Estalishment of 4 Irrigation Schemes,Human resource,0,,"4,500,000","4,950,000","5,445,000","5,989,500",,"MoA, Local authority (CDF) & private sector",,MoA

Processing: 5
Original shape: (10, 10)

Processing: 6
Original shape: (7, 10)

Processing: 7
Original shape: (5, 9)

Processing: 8
Original shape: (6, 9)

Processing: 9
Original shape: (6, 9)

Processing: 10
Original shape: (7, 11)

Processing: 11
Original shape: (6, 9)

Processing: 12
Original shape: (7, 11)

Processing: 13
Original shape: (9, 10)

Processing: 14
Original shape: (9, 9)

Processing: 15
Original shape: (8, 10)

Processing: 16
Original shape: (3, 10)

Processing: 17
Original shape: (3, 9)

Processing: 18
Original shape: (6, 10)

Processing: 19
Original shape: (5, 9)

Processing: 20
Original shape: (2, 9)

In [844]:
table30_df = pd.concat(
    table30_parts,
    ignore_index=True
)

In [845]:
combined = (
    table30_df.astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

header_mask = (
    combined.str.contains("strateg")
    & combined.str.contains("activit")
    & combined.str.contains("cost")
)

table30_df = table30_df[
    ~header_mask
].reset_index(drop=True)

In [846]:
combined = (
    table30_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table30_df = table30_df[
    ~(
        combined.str.startswith("objective")
        | combined.str.startswith("goal")
    )
].reset_index(drop=True)

In [847]:
combined = (
    table30_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table30_df = table30_df[
    ~(
        combined.str.startswith("objective")
        | combined.str.startswith("goal")
    )
].reset_index(drop=True)

In [848]:
cost_cols = [
    "cost_2024",
    "cost_2025",
    "cost_2026",
    "cost_2027",
    "cost_2028"
]

for col in cost_cols:

    table30_df[col] = (
        table30_df[col]
        .astype(str)
        .str.replace("K", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    table30_df[col] = pd.to_numeric(
        table30_df[col],
        errors="coerce"
    )

In [849]:
save_table_csv(
    table30_df,
    "db-unza26-csc4792_capital_investment_plan_for_economic_transformation_and_job_creation.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_economic_transformation_and_job_creation_csv.csv
Rows: 116
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_economic_transformation_and_job_creation_csv.csv'

In [850]:
tables_31 = camelot.read_pdf(
    PDF_PATH,
    pages="186-198",
    flavor="lattice"
)

print("Sections detected:", tables_31.n)

for i, table in enumerate(tables_31):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df.head())

Sections detected: 13

SECTION: 0
Page: 186
Shape: (10, 10)

,0,1,2,3,4,5,6,7,8,9
0,"Goal 2: To Provide Universal Coverage Health, ...",,,,,,,,,
1,Objective 1: The Ministry of Health will work ...,,,,,,,,,
2,Strategies,Activities,Input,Cost (ZMK),,,,,Proposed Source \nof Funding,Source of \nInformation
3,,,,2024,2025,2026,2027,2028,,
4,Increase \naccess to \nquality \nhealth care,Construction \nof 21 health \nposts,Human \nResource,"2,800,000","2,310,000","2,541,000","2,795,100","3,074,610",Local Authority \n(CDF)/MOH,MOH

SECTION: 1
Page: 187
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Construction \nof 35 staff \nhouses,Human \nResource,"3,900,000","4,290,000","4,719,000","5,190,900","5,709,990",Local Authority \n(CDF)/MOH,MOH
1,,Expand \ninfrastructure \nof 18 \nmaternity \n...,Human \nResource,"3,280,000","3,608,000","3,968,800","4,365,680","4,802,248",Local Authority \n(CDF)/MOH,MOH
2,,Procurement \nof 3 \nAmbulances,Human \nResource,"2,700,000",0,"3,240,000",0,"3,888,000",Local Authority \n(CDF)/MOH,MOH
3,,Procurement \nof 3 Utility \nvehicles,Human \nResource,0,"1,600,000","1,760,000","1,936,000",0,Local Authority \n(CDF)/MOH,MOH
4,,Procurement \nof 19 \nautoclaving \nmachines,Human \nResource,0,"300,000","330,000","363,000","399,300",Local Authority \n(CDF)/MOH,MOH

SECTION: 2
Page: 188
Shape: (4, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Construction \nof Mental \nHealth ward,Human \nResource,"200,000","220,000","242,000","266,200","292,820",Local Authority \n(CDF)/MOH,MOH
1,,Training of 35 \nhealth care \nworkers in \nfa...,Human \nResource,0,0,0,0,0,Local \nAuthority(CDF)/\nMOH,MOH
2,,Construction \nof 2 isolation \nwards,Human \nResource,0,0,"2,400,000",0,"2,880,000",Local \nAuthority(CDF)/\nMOH,MOH
3,,Procurement \nof digital X \nray machine,Human \nResource,,,,,,Local \nAuthority(CDF)/\nMOH,MOH

SECTION: 3
Page: 189
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Procurement \nof Ultra Sound \nmachine,Human \nResource,0,0,"950,000",0,0,Local \nAuthority(CDF)/\nMOH,MOH
1,,Procurement \nof 2 water \ndistillers,Human \nResource,0,"170,000",0,0,0,Local \nAuthority(CDF)/\nMOH,MOH
2,,Construction \nof a \nphysiotherapy \nblock,Human \nResource,0,0,"1,200,000",0,0,Local \nAuthority(CDF)/\nMOH,MOH
3,,Carry out \nmonthly radio \nprogrammes,Human \nResource,"60,000","66,000","72,600","79,860","87,846",local \nAuthority(CDF)/\nMOH,MOH
4,,Carry out \noutreach \nservices,Human \nResource,"73,500","80,850","88,935","97,829","107,611",Local \nAuthority(CDF)/\nMOH,MOH

SECTION: 4
Page: 190
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Connection of \n17 health \nfacilities to the ...,Human \nResource,"432,941","476,235","523,859","576,245","633,869",Local \nAuthority(CDF)/\nMOH,MOH
1,,Connection of \nwater \nreticulation to \n16 h...,Human \nResource,"1,952,000","2,147,200","2,361,920","2,598,112","2,857,923",Local \nAuthority(CDF)/\nMOH,MOH
2,,,TOTAL,"18,191,941","20,011,135","22,012,249","24,213,474","26,634,821",,
3,Objective 4: The Ministry of Education will co...,,,,,,,,,
4,Strengthen \nPublic \nHealth,Construction \nof 13 \nstandalone \nECE center...,Human \nResource,0,"2,250,000","2,475,000","2,722,500","2,994,750",MOE/LA,MOE/LA

SECTION: 5
Page: 191
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Construct of 4 \nWeekly \nBoarding \nFacilitie...,Human \nResource,"1,920,000.00","2,112,000","2,323,200","2,555,520","2,811,072",MOE/LA,MOE
1,,Procurement \nof 498 Office \ntables and 498 \...,Human \nResource,"129,800.00","142,780","157,058","172,764","190,040",MOE,MOE
2,,Recruitment of \n2000 teachers \nin the District,Human \nResource,"12,000,000.0\n0","13,200,000","14,520,000","15,972,000","17,569,200",MOE,MOE
3,,"Procurement \nof 15, 000 \ndesks in all the \n...",Human \nResource,"4,500,000.00","4,950,000","5,445,000","5,989,500","6,588,450",MOE/LA,MOE
4,,Construction \nof 1 College of \nEducation,Human \nResource,0,0,"16,666,667","18,333,333","20,166,667",MOE/LA,MOE

SECTION: 6
Page: 192
Shape: (8, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Upgrading of \nPrimary \nSchools into \nSecond...,Muman \nResource,0,"11,200,000","12,320,000","13,552,000","14,907,200 MOE",,MOE
1,,Completion of \nmumbwa \nskills vocation \ncenter,Human \nResource,0.00,0.00,"6,666,666.67","7,333,333.33","8,066,666.67",TEVETA/MOE/L\nA,TEVETA
2,,Procurement \nof specialized \nequipment’s \na...,Human \nResource,"400,000","440,000","484,000","532,400","585,640 MOE",,MOE
3,,Procurement \nof 2 Utility \nVehicles,Human \nResource,0,"1,400,000","1,540,000",0,,0 MOE/LA,MOE
4,,,TOTAL,"43,239,800","64,440,780","94,236,192","102,001,811","109,588,035",,

SECTION: 7
Page: 193
Shape: (12, 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,,Construction \nof 100 VIP \nToilets in \nprima...,Human \nResource,,"1,500,000",,"1,650,000","1,815,000","1,996,500","2,196,150",MOE/LA,,MOE
1,,Construction \nof 10 \nablotution \nblocks,Human \nResource,,"1,000,000",,"1,100,000","1,210,000","1,331,000","1,464,100",MOE/LA,,MOE
2,,,TOTAL,,"2,506,000",,"2,756,600","3,032,260","3,335,486","3,669,035",,,
3,Objective 7: The Local Authority will collabor...,,,,,,,,,,,,
4,Improve \naccess \nto \nclean \nand \nsafe wa...,Drilling of 350 \nboreholes,,Human \nResource,"4,200,000","4,620,000",,"5,082,000","5,590,200","6,149,220",Local \nAuthority/WRD,WRD,

SECTION: 8
Page: 194
Shape: (13, 10)

,0,1,2,3,4,5,6,7,8,9
0,Improve \nSanitation \nServices,Community led \ntotal sanitation \nmonitoring ...,Human \nResource,"540,000","594,000","653,400","718,740","790,614",LA//WRD,WRD
1,,Open defecation \nfree verification,Human \nResource,"540,000","594,000","653,400","718,740","790,614",LA/WRD,WRD
2,,,TOTAL,"1,080,000","1,188,000","1,306,800","1,437,480","1,581,228",,
3,,Construction of \n2 dump sites,Human \nResource,"500,000",0,"600,000",0,0,Local Authority,Local \nAuthority
4,,Clearing of \ncurrent dumpsite,Human \nResource,"60,000","120,000","240,000","480,000","960,000",Local Authority,Local \nAuthority

SECTION: 9
Page: 195
Shape: (10, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,,Radio talks,Human \nResource,"5,000","5,500","6,050","6,655","7,321",Local Authority,Local \nAuthority,
1,,Community \nawareness \nmeetings,Human \nResource,"40,000","44,000","48,400","53,240","58,564",Local Authority,Local \nAuthority,
2,,,TOTAL,"3,913,000","7,733,300","22,764,630","30,617,093","52,025,885",,,
3,Objective 9: The Department of Social Welfare ...,,,,,,,,,,
4,Enhance \nwelfare and \nlivelihoods \nof poor ...,scale up of \nsocial cash \ntransfer \nbenefic...,Human \nResource,"48,000,000","52,800,000","58,080,000","63,888,000","70,276,800",MCDSS/ GRZ,,MCDSS/Dep\nartment of \nSocial \nWelfare

SECTION: 10
Page: 196
Shape: (10, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Purchase of \nbaby formula,Human \nResource,"450,000","495,000","544,500","598,950","658,845",MCDSS/GRZ,MCDSS/Dep\nartment of \nSocial \nWelfare
1,,Juvenile justice/ \ncourt \ninvestigations,Human \nResource,"410,000","451,000","496,100","545,710","600,281",MCDSS/GRZ,MCDSS/Dep\nartment of \nSocial \nWelfare
2,,Adoption/foster \ncare,Human \nResource,"200,000","220,000","242,000","266,200","292,820",MCDSS/GRZ,MCDSS/Dep\nartment of \nSocial \nWelfare
3,,Community \nsensitization \nmeetings,Human \nResource,"400,000","440,000","484,000","532,400","585,640",MCSS/GRZ,MCDSS/Dep\nartment of \nSocial \nWelfare
4,,Repatriation of \nun- \naccompanied \nchildren,Human \nResource,"400,000","440,000","484,000","532,400","585,640",MCDSS/GRZ,MCDSS/Dep\nartment of \nSocial \nWelfare

SECTION: 11
Page: 197
Shape: (6, 10)

,0,1,2,3,4,5,6,7,8,9
0,Enhance \nwelfare and \nlivelihoods \nof poor ...,Increasing the \nnumber of \nVillage bank \nbe...,Human \nResource,"2,121,620","2,333,782","2,567,160.20","2,823,876.22","3,106,263.84",MCDSS/GRZ,MCDSS/ \nDepartment \nof \nCommunity \nDevelop...
1,,Increasing the \nnumber of \nCSLG in the \nDis...,Human \nResource,"1,202,548.80","1,322,803.68","1,455,084.05","1,600,592.45","1,760,651.70",MCDSS/GRZ,MCDSS/ \nDepartment \nof \nCommunity \nDevelop...
2,,Increasing the \nnumber of \ntargeted \ndisabl...,Human \nResource \nand \nadditional \nFSP inputs,"480,000","528,000.00","580,800.00","638,880.00","702,768.00",MCDSS/GRZ,MCDSS/Dep\nartment of \nCommunity \nDevelopment
3,,Increased \nnumber of Self-\nhelp initiatives ...,Human \nResource,"2,240,000","2,464,000","2,710,400","2,981,440","3,279,584",MCDSS/Local \nAuthority/ GRZ,Local \nAuthority/M\nDCSS/Depar\ntment of \nCo...
4,,Increasing the \nnumber of \ntargeted \nbenefi...,Human \nResource,"3,242,800","3,567,080","3,923,788","4,316,166.8","4,747,783.48",MCDSS/ GRZ,MCDSS/Dep\nartment of \nCommunity \nDevelopment

SECTION: 12
Page: 198
Shape: (4, 10)

,0,1,2,3,4,5,6,7,8,9
0,,for Women \nGroups,,,,,,,,
1,,Intensifying on \nthe number of \nentrepreneu...,Human \nResource,"2,440,000","2,684,000","2,952,400","3,247,640","3,572,404",MCDSS/ GRZ,MCDSS/Dep\nartment of \nCommunity \nDevelopment
2,,Reduced cases \nof Gender based \nViolence \nI...,Human \nResource,"2,600,000","2,860,000","3,146,000","3,460,600","3,806,660",MCDSS/GRZ,MCDSS/Dep\nartment of \nCommunity \nDevelopment
3,,,TOTAL,"16,510,569","18,161,626","19,977,788","21,975,567","24,173,124",,

In [851]:
table31_parts = []

for i, table in enumerate(tables_31):

    print("\nProcessing:", i)

    part = normalize_capital_section(
        table.df
    )

    if part is not None:
        table31_parts.append(part)

Processing: 0
Original shape: (10, 10)

Processing: 1
Original shape: (7, 9)

Processing: 2
Original shape: (4, 9)

Processing: 3
Original shape: (7, 9)

Processing: 4
Original shape: (9, 10)

Processing: 5
Original shape: (7, 9)

Processing: 6
Original shape: (8, 10)

Processing: 7
Original shape: (12, 13)
⚠ Could not normalize: (12, 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,,Construction of 100 VIP Toilets in primary Sch...,Human Resource,,"1,500,000",,"1,650,000","1,815,000","1,996,500","2,196,150",MOE/LA,,MOE
1,,Construction of 10 ablotution blocks,Human Resource,,"1,000,000",,"1,100,000","1,210,000","1,331,000","1,464,100",MOE/LA,,MOE
2,,,TOTAL,,"2,506,000",,"2,756,600","3,032,260","3,335,486","3,669,035",,,
3,Objective 7: The Local Authority will collabor...,,,,,,,,,,,,
4,Improve access to clean and safe water supply,Drilling of 350 boreholes,,Human Resource,"4,200,000","4,620,000",,"5,082,000","5,590,200","6,149,220",Local Authority/WRD,WRD,
5,,Rehabilitation of 200 boreholes,,Human Resource,"2,400,000","2,640,000",,"2,904,000","3,194,400","3,513,840",Local Authority/WRD,WRD,
6,,Construction of 50 mechanised boreholes,,Human Resource,"12,500,000","13,750,000",,"15,125,000","16,637,500","18,301,250",Local Authority/WRD,WRD,
7,,Construction of dams,,Human Resource,"8,000,000","8,800,000",,"9,680,000","10,648,000","11,712,800",Local Authority/WRD,WRD,
8,,Rehabilitation and maintentance of 5 dams,,Human Resource,"7,000,000","7,700,000",,"8,470,000","9,317,000","10,248,700",Local Authority/WRD,WRD,
9,,Monitoring of water quality,,Human Resource,"2,400","2,640",,"2,904","3,194","3,514",Local Authority/WRD,WRD,
10,,,,TOTAL,"34,102,400","37,512,640",,"41,263,904","45,390,294","49,929,324",,,
11,Objective 8 The Local Authority will collabora...,,,,,,,,,,,,

Processing: 8
Original shape: (13, 10)

Processing: 9
Original shape: (10, 11)

Processing: 10
Original shape: (10, 10)

Processing: 11
Original shape: (6, 10)

Processing: 12
Original shape: (4, 9)

In [852]:
table31_df = pd.concat(
    table31_parts,
    ignore_index=True
)

In [853]:
combined = (
    table31_df.astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

header_mask = (
    combined.str.contains("strateg")
    & combined.str.contains("activit")
    & combined.str.contains("cost")
)

table31_df = table31_df[
    ~header_mask
].reset_index(drop=True)

In [854]:
combined = (
    table31_df.astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

header_mask = (
    combined.str.contains("strateg")
    & combined.str.contains("activit")
    & combined.str.contains("cost")
)

table31_df = table31_df[
    ~header_mask
].reset_index(drop=True)

In [855]:
table31_df["strategy"] = (
    table31_df["strategy"]
    .replace("", pd.NA)
    .ffill()
)

In [856]:
table31_df["strategy"] = (
    table31_df["strategy"]
    .replace("", pd.NA)
    .ffill()
)

In [857]:
save_table_csv(
    table31_df,
    "db-unza26-csc4792_capital_investment_plan_for_human_and_social_development_cluster.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_human_and_social_development_cluster_csv.csv
Rows: 94
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_human_and_social_development_cluster_csv.csv'

In [858]:
tables_33 = camelot.read_pdf(
    PDF_PATH,
    pages="202-203",
    flavor="lattice"
)

print("Sections detected:", tables_33.n)

for i, table in enumerate(tables_33):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df)

Sections detected: 2

SECTION: 0
Page: 202
Shape: (11, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 4: To Promote a Peaceful and Secure Envir...,,,,,,,,,
1,Objective 1: Zambia Police will work in collab...,,,,,,,,,
2,Strategies,Activities,Input,Cost (ZMK),,,,,Proposed \nSource of \nFunding,Source of \nInformation
3,,,,2024,2025,2026,2027,2028,,
4,Strengthen \nthe \nCriminal \nand \nJustice \n...,Construction of 6 \npolice posts,Human \nResource,"2,100,000","2,310,000","2,541,000","2,795,100","3,074,610",MLGRD/CDF,MLGRD/ZP
5,,Rehabilitation of \n2 police posts,Human \nResource,0,0,"600,000",0,"600,000",MLGRD/CDF,MLGRD/ZP
6,,Construction of 8 \nStaff houses in \nthe Poli...,Human \nResource,0,"1,961,780","2,157,958","2,373,754","2,611,129",MLGRD/CDF,MLGRD/ZP
7,,Construction of 2 \nAdministration \nblocks,Human \nResource,0,0,"1,000,000",0,"1,000,000",MLGRD/CDF,MLGRD/ZP
8,,Procurement of 3 \nMotor Vehicles,Human \nResource,"1,200,000",0,"1,440,000",0,"1,728,000",MLGRD/CDF,MLGRD/ZP
9,,Procurement of \n21 Motor bikes \nfor each pol...,Human \nResource,"380,952","419,048","460,952","507,048","557,752",MLGRD/CDF,MLGRD/ZP
10,,Train \nCommunity \nCrime \nPrevention,Human \nResource,"300,000","330,000","363,000","399,300","439,230",MLGRD/CDF,MLGRD/ZP

SECTION: 1
Page: 203
Shape: (4, 10)

,0,1,2,3,4,5,6,7,8,9
0,,Members \n(CCPU),,,,,,,,
1,,Conduct Crime \nSensitization \nactivities in ...,Human \nResource,"100,000","110,000","121,000","133,100","146,410",MLGRD/CDF,MLGRD/ZP
2,,Train and deploy \n500 police \nofficers,Human \nResource,"4,000,000","4,400,000","4,840,000","5,324,000","5,856,400",MLGRD/CDF,MLGRD/ZP
3,,,TOTAL,"8,080,952","9,530,828","13,523,910","11,532,301","16,013,532",,

In [859]:
capital_columns = [
    "strategy",
    "activity",
    "input",
    "cost_2024",
    "cost_2025",
    "cost_2026",
    "cost_2027",
    "cost_2028",
    "proposed_source_of_funding",
    "source_of_information"
]

In [860]:
table33_parts = []

for i, table in enumerate(tables_33):

    print("\nProcessing:", i)

    part = normalize_capital_section(
        table.df
    )

    if part is not None:
        table33_parts.append(part)

table33_df = pd.concat(
    table33_parts,
    ignore_index=True
)

Processing: 0
Original shape: (11, 10)

Processing: 1
Original shape: (4, 9)

In [861]:
combined = (
    table33_df.astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

header_mask = (
    combined.str.contains("strateg")
    & combined.str.contains("activit")
    & combined.str.contains("cost")
)

table33_df = table33_df[
    ~header_mask
].reset_index(drop=True)

In [862]:
combined = (
    table33_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table33_df = table33_df[
    ~(
        combined.str.startswith("objective")
        | combined.str.startswith("goal")
    )
].reset_index(drop=True)

In [863]:
table33_df["strategy"] = (
    table33_df["strategy"]
    .replace("", pd.NA)
    .ffill()
)

In [864]:
cost_cols = [
    "cost_2024",
    "cost_2025",
    "cost_2026",
    "cost_2027",
    "cost_2028"
]

for col in cost_cols:

    table33_df[col] = (
        table33_df[col]
        .astype(str)
        .str.replace("K", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    table33_df[col] = pd.to_numeric(
        table33_df[col],
        errors="coerce"
    )

In [865]:
save_table_csv(
    table33_df,
    "db-unza26-csc4792_capital_investment_plan_for_good_governance_environment_cluster.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_good_governance_environment_cluster_csv.csv
Rows: 12
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_good_governance_environment_cluster_csv.csv'

In [866]:
monitoring_columns = [
    "output",
    "indicator",
    "baseline",
    "plan_target",
    "target_2024",
    "target_2025",
    "target_2026",
    "target_2027",
    "target_2028",
    "frequency"
]

In [867]:
def normalize_monitoring_section(df):

    df = clean_dataframe(df)

    print("Original shape:", df.shape)

    if df.shape[1] == 10:
        df.columns = monitoring_columns
        return df

    if df.shape[1] == 11:
        empty_counts = (
            df.replace("", pd.NA)
            .isna()
            .sum()
        )

        emptiest = empty_counts.idxmax()

        df = df.drop(columns=[emptiest])

        if df.shape[1] == 10:
            df.columns = monitoring_columns
            return df

    if df.shape[1] == 9:

        df.insert(
            0,
            "output",
            ""
        )

        df.columns = monitoring_columns
        return df

    print("⚠ Could not normalize:", df.shape)
    display(df)

    return None

In [868]:
tables_34 = camelot.read_pdf(
    PDF_PATH,
    pages="206-211",
    flavor="lattice"
)

print("Sections detected:", tables_34.n)

for i, table in enumerate(tables_34):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df.head())

Sections detected: 6

SECTION: 0
Page: 206
Shape: (17, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 1: To become an industrialised and diver...,,,,,,,,,
1,Objective 1: The Ministry of Agriculture will ...,,,,,,,,,
2,Output,Indicator,Baseline,Plan Target,Annual Target,,,,,Frequency
3,,,,,Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,
4,25 \ncamp \nhouses \nfor \nextension \nofficer...,Number of camp houses for extension \nofficers...,2023,25,5,5,5,5,5,Annually

SECTION: 1
Page: 207
Shape: (19, 10)

,0,1,2,3,4,5,6,7,8,9
0,Farmers \nowning \nanimal \ndraught \npower,Number of \nfarmers owning animal \ndraught...,2023,"4,600",0,"1,150","1,150","1,150","1,150",Annually
1,Farmers owning post-harvesting and \nprocessin...,Number \nof \nfarmers \nowning \npost-\nharves...,2023,125,25,25,25,25,25,Annually
2,Farmers \naccessing \ntractor \nmechanization ...,Number of farmers accessing tractor \nmech...,2023,"4,111",764,839,836,835,837,Annually
3,Farmers accessing animal draught \npower se...,Number of farmers accessing animal \ndraug...,2023,"25,000","5,000","5,000","5,000","5,000","5,000",Annually
4,Farmers accessing post-harvesting \nand proc...,Number of farmers accessing post-\nharvest...,2023,500,213,234,284,320,500,Annually

SECTION: 2
Page: 208
Shape: (21, 10)

,0,1,2,3,4,5,6,7,8,9
0,Training materials prepared,Number of training materials prepared,2023,20,0,5,5,5,5,Annually
1,Electronic \nextension \nplatform \noperationa...,Number of \nthe electronic extension \nplat...,2023,1,0,0,1,0,0,Annually
2,Farmer register periodically updated Number,of \nfarmer \nregisters \nperiodically updated,2023,5,1,1,1,1,1,Annually
3,Farmer \nMarketing \nBulletins \nprepared,Number of farmer marketing bulletins \nprepared,2023,16,0,4,4,4,4,Annually
4,Objective 6: The Ministry of Agriculture will ...,,,,,,,,,

SECTION: 3
Page: 209
Shape: (19, 10)

,0,1,2,3,4,5,6,7,8,9
0,Permanent biosecurity check points \nestablished,Number \nof \npermanent \nbiosecurity \ncheck ...,2023,4,0,2,2,0,0,Annually
1,Vaccination \nschedules \noperationalised,Number \nof \nvaccination \nschedules \noperat...,2023,10,2,2,2,2,2,Annually
2,Quarantine facilities established,Number \nof \nquarantine \nfacilities \nestabl...,2023,1,0,1,0,0,0,Annually
3,Livestock \nquarantine \nfacilities \nrehabili...,Number \nof \nlivestock \nquarantine \nfacilit...,2023,1,0,1,0,0,0,Annually
4,Disease surveillances conducted,Number \nof \ndisease \nsurveillances \nconducted,2023,45,9,9,9,9,9,Annually

SECTION: 4
Page: 210
Shape: (19, 10)

,0,1,2,3,4,5,6,7,8,9
0,AI satellite centers established,Number \nof \nAI \nsatellite \ncenters \nestab...,2023,3,0,1,0,1,1,Annually
1,Objective 10: The Ministry of Fisheries and Li...,,,,,,,,,
2,Camp \nhouses \nand \noffice \nblocks \ncosntr...,Number of camp houses and office \nblocks...,2023,32,0,6,8,9,9,Annually
3,Camp houses and office blocks \nrehabilitated,Number of camp houses and office \nblocks...,2023,9,0,3,3,3,0,Annually
4,"Fisheries, livestock and veterinary \nextensio...","Number of \nfisheries, \nlivestock and \nvet...",2023,35,0,7,7,7,14,Annually

SECTION: 5
Page: 211
Shape: (16, 10)

,0,1,2,3,4,5,6,7,8,9
0,Rroads rehabilitated and upgraded,Number of \nroads \nrehabilitated and \nupgr...,2023,40Km,0,10Km,10Km,10Km,10Km,Annually
1,Roads rehabilitated and upgraded,Number of \nroads \nrehabilitated and \nupgr...,2023,40Km,4Km,8Km,10Km,10Km,8Km,Annually
2,Roads rehabilitated and upgraded,Number of \nroads \nrehabilitated and \nupgr...,2023,40Km,4Km,8Km,10Km,10Km,8Km,Annually
3,Radio \nand \ntelevision \ntowers \ninstalled,Number of radio and television towers \ninstalled,2023,6,0,0,2,2,2,Annually
4,Objective 14: National Parks and Wildlife will...,,,,,,,,,

In [869]:
table34_parts = []

for i, table in enumerate(tables_34):

    part = normalize_monitoring_section(
        table.df
    )

    if part is not None:
        table34_parts.append(part)

table34_df = pd.concat(
    table34_parts,
    ignore_index=True
)

Original shape: (17, 10)
Original shape: (19, 10)
Original shape: (21, 10)
Original shape: (19, 10)
Original shape: (19, 10)
Original shape: (16, 10)

In [870]:
combined = (
    table34_df.astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

header_mask = (
    combined.str.contains("output")
    & combined.str.contains("indicator")
    & combined.str.contains("baseline")
)

table34_df = table34_df[
    ~header_mask
].reset_index(drop=True)

In [871]:
combined = (
    table34_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table34_df = table34_df[
    ~(
        combined.str.startswith("objective")
        | combined.str.startswith("goal")
    )
].reset_index(drop=True)

In [872]:
save_table_csv(
    table34_df,
    "db-unza26-csc4792_economic_transformation_and_job_creation_monitoring_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_economic_transformation_and_job_creation_monitoring_plan_csv.csv
Rows: 93
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_economic_transformation_and_job_creation_monitoring_plan_csv.csv'

In [873]:
tables_35 = camelot.read_pdf(
    PDF_PATH,
    pages="212-216",
    flavor="lattice"
)

print("Sections detected:", tables_35.n)

for i, table in enumerate(tables_35):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df.head())

Sections detected: 5

SECTION: 0
Page: 212
Shape: (15, 10)

,0,1,2,3,4,5,6,7,8,9
0,"Goal 2: To Provide Universal Coverage Health, ...",,,,,,,,,
1,Objective 1: The Ministry of Health will work ...,,,,,,,,,
2,Output,Indicator,Baseline,Plan Target,Annual Target,,,,,Frequency
3,,,,,Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,
4,Health \nService \nAccess \nPoints \nconstructed,Number of Health Service Access \nPoints c...,2023,21,1,5,5,5,5,Quarterly

SECTION: 1
Page: 213
Shape: (16, 10)

,0,1,2,3,4,5,6,7,8,9
0,Water reticulation systems installed \nat heal...,Number of water reticulation systems \ninstall...,2023,16,0,4,4,4,4,Quarterly
1,Vehicles procured,Number of vehicles procured,2023,5,1,2,2,0,0,Quarterly
2,Objective 2: The Ministry of Health will colla...,,,,,,,,,
3,Adolescent youth \nfriendly \nspaces \nprovided,Number of adolescent youth friendly \nspac...,2023,20,0,5,5,5,5,Quarterly
4,Increased health facilities providing \nmental...,Number of health facilities providing \nmental...,2023,1,0,0,1,0,0,Quarterly

SECTION: 2
Page: 214
Shape: (18, 10)

,0,1,2,3,4,5,6,7,8,9
0,1 X 3 classroom blocks in schools \ncons...,Number of 1 X 3 classroom blocks in \nschools ...,2023,50,10,10,10,10,10,Quarterly
1,Staff houses in schools constructed,Number of staff houses \nin schools \ncons...,2023,30,6,6,6,6,6,Quarterly
2,Weekly \nboarding \nfacilities \nconstructed,Number of weekly boarding facilities \nconstru...,2023,40,8,8,8,8,8,Quarterly
3,Office tables and chairs procured,Number of office \ntables and chairs \npro...,2023,498,100,100,100,100,98,Quarterly
4,Secondary \nschool \nprovided with \nICT spec...,Number of secondary school provided \nwith ICT...,2023,90,10,20,20,20,20,Quarterly

SECTION: 3
Page: 215
Shape: (19, 10)

,0,1,2,3,4,5,6,7,8,9
0,Increased production of vegetables \nand ot...,Number \nof \nschools \nproducing \nvegetables...,2023,158,158,0,0,0,0,Quarterly
1,Objective 7: The Local Authority will collabor...,,,,,,,,,
2,Boreholes drilled,Number of boreholes drilled,2023,100,20,20,20,20,20,Quarterly
3,Boreholes rehabilitated,Number of boreholes rehabilitated,2023,"1,000",200,200,200,200,200,Quarterly
4,Borehole mechanised,Number of borehole mechanised,2023,50,10,10,10,10,10,Quarterly

SECTION: 4
Page: 216
Shape: (7, 10)

,0,1,2,3,4,5,6,7,8,9
0,Women and Youth Empowerment \ngrants paid,Number \nof Women \nand \nYouth \nEmpowerment...,2023,450,61,75,150,300,450,Quarterly
1,People with disabilities \nregistered \nunde...,Number of people with disabilities \nregis...,2023,360,72,144,216,288,360,Quarterly
2,Self Help Initiatives implemented,Number of Self Help Initiatives,2023,24,4,8,16,20,24,Quarterly
3,Beneficiaries on Food Security Pack \nProgram ...,Number of beneficiaries on Food \nSecurity...,2023,"7,205",1441,2882,4323,5764,7205,Quarterly
4,Womens’ clubs economically and \nsocially e...,Number \nof \neconomic \nand \nsocial \nempowe...,2023,48,6,12,24,36,48,Quarterly

In [874]:
table35_parts = []

for i, table in enumerate(tables_35):

    part = normalize_monitoring_section(
        table.df
    )

    if part is not None:
        table35_parts.append(part)

table35_df = pd.concat(
    table35_parts,
    ignore_index=True
)

Original shape: (15, 10)
Original shape: (16, 10)
Original shape: (18, 10)
Original shape: (19, 10)
Original shape: (7, 10)

In [875]:
table35_parts = []

for i, table in enumerate(tables_35):

    part = normalize_monitoring_section(
        table.df
    )

    if part is not None:
        table35_parts.append(part)

table35_df = pd.concat(
    table35_parts,
    ignore_index=True
)

Original shape: (15, 10)
Original shape: (16, 10)
Original shape: (18, 10)
Original shape: (19, 10)
Original shape: (7, 10)

In [876]:
combined = (
    table35_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table35_df = table35_df[
    ~(
        combined.str.startswith("objective")
        | combined.str.startswith("goal")
    )
].reset_index(drop=True)

In [877]:
save_table_csv(
    table35_df,
    "db-unza26-csc4792_human_and_social_development_monitoring_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_human_and_social_development_monitoring_plan_csv.csv
Rows: 64
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_human_and_social_development_monitoring_plan_csv.csv'

In [878]:
tables_36 = camelot.read_pdf(
    PDF_PATH,
    pages="217-218",
    flavor="lattice"
)

print("Sections detected:", tables_36.n)

for i, table in enumerate(tables_36):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df)

Sections detected: 3

SECTION: 0
Page: 217
Shape: (12, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 3: To Promote Sustainable Management of N...,,,,,,,,,
1,Objective 1: The Ministry of Green Economy and...,,,,,,,,,
2,Output,Indicator,Baseline,Plan Target,Annual Target,,,,,Frequency
3,,,,,Tutor \n2024,Total \n2025,Total \n2026,Total \n2027,Total \n2028,
4,Education and awareness meetings \non climate ...,Number of education and awareness \nmeetings o...,2023,30,2 \nMeetings,6 \nMeetings,8 \nMeetings,7 \nMeetings,7 \nMeetings,Quarterly
5,Land designated and secured for \nCommunity Fo...,Number of hectares designated and \nsecured fo...,2023,"1,000,000","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors",Quarterly
6,Plantations established and \nrehabilitated,Number of plantations established \nand rehabi...,2023,"83,000","12,000 \nPlants","15,000 \nPlants","17,000 \nPlants","19,000 \nPlants","20,000 \nPlants",Quarterly
7,Objective 2: The Ministry of Green Economy and...,,,,,,,,,
8,Extension support services provided,Number of extension support services \nconducted,2023,80%,25%,50%,60%,70%,80%,Quarterly
9,Objective 3: The Ministry of Green Economy and...,,,,,,,,,
10,Traditional leaders and \ncommunities particip...,Number of traditional leaders and \ncommuniti...,2023,85%,20%,50%,60%,70%,85%,Quarterly
11,Objective 4: The Ministry of Green Economy and...,,,,,,,,,

SECTION: 1
Page: 218
Shape: (3, 10)

,0,1,2,3,4,5,6,7,8,9
0,Monitoring of protected area,Number of forest and wildlife patrols \nin all...,2023,"2,500",500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,Quarterly
1,,Number of law enforcement patrols \nalong Lusa...,2023,600,100 \nPatrols,140 \nPatrols,120 \nPatrols,120 \nPatrols,120 \nPatrols,Quarterly
2,,Number of community forest and \nwildlife rang...,2023,"1,000",200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,Quarterly

SECTION: 2
Page: 218
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 4: To Promote a Peaceful and Secure Envir...,,,,,,,,,
1,Objective 1: Zambia Police will work in collab...,,,,,,,,,
2,Output,Indicator,Baseline,Plan Target,Annual Target,,,,,Responsible \nAgency
3,,,,,Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,
4,Police posts constructed,Number of police posts constructed,2023,6,2,1,1,1,1,Quarterly
5,Police posts rehabilitated,Number of police posts rehabilitated,2023,2,0,1,1,0,0,Quarterly
6,Staff houses constructed,Number of staff houses constructed,2023,8,0,2,2,2,2,Quarterly
7,Administration blocks constructed,Number of administration blocks \nconstructed,2023,2,0,1,1,0,0,Quarterly
8,Motor vehicles procured,Number of motor vehicles procured,2023,3,0,1,1,1,0,Quarterly

In [879]:
tables_36 = camelot.read_pdf(
    PDF_PATH,
    pages="217-218",
    flavor="lattice"
)

print("Sections detected:", tables_36.n)

for i, table in enumerate(tables_36):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df)

Sections detected: 3

SECTION: 0
Page: 217
Shape: (12, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 3: To Promote Sustainable Management of N...,,,,,,,,,
1,Objective 1: The Ministry of Green Economy and...,,,,,,,,,
2,Output,Indicator,Baseline,Plan Target,Annual Target,,,,,Frequency
3,,,,,Tutor \n2024,Total \n2025,Total \n2026,Total \n2027,Total \n2028,
4,Education and awareness meetings \non climate ...,Number of education and awareness \nmeetings o...,2023,30,2 \nMeetings,6 \nMeetings,8 \nMeetings,7 \nMeetings,7 \nMeetings,Quarterly
5,Land designated and secured for \nCommunity Fo...,Number of hectares designated and \nsecured fo...,2023,"1,000,000","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors","200,000 \nHectors",Quarterly
6,Plantations established and \nrehabilitated,Number of plantations established \nand rehabi...,2023,"83,000","12,000 \nPlants","15,000 \nPlants","17,000 \nPlants","19,000 \nPlants","20,000 \nPlants",Quarterly
7,Objective 2: The Ministry of Green Economy and...,,,,,,,,,
8,Extension support services provided,Number of extension support services \nconducted,2023,80%,25%,50%,60%,70%,80%,Quarterly
9,Objective 3: The Ministry of Green Economy and...,,,,,,,,,
10,Traditional leaders and \ncommunities particip...,Number of traditional leaders and \ncommuniti...,2023,85%,20%,50%,60%,70%,85%,Quarterly
11,Objective 4: The Ministry of Green Economy and...,,,,,,,,,

SECTION: 1
Page: 218
Shape: (3, 10)

,0,1,2,3,4,5,6,7,8,9
0,Monitoring of protected area,Number of forest and wildlife patrols \nin all...,2023,"2,500",500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,Quarterly
1,,Number of law enforcement patrols \nalong Lusa...,2023,600,100 \nPatrols,140 \nPatrols,120 \nPatrols,120 \nPatrols,120 \nPatrols,Quarterly
2,,Number of community forest and \nwildlife rang...,2023,"1,000",200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,Quarterly

SECTION: 2
Page: 218
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 4: To Promote a Peaceful and Secure Envir...,,,,,,,,,
1,Objective 1: Zambia Police will work in collab...,,,,,,,,,
2,Output,Indicator,Baseline,Plan Target,Annual Target,,,,,Responsible \nAgency
3,,,,,Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,
4,Police posts constructed,Number of police posts constructed,2023,6,2,1,1,1,1,Quarterly
5,Police posts rehabilitated,Number of police posts rehabilitated,2023,2,0,1,1,0,0,Quarterly
6,Staff houses constructed,Number of staff houses constructed,2023,8,0,2,2,2,2,Quarterly
7,Administration blocks constructed,Number of administration blocks \nconstructed,2023,2,0,1,1,0,0,Quarterly
8,Motor vehicles procured,Number of motor vehicles procured,2023,3,0,1,1,1,0,Quarterly

In [880]:
combined = (
    table36_df.astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

header_mask = (
    combined.str.contains("output")
    & combined.str.contains("indicator")
    & combined.str.contains("baseline")
)

table36_df = table36_df[
    ~header_mask
].reset_index(drop=True)

In [881]:
combined = (
    table36_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table36_df = table36_df[
    ~(
        combined.str.startswith("objective")
        | combined.str.startswith("goal")
    )
].reset_index(drop=True)

In [882]:
save_table_csv(
    table36_df,
    "db-unza26-csc4792_environmental_sustainability_monitoring_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_environmental_sustainability_monitoring_plan_csv.csv
Rows: 15
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_environmental_sustainability_monitoring_plan_csv.csv'

In [883]:
tables_37 = camelot.read_pdf(
    PDF_PATH,
    pages="218-219",
    flavor="lattice"
)

print("Sections detected:", tables_37.n)

for i, table in enumerate(tables_37):
    print("\nSECTION:", i)
    print("Page:", table.page)
    print("Shape:", table.df.shape)
    display(table.df)

Sections detected: 3

SECTION: 0
Page: 218
Shape: (3, 10)

,0,1,2,3,4,5,6,7,8,9
0,Monitoring of protected area,Number of forest and wildlife patrols \nin all...,2023,"2,500",500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,500 \nPatrols,Quarterly
1,,Number of law enforcement patrols \nalong Lusa...,2023,600,100 \nPatrols,140 \nPatrols,120 \nPatrols,120 \nPatrols,120 \nPatrols,Quarterly
2,,Number of community forest and \nwildlife rang...,2023,"1,000",200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,200 \nRangers,Quarterly

SECTION: 1
Page: 218
Shape: (9, 10)

,0,1,2,3,4,5,6,7,8,9
0,Goal 4: To Promote a Peaceful and Secure Envir...,,,,,,,,,
1,Objective 1: Zambia Police will work in collab...,,,,,,,,,
2,Output,Indicator,Baseline,Plan Target,Annual Target,,,,,Responsible \nAgency
3,,,,,Target \n2024,Target \n2025,Target \n2026,Target \n2027,Target \n2028,
4,Police posts constructed,Number of police posts constructed,2023,6,2,1,1,1,1,Quarterly
5,Police posts rehabilitated,Number of police posts rehabilitated,2023,2,0,1,1,0,0,Quarterly
6,Staff houses constructed,Number of staff houses constructed,2023,8,0,2,2,2,2,Quarterly
7,Administration blocks constructed,Number of administration blocks \nconstructed,2023,2,0,1,1,0,0,Quarterly
8,Motor vehicles procured,Number of motor vehicles procured,2023,3,0,1,1,1,0,Quarterly

SECTION: 2
Page: 219
Shape: (3, 10)

,0,1,2,3,4,5,6,7,8,9
0,Motor bikes for each station \nprocured,Number of motor bikes for each \nstation procured,2023,25,4,4,4,4,5,Quarterly
1,Officers under the community \ncrime and preve...,Number \nof \nofficers \nunder \nthe \ncommuni...,2023,100,20,20,20,20,20,Quarterly
2,Community sensitisations on GBV \nand other cr...,Number of community sensitisations \non GBV an...,2023,100,20,20,20,20,20,Quarterly

In [884]:
table37_parts = []

for i, table in enumerate(tables_37):

    part = normalize_monitoring_section(
        table.df
    )

    if part is not None:
        table37_parts.append(part)

table37_df = pd.concat(
    table37_parts,
    ignore_index=True
)

Original shape: (3, 10)
Original shape: (9, 10)
Original shape: (3, 10)

In [885]:
combined = (
    table37_df.astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

header_mask = (
    combined.str.contains("output")
    & combined.str.contains("indicator")
    & combined.str.contains("baseline")
)

table37_df = table37_df[
    ~header_mask
].reset_index(drop=True)

In [886]:
combined = (
    table37_df.astype(str)
    .agg(" ".join, axis=1)
    .str.strip()
    .str.lower()
)

table37_df = table37_df[
    ~(
        combined.str.startswith("objective")
        | combined.str.startswith("goal")
    )
].reset_index(drop=True)

In [887]:
save_table_csv(
    table37_df,
    "db-unza26-csc4792_good_governance_environment_monitoring_plan.csv"
)

Saved: db-unza26-csc4792_db_unza26_csc4792_good_governance_environment_monitoring_plan_csv.csv
Rows: 12
Columns: 10

'db-unza26-csc4792_db_unza26_csc4792_good_governance_environment_monitoring_plan_csv.csv'

In [891]:
import os
import pandas as pd

OUTPUT_DIR = "/content/csv_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def save_csv(df, filename):
    path = os.path.join(OUTPUT_DIR, filename)

    df.to_csv(
        path,
        index=False,
        sep="|",               # <-- pipe separator
        encoding="utf-8-sig"
    )

    print(f"✅ Saved: {path}")
    print(f"   Rows: {df.shape[0]}")
    print(f"   Columns: {df.shape[1]}")
    print("   Separator: |")

    return path

In [892]:
import os

print("Searching for CSV files...\n")

found = []

for root, dirs, files in os.walk("/content"):
    for filename in files:
        if filename.endswith(".csv"):
            full_path = os.path.join(root, filename)
            found.append(full_path)
            print(full_path)

print("\nTotal CSV files found:", len(found))

Searching for CSV files...

/content/db-unza26-csc4792_db_unza26_csc4792_economic_transformation_and_job_creation_implementation_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_good_governance_environment_monitoring_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_good_governance_implementation_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_good_governance_environment_cluster_csv.csv
/content/db-unza26-csc4792_production_trend_in_mumbwa.csv
/content/db-unza26-csc4792_db_unza26_csc4792_district_electricity_supply_csv.csv
/content/db-unza26-csc4792_status_of_implementation_of_existing_plans_and_strategies.csv
/content/db-unza26-csc4792_db_unza26_csc4792_revenue_collection_for_mumbwa_town_council_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_locally_generated_revenue_csv.csv
/content/db-unza26-csc4792_future_demand_for_services.csv
/content/db-unza26-csc4792_db_unza26_csc4792_local_government_equalization_fund_20_percent_capital_projects_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_human_and_social_development_monitoring_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_production_trend_in_mumbwa_district_csv.csv
/content/ db-unza26-csc4792-mumbwa_council_projects_2023.csv
/content/db-unza26-csc4792_db_unza26_csc4792_revenue_projection_for_first_five_years_of_implementation_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_economic_transformation_and_job_creation_csv.csv
/content/db-unza26-csc4792_number_of_facilities_connected_to_electrical_grid_and_solar_power.csv
/content/db-unza26-csc4792_db_unza26_csc4792_environmental_sustainability_monitoring_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_status_of_forest_reserves_in_mumbwa_district_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_environmental_sustainability_implementation_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_economic_transformation_and_job_creation_monitoring_plan_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_human_and_social_development_implementation_plan_csv.csv
/content/db-unza26-csc4792_number_of_available_classrooms_and_toilets.csv
/content/db-unza26-csc4792_db_unza26_csc4792_capital_investment_plan_for_human_and_social_development_cluster_csv.csv
/content/db-unza26-csc4792_number_of_schools_in_mumbwa_district.csv
/content/db-unza26-csc4792_availability_of_water_supply_services.csv
/content/db-unza26-csc4792_db_unza26_csc4792_key_implementation_sector_priorities_csv.csv
/content/db-unza26-csc4792_db_unza26_csc4792_cfmgs_established_protected_areas_and_open_areas_csv.csv
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_train.csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_test.csv

Total CSV files found: 32